### ISSUE TITLE
coredump with SCTPD on 1.7

### ISSUE THREAD

**Issue by milapjoshi** [magma/magma#10039]
While running ipv6 test for 5 subs i have observed sctpd crashed.

- **Version:** 1.7.0-1635462558-6b022ef8
- **Affected Component:** AGW
- **Affected Subcomponent:** sctpd
- **Deployment Environment:** bare-metal (AGW)

### Describe the Issue

We are working on new test case to setup ipv6 transport with ipv6 ip address allocation. while doing that test for 5 users we have observed sctpd crashed and created coredump.

coredump  - 
`get http://ens-spirent-test-summary.com.s3-us-west-1.amazonaws.com/cores/core-1635878143-grpcpp_sync_ser-108886-1.7.0-1635462558-6b022ef8.tgz`

log
`Nov  2 18:35:43 phy-u6 sctpd[108886]: E1102 18:35:43.210508831  108891 sync.cc:105]                assertion failed: prior > 0
Nov  2 18:35:44 phy-u6 systemd[1]: sctpd.service: Main process exited, code=killed, status=6/ABRT
Nov  2 18:35:44 phy-u6 systemd[1]: sctpd.service: Failed with result 'signal'.`

backtrace 
```
Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
Core was generated by `/usr/local/sbin/sctpd'.
Program terminated with signal SIGABRT, Aborted.
#0  __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:50
50	../sysdeps/unix/sysv/linux/raise.c: No such file or directory.
[Current thread is 1 (Thread 0x7fe929c36700 (LWP 108891))]
(gdb) bt
#0  __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:50
#1  0x00007fe92bf2f859 in __GI_abort () at abort.c:79
#2  0x00007fe92bc6b98f in gpr_unref () from /usr/local/lib/libgrpc.so.6
#3  0x00007fe92bbe58f9 in grpc_resource_quota_unref_internal(grpc_resource_quota*) () from /usr/local/lib/libgrpc.so.6
#4  0x00007fe92bbd5181 in grpc_combiner_continue_exec_ctx() () from /usr/local/lib/libgrpc.so.6
#5  0x00007fe92bbe1c6d in grpc_core::ExecCtx::Flush() () from /usr/local/lib/libgrpc.so.6
#6  0x00007fe92bbda2d4 in ?? () from /usr/local/lib/libgrpc.so.6
#7  0x00007fe92bc00095 in ?? () from /usr/local/lib/libgrpc.so.6
#8  0x00007fe92bc008bb in grpc_completion_queue_next () from /usr/local/lib/libgrpc.so.6
#9  0x00007fe92c65a738 in grpc::CompletionQueue::AsyncNextInternal(void**, bool*, gpr_timespec) () from /usr/local/lib/libgrpc++.so.1
#10 0x00007fe92c665ff0 in grpc::Server::SyncRequestThreadManager::PollForWork(void**, bool*) () from /usr/local/lib/libgrpc++.so.1
#11 0x00007fe92c66d05f in grpc::ThreadManager::MainWorkLoop() () from /usr/local/lib/libgrpc++.so.1
#12 0x00007fe92c66d20c in grpc::ThreadManager::WorkerThread::Run() () from /usr/local/lib/libgrpc++.so.1
#13 0x00007fe92bc6ce4c in ?? () from /usr/local/lib/libgrpc.so.6
#14 0x00007fe92c888609 in start_thread (arg=<optimized out>) at pthread_create.c:477
#15 0x00007fe92c02c293 in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95
```

**Comment by milapjoshi** [comment]
cc @sudhikan
