### ISSUE TITLE
agw: s1ap: attach detatch test failed.

### ISSUE THREAD

**Issue by pshelar** [magma/magma#10659]
### Your Environment

- **Version:** master with PR #10613 
- **Affected Component:** Access Gateway
- **Affected Subcomponent:** s1ap test
- **Deployment Environment:** integ test

### Describe the Issue
S1AP tests with IPv6 enabled failing on basic test. but same build works on lab setup with spirent. 
```
vagrant@magma-test:~/magma/lte/gateway/python/integ_tests$ make integ_test TESTS=s1aptests/test_attach_detach.py
. /home/vagrant/build/python/bin/activate
echo "Running test: s1aptests/test_attach_detach.py"
Running test: s1aptests/test_attach_detach.py
timeout --foreground -k 930s 900s sudo -E PATH=/usr/lib/ccache:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/local/go/bin PYTHONPATH=:/home/vagrant/s1ap-tester/bin /home/vagrant/build/python/bin/nosetests --with-xunit --xunit-file=/var/tmp/test_results/test_attach_detach.xml -x -s s1aptests/test_attach_detach.py || exit 1
Start time 05:10:15
tag: AUTH_TYPE tagVal: MILENAGE
************************* Enb tester config

**********************TPT open server******** 0

 Server Socket FD =[13]
************* Testing *Time elapsed(in usec): for timer expiry               :12355 usec
AGW is stateless
APN Correction configured
Health service is disabled
Using subscriber IMSI IMSI001010000000001
Using IMEI 3805468432113171
Using subscriber IMSI IMSI001010000000002
Using IMEI 3805468432113172
************************* UE device config for ue_id  1
************************* UE device config for ue_id  2
************************* Configuring IP block
************************* Waiting for IP changes to propagate
************************* S1 setup
************************* UE App config
************************* Running End to End attach for  UE id  1
ue id 1 found
************************* send SCTP SHUTDOWN
Keys left in Redis (list should be empty)[

]
Entries in s1ap_imsi_map (should be zero): 0
Entries left in hashtables (should be zero): 0
Entries in mme_ueip_imsi_map (should be zero): 0
F
======================================================================
FAIL: Basic attach/detach test with a single UE
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/vagrant/magma/lte/gateway/python/integ_tests/s1aptests/test_attach_detach.py", line 48, in test_attach_detach
    s1ap_types.ueAttachAccept_t,
  File "/home/vagrant/magma/lte/gateway/python/integ_tests/s1aptests/s1ap_utils.py", line 346, in attach
    assert resp_type.value == response.msg_type
AssertionError:
-------------------- >> begin captured logging << --------------------
root: ERROR: Could not load magmad yml config for mconfig modules
urllib3.connectionpool: DEBUG: Starting new HTTP connection (1): 192.168.60.142:3333
urllib3.connectionpool: DEBUG: http://192.168.60.142:3333 "GET /stats/switches HTTP/1.1" 200 17
root: INFO: Adding subscriber : IMSI001010000000001
root: INFO: Adding subscriber : IMSI001010000000002
root: DEBUG: s1ap response expected, received: 12, 52
root: INFO: Deleting subscriber : IMSI001010000000001
root: INFO: Deleting subscriber : IMSI001010000000002
--------------------- >> end captured logging << ---------------------

----------------------------------------------------------------------
Ran 1 test in 13.033s

FAILED (failures=1)
Makefile:42: recipe for target 'integ_test' failed
make: *** [integ_test] Error 1
```

**To Reproduce**
1. Apply PR #10613 
2. run `vagrant provision magma`
3. `make run`
4. on magma-test VM: `make integ_test TESTS=s1aptests/test_attach_detach.py`

cc: @ulaskozat

**Comment by ssanadhya** [comment]
@pshelar , this issue is not happening on latest master. Could you please close it?
