### ISSUE TITLE
QoS profiles with max BW smaller than 60 bps crashes pipelined/sessiond

### ISSUE THREAD

**Issue by crbertoldo** [magma/magma#10737]
### Your Environment

- **Version:** 1.5
- **Affected Component:** Access Gateway
- **Affected Subcomponent:**  pipelined/sessiond
- **Deployment Environment:** AWS (orc8r), bare-metal (AGW)

### Describe the Issue

Magma sends upstream CCR-I for both Gx and Gy interface and detaches the subscriber about 10s later, with natural CCR-T for both interfaces. This undesired behavior happens for the target policy rule(s), installed by Gx in this case (but omni ones may have the same problem), if its/their QoS profile has a very low Max Bandwidth (<60 bps for downlink **and/or** uplink). The symptoms are very similar to https://github.com/magma/magma/issues/9169, but the root cause seems different (so borrowing some words as follows from there). Remark: this very low BW is part of a specific case in which we need the target Rating Group active but we cannot allow the subscriber to use data (or to almost not with such BW).

- UE attached and an attach accept was sent from the MME.
- Pipelined logs show the pyroute2 ERROR when the session is initiated (see "Additional context" below).
- Sessiond logs show deadline exceeded a few seconds later as shown below.
Dec 07 15:05:21 agw sessiond[2312]: I1207 15:05:21.323825  2325 LocalEnforcer.cpp:1885] Could not activate rules for IMSI**** rpc failed: Deadline Exceeded, terminating session...
Dec 07 15:05:21 agw sessiond[2312]: I1207 15:05:21.325419  2312 LocalEnforcer.cpp:381] Initiating session termination for IMSI****-640000
- Subsequently a network initiated detach is sent to the user.

**To Reproduce**
1. Go to 'NMS>Traffic>Create New>Rating Group' and create a random one
2. Go to 'NMS>Traffic>Create New>Profile' and create a 'QoS Profile' with e.g. Class ID = 9; Max Bandwidth Downlink(bps) = 59; Max Bandwidth Uplink(bps) = 59
3. Go to 'NMS>Traffic>Create New>Policy' and create a new one, with random values, and the just created QoS Profile and Rating Group. You may toggle 'Network Wide' in order to make the test simpler, without FeG/OCS/PCRF, putting this new policy rule as omni.
4. See the error according to the steps above in "Describe the Issue".

**Expected behavior**

Magma may accept 'QoS Profile' with both Max Bandwidth Downlink(bps) and Max Bandwidth Uplink(bps) smaller than 60 bps, or the corresponding inputs in _NMS>Traffic>Create New>Profile_ may have minlength=60. Remark: negative values are allowed to be inputted, but not zero.

![Screen Shot 2021-12-08 at 11 50 36](https://user-images.githubusercontent.com/6054708/145230884-3e5b1618-4251-41d4-9232-d13bb426368f.png)

**Additional context**

pipelined logs:

```
Dec 07 15:05:15 agw pipelined[2440]: ERROR:pyroute2.netlink:  File "/usr/lib/python3.5/runpy.py", line 193, in _run_module_as_main
Dec 07 15:05:15 agw pipelined[2440]:     "__main__", mod_spec)
Dec 07 15:05:15 agw pipelined[2440]:   File "/usr/lib/python3.5/runpy.py", line 85, in _run_code
Dec 07 15:05:15 agw pipelined[2440]:     exec(code, run_globals)
Dec 07 15:05:15 agw pipelined[2440]:   File "/usr/local/lib/python3.5/dist-packages/magma/pipelined/main.py", line 202, in <module>
Dec 07 15:05:15 agw pipelined[2440]:     main()
Dec 07 15:05:15 agw pipelined[2440]:   File "/usr/local/lib/python3.5/dist-packages/magma/pipelined/main.py", line 186, in main
Dec 07 15:05:15 agw pipelined[2440]:     service.run()
Dec 07 15:05:15 agw pipelined[2440]:   File "/usr/local/lib/python3.5/dist-packages/magma/common/service.py", line 243, in run
Dec 07 15:05:15 agw pipelined[2440]:     self._loop.run_forever()
Dec 07 15:05:15 agw pipelined[2440]:   File "/usr/lib/python3/dist-packages/aioeventlet.py", line 253, in run_forever
Dec 07 15:05:15 agw pipelined[2440]:     super(EventLoop, self).run_forever()
Dec 07 15:05:15 agw pipelined[2440]:   File "/usr/lib/python3.5/asyncio/base_events.py", line 421, in run_forever
Dec 07 15:05:15 agw pipelined[2440]:     self._run_once()
Dec 07 15:05:15 agw pipelined[2440]:   File "/usr/lib/python3.5/asyncio/base_events.py", line 1424, in _run_once
Dec 07 15:05:15 agw pipelined[2440]:     handle._run()
Dec 07 15:05:15 agw pipelined[2440]:   File "/usr/lib/python3.5/asyncio/events.py", line 126, in _run
Dec 07 15:05:15 agw pipelined[2440]:     self._callback(*self._args)
Dec 07 15:05:15 agw pipelined[2440]:   File "/usr/local/lib/python3.5/dist-packages/magma/pipelined/rpc_servicer.py", line 254, in _activate_flows
Dec 07 15:05:15 agw pipelined[2440]:     ret_ipv4 = self._install_flows_gx(request, ipv4)
Dec 07 15:05:15 agw pipelined[2440]:   File "/usr/local/lib/python3.5/dist-packages/magma/pipelined/rpc_servicer.py", line 297, in _install_flows_gx
Dec 07 15:05:15 agw pipelined[2440]:     policies)
Dec 07 15:05:15 agw pipelined[2440]:   File "/usr/local/lib/python3.5/dist-packages/magma/pipelined/rpc_servicer.py", line 360, in _activate_rules_in_enforcement
Dec 07 15:05:15 agw pipelined[2440]:     imsi, msisdn, uplink_tunnel, ip_addr, apn_ambr, policies)
Dec 07 15:05:15 agw pipelined[2440]:   File "/usr/local/lib/python3.5/dist-packages/magma/pipelined/app/policy_mixin.py", line 92, in activate_rules
Dec 07 15:05:15 agw pipelined[2440]:     res = self._install_flow_for_rule(imsi, msisdn, uplink_tunnel, ip_addr, apn_ambr, policy.rule, policy.version)
Dec 07 15:05:15 agw pipelined[2440]:   File "/usr/local/lib/python3.5/dist-packages/magma/pipelined/app/enforcement.py", line 207, in _install_flow_for_rule
Dec 07 15:05:15 agw pipelined[2440]:     flow_adds = self._get_rule_match_flow_msgs(imsi, msisdn, uplink_tunnel, ip_addr, apn_ambr, rule, version)
Dec 07 15:05:15 agw pipelined[2440]:   File "/usr/local/lib/python3.5/dist-packages/magma/pipelined/app/enforcement.py", line 176, in _get_rule_match_flow_msgs
Dec 07 15:05:15 agw pipelined[2440]:     version, self._qos_mgr, self._enforcement_stats_tbl, rule.he.urls))
Dec 07 15:05:15 agw pipelined[2440]:   File "/usr/local/lib/python3.5/dist-packages/magma/pipelined/app/policy_mixin.py", line 150, in _get_classify_rule_flow_msgs
Dec 07 15:05:15 agw pipelined[2440]:     flow, rule_num, imsi, ip_addr, apn_ambr, qos, rule_id, version, qos_mgr)
Dec 07 15:05:15 agw pipelined[2440]:   File "/usr/local/lib/python3.5/dist-packages/magma/pipelined/app/policy_mixin.py", line 251, in _get_action_for_rule
Dec 07 15:05:15 agw pipelined[2440]:     imsi, ip_addr.address.decode('utf8'), ambr, rule_num, d, qos_info)
Dec 07 15:05:15 agw pipelined[2440]:   File "/usr/local/lib/python3.5/dist-packages/magma/pipelined/qos/common.py", line 429, in add_subscriber_qos
Dec 07 15:05:15 agw pipelined[2440]:     qos_handle = self.impl.add_qos(direction, qos_info, parent=ambr_qos_handle_root)
Dec 07 15:05:15 agw pipelined[2440]:   File "/usr/local/lib/python3.5/dist-packages/magma/pipelined/qos/qos_tc_impl.py", line 261, in add_qos
Dec 07 15:05:15 agw pipelined[2440]:     skip_filter=skip_filter)
Dec 07 15:05:15 agw pipelined[2440]:   File "/usr/local/lib/python3.5/dist-packages/magma/pipelined/qos/qos_tc_impl.py", line 66, in create_class
Dec 07 15:05:15 agw pipelined[2440]:     err = TrafficClass.tc_ops.create_htb(intf, qid_hex, max_bw, rate, parent_qid_hex)
Dec 07 15:05:15 agw pipelined[2440]:   File "/usr/local/lib/python3.5/dist-packages/magma/pipelined/qos/tc_ops_pyroute2.py", line 62, in create_htb
Dec 07 15:05:15 agw pipelined[2440]:     rate=str(rate).lower(), ceil=max_bw, prio=1)
Dec 07 15:05:15 agw pipelined[2440]:   File "/usr/local/lib/python3.5/dist-packages/pyroute2/iproute/linux.py", line 1614, in tc
Dec 07 15:05:15 agw pipelined[2440]:     return tuple(self.nlm_request(msg, msg_type=command, msg_flags=flags))
Dec 07 15:05:15 agw pipelined[2440]:   File "/usr/local/lib/python3.5/dist-packages/pyroute2/netlink/nlsocket.py", line 376, in nlm_request
Dec 07 15:05:15 agw pipelined[2440]:     return tuple(self._genlm_request(*argv, **kwarg))
Dec 07 15:05:15 agw pipelined[2440]:   File "/usr/local/lib/python3.5/dist-packages/pyroute2/netlink/nlsocket.py", line 866, in nlm_request
Dec 07 15:05:15 agw pipelined[2440]:     self.put(msg, msg_type, msg_flags, msg_seq=msg_seq)
Dec 07 15:05:15 agw pipelined[2440]:   File "/usr/local/lib/python3.5/dist-packages/pyroute2/netlink/nlsocket.py", line 615, in put
Dec 07 15:05:15 agw pipelined[2440]:     self.sendto_gate(msg, addr)
Dec 07 15:05:15 agw pipelined[2440]:   File "/usr/local/lib/python3.5/dist-packages/pyroute2/netlink/rtnl/iprsocket.py", line 61, in _gate_linux
Dec 07 15:05:15 agw pipelined[2440]:     msg.encode()
Dec 07 15:05:15 agw pipelined[2440]:   File "/usr/local/lib/python3.5/dist-packages/pyroute2/netlink/__init__.py", line 1110, in encode
Dec 07 15:05:15 agw pipelined[2440]:     offset = self.encode_nlas(offset)
Dec 07 15:05:15 agw pipelined[2440]:   File "/usr/local/lib/python3.5/dist-packages/pyroute2/netlink/__init__.py", line 1451, in encode_nlas
Dec 07 15:05:15 agw pipelined[2440]:     nla.encode()
Dec 07 15:05:15 agw pipelined[2440]:   File "/usr/local/lib/python3.5/dist-packages/pyroute2/netlink/__init__.py", line 1110, in encode
Dec 07 15:05:15 agw pipelined[2440]:     offset = self.encode_nlas(offset)
Dec 07 15:05:15 agw pipelined[2440]:   File "/usr/local/lib/python3.5/dist-packages/pyroute2/netlink/__init__.py", line 1451, in encode_nlas
Dec 07 15:05:15 agw pipelined[2440]:     nla.encode()
Dec 07 15:05:15 agw pipelined[2440]:   File "/usr/local/lib/python3.5/dist-packages/pyroute2/netlink/rtnl/tcmsg/common.py", line 344, in encode
Dec 07 15:05:15 agw pipelined[2440]:     nla.encode(self)
Dec 07 15:05:15 agw pipelined[2440]:   File "/usr/local/lib/python3.5/dist-packages/pyroute2/netlink/__init__.py", line 1097, in encode
Dec 07 15:05:15 agw pipelined[2440]:     log.error(''.join(traceback.format_stack()))
Dec 07 15:05:15 agw pipelined[2440]: ERROR:pyroute2.netlink:Traceback (most recent call last):
Dec 07 15:05:15 agw pipelined[2440]:   File "/usr/local/lib/python3.5/dist-packages/pyroute2/netlink/__init__.py", line 1095, in encode
Dec 07 15:05:15 agw pipelined[2440]:     struct.pack_into(efmt, self.data, offset, value)
Dec 07 15:05:15 agw pipelined[2440]: struct.error: 'I' format requires 0 <= number <= 4294967295
Dec 07 15:05:15 agw pipelined[2440]: ERROR:pyroute2.netlink:error pack: I 22222222218 <class 'int'>
Dec 07 15:05:15 agw pipelined[2440]: ERROR:asyncio:Exception in callback PipelinedRpcServicer._activate_flows(sid {
Dec 07 15:05:15 agw pipelined[2440]:   id: "... version: 1
Dec 07 15:05:15 agw pipelined[2440]: }
Dec 07 15:05:15 agw pipelined[2440]: , <Future at 0x...state=pending>)
Dec 07 15:05:15 agw pipelined[2440]: handle: <Handle PipelinedRpcServicer._activate_flows(sid {
Dec 07 15:05:15 agw pipelined[2440]:   id: "... version: 1
Dec 07 15:05:15 agw pipelined[2440]: }
Dec 07 15:05:15 agw pipelined[2440]: , <Future at 0x...state=pending>)>
Dec 07 15:05:15 agw pipelined[2440]: Traceback (most recent call last):
Dec 07 15:05:15 agw pipelined[2440]:   File "/usr/lib/python3.5/asyncio/events.py", line 126, in _run
Dec 07 15:05:15 agw pipelined[2440]:     self._callback(*self._args)
Dec 07 15:05:15 agw pipelined[2440]:   File "/usr/local/lib/python3.5/dist-packages/magma/pipelined/rpc_servicer.py", line 254, in _activate_flows
Dec 07 15:05:15 agw pipelined[2440]:     ret_ipv4 = self._install_flows_gx(request, ipv4)
Dec 07 15:05:15 agw pipelined[2440]:   File "/usr/local/lib/python3.5/dist-packages/magma/pipelined/rpc_servicer.py", line 297, in _install_flows_gx
Dec 07 15:05:15 agw pipelined[2440]:     policies)
Dec 07 15:05:15 agw pipelined[2440]:   File "/usr/local/lib/python3.5/dist-packages/magma/pipelined/rpc_servicer.py", line 360, in _activate_rules_in_enforcement
Dec 07 15:05:15 agw pipelined[2440]:     imsi, msisdn, uplink_tunnel, ip_addr, apn_ambr, policies)
Dec 07 15:05:15 agw pipelined[2440]:   File "/usr/local/lib/python3.5/dist-packages/magma/pipelined/app/policy_mixin.py", line 92, in activate_rules
Dec 07 15:05:15 agw pipelined[2440]:     res = self._install_flow_for_rule(imsi, msisdn, uplink_tunnel, ip_addr, apn_ambr, policy.rule, policy.version)
Dec 07 15:05:15 agw pipelined[2440]:   File "/usr/local/lib/python3.5/dist-packages/magma/pipelined/app/enforcement.py", line 207, in _install_flow_for_rule
Dec 07 15:05:15 agw pipelined[2440]:     flow_adds = self._get_rule_match_flow_msgs(imsi, msisdn, uplink_tunnel, ip_addr, apn_ambr, rule, version)
Dec 07 15:05:15 agw pipelined[2440]:   File "/usr/local/lib/python3.5/dist-packages/magma/pipelined/app/enforcement.py", line 176, in _get_rule_match_flow_msgs
Dec 07 15:05:15 agw pipelined[2440]:     version, self._qos_mgr, self._enforcement_stats_tbl, rule.he.urls))
Dec 07 15:05:15 agw pipelined[2440]:   File "/usr/local/lib/python3.5/dist-packages/magma/pipelined/app/policy_mixin.py", line 150, in _get_classify_rule_flow_msgs
Dec 07 15:05:15 agw pipelined[2440]:     flow, rule_num, imsi, ip_addr, apn_ambr, qos, rule_id, version, qos_mgr)
Dec 07 15:05:15 agw pipelined[2440]:   File "/usr/local/lib/python3.5/dist-packages/magma/pipelined/app/policy_mixin.py", line 251, in _get_action_for_rule
Dec 07 15:05:15 agw pipelined[2440]:     imsi, ip_addr.address.decode('utf8'), ambr, rule_num, d, qos_info)
Dec 07 15:05:15 agw pipelined[2440]:   File "/usr/local/lib/python3.5/dist-packages/magma/pipelined/qos/common.py", line 429, in add_subscriber_qos
Dec 07 15:05:15 agw pipelined[2440]:     qos_handle = self.impl.add_qos(direction, qos_info, parent=ambr_qos_handle_root)
Dec 07 15:05:15 agw pipelined[2440]:   File "/usr/local/lib/python3.5/dist-packages/magma/pipelined/qos/qos_tc_impl.py", line 261, in add_qos
Dec 07 15:05:15 agw pipelined[2440]:     skip_filter=skip_filter)
Dec 07 15:05:15 agw pipelined[2440]:   File "/usr/local/lib/python3.5/dist-packages/magma/pipelined/qos/qos_tc_impl.py", line 66, in create_class
Dec 07 15:05:15 agw pipelined[2440]:     err = TrafficClass.tc_ops.create_htb(intf, qid_hex, max_bw, rate, parent_qid_hex)
Dec 07 15:05:15 agw pipelined[2440]:   File "/usr/local/lib/python3.5/dist-packages/magma/pipelined/qos/tc_ops_pyroute2.py", line 62, in create_htb
Dec 07 15:05:15 agw pipelined[2440]:     rate=str(rate).lower(), ceil=max_bw, prio=1)
Dec 07 15:05:15 agw pipelined[2440]:   File "/usr/local/lib/python3.5/dist-packages/pyroute2/iproute/linux.py", line 1614, in tc
Dec 07 15:05:15 agw pipelined[2440]:     return tuple(self.nlm_request(msg, msg_type=command, msg_flags=flags))
Dec 07 15:05:15 agw pipelined[2440]:   File "/usr/local/lib/python3.5/dist-packages/pyroute2/netlink/nlsocket.py", line 376, in nlm_request
Dec 07 15:05:15 agw pipelined[2440]:     return tuple(self._genlm_request(*argv, **kwarg))
Dec 07 15:05:15 agw pipelined[2440]:   File "/usr/local/lib/python3.5/dist-packages/pyroute2/netlink/nlsocket.py", line 866, in nlm_request
Dec 07 15:05:15 agw pipelined[2440]:     self.put(msg, msg_type, msg_flags, msg_seq=msg_seq)
Dec 07 15:05:15 agw pipelined[2440]:   File "/usr/local/lib/python3.5/dist-packages/pyroute2/netlink/nlsocket.py", line 615, in put
Dec 07 15:05:15 agw pipelined[2440]:     self.sendto_gate(msg, addr)
Dec 07 15:05:15 agw pipelined[2440]:   File "/usr/local/lib/python3.5/dist-packages/pyroute2/netlink/rtnl/iprsocket.py", line 61, in _gate_linux
Dec 07 15:05:15 agw pipelined[2440]:     msg.encode()
Dec 07 15:05:15 agw pipelined[2440]:   File "/usr/local/lib/python3.5/dist-packages/pyroute2/netlink/__init__.py", line 1110, in encode
Dec 07 15:05:15 agw pipelined[2440]:     offset = self.encode_nlas(offset)
Dec 07 15:05:15 agw pipelined[2440]:   File "/usr/local/lib/python3.5/dist-packages/pyroute2/netlink/__init__.py", line 1451, in encode_nlas
Dec 07 15:05:15 agw pipelined[2440]:     nla.encode()
Dec 07 15:05:15 agw pipelined[2440]:   File "/usr/local/lib/python3.5/dist-packages/pyroute2/netlink/__init__.py", line 1110, in encode
Dec 07 15:05:15 agw pipelined[2440]:     offset = self.encode_nlas(offset)
Dec 07 15:05:15 agw pipelined[2440]:   File "/usr/local/lib/python3.5/dist-packages/pyroute2/netlink/__init__.py", line 1451, in encode_nlas
Dec 07 15:05:15 agw pipelined[2440]:     nla.encode()
Dec 07 15:05:15 agw pipelined[2440]:   File "/usr/local/lib/python3.5/dist-packages/pyroute2/netlink/rtnl/tcmsg/common.py", line 344, in encode
Dec 07 15:05:15 agw pipelined[2440]:     nla.encode(self)
Dec 07 15:05:15 agw pipelined[2440]:   File "/usr/local/lib/python3.5/dist-packages/pyroute2/netlink/__init__.py", line 1095, in encode
Dec 07 15:05:15 agw pipelined[2440]:     struct.pack_into(efmt, self.data, offset, value)
Dec 07 15:05:15 agw pipelined[2440]: struct.error: 'I' format requires 0 <= number <= 4294967295
```

**Comment by crbertoldo** [comment]
@joary @jpad-freedomfi
