### ISSUE TITLE
Pipelined managed tbl0 error

### ISSUE THREAD

**Issue by koolzz** [magma/magma#10943]
When using the pipelined managed tbl0 flag from spgw I'm getting this error. 
```
Dec 20 17:32:57 phy-agw1 pipelined[10622]: AttributeError: 'NoneType' object has no attribute 'IsInitialized'
Dec 20 17:36:01 phy-agw1 pipelined[10622]: ERROR:grpc._common:Exception serializing message!
Dec 20 17:36:01 phy-agw1 pipelined[10622]: Traceback (most recent call last):
Dec 20 17:36:01 phy-agw1 pipelined[10622]:   File "/usr/local/lib/python3.8/dist-packages/grpc/_common.py", line 86, in _transform
Dec 20 17:36:01 phy-agw1 pipelined[10622]:     return transformer(message)
Dec 20 17:36:01 phy-agw1 pipelined[10622]:   File "/usr/local/lib/python3.8/dist-packages/google/protobuf/internal/python_message.py", line 1093, in SerializeToString
Dec 20 17:36:01 phy-agw1 pipelined[10622]:     if not self.IsInitialized():
Dec 20 17:36:01 phy-agw1 pipelined[10622]: AttributeError: 'NoneType' object has no attribute 'IsInitialized'
Dec 20 17:41:02 phy-agw1 pipelined[10622]: ERROR:grpc._common:Exception serializing message!
Dec 20 17:41:02 phy-agw1 pipelined[10622]: Traceback (most recent call last):
Dec 20 17:41:02 phy-agw1 pipelined[10622]:   File "/usr/local/lib/python3.8/dist-packages/grpc/_common.py", line 86, in _transform
Dec 20 17:41:02 phy-agw1 pipelined[10622]:     return transformer(message)
Dec 20 17:41:02 phy-agw1 pipelined[10622]:   File "/usr/local/lib/python3.8/dist-packages/google/protobuf/internal/python_message.py", line 1093, in SerializeToString
Dec 20 17:41:02 phy-agw1 pipelined[10622]:     if not self.IsInitialized():
Dec 20 17:41:02 phy-agw1 pipelined[10622]: AttributeError: 'NoneType' object has no attribute 'IsInitialized'
Dec 20 17:46:02 phy-agw1 pipelined[10622]: ERROR:grpc._common:Exception serializing message!
Dec 20 17:46:02 phy-agw1 pipelined[10622]: Traceback (most recent call last):
Dec 20 17:46:02 phy-agw1 pipelined[10622]:   File "/usr/local/lib/python3.8/dist-packages/grpc/_common.py", line 86, in _transform
Dec 20 17:46:02 phy-agw1 pipelined[10622]:     return transformer(message)
Dec 20 17:46:02 phy-agw1 pipelined[10622]:   File "/usr/local/lib/python3.8/dist-packages/google/protobuf/internal/python_message.py", line 1093, in SerializeToString
Dec 20 17:46:02 phy-agw1 pipelined[10622]:     if not self.IsInitialized():
Dec 20 17:46:02 phy-agw1 pipelined[10622]: AttributeError: 'NoneType' object has no attribute 'IsInitialized'
```

**Comment by koolzz** [comment]
Actually when updating to master I think the error is gone but I don't see any table0 flows added, is there anything required besides the `pipelined_managed_tbl0: true   ` flag on spgw.yml to enable the pipelined managed tbl0?
@prabinakpattnaik @panyogesh
