### ISSUE TITLE
CWF Integration test is broken due to unhealthy pipelined

### ISSUE THREAD

**Issue by themarwhal** [magma/magma#11061]
See CI dashboard @ https://magma-ci.web.app

<img width="1683" alt="Screen Shot 2022-01-05 at 7 24 07 PM" src="https://user-images.githubusercontent.com/37634144/148276593-8457d40b-3764-45f3-b32e-98269954fd4c.png">

First PR with the failure seems to be this : https://github.com/magma/magma/pull/11010

**Comment by themarwhal** [comment]
Logs can be found here:https://github.com/magma/magma/actions/runs/1637039257

PipelineD error
```
2021-12-30T11:12:44.127931000Z Traceback (most recent call last):
2021-12-30T11:12:44.128206000Z   File "/usr/lib/python3.8/runpy.py", line 194, in _run_module_as_main
2021-12-30T11:12:44.128309000Z     return _run_code(code, main_globals, None,
2021-12-30T11:12:44.128408000Z   File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
2021-12-30T11:12:44.128602000Z     exec(code, run_globals)
2021-12-30T11:12:44.128664000Z   File "/usr/local/lib/python3.8/dist-packages/magma/pipelined/main.py", line 44, in <module>
2021-12-30T11:12:44.128761000Z     from magma.pipelined.service_manager import ServiceManager
2021-12-30T11:12:44.128821000Z   File "/usr/local/lib/python3.8/dist-packages/magma/pipelined/service_manager.py", line 80, in <module>
2021-12-30T11:12:44.128883000Z     from magma.pipelined.ebpf.ebpf_manager import get_ebpf_manager
2021-12-30T11:12:44.128982000Z ModuleNotFoundError: No module named 'magma.pipelined.ebpf'
```

**Comment by themarwhal** [comment]
With the latest failure, I see this separate error:
```
2022-01-05T09:26:37.076672000Z Traceback (most recent call last):
2022-01-05T09:26:37.076772000Z   File "/usr/lib/python3.8/runpy.py", line 194, in _run_module_as_main
2022-01-05T09:26:37.076839000Z     return _run_code(code, main_globals, None,
2022-01-05T09:26:37.076890000Z   File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
2022-01-05T09:26:37.076966000Z     exec(code, run_globals)
2022-01-05T09:26:37.077028000Z   File "/usr/local/lib/python3.8/dist-packages/magma/pipelined/main.py", line 44, in <module>
2022-01-05T09:26:37.077086000Z     from magma.pipelined.service_manager import ServiceManager
2022-01-05T09:26:37.077166000Z   File "/usr/local/lib/python3.8/dist-packages/magma/pipelined/service_manager.py", line 80, in <module>
2022-01-05T09:26:37.077226000Z     from magma.pipelined.ebpf.ebpf_manager import get_ebpf_manager
2022-01-05T09:26:37.077278000Z   File "/usr/local/lib/python3.8/dist-packages/magma/pipelined/ebpf/ebpf_manager.py", line 26, in <module>
2022-01-05T09:26:37.077333000Z     from bcc import BPF
2022-01-05T09:26:37.077384000Z ModuleNotFoundError: No module named 'bcc'
```

**Comment by pshelar** [comment]
first issue is already fixed: https://github.com/magma/magma/pull/11035
