### ISSUE TITLE
[Broken_Sanity] Test case test_attach_without_ips_available.py is failing

### ISSUE THREAD

**Issue by VinashakAnkitAman** [magma/magma#11122]
### Your Environment

- **Version:** Local Development Setup
- **Affected Component:** Access Gateway
- **Affected Subcomponent:** Magma MME/SPGW service
- **Deployment Environment:** Vagrant (AGW)

### Setup Details
The S1APTester ([https://github.com/facebookexperimental/S1APTester](https://github.com/facebookexperimental/S1APTester)) was used along with Magma EPC in Vagrant based setup to reproduce the issue.

### Describe the Issue
The sanity run is always failing with assert for test case **s1aptests/test_attach_without_ips_available.py**. The test case expects the attach to fail whereas it is passing. The mobilityd cleanup seems to not work as the list IP block function gives the same list before and after the mobilityd cleanup in the test case. The relevant logs and pcaps are attached here:
[test_attach_without_ips_available.py.zip](https://github.com/magma/magma/files/7846411/test_attach_without_ips_available.py.zip)

The terminal error log is as follows:
```
(python) vagrant@magma-test:~/magma/lte/gateway/python/integ_tests$ make integ_test TESTS=s1aptests/test_attach_without_ips_available.py
. /home/vagrant/build/python/bin/activate
echo "Running test: s1aptests/test_attach_without_ips_available.py"
Running test: s1aptests/test_attach_without_ips_available.py
timeout --foreground -k 930s 900s sudo -E PATH=/home/vagrant/build/python/bin:/usr/lib/ccache:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/local/go/bin PYTHONPATH=:/home/vagrant/s1ap-tester/bin /home/vagrant/build/python/bin/nosetests --with-xunit --xunit-file=/var/tmp/test_results/test_attach_without_ips_available.xml -x -s s1aptests/test_attach_without_ips_available.py || exit 1
Start time 12:18:20
tag: AUTH_TYPE tagVal: MILENAGE
************************* Enb tester config

**********************TPT open server******** 0

 Server Socket FD =[13]
************* Testing *Time elapsed(in usec): for timer expiry               :9759 usec
AGW is stateless
APN Correction configured
Health service is disabled
Using subscriber IMSI IMSI001010000000001
Using IMEI 3805468432113171
************************* UE device config for ue_id  1
************************* Configuring IP block
************************* Waiting for IP changes to propagate
************************* S1 setup
************************* UE App config
************************* Running End to End attach for  UE id  1
ue id 1 found

*************NbUiNbuHdlUeRadioCapMsg: Send UE cap msg SUCCESS*********
PDN_TYPE: 1
IPv4 PDN_ADDRESS:192 168 128 14
************************* send SCTP SHUTDOWN
Deleting Ue Context from Traffic Handler
Keys left in Redis (list should be empty)[
 IMSI001010000000001:MME
IMSI001010000000001.internet,ipv4:mobilityd_ipdesc_record
IMSI001010000000001.ims,ipv4:mobilityd_ipdesc_record
IMSI001010000000002.magma.ipv4,ipv4:mobilityd_ipdesc_record
IMSI001010000000001.magma.ipv4,ipv4:mobilityd_ipdesc_record
IMSI001010000000001:SPGW

nb_ue_attached: 1
]
Entries in s1ap_imsi_map (should be zero): 1
Entries left in hashtables (should be zero): 3
Entries in mme_ueip_imsi_map (should be zero): 1
F
======================================================================
FAIL: Attaching without available IPs in mobilityd
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/vagrant/magma/lte/gateway/python/integ_tests/s1aptests/test_attach_without_ips_available.py", line 46, in test_attach_without_ips_available
    s1ap_types.tfwCmd.UE_ATTACH_REJECT_IND, s1ap_types.ueAttachFail_t,
  File "/home/vagrant/magma/lte/gateway/python/integ_tests/s1aptests/s1ap_utils.py", line 346, in attach
    assert resp_type.value == response.msg_type
AssertionError:
-------------------- >> begin captured logging << --------------------
root: ERROR: Could not load magmad yml config for mconfig modules
urllib3.connectionpool: DEBUG: Starting new HTTP connection (1): 192.168.60.142:3333
urllib3.connectionpool: DEBUG: http://192.168.60.142:3333 "GET /stats/switches HTTP/1.1" 200 17
root: INFO: Adding subscriber : IMSI001010000000001
root: INFO: Ignoring FAILED_PRECONDITION exception
root: DEBUG: s1ap response expected, received: 23, 12
root: INFO: Deleting subscriber : IMSI001010000000001
--------------------- >> end captured logging << ---------------------

----------------------------------------------------------------------
Ran 1 test in 13.059s

FAILED (failures=1)
Makefile:42: recipe for target 'integ_test' failed
make: *** [integ_test] Error 1

```

**To Reproduce**
1) Run the test case in loop with "make integ_test TESTS=s1aptests/test_attach_without_ips_available.py"

**Comment by ardzoht** [comment]
@VinashakAnkitAman I have not had success to reproduce this failure on my local, can you double verify on this failure to discard any issue within your environment?

**Comment by VinashakAnkitAman** [comment]
The issue is not getting reproduced on latest master. Verified in 2 different setups with multiple individual test case, precommit and sanity executions. Closing the issue.

**Comment by VinashakAnkitAman** [comment]
Hi @ardzoht The issue has recently been seen on latest master with commit id: 54e5c63c6ff24e56f4fbba5a306680e92dde9176. The test case failed while running sanity. I was unable to upload the logs directly to Github, hence uploaded the logs and pcaps here:
https://drive.google.com/drive/folders/1-LruYpE9D5yRM9oLl4c7Wqun8RmXbkXd?usp=sharing
However, the same test case passed successfully while running it again with precommit and individually.
