### ISSUE TITLE
Error in building NMS

### ISSUE THREAD

**Issue by Bahador-Bakhshi** [magma/magma#11282]
Following the steps of the "Quick Start Guide", the NMS is not build successfully. 

This is the output of the `./scripts/dev_setup.sh` (errors are bold):

-----------------------------------------------------------------
yarn run v1.22.5
$ node -r @fbcnms/babel-register scripts/migrate.js
Browserslist: caniuse-lite is outdated. Please run:
npx browserslist@latest --update-db

Why you should do it regularly:
https://github.com/browserslist/browserslist#browsers-data-updating
2022-01-26T13:40:52.812Z [scripts/runMigrations.js] info: == 20190509000000-make-organization-unique: migrating =======
**Failed to run migrations**
Done in 13.82s.
yarn run v1.22.5
$ node -r '@fbcnms/babel-register' scripts/setPassword.js magma-test admin@magma.test password1234
Browserslist: caniuse-lite is outdated. Please run:
npx browserslist@latest --update-db

Why you should do it regularly:
https://github.com/browserslist/browserslist#browsers-data-updating
Creating a new user: email=admin@magma.test, password=password1234
{ Error:
    at Query.run (../../../../lib/dialects/postgres/query.js:76:25)
    at retry (../../lib/sequelize.js:642:28)
    at process._tickCallback (internal/process/next_tick.js:68:7)
  **name: 'SequelizeDatabaseError',**
  parent:
   { **error: column "tabs" does not exist**
       at Parser.parseErrorMessage (../src/parser.ts:369:69)
       at Parser.handlePacket (../src/parser.ts:188:21)
       at Parser.parse (../src/parser.ts:103:30)
       at Socket.stream.on.buffer (../src/index.ts:7:48)
       at Socket.emit (events.js:198:13)
       at addChunk (_stream_readable.js:288:12)
       at readableAddChunk (_stream_readable.js:269:11)
       at Socket.Readable.push (_stream_readable.js:224:10)
       at TCP.onStreamRead [as onread] (internal/stream_base_commons.js:94:17)
     length: 97,
     name: 'error',
     severity: 'ERROR',
     code: '42703',
     detail: undefined,
     hint: undefined,
     position: '73',
     internalPosition: undefined,
     internalQuery: undefined,
     where: undefined,
     schema: undefined,
     table: undefined,
     column: undefined,
     dataType: undefined,
     constraint: undefined,
     file: 'parse_relation.c',
     line: '3194',
     routine: 'errorMissingColumn',
     sql:
      'SELECT "id", "email", "organization", "password", "role", "networkIDs", "tabs", "createdAt", "updatedAt" FROM "Users" AS "User" WHERE "User"."organization" = \'magma-test\' AND "User"."email" = \'admin@magma.test\' LIMIT 1;',
     parameters: undefined },
  original:
   { **error: column "tabs" does not exist**
       at Parser.parseErrorMessage (../src/parser.ts:369:69)
       at Parser.handlePacket (../src/parser.ts:188:21)
       at Parser.parse (../src/parser.ts:103:30)
       at Socket.stream.on.buffer (../src/index.ts:7:48)
       at Socket.emit (events.js:198:13)
       at addChunk (_stream_readable.js:288:12)
       at readableAddChunk (_stream_readable.js:269:11)
       at Socket.Readable.push (_stream_readable.js:224:10)
       at TCP.onStreamRead [as onread] (internal/stream_base_commons.js:94:17)
     length: 97,
     name: 'error',
     severity: 'ERROR',
     code: '42703',
     detail: undefined,
     hint: undefined,
     position: '73',
     internalPosition: undefined,
     internalQuery: undefined,
     where: undefined,
     schema: undefined,
     table: undefined,
     column: undefined,
     dataType: undefined,
     constraint: undefined,
     file: 'parse_relation.c',
     line: '3194',
     routine: 'errorMissingColumn',
     sql:
      'SELECT "id", "email", "organization", "password", "role", "networkIDs", "tabs", "createdAt", "updatedAt" FROM "Users" AS "User" WHERE "User"."organization" = \'magma-test\' AND "User"."email" = \'admin@magma.test\' LIMIT 1;',
     parameters: undefined },
  sql:
   'SELECT "id", "email", "organization", "password", "role", "networkIDs", "tabs", "createdAt", "updatedAt" FROM "Users" AS "User" WHERE "User"."organization" = \'magma-test\' AND "User"."email" = \'admin@magma.test\' LIMIT 1;',
  parameters: {} }
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

----------------------------------------------------------------------------

This is the output of `docker-compose logs magmalte`

-------------------------------------------------------------
Attaching to magmalte_magmalte_1
magmalte_1     | wait-for-it.sh: waiting 30 seconds for postgres:5432
magmalte_1     | wait-for-it.sh: postgres:5432 is available after 4 seconds
magmalte_1     | yarn run v1.22.5
magmalte_1     | $ nodemon scripts/server
magmalte_1     | [nodemon] 2.0.6
magmalte_1     | [nodemon] reading config ./nodemon.json
magmalte_1     | [nodemon] to restart at any time, enter `rs`
magmalte_1     | [nodemon] or send SIGHUP to 55 to restart
magmalte_1     | [nodemon] watching path(s): ../fbcnms-magma-api/**/* config/**/* scripts/**/* server/**/* grafana/**/* alerts/**/*
magmalte_1     | [nodemon] watching extensions: js,mjs,json
magmalte_1     | [nodemon] starting `node -r '@fbcnms/babel-register' scripts/server.js`
magmalte_1     | [nodemon] spawning
magmalte_1     | [nodemon] child pid: 67
magmalte_1     | [nodemon] watching 45 files
magmalte_1     | Browserslist: caniuse-lite is outdated. Please run:
magmalte_1     | npx browserslist@latest --update-db
magmalte_1     |
magmalte_1     | Why you should do it regularly:
magmalte_1     | https://github.com/browserslist/browserslist#browsers-data-updating
magmalte_1     | Browserslist: caniuse-lite is outdated. Please run:
magmalte_1     | npx browserslist@latest --update-db
magmalte_1     |
magmalte_1     | Why you should do it regularly:
magmalte_1     | https://github.com/browserslist/browserslist#browsers-data-updating
magmalte_1     | 2022-01-26T13:06:43.455Z [scripts/runMigrations.js] info: == 20180824030303-create-user: migrating =======
magmalte_1     | 2022-01-26T13:06:43.806Z [scripts/runMigrations.js] info: == 20180824030303-create-user: migrated (0.350s)
magmalte_1     |
magmalte_1     | 2022-01-26T13:06:43.882Z [scripts/runMigrations.js] info: == 20181009191125-add-network-ids-user: migrating =======
magmalte_1     | 2022-01-26T13:06:44.055Z [scripts/runMigrations.js] info: == 20181009191125-add-network-ids-user: migrated (0.173s)
magmalte_1     |
magmalte_1     | 2022-01-26T13:06:44.203Z [scripts/runMigrations.js] info: == 20181129155300-create-user: migrating =======
magmalte_1     | 2022-01-26T13:06:44.448Z [scripts/runMigrations.js] info: == 20181129155300-create-user: migrated (0.245s)
magmalte_1     |
magmalte_1     | 2022-01-26T13:06:44.583Z [scripts/runMigrations.js] info: == 20181203215100-create-user: migrating =======
magmalte_1     | 2022-01-26T13:06:45.038Z [scripts/runMigrations.js] info: == 20181203215100-create-user: migrated (0.455s)
magmalte_1     |
magmalte_1     | 2022-01-26T13:06:45.369Z [scripts/runMigrations.js] info: == 20190105000000-create-user: migrating =======
magmalte_1     | 2022-01-26T13:06:45.578Z [scripts/runMigrations.js] info: == 20190105000000-create-user: migrated (0.209s)
magmalte_1     |
magmalte_1     | 2022-01-26T13:06:45.655Z [scripts/runMigrations.js] info: == 20190211030303-create-organization: migrating =======
magmalte_1     | 2022-01-26T13:06:46.155Z [scripts/runMigrations.js] info: == 20190211030303-create-organization: migrated (0.500s)
magmalte_1     |
magmalte_1     | 2022-01-26T13:06:46.541Z [scripts/runMigrations.js] info: == 20190211030304-populate-default-organization: migrating =======
magmalte_1     | 2022-01-26T13:06:46.583Z [scripts/runMigrations.js] info: == 20190211030304-populate-default-organization: migrated (0.042s)
magmalte_1     |
magmalte_1     | 2022-01-26T13:06:46.589Z [scripts/runMigrations.js] info: == 20190225030305-make-organization-networkIDs-required: migrating =======
magmalte_1     | 2022-01-26T13:06:46.719Z [scripts/runMigrations.js] info: == 20190225030305-make-organization-networkIDs-required: migrated (0.130s)
magmalte_1     |
magmalte_1     | 2022-01-26T13:06:47.139Z [scripts/runMigrations.js] info: == 20190417000000-create-feature-flag: migrating =======
magmalte_1     | 2022-01-26T13:06:47.357Z [scripts/runMigrations.js] info: == 20190417000000-create-feature-flag: migrated (0.218s)
magmalte_1     |
magmalte_1     | 2022-01-26T13:06:48.308Z [scripts/runMigrations.js] info: == 20190424161229-add_sso_to_organization: migrating =======
magmalte_1     | 2022-01-26T13:06:49.116Z [scripts/runMigrations.js] info: == 20190424161229-add_sso_to_organization: migrated (0.808s)
magmalte_1     |
magmalte_1     | 2022-01-26T13:06:49.158Z [scripts/runMigrations.js] info: == 20190509000000-make-organization-unique: migrating =======
magmalte_1     | 2022-01-26T13:06:49.219Z [scripts/server.js] **error: Fields must be specified through options.fields**

-----------------------------------------------------------------

Any help to resolve this issue is appreciated
Thanks in advance

**Comment by Bahador-Bakhshi** [comment]
This is due to an update in sequelize API.
Explained here: https://sequelize.org/master/manual/upgrade-to-v6.html
