### ISSUE TITLE
[1.7] [ipv6]AGW sessiond service crash observed with all service restarts.

### ISSUE THREAD

**Issue by milapjoshi** [magma/magma#11623]
We have Magma AGW with ipv6 enabled

running -  1.7.0-1644523313-a451d376
ipv6 enabled.
test case HIL ipv6 test TC002 UE ipv4 address allocation with GTP on ipv6 transport.

with test completion we restarted all services and core was observed for sessiond.

here is bt

```
(gdb) bt
#0  __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:50
#1  0x00007f1992375859 in __GI_abort () at abort.c:79
#2  0x00007f19925fd911 in ?? () from /lib/x86_64-linux-gnu/libstdc++.so.6
#3  0x00007f199260938c in ?? () from /lib/x86_64-linux-gnu/libstdc++.so.6
#4  0x00007f1992608369 in ?? () from /lib/x86_64-linux-gnu/libstdc++.so.6
#5  0x00007f1992608d21 in __gxx_personality_v0 ()
   from /lib/x86_64-linux-gnu/libstdc++.so.6
#6  0x00007f1992554bef in ?? () from /lib/x86_64-linux-gnu/libgcc_s.so.1
#7  0x00007f19925555aa in _Unwind_Resume ()
   from /lib/x86_64-linux-gnu/libgcc_s.so.1
#8  0x000055bc8fa14b4f in magma::LocalSessionManagerHandlerImpl::<lambda()>::operator()(void) const (__closure=0x60c000149680)
    at /home/vagrant/magma/lte/gateway/c/session_manager/LocalSessionManagerHandler.cpp:645
#9  0x000055bc8fa20450 in folly::detail::function::FunctionTraits<void()>::callBig<magma::LocalSessionManagerHandlerImpl::UpdateTunnelIds(grpc::ServerContext*, magma::lte::UpdateTunnelIdsRequest*, std::function<void(grpc::Status, magma::lte::UpdateTunnelIdsResponse)>)::<lambda()> >(folly::detail::function::Data &) (p=...)
    at /usr/local/include/folly/Function.h:321
#10 0x00007f1993189feb in folly::NotificationQueue<folly::Function<void ()> >::Consumer::consumeMessages(bool, unsigned long*) ()
   from /usr/local/lib/libfolly.so.57
#11 0x00007f1991b5113f in ?? () from /lib/x86_64-linux-gnu/libevent-2.1.so.7
#12 0x00007f1991b5187f in event_base_loop ()
```

core is attached here with

[core-1644966661-sessiond-1563234.tgz.zip](https://github.com/magma/magma/files/8075404/core-1644966661-sessiond-1563234.tgz.zip)

**Comment by uri200** [comment]
At this line 
```
  at /home/vagrant/magma/lte/gateway/c/session_manager/LocalSessionManagerHandler.cpp:645
```
it does this 
```
   auto session_map = session_store_.read_sessions({imsi});
```
Since this was while shuting down, my guess is REDIS was stopped while sessiond was trying to read
