### ISSUE TITLE
Explore failing //lte/gateway/c/core/oai/test/ngap:ngap_state_converter_test

### ISSUE THREAD

**Issue by electronjoe** [magma/magma#11676]
Under Bazel testing - two sub-tests of 36 are failing within `bazel test //lte/gateway/c/core/oai/test/ngap:ngap_state_converter_test --test_output=errors`.

These tests do not appear flaky in Bazel, they appear to fail 100% for me.

Error messages for both tests:

```
173 [----------] 2 tests from NgapStateConverterTest                                 
 174 [ RUN      ] NgapStateConverterTest.TestAfterSctpAssociation                     
 175 lte/gateway/c/core/oai/test/ngap/test_ngap_state_converter.cpp:431: Failure      
 176 Expected equality of these values:                                               
 177   hashtable_ts_is_key_exists(&state->amfid2associd, (const hash_key_t)ue_ref->amf_ue_ngap_id)
 178     Which is: 2                                                                  
 179   HASH_TABLE_OK                                                                  
 180     Which is: 0                                                                  
 181 lte/gateway/c/core/oai/test/ngap/test_ngap_state_converter.cpp:435: Failure      
 182 Expected equality of these values:                                               
 183   hashtable_uint64_ts_is_key_exists( &get_gNB_ref->ue_id_coll, (const hash_key_t)ue_ref->amf_ue_ngap_id)
 184     Which is: 2                                                                  
 185   HASH_TABLE_OK                                                                  
 186     Which is: 0                                                                  
 187 [  FAILED  ] NgapStateConverterTest.TestAfterSctpAssociation (1 ms)  
 188 [ RUN      ] NgapStateConverterTest.TestNgapServiceRestart                       
 189 Could not create logging file: Permission denied                                 
 190 COULD NOT CREATE A LOGGINGFILE 20220218-121013.6834!lte/gateway/c/core/oai/test/ngap/test_ngap_state_converter.cpp:605: Failure
 191 Expected equality of these values:                                               
 192   hashtable_ts_is_key_exists(&state->amfid2associd, (const hash_key_t)ue_ref->amf_ue_ngap_id)
 193     Which is: 2                                                                  
 194   HASH_TABLE_OK                                                                  
 195     Which is: 0                                                                  
 196 lte/gateway/c/core/oai/test/ngap/test_ngap_state_converter.cpp:609: Failure      
 197 Expected equality of these values:                                               
 198   hashtable_uint64_ts_is_key_exists( &get_gNB_ref->ue_id_coll, (const hash_key_t)ue_ref->amf_ue_ngap_id)
 199     Which is: 2                                                                  
 200   HASH_TABLE_OK                                                                  
 201     Which is: 0                                                                  
 202 lte/gateway/c/core/oai/test/ngap/test_ngap_state_converter.cpp:613: Failure      
 203 Expected equality of these values:                                               
 204   hashtable_uint64_ts_is_key_exists( imsi_map->amf_ue_id_imsi_htbl, (const hash_key_t)ue_ref->amf_ue_ngap_id)
 205     Which is: 2                                                                  
 206   HASH_TABLE_OK                                                                  
 207     Which is: 0                                                                  
 208 [  FAILED  ] NgapStateConverterTest.TestNgapServiceRestart (0 ms) 
```

**Comment by ardzoht** [comment]
From looking at the code looks like there are some `hashtable_ts_is_key_exists` that should not be returning `HASH_TABLE_OK` as the hashtables are empty after state restart. Assertions are failing because the hashtables lookup are instead returning `HASH_TABLE_KEY_NOT_EXISTS` and thus the tests fail.

**Comment by sreedharkumartn** [comment]
@electronjoe Can you help me how to run the bazel unit test.

**Comment by electronjoe** [comment]
@sreedharkumartn do we know if the unit test is running in our normal test procedures today? Wondering if it could be broken there (not running or other?). E.g. does it pass if you:

```
cd lte/gateway/
make test_oai
```

> Can you help me how to run the bazel unit test

If this cannot reproduce in our existing builds (it seems like it should reproduce per Alex above - if the tests are actually running). 

## To run Prototype Bazel Test

- If you have access to GitHub Codespaces (you should because you are a member of GH Magma)
- Go over to my [Bazel prototype branch](https://github.com/electronjoe/magma/tree/pr-giant-bazel-mme-rebase) (~4 PRs on master today)
- Click on the Green colored `Code` drop down button
- Select the `Codespaces` toggle
- Select `New Codespace` and when asked select 16 core (why not!)
- This will spin up a GitHub codespace that contains my branch
- Once the codespace is up (vs code in browswer) in the terminal window type `bazel test //lte/gateway/c/core/oai/test/ngap:ngap_state_converter_test --test_output=errors` and hit enter. This triggers a bazel build of all necessary components to run the ngap_state_converter_test, then runs the test

FYI @themarwhal

**Comment by electronjoe** [comment]
Re-opening the GH issue because #11755 appears to have built but not run the Bazel-driven test (I think).  Note the `SUCCESS` line, which I believe indicates a build target was built successfully (was the command executed a `bazel build...`).  You should see `PASSED` if a test was executed with a `bazel test` command -> only built the test binary but did not run it.  When I rebase on master this morning (containing #11755) and run the test with `bazel test //lte/gateway/c/core/oai/test/ngap:ngap_state_converter_test --test_output=errors` I get:

![image](https://user-images.githubusercontent.com/3752618/155719180-dc8b9337-0b5e-481d-a170-4f63c45b3076.png)

Note that the log output for the failure is "strange" as it does not finish running the first test. Seems almost like Google Test terminates abnormally without even a segfault or exception being thrown / displayed?

Also note that the test suite passes if I comment out this first failing test:

```
/*
TEST(NgapStateConversionSuccess, NgapStateConversionSuccess) {
...
}
*/
```

Edit: If I bisect the failing test I find that the first line causing mis-behavior is [this one](https://github.com/magma/magma/blob/master/lte/gateway/c/core/oai/test/ngap/test_ngap_state_converter.cpp#L52):
```cpp
  hashtable_uint64_ts_insert(&gnb_association->ue_id_coll, (const hash_key_t)1,
                             17);
```

Is the gnb_association struct allocated? Could we be writing to unallocated pointer space for the `ue_id_coll` object?

**Comment by electronjoe** [comment]
OK so thanks to @themarwhal advice I built with debug symbols:

```
bazel build //lte/gateway/c/core/oai/test/ngap:ngap_state_converter_test --compilation_mode=dbg
```

and then took the output binary and ran in gdb.

And got output:

![image](https://user-images.githubusercontent.com/3752618/155805568-e02fb375-22ab-4e35-9f84-fcc9053ec89e.png)

Appears the hashtable size is zero in the Bazel test for some reason, causing the binary to throw a SIGFPE (fatal arithmetic error).

**Comment by electronjoe** [comment]
The hashtable is size zero because this test does not initialize the `amf_config.max_ues` field - because the amf_config is un-ninitialized by these tests.  Thanks to @ardzoht for the help on root cause.

We are missing a call to `amf_config_init(&amf_config);` which itself relies on itti initialization etc.

All of which is to say that this test (NgapStateConversionSuccess.NgapStateConversionSuccess) needs the test fixture of the other tests.

**Comment by themarwhal** [comment]
Running this test with ASAN still seems to fail
```
bazel test //lte/gateway/c/core/oai/test/ngap:ngap_state_converter_test --config=asan --compilation_mode=dbg --runs_per_test=10
```
yields
```bash
==================== Test output for //lte/gateway/c/core/oai/test/ngap:ngap_state_converter_test (run 9 of 10):
Running main() from gmock_main.cc
[==========] Running 5 tests from 3 test suites.
[----------] Global test environment set-up.
[----------] 3 tests from NgapStateConverterTest
[ RUN      ] NgapStateConverterTest.NgapStateConversionSuccess
=================================================================
==20955==ERROR: AddressSanitizer: stack-buffer-overflow on address 0x7ffc8dae8736 at pc 0x7f704ea4ca6d bp 0x7ffc8dae85a0 sp 0x7ffc8dae7d48
READ of size 7 at 0x7ffc8dae8736 thread T0
    #0 0x7f704ea4ca6c  (/lib/x86_64-linux-gnu/libasan.so.5+0x67a6c)
    #1 0x7f70443df438 in std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::assign(char const*) (/lib/x86_64-linux-gnu/libstdc++.so.6+0x144438)
    #2 0x7f704e462318 in magma::lte::oai::Ngap_SupportedTaiItems::add_bplmns(char const*) bazel-out/k8-dbg/bin/lte/protos/oai/ngap_state_cpp_proto_pb/lte/protos/oai/ngap_state.pb.h:1719
    #3 0x7f704e461496 in magma5g::NgapStateConverter::supported_tai_item_to_proto(m5g_supported_tai_items_s const*, magma::lte::oai::Ngap_SupportedTaiItems*) lte/gateway/c/core/oai/tasks/ngap/ngap_state_converter.cpp:238
    #4 0x7f704e460e9c in magma5g::NgapStateConverter::supported_ta_list_to_proto(m5g_supported_ta_list_s const*, magma::lte::oai::Ngap_SupportedTaList*) lte/gateway/c/core/oai/tasks/ngap/ngap_state_converter.cpp:195
    #5 0x7f704e45ff2c in magma5g::NgapStateConverter::gnb_to_proto(gnb_description_s*, magma::lte::oai::GnbDescription*) lte/gateway/c/core/oai/tasks/ngap/ngap_state_converter.cpp:103
    #6 0x7f704e46686f in std::_Function_handler<void (gnb_description_s*, magma::lte::oai::GnbDescription*), void (*)(gnb_description_s*, magma::lte::oai::GnbDescription*)>::_M_invoke(std::_Any_data const&, gnb_description_s*&&, magma::lte::oai::GnbDescription*&&) /usr/include/c++/9/bits/std_function.h:300
    #7 0x7f704e466b50 in std::function<void (gnb_description_s*, magma::lte::oai::GnbDescription*)>::operator()(gnb_description_s*, magma::lte::oai::GnbDescription*) const /usr/include/c++/9/bits/std_function.h:688
    #8 0x7f704e46434e in void magma::lte::StateConverter::hashtable_ts_to_proto<gnb_description_s, magma::lte::oai::GnbDescription>(hash_table_ts_s*, google::protobuf::Map<unsigned int, magma::lte::oai::GnbDescription>*, std::function<void (gnb_description_s*, magma::lte::oai::GnbDescription*)>, log_proto_t) lte/gateway/c/core/oai/include/state_converter.h:97
    #9 0x7f704e45ef50 in magma5g::NgapStateConverter::state_to_proto(ngap_state_s*, magma::lte::oai::NgapState*) lte/gateway/c/core/oai/tasks/ngap/ngap_state_converter.cpp:41
    #10 0x55ba0821d6fe in magma5g::NgapStateConverterTest_NgapStateConversionSuccess_Test::TestBody() lte/gateway/c/core/oai/test/ngap/test_ngap_state_converter.cpp:139
    #11 0x7f7044c99b54 in void testing::internal::HandleSehExceptionsInMethodIfSupported<testing::Test, void>(testing::Test*, void (testing::Test::*)(), char const*) external/com_google_googletest/googletest/src/gtest.cc:2439
    #12 0x7f7044c8e1fb in void testing::internal::HandleExceptionsInMethodIfSupported<testing::Test, void>(testing::Test*, void (testing::Test::*)(), char const*) external/com_google_googletest/googletest/src/gtest.cc:2475
    #13 0x7f7044c596cb in testing::Test::Run() external/com_google_googletest/googletest/src/gtest.cc:2514
    #14 0x7f7044c5ab10 in testing::TestInfo::Run() external/com_google_googletest/googletest/src/gtest.cc:2690
    #15 0x7f7044c5b7f3 in testing::TestSuite::Run() external/com_google_googletest/googletest/src/gtest.cc:2822
    #16 0x7f7044c77e95 in testing::internal::UnitTestImpl::RunAllTests() external/com_google_googletest/googletest/src/gtest.cc:5342
    #17 0x7f7044c9ce79 in bool testing::internal::HandleSehExceptionsInMethodIfSupported<testing::internal::UnitTestImpl, bool>(testing::internal::UnitTestImpl*, bool (testing::internal::UnitTestImpl::*)(), char const*) external/com_google_googletest/googletest/src/gtest.cc:2439
    #18 0x7f7044c90bbc in bool testing::internal::HandleExceptionsInMethodIfSupported<testing::internal::UnitTestImpl, bool>(testing::internal::UnitTestImpl*, bool (testing::internal::UnitTestImpl::*)(), char const*) external/com_google_googletest/googletest/src/gtest.cc:2475
    #19 0x7f7044c74b07 in testing::UnitTest::Run() external/com_google_googletest/googletest/src/gtest.cc:4930
    #20 0x7f7044d236d0 in RUN_ALL_TESTS() external/com_google_googletest/googletest/include/gtest/gtest.h:2472
    #21 0x7f7044d235bf in main external/com_google_googletest/googlemock/src/gmock_main.cc:63
    #22 0x7f70440b30b2 in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x270b2)
    #23 0x55ba0821c1dd in _start (/tmp/bazel/execroot/__main__/bazel-out/k8-dbg/bin/lte/gateway/c/core/oai/test/ngap/ngap_state_converter_test+0x49a1dd)

Address 0x7ffc8dae8736 is located in stack of thread T0 at offset 38 in frame
    #0 0x7f704e460fdb in magma5g::NgapStateConverter::supported_tai_item_to_proto(m5g_supported_tai_items_s const*, magma::lte::oai::Ngap_SupportedTaiItems*) lte/gateway/c/core/oai/tasks/ngap/ngap_state_converter.cpp:214

  This frame has 1 object(s):
    [32, 38) 'plmn_array' (line 218) <== Memory access at offset 38 overflows this variable
HINT: this may be a false positive if your program uses some custom stack unwind mechanism, swapcontext or vfork
      (longjmp and C++ exceptions *are* supported)
SUMMARY: AddressSanitizer: stack-buffer-overflow (/lib/x86_64-linux-gnu/libasan.so.5+0x67a6c) 
Shadow bytes around the buggy address:
  0x100011b55090: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x100011b550a0: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x100011b550b0: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 f1 f1
  0x100011b550c0: f1 f1 f1 f1 01 f2 00 00 00 00 00 00 00 f3 f3 f3
  0x100011b550d0: f3 f3 00 00 00 00 00 00 00 00 00 00 00 00 00 00
=>0x100011b550e0: 00 00 f1 f1 f1 f1[06]f3 f3 f3 00 00 00 00 00 00
  0x100011b550f0: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x100011b55100: 00 00 00 00 00 00 f1 f1 f1 f1 00 f2 f2 f2 00 f3
  0x100011b55110: f3 f3 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x100011b55120: f1 f1 f1 f1 f1 f1 04 f2 00 f2 f2 f2 00 00 00 00
  0x100011b55130: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
Shadow byte legend (one shadow byte represents 8 application bytes):
  Addressable:           00
  Partially addressable: 01 02 03 04 05 06 07 
  Heap left redzone:       fa
  Freed heap region:       fd
  Stack left redzone:      f1
  Stack mid redzone:       f2
  Stack right redzone:     f3
  Stack after return:      f5
  Stack use after scope:   f8
  Global redzone:          f9
  Global init order:       f6
  Poisoned by user:        f7
  Container overflow:      fc
  Array cookie:            ac
  Intra object redzone:    bb
  ASan internal:           fe
  Left alloca redzone:     ca
  Right alloca redzone:    cb
  Shadow gap:              cc
==20955==ABORTING
================================================================================
Target //lte/gateway/c/core/oai/test/ngap:ngap_state_converter_test up-to-date:
  bazel-bin/lte/gateway/c/core/oai/test/ngap/ngap_state_converter_test
INFO: Elapsed time: 11.125s, Critical Path: 4.26s
INFO: 11 processes: 20 processwrapper-sandbox.
INFO: Build completed, 1 test FAILED, 11 total actions
//lte/gateway/c/core/oai/test/ngap:ngap_state_converter_test             FAILED in 10 out of 10 in 3.4s
```

**Comment by themarwhal** [comment]
Opening a new issue for the --config=asan ^ : https://github.com/magma/magma/issues/11842
