### ISSUE TITLE
[Sanity_Test_Failing] The ICS timer expiry handling after mme restart is failing

### ISSUE THREAD

**Issue by VinashakAnkitAman** [magma/magma#11894]
### Your Environment

- **Version:** Local Development Setup
- **Affected Component:** Access Gateway
- **Affected Subcomponent:** Magma MME/SPGW service
- **Deployment Environment:** Vagrant (AGW)

### Setup Details
The S1APTester ([https://github.com/facebookexperimental/S1APTester](https://github.com/facebookexperimental/S1APTester)) was used along with Magma EPC in Vagrant based setup to reproduce the issue.

### Describe the Issue
The sanity test case **s1aptests/test_ics_timer_expiry_with_mme_restart.py** is always getting stuck waiting for response from MME and fails with timeout. The test case expects the UE context release after attach but does not receive the response and gets stuck. 

On the MME side, as per the current timer implementation, the timer id is created when starting any timer only and based on the timer id mme_ue_s1ap_id is retrieved on any timer expiry and then handled accordingly. The ICS timer expiry is of 4 seconds. For the above mentioned test case, the timer has already expired by the time MME comes up after restart. But since the timer has already expired, it does not resume timer to create new timer id and rather calls for timer expiry handling. The timer expiry handling fails to fetch mme_ue_s1ap_id based on timer id, because timer id is an invalid one since we don't restore timer ids from redis db after mme restart.

Proposed solution: Need to store timer id and mme_ue_s1ap_id mapping to redis db before MME restart and restore them before timer expiry handling.

Point of culprit:
```
Function mme_app_recover_timers_for_ue in file magma/lte/gateway/c/core/oai/tasks/mme_app/mme_app_context.c
Function mme_app_handle_initial_context_setup_rsp_timer_expiry in file magma/lte/gateway/c/core/oai/tasks/mme_app/mme_app_bearer.c
```

The error log in the MME are:
```
000399 Wed Mar 02 07:46:31 2022 7FA00D718700 DEBUG MME-AP tasks/mme_app/mme_app_timer_mana:0056         Handling :Initial Context Setup Response timer
000400 Wed Mar 02 07:46:31 2022 7FA00D718700 ERROR MME-AP tasks/mme_app/mme_app_bearer.c  :2042            Invalid Timer Id expiration, Timer Id: 4294967295

```

The terminal error log is as follows:
```
(python) vagrant@magma-test:~/magma/lte/gateway/python/integ_tests$ make integ_test TESTS=s1aptests/test_ics_timer_expiry_with_mme_restart.py
. /home/vagrant/build/python/bin/activate
echo "Running test: s1aptests/test_ics_timer_expiry_with_mme_restart.py"
Running test: s1aptests/test_ics_timer_expiry_with_mme_restart.py
timeout --foreground -k 930s 900s sudo -E PATH=/home/vagrant/build/python/bin:/usr/lib/ccache:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/local/go/bin PYTHONPATH=:/home/vagrant/s1ap-tester/bin:/home/vagrant/s1ap-tester/bin /home/vagrant/build/python/bin/nosetests --with-flaky --force-flaky --no-success-flaky-report --max-runs=1 --min-passes=1 --with-xunit --xunit-file=/var/tmp/test_results/test_ics_timer_expiry_with_mme_restart.xml -x -s s1aptests/test_ics_timer_expiry_with_mme_restart.py || exit 1
Start time 07:46:08
tag: AUTH_TYPE tagVal: MILENAGE
************************* Enb tester config

**********************TPT open server******** 0

 Server Socket FD =[13]
************* Testing *Time elapsed(in usec): for timer expiry               :9263 usec
AGW is stateless
APN Correction configured
Health service is disabled
Using subscriber IMSI IMSI001010000000001
Using IMEI 3805468432113171
************************* UE device config for ue_id  1
************************* Configuring IP block
************************* Waiting for IP changes to propagate
************************* S1 setup
************************* UE App config
************************* Running End to End attach for UE id  1
ue id 1 found

*************NbUiNbuHdlUeRadioCapMsg: Send UE cap msg SUCCESS*********
PDN_TYPE: 1
IPv4 PDN_ADDRESS:192 168 128 12
************************* Sending UE context release request  for UE id  1
Deleting Ue Context from Traffic Handler
*** Sending indication to drop Initial Context Setup Req ***
************************* Sending Service request for UE id  1
************************* Restarting MME service on gateway
Waiting for 0 seconds
Waiting for 1 seconds
Waiting for 2 seconds
Waiting for 3 seconds
Waiting for 4 seconds
Waiting for 5 seconds
Waiting for 6 seconds
Waiting for 7 seconds
Waiting for 8 seconds
Waiting for 9 seconds
Waiting for 10 seconds
Waiting for 11 seconds
Waiting for 12 seconds
Waiting for 13 seconds
Waiting for 14 seconds
Waiting for 15 seconds
Waiting for 16 seconds
Waiting for 17 seconds
Waiting for 18 seconds
Waiting for 19 seconds
Waiting for 20 seconds
Waiting for 21 seconds
Waiting for 22 seconds
Waiting for 23 seconds
Waiting for 24 seconds
Waiting for 25 seconds
Waiting for 26 seconds
Waiting for 27 seconds
Waiting for 28 seconds
Waiting for 29 seconds
************************* send SCTP SHUTDOWN
Keys left in Redis (list should be empty)[
 IMSI001010000000001.magma.ipv4,ipv4:mobilityd_ipdesc_record
IMSI001010000000001:SPGW
IMSI001010000000001:MME

nb_ue_attached: 1
]
Entries in s1ap_imsi_map (should be zero): 1
Entries left in hashtables (should be zero): 3
Entries in mme_ueip_imsi_map (should be zero): 1
F
======================================================================
FAIL: The test case validates the functionality of ICS timer expiry while UE
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/vagrant/magma/lte/gateway/python/integ_tests/s1aptests/test_ics_timer_expiry_with_mme_restart.py", line 118, in test_ics_timer_expiry_with_mme_restart
    response = self._s1ap_wrapper.s1_util.get_response()
  File "/home/vagrant/magma/lte/gateway/python/integ_tests/s1aptests/s1ap_utils.py", line 212, in get_response
    + " sec) occurred while waiting for response message",
AssertionError: Timeout (900 sec) occurred while waiting for response message
-------------------- >> begin captured logging << --------------------
root: ERROR: Could not load magmad yml config for mconfig modules
urllib3.connectionpool: DEBUG: Starting new HTTP connection (1): 192.168.60.142:3333
urllib3.connectionpool: DEBUG: http://192.168.60.142:3333 "GET /stats/switches HTTP/1.1" 200 17
urllib3.connectionpool: DEBUG: Starting new HTTP connection (1): 192.168.60.142:3333
urllib3.connectionpool: DEBUG: http://192.168.60.142:3333 "GET /stats/switches HTTP/1.1" 200 17
root: INFO: Deleting subscriber : IMSI001010000000001
root: INFO: Adding subscriber : IMSI001010000000001
root: INFO: Ignoring FAILED_PRECONDITION exception
root: DEBUG: s1ap response expected, received: 12, 12
root: DEBUG: s1ap message expected, received: 68, 68
root: INFO: Deleting subscriber : IMSI001010000000001
--------------------- >> end captured logging << ---------------------

Ran 1 test in 957.139s

FAILED (failures=1)
Makefile:44: recipe for target 'integ_test' failed
make: *** [integ_test] Error 1
(python) vagrant@magma-test:~/magma/lte/gateway/python/integ_tests$
```

**To Reproduce**
1) Run the test case in loop with "make integ_test TESTS=s1aptests/test_ics_timer_expiry_with_mme_restart.py"

CC: @rsarwad

**Comment by VinashakAnkitAman** [comment]
Github Issue id #11902 points to same issue and both the issues should be closed after PR #11909 merge
