### ISSUE TITLE
Bazel build failure on clean rebuild - upstream issue?

### ISSUE THREAD

**Issue by electronjoe** [magma/magma#11947]
Just iterating on a local PR and suddenly Bazel build is failing after executing:

```
bazel clean --expunge
rm -rf .bazel*
```

Wondering if there is a regression in an un-pinned asset?

```
@electronjoe ➜ /workspaces/magma (pr-bazel-cachify-moar ✗) $ bazel build //... && bazel test //... && bazel test //... --config=asan && bazel test //... --config=lsan
Starting local Bazel server and connecting to it...
ERROR: Traceback (most recent call last):
        File "/home/vscode/.cache/bazel/_bazel_vscode/5749526a064e5b741899590751c2abdd/external/build_bazel_rules_apple/apple/internal/testing/ios_rules.bzl", line 62, column 61, in <toplevel>
                ios_ui_test_bundle = rule_factory.create_apple_bundling_rule(
        File "/home/vscode/.cache/bazel/_bazel_vscode/5749526a064e5b741899590751c2abdd/external/build_bazel_rules_apple/apple/internal/rule_factory.bzl", line 904, column 55, in _create_apple_bundling_rule
                rule_attrs.append(_common_binary_linking_attrs(rule_descriptor))
        File "/home/vscode/.cache/bazel/_bazel_vscode/5749526a064e5b741899590751c2abdd/external/build_bazel_rules_apple/apple/internal/rule_factory.bzl", line 218, column 21, in _common_binary_linking_attrs
                apple_common.objc_proto_aspect,
Error: 'apple_common' value has no field or method 'objc_proto_aspect'
ERROR: Analysis of target '//lte/gateway/python/magma/subscriberdb/tests:client_tests-runner.py' failed; build aborted: error loading package '@com_github_grpc_grpc//': at /home/vscode/.cache/bazel/_bazel_vscode/5749526a064e5b741899590751c2abdd/external/com_github_grpc_grpc/bazel/grpc_build_system.bzl:28:6: at /home/vscode/.cache/bazel/_bazel_vscode/5749526a064e5b741899590751c2abdd/external/build_bazel_rules_apple/apple/ios.bzl:22:5: initialization of module 'apple/internal/testing/ios_rules.bzl' failed
INFO: Elapsed time: 12.540s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (188 packages loaded, 1010 targets configured)
    currently loading: @com_github_grpc_grpc//
    Fetching @go_sdk; Downloading and extracting Go toolchain 5s
    Fetching @python_deps_pypi__systemd; fetching 5s
    Fetching @python_deps_pypi__setuptools; fetching
    Fetching @python_deps_pypi__snowflake; fetching
    Fetching @python_deps_pypi__cffi; fetching
    Fetching @python_deps_pypi__idna; fetching
    Fetching @python_deps_pypi__priority; fetching
    Fetching @python_deps_pypi__urllib3; fetching ... (13 fetches)
```

**Comment by electronjoe** [comment]
False alarm, my workflow was at fault. Or at least the breakage is not so feasible in CI as I had feared.

My `rm .bazel*` was catching and removing `.bazelrc` - which was causing this failure.

**Comment by electronjoe** [comment]
As noted by @nstng - most likely I broke things by updating my Bazel build version through deletion of `.bazelversion`.
