### ISSUE TITLE
mme: memory leak with init_call_data

### ISSUE THREAD

**Issue by themarwhal** [magma/magma#11968]
As soon as I ran`make integ_test` locally, I'm seeing
```bash
ar 04 15:49:58 magma-dev-focal mme[37541]: TASK_SCTP terminated
Mar 04 15:50:00 magma-dev-focal mme[37541]: [ITTI][D] Some threads are still running, force exit
Mar 04 15:50:00 magma-dev-focal mme[37541]: Cleaning up SPGW configsE: 22-03-04 15:50:00 [37541]dangling 'PUSH' socket created at /home/vagrant/magma/lte/gateway/c/core/oai/lib/itti/intertask_interface.c:206
Mar 04 15:50:00 magma-dev-focal mme[37541]: E: 22-03-04 15:50:00 [37541]dangling 'PUSH' socket created at /home/vagrant/magma/lte/gateway/c/core/oai/lib/itti/intertask_interface.c:206
Mar 04 15:50:00 magma-dev-focal mme[37541]: E: 22-03-04 15:50:00 [37541]dangling 'PULL' socket created at /home/vagrant/magma/lte/gateway/c/core/oai/lib/itti/intertask_interface.c:214
Mar 04 15:50:00 magma-dev-focal mme[37541]: =================================================================
Mar 04 15:50:00 magma-dev-focal mme[37541]: ==37541==ERROR: LeakSanitizer: detected memory leaks
Mar 04 15:50:00 magma-dev-focal mme[37541]: Direct leak of 728 byte(s) in 1 object(s) allocated from:
Mar 04 15:50:00 magma-dev-focal mme[37541]:     #0 0x7f0dc153d3d1 in operator new(unsigned long) (/lib/x86_64-linux-gnu/liblsan.so.0+0x103d1)
Mar 04 15:50:00 magma-dev-focal mme[37541]:     #1 0x55f9e4298c7e in magma::S6aProxyResponderAsyncService::init_call_data() /home/vagrant/magma/lte/gateway/c/core/oai/tasks/async_grpc_service/grpc_async_service_task.cpp:91
Mar 04 15:50:00 magma-dev-focal mme[37541]:     #2 0x55f9e4297934 in magma::AsyncService::wait_for_requests() /home/vagrant/magma/lte/gateway/c/core/oai/tasks/async_grpc_service/grpc_async_service_task.cpp:55
Mar 04 15:50:00 magma-dev-focal mme[37541]:     #3 0x55f9e4297a27 in operator() /home/vagrant/magma/lte/gateway/c/core/oai/tasks/async_grpc_service/grpc_async_service_task.cpp:207
Mar 04 15:50:00 magma-dev-focal mme[37541]:     #4 0x55f9e4297a27 in __invoke_impl<void, grpc_async_service_thread(void*)::<lambda()> > /usr/include/c++/9/bits/invoke.h:60
Mar 04 15:50:00 magma-dev-focal mme[37541]:     #5 0x55f9e4297a27 in __invoke<grpc_async_service_thread(void*)::<lambda()> > /usr/include/c++/9/bits/invoke.h:95
Mar 04 15:50:00 magma-dev-focal mme[37541]:     #6 0x55f9e4297a27 in _M_invoke<0> /usr/include/c++/9/thread:244
Mar 04 15:50:00 magma-dev-focal mme[37541]:     #7 0x55f9e4297a27 in operator() /usr/include/c++/9/thread:251
Mar 04 15:50:00 magma-dev-focal mme[37541]:     #8 0x55f9e4297a27 in _M_run /usr/include/c++/9/thread:195
Mar 04 15:50:00 magma-dev-focal mme[37541]:     #9 0x7f0dc0411d83  (/lib/x86_64-linux-gnu/libstdc++.so.6+0xd6d83)
Mar 04 15:50:00 magma-dev-focal mme[37541]: Direct leak of 632 byte(s) in 1 object(s) allocated from:
Mar 04 15:50:00 magma-dev-focal mme[37541]:     #0 0x7f0dc153d651 in operator new(unsigned long, std::nothrow_t const&) (/lib/x86_64-linux-gnu/liblsan.so.0+0x10651)
Mar 04 15:50:00 magma-dev-focal mme[37541]:     #1 0x7f0dbfba4744 in zmq_ctx_new (/lib/x86_64-linux-gnu/libzmq.so.5+0x79744)
Mar 04 15:50:00 magma-dev-focal mme[37541]: Direct leak of 240 byte(s) in 3 object(s) allocated from:
Mar 04 15:50:00 magma-dev-focal mme[37541]:     #0 0x7f0dc153d511 in operator new[](unsigned long) (/lib/x86_64-linux-gnu/liblsan.so.0+0x10511)
Mar 04 15:50:00 magma-dev-focal mme[37541]:     #1 0x7f0dc09ceb73 in fluid_base::BaseOFConnection::OFReadBuffer::read_notify(unsigned short) fluid/base/BaseOFConnection.cc:84
Mar 04 15:50:00 magma-dev-focal mme[37541]:     #2 0x7f0dc09ceb73 in fluid_base::BaseOFConnection::OFReadBuffer::read_notify(unsigned short) fluid/base/BaseOFConnection.cc:77
Mar 04 15:50:00 magma-dev-focal mme[37541]:     #3 0x7f0dc09ceb73 in fluid_base::BaseOFConnection::LibEventBaseOFConnection::read_cb(bufferevent*, void*) fluid/base/BaseOFConnection.cc:353
Mar 04 15:50:00 magma-dev-focal mme[37541]: Direct leak of 48 byte(s) in 1 object(s) allocated from:
Mar 04 15:50:00 magma-dev-focal mme[37541]:     #0 0x7f0dc153c722  (/lib/x86_64-linux-gnu/liblsan.so.0+0xf722)
Mar 04 15:50:00 magma-dev-focal mme[37541]:     #1 0x7f0dc0838c0f in zlist_new (/lib/x86_64-linux-gnu/libczmq.so.4+0x24c0f)
Mar 04 15:50:00 magma-dev-focal mme[37541]: Direct leak of 19 byte(s) in 1 object(s) allocated from:
Mar 04 15:50:00 magma-dev-focal mme[37541]:     #0 0x7f0dc153c9d1 in malloc (/lib/x86_64-linux-gnu/liblsan.so.0+0xf9d1)
Mar 04 15:50:00 magma-dev-focal mme[37541]:     #1 0x7f0dc01d050e in strdup (/lib/x86_64-linux-gnu/libc.so.6+0xa250e)
Mar 04 15:50:00 magma-dev-focal mme[37541]: Indirect leak of 1088 byte(s) in 1 object(s) allocated from:
Mar 04 15:50:00 magma-dev-focal mme[37541]:     #0 0x7f0dc153cfde in __interceptor_posix_memalign (/lib/x86_64-linux-gnu/liblsan.so.0+0xffde)
Mar 04 15:50:00 magma-dev-focal mme[37541]:     #1 0x7f0dbfb5ea94  (/lib/x86_64-linux-gnu/libzmq.so.5+0x33a94)
Mar 04 15:50:00 magma-dev-focal mme[37541]: SUMMARY: LeakSanitizer: 2755 byte(s) leaked in 8 allocation(s).
Mar 04 15:50:00 magma-dev-focal systemd[1]: magma@mme.service: Main process exited, code=exited, status=23/n/a
Mar 04 15:50:00 magma-dev-focal mme[38223]: ERROR:root:Failed to write to redis, status Error 111 connecting to 127.0.0.1:6380. Connection refused.
Mar 04 15:50:00 magma-dev-focal mme[38223]: ERROR:root:Logging exit info instead
Mar 04 15:50:00 magma-dev-focal mme[38223]: latest_service_result: EXIT_CODE
Mar 04 15:50:00 magma-dev-focal mme[38223]: latest_exit_code: EXITED
Mar 04 15:50:00 magma-dev-focal mme[38223]: latest_rc: 23
Mar 04 15:50:00 magma-dev-focal systemd[1]: magma@mme.service: Failed with result 'exit-code'.
```

**Comment by themarwhal** [comment]
This probably happens after the config change + restart.
