### ISSUE TITLE
[pipelined] : pipelined_cli.py not working with "debug qos" option

### ISSUE THREAD

**Issue by GANESH-WAVELABS** [magma/magma#12337]
pipelined_cli.py not working with "debug qos" option
```
(python) vagrant@magma-dev-focal:~/magma/lte/gateway/python/scripts$ ./pipelined_cli.py debug qos
Traceback (most recent call last):
  File "./pipelined_cli.py", line 936, in <module>
    main()
  File "./pipelined_cli.py", line 932, in main
    args.func(args, PipelinedStub, 'pipelined')
  File "/home/vagrant/magma/lte/gateway/python/magma/pipelined/qos/common.py", line 204, in debug
    qos_store = QosStore(cls.__name__)
TypeError: __init__() missing 1 required positional argument: 'client'
```

**Comment by GANESH-WAVELABS** [comment]
[29-March-2022 : Ganesh . I] Following PR has been raised for this task #12338 
 https://github.com/magma/magma/pull/12338
