### ISSUE TITLE
Observed TraceBacks in Pipelined service during stopping of magma services.

### ISSUE THREAD

**Issue by NeelimaKalpana** [magma/magma#12603]
Version: 1.8.0-1651212312-98651caf
-Affected Component: Access Gateway.
- Affected Subcomponent: AGW service
- Deployment Environment:  bare-metal (AGW)-VM Based

### Describe the Issue
AMF is throwing  Back traces in pipelined service during stopping of services.
**To Reproduce**
Stop magma service using
sudo service magma@* stop

and see that coredump getting generated in mme in /var/core path.

**Screenshots**

BT from core Dump:

![image.png](https://images.zenhubusercontent.com/6139f1931bcb9da2af1bf651/e0d3e10d-d934-471a-8259-3bf68ba807ab)

TraceBack :

Apr 29 08:58:31 localhost pipelined[3450324]: Traceback (most recent call last):
Apr 29 08:58:31 localhost pipelined[3450324]:   File "/usr/local/lib/python3.8/dist-packages/magma/pipelined/qos/tc_ops_pyroute2.py", line 135, in del_filter
Apr 29 08:58:31 localhost pipelined[3450324]:     ret = self._ipr.tc(
Apr 29 08:58:31 localhost pipelined[3450324]:   File "/usr/local/lib/python3.8/dist-packages/pyroute2/iproute/linux.py", line 1614, in tc
Apr 29 08:58:31 localhost pipelined[3450324]:     return tuple(self.nlm_request(msg, msg_type=command, msg_flags=flags))
Apr 29 08:58:31 localhost pipelined[3450324]:   File "/usr/local/lib/python3.8/dist-packages/pyroute2/netlink/nlsocket.py", line 376, in nlm_request
Apr 29 08:58:31 localhost pipelined[3450324]:     return tuple(self._genlm_request(*argv, **kwarg))
Apr 29 08:58:31 localhost pipelined[3450324]:   File "/usr/local/lib/python3.8/dist-packages/pyroute2/netlink/nlsocket.py", line 867, in nlm_request
Apr 29 08:58:31 localhost pipelined[3450324]:     for msg in self.get(msg_seq=msg_seq,
Apr 29 08:58:31 localhost pipelined[3450324]:   File "/usr/local/lib/python3.8/dist-packages/pyroute2/netlink/nlsocket.py", line 379, in get
Apr 29 08:58:31 localhost pipelined[3450324]:     return tuple(self._genlm_get(*argv, **kwarg))
Apr 29 08:58:31 localhost pipelined[3450324]:   File "/usr/local/lib/python3.8/dist-packages/pyroute2/netlink/nlsocket.py", line 704, in get
Apr 29 08:58:31 localhost pipelined[3450324]:     raise msg['header']['error']
Apr 29 08:58:31 localhost pipelined[3450324]: pyroute2.netlink.exceptions.NetlinkError: (2, 'No such file or directory')
Apr 29 08:58:31 localhost pipelined[3450324]: DEBUG:pipelined.qos.tc_pyroute2:Delete HTB iface eth0 qid 0x7
Apr 29 08:58:31 localhost pipelined[3450324]: DEBUG:pipelined.qos.tc_pyroute2:Return: ({'header': {'length': 36, 'type': 2, 'flags': 256, 'sequence_number': 259, 'pid': 3450324, 'error': None, 'target': 'localhost', 'stats': Stats(qsize=0, delta=0, delay=0)}, 'event': 'NLMSG_ERROR'},)
Apr 29 08:58:31 localhost pipelined[3450324]: DEBUG:pipelined.qos.qos_tc_impl:TC-dump: class htb 1:8 parent 1:6 prio 1 rate 80Kbit ceil 1Mbit burst 1600b cburst 1600b qid 8 pqid 6
@@@
[Uploading... core-1651229266-mme-3498212.tgz]

**Comment by NeelimaKalpana** [comment]
Hi Prabinak,

Please find the requested logs from the attachment.[https://app.zenhub.com/files/170803235/36408b8c-4895-43aa-90be-e62c1de30f0c/download](https://app.zenhub.com/files/170803235/36408b8c-4895-43aa-90be-e62c1de30f0c/download)

**Comment by NeelimaKalpana** [comment]
Closing the this issue as it is not observed in the latest master .
