### ISSUE TITLE
Investigate state of `load_test`s and relevance for bazel migration

### ISSUE THREAD

**Issue by LKreutzer** [magma/magma#13813]
- where are the load tests currently used and how are they setup?
- how could a bazel setup look like?

timeboxed: 2

**Comment by LKreutzer** [comment]
See https://github.com/magma/magma/issues/13591

**Comment by LKreutzer** [comment]
Target is defined in https://vscode.dev/github/magma/magma/blob/cafcace4e0551b57acf32db8f61a036e21cff665/lte/gateway/python/load_tests/Makefile#L14

Only use in https://vscode.dev/github/magma/magma/blob/cafcace4e0551b57acf32db8f61a036e21cff665/lte/gateway/fabfile.py#L911

**Comment by LKreutzer** [comment]
Some of the load tests were bazelified in https://github.com/magma/magma/pull/13451

**Comment by LKreutzer** [comment]
The ordering of the tests is relevant!

**Comment by LKreutzer** [comment]
`_run_load_tests` function was refactored in https://github.com/magma/magma/pull/14173

**Comment by LKreutzer** [comment]
None of the test sets works locally.
Services are running normal.

Errors for each group are:
```
. /home/vagrant/build/python/bin/activate
echo "Running load test: loadtest_policydb.py:enable_static_rules"
Running load test: loadtest_policydb.py:enable_static_rules
timeout --foreground -k 930s 900s sudo -E PATH=/home/vagrant/.local/bin:/usr/lib/ccache:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/snap/bin:/usr/local/go/bin:/usr/local/bin/go/:/home/vagrant/go/bin/ /home/vagrant/build/python/bin/python3 loadtest_policydb.py enable_static_rules || exit 1
Preparing enable_static_rules load test...
Traceback (most recent call last):
  File "loadtest_policydb.py", line 166, in <module>
    main()
  File "loadtest_policydb.py", line 160, in main
    args.func(args)
  File "loadtest_policydb.py", line 85, in enable_static_rules_test
    benchmark_grpc_request(
  File "/home/vagrant/magma/lte/gateway/python/load_tests/common.py", line 91, in benchmark_grpc_request
    if not Path(import_path).exists():
  File "/usr/lib/python3.8/pathlib.py", line 1042, in __new__
    self = cls._from_parts(args, init=False)
  File "/usr/lib/python3.8/pathlib.py", line 683, in _from_parts
    drv, root, parts = self._parse_args(args)
  File "/usr/lib/python3.8/pathlib.py", line 667, in _parse_args
    a = os.fspath(a)
TypeError: expected str, bytes or os.PathLike object, not NoneType
make: *** [Makefile:16: load_test] Error 1

```

**Comment by LKreutzer** [comment]
Last time that people discussed them actively on slack was ca. Oct. 2021

**Comment by LKreutzer** [comment]
Used for load testing before the release in 2021. See  https://github.com/magma/magma/pull/9698#issuecomment-944354534

**Comment by LKreutzer** [comment]
- Should be removed from bazel `.deb`
- Likely not used currently. Not used in CI.
- Assess a possible fix for running with Make.
  - If possible migrate to Bazel
  - Else discuss further steps.

**Comment by LKreutzer** [comment]
Issue:
   `import_path (str): protobuf import path` is `None`

**Comment by LKreutzer** [comment]
Initial commit:
`IMPORT_PATH = '/home/vagrant/magma'` 18 months ago
`IMPORT_PATH = str(Path.home()) + '/magma'` 12 months ago
11 months ago:
```
parents = Path.cwd().parents
parts = Path.cwd().parts
home = str(Path.home())
if 'lte' in parts and len(parents) > 3:
    # Get relative import path for protos
    IMPORT_PATH = parents[3]
else:
    IMPORT_PATH = str(home) + '/magma'
```
7 months ago:
`import_path` removed in https://github.com/magma/magma/pull/12086

**Comment by LKreutzer** [comment]
Error `No such file or directory: 'allocate_data.json'` 
This file never existed in the projekt. See output of `git log --all --full-history -- "**/thefile.*"`

**Comment by LKreutzer** [comment]
- `git checkout 7b214c83f8a93c4b07e59c85c626738979a185ce`
  - WORKING!
  - `Author: Alex Rodriguez <alexrod@fb.com> Date:   Sun Nov 14 21:44:45 2021 -0800`
  - `fix(agw): Updating import path for load test protos (#10264)`

**Comment by LKreutzer** [comment]
These commits are also working for the load tests:
```
commit 76d1a6caf040aa30e71a68e5e3de140c5cf10a3d (pruthvihebbani/s1sim_tcs_eps_bearer_context_status_ie)
Merge: fb1a1694f9 178218a654
Author: Pruthvi Hebbani <pruthvi.hebbani@radisys.com>
Date:   Tue Dec 14 14:21:34 2021 +0530

    Merge remote-tracking branch 'upstream/master' into s1sim_tcs_eps_bearer_context_status_ie

commit e23dd7e192aaab25bd472d5eba69cbad96323ef0
Merge: 758ec388b9 928e417667
Author: Pruthvi Hebbani <pruthvi.hebbani@radisys.com>
Date:   Mon Nov 22 10:34:52 2021 +0530

    Merge remote-tracking branch 'upstream/master' into handle_eps_bearer_context_status_ie
```

**Comment by LKreutzer** [comment]
Going through `git log --all --full-history -- "lte/gateway/python/load_tests/common.py"`

The first commit that breaks the load tests is:
```
commit f98b0b406ec3dd84f8231b4ad71803a476b331d5
Author: Fritz Lehnert <Fritz.Lehnert@tngtech.com>
Date:   Thu Mar 24 10:37:18 2022 +0100

    chore: fix mypy static type checking issues (#12086)
    
    * chore: reduce mypy exclusion list
    
    Signed-off-by: Fritz Lehnert <Fritz.Lehnert@tngtech.com>
    
    * chore: import_path is always given and must not be optional
```

**Comment by LKreutzer** [comment]
Go to `lte/gateway` then run `mypy --ignore-missing-imports python/load_tests` to check mypy.

**Comment by LKreutzer** [comment]
Load tests are fixed in https://github.com/magma/magma/pull/14287

**Comment by LKreutzer** [comment]
- [ ] Update Readme
- [ ] Migrate all as bazel scripts
- [ ] Create bash script to run them all
- [ ] Remove Make for load tests

**Comment by LKreutzer** [comment]
Make output:
```
vagrant@magma-dev:~/magma$ make -C $MAGMA_ROOT/lte/gateway/python/load_tests load_test
make: Entering directory '/home/vagrant/magma/lte/gateway/python/load_tests'
. /home/vagrant/build/python/bin/activate
echo "Running load test: loadtest_mobilityd.py:allocate"
Running load test: loadtest_mobilityd.py:allocate
timeout --foreground -k 930s 900s sudo -E PATH=/home/vagrant/.local/bin:/usr/lib/ccache:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/snap/bin:/usr/local/go/bin:/usr/local/bin/go/:/home/vagrant/go/bin/ /home/vagrant/build/python/bin/python3 loadtest_mobilityd.py allocate || exit 1
Preparing allocate load test...
Done
sleep 1; 	echo "Running load test: loadtest_mobilityd.py:release"
Running load test: loadtest_mobilityd.py:release
timeout --foreground -k 930s 900s sudo -E PATH=/home/vagrant/.local/bin:/usr/lib/ccache:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/snap/bin:/usr/local/go/bin:/usr/local/bin/go/:/home/vagrant/go/bin/ /home/vagrant/build/python/bin/python3 loadtest_mobilityd.py release || exit 1
Preparing release load test...
Done
sleep 1; 	echo "Running load test: loadtest_pipelined.py:activate_flows"
Running load test: loadtest_pipelined.py:activate_flows
timeout --foreground -k 930s 900s sudo -E PATH=/home/vagrant/.local/bin:/usr/lib/ccache:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/snap/bin:/usr/local/go/bin:/usr/local/bin/go/:/home/vagrant/go/bin/ /home/vagrant/build/python/bin/python3 loadtest_pipelined.py activate_flows || exit 1
Preparing activate_flows load test...
QOS Enabled
Done
sleep 1; 	echo "Running load test: loadtest_pipelined.py:deactivate_flows"
Running load test: loadtest_pipelined.py:deactivate_flows
timeout --foreground -k 930s 900s sudo -E PATH=/home/vagrant/.local/bin:/usr/lib/ccache:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/snap/bin:/usr/local/go/bin:/usr/local/bin/go/:/home/vagrant/go/bin/ /home/vagrant/build/python/bin/python3 loadtest_pipelined.py deactivate_flows || exit 1
Preparing deactivate_flows load test...
Done
sleep 1; 	echo "Running load test: loadtest_sessiond.py:create"
Running load test: loadtest_sessiond.py:create
timeout --foreground -k 930s 900s sudo -E PATH=/home/vagrant/.local/bin:/usr/lib/ccache:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/snap/bin:/usr/local/go/bin:/usr/local/bin/go/:/home/vagrant/go/bin/ /home/vagrant/build/python/bin/python3 loadtest_sessiond.py create || exit 1
Preparing create load test...
Done
sleep 1; 	echo "Running load test: loadtest_sessiond.py:end"
Running load test: loadtest_sessiond.py:end
timeout --foreground -k 930s 900s sudo -E PATH=/home/vagrant/.local/bin:/usr/lib/ccache:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/snap/bin:/usr/local/go/bin:/usr/local/bin/go/:/home/vagrant/go/bin/ /home/vagrant/build/python/bin/python3 loadtest_sessiond.py end || exit 1
Preparing end load test...
Done
sleep 1; 	echo "Running load test: loadtest_subscriberdb.py:add"
Running load test: loadtest_subscriberdb.py:add
timeout --foreground -k 930s 900s sudo -E PATH=/home/vagrant/.local/bin:/usr/lib/ccache:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/snap/bin:/usr/local/go/bin:/usr/local/bin/go/:/home/vagrant/go/bin/ /home/vagrant/build/python/bin/python3 loadtest_subscriberdb.py add || exit 1
Preparing add load test...
Done
sleep 1; 	echo "Running load test: loadtest_subscriberdb.py:list"
Running load test: loadtest_subscriberdb.py:list
timeout --foreground -k 930s 900s sudo -E PATH=/home/vagrant/.local/bin:/usr/lib/ccache:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/snap/bin:/usr/local/go/bin:/usr/local/bin/go/:/home/vagrant/go/bin/ /home/vagrant/build/python/bin/python3 loadtest_subscriberdb.py list || exit 1
Preparing list load test...
Done
sleep 1; 	echo "Running load test: loadtest_subscriberdb.py:delete"
Running load test: loadtest_subscriberdb.py:delete
timeout --foreground -k 930s 900s sudo -E PATH=/home/vagrant/.local/bin:/usr/lib/ccache:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/snap/bin:/usr/local/go/bin:/usr/local/bin/go/:/home/vagrant/go/bin/ /home/vagrant/build/python/bin/python3 loadtest_subscriberdb.py delete || exit 1
Preparing delete load test...
Done
sleep 1; 	echo "Running load test: loadtest_subscriberdb.py:get"
Running load test: loadtest_subscriberdb.py:get
timeout --foreground -k 930s 900s sudo -E PATH=/home/vagrant/.local/bin:/usr/lib/ccache:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/snap/bin:/usr/local/go/bin:/usr/local/bin/go/:/home/vagrant/go/bin/ /home/vagrant/build/python/bin/python3 loadtest_subscriberdb.py get || exit 1
Preparing get load test...
Done
sleep 1; 	echo "Running load test: loadtest_subscriberdb.py:update"
Running load test: loadtest_subscriberdb.py:update
timeout --foreground -k 930s 900s sudo -E PATH=/home/vagrant/.local/bin:/usr/lib/ccache:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/snap/bin:/usr/local/go/bin:/usr/local/bin/go/:/home/vagrant/go/bin/ /home/vagrant/build/python/bin/python3 loadtest_subscriberdb.py update || exit 1
Preparing update load test...
Done
sleep 1; 	echo "Running load test: loadtest_policydb.py:enable_static_rules"
Running load test: loadtest_policydb.py:enable_static_rules
timeout --foreground -k 930s 900s sudo -E PATH=/home/vagrant/.local/bin:/usr/lib/ccache:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/snap/bin:/usr/local/go/bin:/usr/local/bin/go/:/home/vagrant/go/bin/ /home/vagrant/build/python/bin/python3 loadtest_policydb.py enable_static_rules || exit 1
Preparing enable_static_rules load test...
Done
sleep 1; 	echo "Running load test: loadtest_policydb.py:disable_static_rules"
Running load test: loadtest_policydb.py:disable_static_rules
timeout --foreground -k 930s 900s sudo -E PATH=/home/vagrant/.local/bin:/usr/lib/ccache:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/snap/bin:/usr/local/go/bin:/usr/local/bin/go/:/home/vagrant/go/bin/ /home/vagrant/build/python/bin/python3 loadtest_policydb.py disable_static_rules || exit 1
Preparing disable_static_rules load test...
Done
sleep 1;
make: Leaving directory '/home/vagrant/magma/lte/gateway/python/load_tests'
```

**Comment by LKreutzer** [comment]
Bazel script output:
```
vagrant@magma-dev:~/magma$ ./bazel/scripts/run_load_tests.sh 
Building load tests...
INFO: Invocation ID: c9bd9af4-0a8c-4ad1-9d6c-e1a37495bef5
INFO: Reading 'startup' options from /home/vagrant/magma/.bazelrc: --output_base=/tmp/bazel, --host_jvm_args=-Xmx8g
INFO: Options provided by the client:
  Inherited 'common' options: --isatty=1 --terminal_columns=207
INFO: Reading rc options for 'build' from /home/vagrant/magma/bazel/bazelrcs/cache.bazelrc:
  Inherited 'common' options: --config=disk_cache
INFO: Reading rc options for 'build' from /home/vagrant/magma/.bazelrc:
  'build' options: --announce_rc --color=yes --cxxopt=-std=c++14 --strip=never --per_file_copt=^lte/gateway/c/.*$@-g --define=folly_so=1 --test_env=PATH=/bin:/usr/bin:/usr/local/bin:/usr/sbin --test_env=MAGMA_ROOT --test_env=S1AP_TESTER_ROOT --per_file_copt=^lte/gateway/c/core/.*$@-DPACKAGE_BUGREPORT="TBD" --per_file_copt=^lte/gateway/c/core/.*$@-DPACKAGE_VERSION="0.1" --per_file_copt=^lte/gateway/c/core/oai/tasks/amf/.*$@-DPACKAGE_NAME="AMF" --per_file_copt=^lte/gateway/c/core/oai/tasks/mme_app/.*$@-DPACKAGE_NAME="MME" --per_file_copt=^lte/gateway/c/core/oai/tasks/sgw/.*$@-DPACKAGE_NAME="S/P-GW" --javacopt=-source 8 --javacopt=-target 8 --java_runtime_version=remotejdk_11
INFO: Reading rc options for 'build' from /home/vagrant/magma/bazel/bazelrcs/vm.bazelrc:
  'build' options: --config=vm
INFO: Found applicable config definition common:disk_cache in file /home/vagrant/magma/.bazelrc: --repository_cache=/var/cache/bazel-cache-repo
INFO: Found applicable config definition build:disk_cache in file /home/vagrant/magma/.bazelrc: --disk_cache=/var/cache/bazel-cache
INFO: Found applicable config definition build:vm in file /home/vagrant/magma/.bazelrc: --config=specify_vm_cc
INFO: Found applicable config definition build:specify_vm_cc in file /home/vagrant/magma/.bazelrc: --action_env=CC=/usr/bin/gcc
INFO: Analyzed 6 targets (0 packages loaded, 0 targets configured).
INFO: Found 6 targets...
INFO: Elapsed time: 0.147s, Critical Path: 0.00s
INFO: 1 process: 1 internal.
INFO: Build completed successfully, 1 total action
Finished building load tests.
Running load tests...
Running load test: loadtest_mobilityd allocate
Preparing allocate load test...
Done
Running load test: loadtest_mobilityd release
Preparing release load test...
Done
Running load test: loadtest_pipelined activate_flows
/home/vagrant/magma/bazel-bin/lte/gateway/python/load_tests/loadtest_pipelined.runfiles/ryu_repo/ryu/lib/packet/cfm.py:271: SyntaxWarning: "is not" with a literal. Did you mean "!="?
  assert interval is not 0
Preparing activate_flows load test...
QOS Enabled
Done
Running load test: loadtest_pipelined deactivate_flows
/home/vagrant/magma/bazel-bin/lte/gateway/python/load_tests/loadtest_pipelined.runfiles/ryu_repo/ryu/lib/packet/cfm.py:271: SyntaxWarning: "is not" with a literal. Did you mean "!="?
  assert interval is not 0
Preparing deactivate_flows load test...
Done
Running load test: loadtest_sessiond create
Preparing create load test...
Done
Running load test: loadtest_sessiond end
Preparing end load test...
Done
Running load test: loadtest_subscriberdb add
Preparing add load test...
Done
Running load test: loadtest_subscriberdb list
Preparing list load test...
Done
Running load test: loadtest_subscriberdb delete
Preparing delete load test...
Done
Running load test: loadtest_subscriberdb get
Preparing get load test...
Done
Running load test: loadtest_subscriberdb update
Preparing update load test...
Done
Running load test: loadtest_policydb enable_static_rules
Preparing enable_static_rules load test...
Done
Running load test: loadtest_policydb disable_static_rules
Preparing disable_static_rules load test...
Done
Finished running load tests.
```
