### ISSUE TITLE
Stabilize another flaky orc8r test

### ISSUE THREAD

**Issue by sebathomas** [magma/magma#13998]
- [ ] Fix and test flaky indexer tests.
- [ ] Prepare internal review meeting.

Recently, the test `reindexer_queue_test.go` has been pretty flaky. It is likely that the issues are similar to what we observed for the other reindexer test in #13537.

```
=== Failed
=== FAIL: services/state/indexer/reindex TestSingletonRunFail (1.59s)
I0923 07:10:56.334022    9591 service_config.go:161] Successfully loaded 'orc8r::accessd' service configs from '/etc/magma/configs/orc8r/accessd.yml'
I0923 07:10:56.334065    9591 service.go:128] Registering Service303 as a protected GRPC server.
I0923 07:10:56.336968    9591 reindexer_singleton.go:62] Sleeping for 1 minute(s) before looking for new jobs to reindex
W0923 07:10:56.336982    9591 reindexer_singleton.go:52] State reindexing async job canceled
I0923 07:10:56.793285    9591 service_config.go:161] Successfully loaded 'orc8r::certifier' service configs from '/etc/magma/configs/orc8r/certifier.yml'
I0923 07:10:56.793349    9591 service.go:128] Registering Service303 as a protected GRPC server.
I0923 07:10:56.793575    9591 service_config.go:161] Successfully loaded 'orc8r::configurator' service configs from '/etc/magma/configs/orc8r/configurator.yml'
I0923 07:10:56.793612    9591 service.go:128] Registering Service303 as a protected GRPC server.
I0923 07:10:56.794227    9591 service_config.go:161] Successfully loaded 'orc8r::device' service configs from '/etc/magma/configs/orc8r/device.yml'
I0923 07:10:56.794267    9591 service.go:128] Registering Service303 as a protected GRPC server.
I0923 07:10:56.794487    9591 service_config.go:161] Successfully loaded 'orc8r::state' service configs from '/etc/magma/configs/orc8r/state.yml'
I0923 07:10:56.794527    9591 service.go:128] Registering Service303 as a protected GRPC server.
    access.go:59: Test Gateway Certificate SN: F10F786D8507AD15528D4792E69B2DD3
    access.go:59: Test Gateway Certificate SN: 5F8331D3B19B076BA17BC59696A7C6FC
    access.go:59: Test Gateway Certificate SN: B07DB8453FE09A03778E10E57E2F9156
    access.go:59: Test Gateway Certificate SN: D28634C9540F61CFC10E0842288E46EF
W0923 07:10:57.697485    9591 service_config.go:189] Cannot find '/etc/magma/configs/orc8r/some_indexerid_1.yml': stat /etc/magma/configs/orc8r/some_indexerid_1.yml: no such file or directory, or Legacy Service Registry Configuration: '/etc/magma/orc8r/some_indexerid_1.yml': stat /etc/magma/orc8r/some_indexerid_1.yml: no such file or directory
E0923 07:10:57.697579    9591 service_config.go:159] Error Loading orc8r::some_indexerid_1 configs from '/etc/magma/orc8r/some_indexerid_1.yml': open /etc/magma/orc8r/some_indexerid_1.yml: no such file or directory
W0923 07:10:57.697594    9591 service.go:98] Failed to load config for service some_indexerid_1: open /etc/magma/orc8r/some_indexerid_1.yml: no such file or directory
I0923 07:10:57.697623    9591 service.go:128] Registering Service303 as a protected GRPC server.
W0923 07:10:57.697787    9591 service_config.go:189] Cannot find '/etc/magma/configs/orc8r/some_indexerid_2.yml': stat /etc/magma/configs/orc8r/some_indexerid_2.yml: no such file or directory, or Legacy Service Registry Configuration: '/etc/magma/orc8r/some_indexerid_2.yml': stat /etc/magma/orc8r/some_indexerid_2.yml: no such file or directory
E0923 07:10:57.697804    9591 service_config.go:159] Error Loading orc8r::some_indexerid_2 configs from '/etc/magma/orc8r/some_indexerid_2.yml': open /etc/magma/orc8r/some_indexerid_2.yml: no such file or directory
W0923 07:10:57.697816    9591 service.go:98] Failed to load config for service some_indexerid_2: open /etc/magma/orc8r/some_indexerid_2.yml: no such file or directory
I0923 07:10:57.697834    9591 service.go:128] Registering Service303 as a protected GRPC server.
W0923 07:10:57.698026    9591 service_config.go:189] Cannot find '/etc/magma/configs/orc8r/some_indexerid_3.yml': stat /etc/magma/configs/orc8r/some_indexerid_3.yml: no such file or directory, or Legacy Service Registry Configuration: '/etc/magma/orc8r/some_indexerid_3.yml': stat /etc/magma/orc8r/some_indexerid_3.yml: no such file or directory
E0923 07:10:57.698037    9591 service_config.go:159] Error Loading orc8r::some_indexerid_3 configs from '/etc/magma/orc8r/some_indexerid_3.yml': open /etc/magma/orc8r/some_indexerid_3.yml: no such file or directory
W0923 07:10:57.698045    9591 service.go:98] Failed to load config for service some_indexerid_3: open /etc/magma/orc8r/some_indexerid_3.yml: no such file or directory
I0923 07:10:57.698061    9591 service.go:128] Registering Service303 as a protected GRPC server.
E0923 07:10:57.702304    9591 interceptors.go:74] [ERROR /magma.orc8r.state.Indexer/PrepareReindex]: some_error_1
I0923 07:10:57.702683    9591 reindexer_singleton.go:150] Attempt at state reindex job {id: some_indexerid_1, from: 0, to: 20} took 0.001662 seconds
I0923 07:10:57.803286    9591 reindexer_singleton.go:62] Sleeping for 1 minute(s) before looking for new jobs to reindex
E0923 07:10:57.865993    9591 interceptors.go:74] [ERROR /magma.orc8r.state.Indexer/Index]: some_error_2
I0923 07:10:57.866242    9591 reindexer_singleton.go:150] Attempt at state reindex job {id: some_indexerid_2, from: 0, to: 30} took 0.059735 seconds
E0923 07:10:57.925844    9591 interceptors.go:74] [ERROR /magma.orc8r.state.Indexer/CompleteReindex]: some_error_3
I0923 07:10:57.926123    9591 reindexer_singleton.go:150] Attempt at state reindex job {id: some_indexerid_3, from: 0, to: 40} took 0.059746 seconds
E0923 07:10:57.926637    9591 interceptors.go:74] [ERROR /magma.orc8r.state.Indexer/PrepareReindex]: rpc error: code = Unknown desc = handler panic: 
assert: mock: The method has been called over 1 times.
	Either do one more Mock.On("PrepareReindex").Return(...), or remove extra call.
	This call was unexpected:
		PrepareReindex(indexer.Version,indexer.Version,bool)
		0: 0x0
		1: 0x14
		2: true
	at: [Indexer.go:126 test_indexer_servicer.go:68 indexer.pb.go:866 interceptors.go:90 server.go:1129 interceptors.go:90 server.go:1132 server_metrics.go:107 server.go:1132 interceptors.go:65 server.go:1132 interceptors.go:72 server.go:1132 server.go:1134 indexer.pb.go:868 server.go:1295 server.go:1636 server.go:932 asm_amd64.s:1571]; stack trace: goroutine 2874 [running]:
runtime/debug.Stack()
	/usr/local/go/src/runtime/debug/stack.go:24 +0x65
magma/orc8r/cloud/go/service/middleware/unary.recoveryInterceptor.func1()
	/src/magma/orc8r/cloud/go/service/middleware/unary/interceptors.go:61 +0x6b
panic({0xe565a0, 0xc0008cb560})
	/usr/local/go/src/runtime/panic.go:838 +0x207
github.com/stretchr/testify/mock.(*Mock).fail(0xc00192be00, {0x1022b79?, 0x20?}, {0xc0009bea00?, 0x3?, 0x3?})
	/go/pkg/mod/github.com/stretchr/testify@v1.7.0/mock/mock.go:254 +0x145
github.com/stretchr/testify/mock.(*Mock).MethodCalled(0xc00192be00, {0x12dd3af, 0xe}, {0xc001518180, 0x3, 0x3})
	/go/pkg/mod/github.com/stretchr/testify@v1.7.0/mock/mock.go:399 +0x29d
github.com/stretchr/testify/mock.(*Mock).Called(0xc0007b4668?, {0xc001518180, 0x3, 0x3})
	/go/pkg/mod/github.com/stretchr/testify@v1.7.0/mock/mock.go:383 +0x148
magma/orc8r/cloud/go/services/state/indexer/mocks.(*Indexer).PrepareReindex(0xc00192be00, 0x4191e5?, 0x0?, 0x1)
	/src/magma/orc8r/cloud/go/services/state/indexer/mocks/Indexer.go:126 +0xec
magma/orc8r/cloud/go/services/state/test_init.(*indexerServicer).PrepareReindex(0x29?, {0xc000ab9f20?, 0xc0010fb1e0?}, 0xc0010fb1e0?)
	/src/magma/orc8r/cloud/go/services/state/test_init/test_indexer_servicer.go:68 +0x2b
magma/orc8r/cloud/go/services/state/protos._Indexer_PrepareReindex_Handler.func1({0x114d9e8, 0xc001518090}, {0xf60620?, 0xc0016317c0})
	/src/magma/orc8r/cloud/go/services/state/protos/indexer.pb.go:866 +0x78
magma/orc8r/cloud/go/service/middleware/unary.makeInterceptorFromTemplate.func1({0x114d9e8, 0xc001518090}, {0xf60620, 0xc0016317c0}, 0xc001518150?, 0xc000b42330)
	/src/magma/orc8r/cloud/go/service/middleware/unary/interceptors.go:90 +0x8b
google.golang.org/grpc.chainUnaryInterceptors.func1.1({0x114d9e8?, 0xc001518090?}, {0xf60620?, 0xc0016317c0?})
	/go/pkg/mod/google.golang.org/grpc@v1.48.0/server.go:1129 +0x5b
magma/orc8r/cloud/go/service/middleware/unary.makeInterceptorFromTemplate.func1({0x114d9e8, 0xc001518090}, {0xf60620, 0xc0016317c0}, 0xc0016317c0?, 0xc0009be880)
	/src/magma/orc8r/cloud/go/service/middleware/unary/interceptors.go:90 +0x8b
google.golang.org/grpc.chainUnaryInterceptors.func1.1({0x114d9e8?, 0xc001518090?}, {0xf60620?, 0xc0016317c0?})
	/go/pkg/mod/google.golang.org/grpc@v1.48.0/server.go:1132 +0x83
github.com/grpc-ecosystem/go-grpc-prometheus.(*ServerMetrics).UnaryServerInterceptor.func1({0x114d9e8, 0xc001518090}, {0xf60620, 0xc0016317c0}, 0x16?, 0xc0009be880)
	/go/pkg/mod/github.com/grpc-ecosystem/go-grpc-prometheus@v1.2.0/server_metrics.go:107 +0x87
google.golang.org/grpc.chainUnaryInterceptors.func1.1({0x114d9e8?, 0xc001518090?}, {0xf60620?, 0xc0016317c0?})
	/go/pkg/mod/google.golang.org/grpc@v1.48.0/server.go:1132 +0x83
magma/orc8r/cloud/go/service/middleware/unary.recoveryInterceptor({0x114d9e8?, 0xc001518090?}, {0xf60620?, 0xc0016317c0?}, 0xc0009be880?, 0x16?)
	/src/magma/orc8r/cloud/go/service/middleware/unary/interceptors.go:65 +0xa2
google.golang.org/grpc.chainUnaryInterceptors.func1.1({0x114d9e8?, 0xc001518090?}, {0xf60620?, 0xc0016317c0?})
	/go/pkg/mod/google.golang.org/grpc@v1.48.0/server.go:1132 +0x83
magma/orc8r/cloud/go/service/middleware/unary.errlogInterceptor({0x114d9e8?, 0xc001518090?}, {0xf60620?, 0xc0016317c0?}, 0xc00045b500, 0x7ff3032f6501?)
	/src/magma/orc8r/cloud/go/service/middleware/unary/interceptors.go:72 +0x49
google.golang.org/grpc.chainUnaryInterceptors.func1.1({0x114d9e8?, 0xc001518090?}, {0xf60620?, 0xc0016317c0?})
	/go/pkg/mod/google.golang.org/grpc@v1.48.0/server.go:1132 +0x83
google.golang.org/grpc.chainUnaryInterceptors.func1({0x114d9e8, 0xc001518090}, {0xf60620, 0xc0016317c0}, 0xc00045b500, 0xc000b42330)
	/go/pkg/mod/google.golang.org/grpc@v1.48.0/server.go:1134 +0x12b
magma/orc8r/cloud/go/services/state/protos._Indexer_PrepareReindex_Handler({0xeeb880?, 0xc001d54c10}, {0x114d9e8, 0xc001518090}, 0xc00029aa80, 0xc0016a6580)
	/src/magma/orc8r/cloud/go/services/state/protos/indexer.pb.go:868 +0x138
google.golang.org/grpc.(*Server).processUnaryRPC(0xc0017fa960, {0x1151568, 0xc000625380}, 0xc000a2a000, 0xc001385c50, 0x19785b0, 0x0)
	/go/pkg/mod/google.golang.org/grpc@v1.48.0/server.go:1295 +0xb0b
google.golang.org/grpc.(*Server).handleStream(0xc0017fa960, {0x1151568, 0xc000625380}, 0xc000a2a000, 0x0)
	/go/pkg/mod/google.golang.org/grpc@v1.48.0/server.go:1636 +0xa1b
google.golang.org/grpc.(*Server).serveStreams.func1.2()
	/go/pkg/mod/google.golang.org/grpc@v1.48.0/server.go:932 +0x98
created by google.golang.org/grpc.(*Server).serveStreams.func1
	/go/pkg/mod/google.golang.org/grpc@v1.48.0/server.go:930 +0x28a
I0923 07:10:57.927286    9591 reindexer_singleton.go:150] Attempt at state reindex job {id: some_indexerid_1, from: 0, to: 20} took 0.001095 seconds
    reindexer_queue_test.go:437: should not receive anything from hook channel

DONE 551 tests, 1 failure in 194.692s
make[1]: *** [test] Error 1
/src/magma/orc8r/cloud/go/module.mk:100: recipe for target 'test' failed
make[1]: Leaving directory '/src/magma/orc8r/cloud/go'
make: *** [/src/magma/orc8r_test] Error 2
Makefile:134: recipe for target '/src/magma/orc8r_test' failed
2
```

Alternatively, sometimes you get the following error:
```
=== Failed
=== FAIL: services/state/indexer/reindex TestRunBrokenIndexer (1.22s)
I0923 13:32:17.316452    9601 service_config.go:161] Successfully loaded 'orc8r::accessd' service configs from '/etc/magma/configs/orc8r/accessd.yml'
I0923 13:32:17.316499    9601 service.go:128] Registering Service303 as a protected GRPC server.
I0923 13:32:17.559588    9601 service_config.go:161] Successfully loaded 'orc8r::certifier' service configs from '/etc/magma/configs/orc8r/certifier.yml'
I0923 13:32:17.559863    9601 service.go:128] Registering Service303 as a protected GRPC server.
I0923 13:32:17.560169    9601 service_config.go:161] Successfully loaded 'orc8r::configurator' service configs from '/etc/magma/configs/orc8r/configurator.yml'
I0923 13:32:17.560348    9601 service.go:128] Registering Service303 as a protected GRPC server.
I0923 13:32:17.561137    9601 service_config.go:161] Successfully loaded 'orc8r::device' service configs from '/etc/magma/configs/orc8r/device.yml'
I0923 13:32:17.561293    9601 service.go:128] Registering Service303 as a protected GRPC server.
I0923 13:32:17.568982    9601 test_init_utils.go:96] Overwriting existing SQL_DIALECT psql
I0923 13:32:17.628004    9601 test_init_utils.go:96] Overwriting existing SQL_DIALECT psql
I0923 13:32:17.628527    9601 service_config.go:161] Successfully loaded 'orc8r::state' service configs from '/etc/magma/configs/orc8r/state.yml'
I0923 13:32:17.628740    9601 service.go:128] Registering Service303 as a protected GRPC server.
    access.go:59: Test Gateway Certificate SN: 161B26355A3DC05A702D013DFFB81E51
    access.go:59: Test Gateway Certificate SN: 23A2D40EF801322DBE54943C0E7E6D08
    access.go:59: Test Gateway Certificate SN: FEE9EB0FCD82DF072D0F6C568F4A3C4
W0923 13:32:18.512077    9601 service_config.go:189] Cannot find '/etc/magma/configs/orc8r/some_indexerid_0.yml': stat /etc/magma/configs/orc8r/some_indexerid_0.yml: no such file or directory, or Legacy Service Registry Configuration: '/etc/magma/orc8r/some_indexerid_0.yml': stat /etc/magma/orc8r/some_indexerid_0.yml: no such file or directory
E0923 13:32:18.512195    9601 service_config.go:159] Error Loading orc8r::some_indexerid_0 configs from '/etc/magma/orc8r/some_indexerid_0.yml': open /etc/magma/orc8r/some_indexerid_0.yml: no such file or directory
W0923 13:32:18.512236    9601 service.go:98] Failed to load config for service some_indexerid_0: open /etc/magma/orc8r/some_indexerid_0.yml: no such file or directory
I0923 13:32:18.512297    9601 service.go:128] Registering Service303 as a protected GRPC server.
I0923 13:32:18.528509    9601 queue_sql.go:163] Succeeded in updating reindex job queue and overwriting new indexer versions
    reindexer_queue_test.go:216: PASS:	GetID()
    reindexer_queue_test.go:216: PASS:	GetVersion()
    reindexer_queue_test.go:216: PASS:	GetTypes()
    reindexer_queue_test.go:216: FAIL:	PrepareReindex(indexer.Version,indexer.Version,bool)
        		at: [reindexer_queue_test.go:210]
    reindexer_queue_test.go:216: FAIL:	Index(string,string)
        		at: [reindexer_queue_test.go:211]
    reindexer_queue_test.go:216: FAIL: 3 out of 5 expectation(s) were met.
        	The code you are testing needs to make 2 more call(s).
        	at: [reindexer_queue_test.go:216]
    reindexer_queue_test.go:459: 
        	Error Trace:	reindexer_queue_test.go:459
        	            				reindexer_queue_test.go:217
        	Error:      	"" does not contain "some_indexerid_0"
        	Test:       	TestRunBrokenIndexer
    reindexer_queue_test.go:461: 
        	Error Trace:	reindexer_queue_test.go:461
        	            				reindexer_queue_test.go:217
        	Error:      	"" does not contain "state reindex error: error from Reindex"
        	Test:       	TestRunBrokenIndexer
    reindexer_queue_test.go:463: 
        	Error Trace:	reindexer_queue_test.go:463
        	            				reindexer_queue_test.go:217
        	Error:      	"" does not contain "some_error"
        	Test:       	TestRunBrokenIndexer
```

**Comment by MoritzThomasHuebner** [comment]
The first test posted above is actually in `reindexer_singleton_test.go`. Upon going through the recent CI runs, the following tests seem to be failing this often:

TestSqlConfiguratorStorage_LoadEntities: 2
TestGetSubscriberState: 2
TestSingletonRunSuccess: 6
TestSingletonRunFail: 4
TestRunBrokenIndexer: 1
