### ISSUE TITLE
[AMF]: DNN Not supported Error value 27

### ISSUE THREAD

**Issue by panyogesh** [magma/magma#14107]
I'm moving from 1.7.0 and created a 1.8.0 system which I'm testing against an OAI gNB/UE at 5G. The OAI UE is getting registered but isn't getting an IP. I confirmed that the following files have enable5gfeatures or ENABLE5G_FEATURES set to true or True as required:
/etc/magma/gateway.mconfig
/var/opt/magma/configs/mme.yml
/var/opt/magma/configs/pipelined.yml
/var/opt/magma/configs/sessiond.yml
/var/opt/magma/configs/subscriberdb.yml
/var/opt/magma/tmp/mme.conf
The MME log shows "DNN is not Supported or not Subscribed, reject with a cause: 27". I added a debug statement to amf_validate_dnn and the dnn being checked is correct: "internet", however, there are no apns in apn_configuration[] that it is being tested against.
I can do "subscriberdb_cli.py list" and see the SID present. If I do "subscriber_cli.py get IMSI901700000000001" then I get an exception "Value out of range: 100000000000000". I can see this same exception in syslog after the MME sends S6A-UPDATE_LOCATION_REQUEST.
I have attached the MME log and an abbreviated syslog with the exception. This was a fresh install on a freshly imaged AMD Ubuntu 20.04 system. The orc8r was a fresh 1.8.0 install, too. (edited) [Uploading... MME.magma-5g-v18-1.root.log.INFO.20221007-184047.182306]

**Comment by panyogesh** [comment]
[Uploading... MME.magma-5g-v18-1.root.log.INFO.20221007-184047.182306]

**Comment by panyogesh** [comment]
Oct  7 19:02:00 magma-5g-v18-1 mme[182306]: [DEBUG] Sending S6A-UPDATE_LOCATION_REQUEST with IMSI: 901700000000001
Oct  7 19:02:00 magma-5g-v18-1 subscriberdb[181666]: ERROR:grpc._server:Exception calling application: Value out of range: 100000000000000
Oct  7 19:02:00 magma-5g-v18-1 subscriberdb[181666]: Traceback (most recent call last):
Oct  7 19:02:00 magma-5g-v18-1 subscriberdb[181666]:   File "/usr/local/lib/python3.8/dist-packages/grpc/_server.py", line 435, in _call_behavior
Oct  7 19:02:00 magma-5g-v18-1 subscriberdb[181666]:     response_or_iterator = behavior(argument, context)
Oct  7 19:02:00 magma-5g-v18-1 subscriberdb[181666]:   File "/usr/local/lib/python3.8/dist-packages/magma/subscriberdb/protocols/s6a_proxy_servicer.py", line 118, in UpdateLocation
Oct  7 19:02:00 magma-5g-v18-1 subscriberdb[181666]:     ula.total_ambr.max_bandwidth_ul = profile.max_ul_bit_rate
Oct  7 19:02:00 magma-5g-v18-1 subscriberdb[181666]:   File "/usr/local/lib/python3.8/dist-packages/google/protobuf/internal/python_message.py", line 702, in field_setter
Oct  7 19:02:00 magma-5g-v18-1 subscriberdb[181666]:     new_value = type_checker.CheckValue(new_value)
Oct  7 19:02:00 magma-5g-v18-1 subscriberdb[181666]:   File "/usr/local/lib/python3.8/dist-packages/google/protobuf/internal/type_checkers.py", line 170, in CheckValue
Oct  7 19:02:00 magma-5g-v18-1 subscriberdb[181666]:     raise ValueError('Value out of range: %d' % proposed_value)
Oct  7 19:02:00 magma-5g-v18-1 subscriberdb[181666]: ValueError: Value out of range: 100000000000000
Oct  7 19:02:00 magma-5g-v18-1 mme[182306]: [ERROR] 2: Exception calling application: Value out of range: 100000000000000
Oct  7 19:02:00 magma-5g-v18-1 mme[182306]: [ERROR]  Received S6A-LOCATION-UPDATE_ANSWER for IMSI: 901700000000001; Status: Exception calling application: Value out of range: 100000000000000; ErrorCode: 0
Oct  7 19:02:00 magma-5g-v18-1 mme[182306]: [INFO] sent itti S6A-LOCATION-UPDATE_ANSWER for IMSI: 901700000000001
Oct  7 19:02:00 magma-5g-v18-1 sctpd[181966]: I1007 19:02:00.497093 182346 sctp_connection.cpp:208] Unhandled notification type 32777

**Comment by shahrahman-fb** [comment]
Closing this issue as part of a repository cleanup effort. This issue has had no activity for over 2 years.

If this issue is still relevant, please reopen it or file a new issue with updated information. We are actively maintaining the project again and want to focus on current, actionable issues.

See: #15833 (Phase 1 cleanup), #15828 (tracking issue)
