### ISSUE TITLE
Bazel fails on devcontainer

### ISSUE THREAD

**Issue by jheidbrink** [magma/magma#14225]
### Describe the Issue

When starting a devcontainer, the console output will show an error when generating the compilation database. Running `bazel` in the devcontainer fails with `could not create directory /home/vscode/.cache/bazelisk: mkdir /home/vscode/.cache/bazelisk: permission denied`

#### To Reproduce

* If you have the magma workspace open in vscode, close it
* Remove existing magma vscode containers:
* * Find the IDs with `docker ps -a | grep vsc-magma`
* * For each ID: `docker rm <id>`
* Open the magma workspace with vscode. You should  see something like
```
Running the initializeCommand from devcontainer.json...

[397 ms] Start: Run: /bin/sh -c docker pull ghcr.io/magma/magma/devcontainer:latest
latest: Pulling from magma/magma/devcontainer
Digest: sha256:be79093aaed62879ce32d6f6d0d502fc6ab28d5fc651b22e26f79008ad894bd7
Status: Image is up to date for ghcr.io/magma/magma/devcontainer:latest
ghcr.io/magma/magma/devcontainer:latest

Running the postCreateCommand from devcontainer.json...

[3367 ms] Start: Run in container:
Assuming the devcontainer is opened locally, not using Bazel remote cache...
Generating compile_commands.json for C/C++ code navigation
2022/10/20 08:59:52 could not create directory /home/vscode/.cache/bazelisk: mkdir /home/vscode/.cache/bazelisk: permission denied
Traceback (most recent call last):
  File "/workspaces/magma/dev_tools/gen_compilation_database.py", line 113, in <module>
    fix_compilation_database(args, generate_compilation_database(args))
  File "/workspaces/magma/dev_tools/gen_compilation_database.py", line 30, in generate_compilation_database
    subprocess.check_call(
  File "/usr/lib/python3.8/subprocess.py", line 364, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['bazel', 'build', '--aspects=@bazel_compdb//:aspects.bzl%compilation_database_aspect', '--output_groups=compdb_files,header_files', '//lte/gateway/c/...', '//orc8r/gateway/c/...']' returned non-zero exit status 1.
[3562 ms] postCreateCommand failed with exit code 1. Skipping any further user-provided commands.
```

##### Root cause
The problem is that the `/home/vscode/.cache` folder belongs to the `root` user. This is most probably caused by an `ARG HOME=/home/vscode` line in the devcontainer Dockerfile: https://github.com/magma/magma/blob/2cc62cd1c0a676203e56656c5d85a232d7144f7d/.devcontainer/Dockerfile#L6
The docker build is run as root user. Some steps write files to $HOME, and they end up in `/home/vscode` although they are owned by `root`.

##### Detection
This problem went undetected for several months. It looks like most developers were using older versions of the devcontainer. Even when new devcontainers are available, vscode seems to keep using the old version that it downloaded upon the first start. I suspect that vscode is only throwing away the old container when the container reference changes. Given that vscode is using the floating `latest` tag, the updates are less explicit and vscode might not be aware that it has to throw away the old container.

**Comment by jheidbrink** [comment]
related Slack thread: https://magmacore.slack.com/archives/C033S1CEAUU/p1666109170167369
