### ISSUE TITLE
libfolly-dev build for arm is fixed

### ISSUE THREAD

**Issue by nstng** [magma/magma#14358]
in order to install libfolly-dev on a docker container, in #13741 sudo was removed from the post install script in the third-party build. The lib was only re-build for amd64 and published to the artifactory - this is missing for arm. Consequence is that the bazel base and devcontainer can not be create on arm.

The build is currently not working on arm - a quick fix was not found yet.
```
third_party/build $ ./build.py folly
[..]
checking whether gcc understands -c and -o together... (cached) yes
checking dependency style of gcc... (cached) none
checking if g++ supports C++1y features without additional flags... no
checking if g++ supports C++1y features with -std=c++1y... no
checking if g++ supports C++1y features with -std=gnu++1y... no
configure: error: Could not find cxx1y support in g++
Traceback (most recent call last):
  File "./build.py", line 193, in <module>
    main(args)
  File "./build.py", line 181, in main
    build(package, env=env, install=not args.no_install)
  File "./build.py", line 109, in build
    subprocess.run([script], check=True, env=env)
  File "/usr/lib/python3.8/subprocess.py", line 516, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['./bin/folly_build.sh']' returned non-zero exit status 1.
```

**Comment by nstng** [comment]
@m-govind do you have a hint here? I see that you uploaded the last libfolly-dev arm artifact - did you encounter an issue like in the description?

**Comment by shahrahman-fb** [comment]
Closing this issue as part of a repository cleanup effort. This issue has had no activity for over 2 years.

If this issue is still relevant, please reopen it or file a new issue with updated information. We are actively maintaining the project again and want to focus on current, actionable issues.

See: #15833 (Phase 1 cleanup), #15828 (tracking issue)
