### ISSUE TITLE
Apt missing in Magmad container on AGW docker installation

### ISSUE THREAD

**Issue by jao-tm** [magma/magma#14352]
Prior to submitting an issue, check to see if one has already been created. If there is currently an open issue, add a thumbs-up emoji to identify that it is also affecting you.

### Your Environment

- **Version:** 1.8.0
- **Affected Component:** AGW
- **Affected Subcomponent:** Magmad
- **Deployment Environment:** e.g. AWS (orc8r), local docker-compose (orc8r), bare-metal (AGW), Vagrant (AGW)

### Describe the Issue

When running the "health_cli.py" function on magmad using the command `docker exec magmad health_cli.py`, the following error occurs:
`/var/opt/magma/docker# docker exec magmad health_cli.py
Traceback (most recent call last):
  File "/build/bin/health_cli.py", line 7, in <module>
    exec(compile(f.read(), __file__, 'exec'))
  File "/magma/orc8r/gateway/python/scripts/health_cli.py", line 19, in <module>
    from magma.common.health.docker_health_service import DockerHealthChecker
  File "/magma/orc8r/gateway/python/magma/common/health/docker_health_service.py", line 21, in <module>
    from magma.common.health.health_service import GenericHealthChecker
  File "/magma/orc8r/gateway/python/magma/common/health/health_service.py", line 21, in <module>
    import apt
ModuleNotFoundError: No module named 'apt'`

#### To Reproduce

1. Install Docker-based AGW (https://docs.magmacore.org/docs/lte/deploy_install_docker)
2. Bring up the AGW containers
3. enter command `docker exec magmad health_cli.py`
4. Error message appears:
`/var/opt/magma/docker# docker exec magmad health_cli.py
Traceback (most recent call last):
  File "/build/bin/health_cli.py", line 7, in <module>
    exec(compile(f.read(), __file__, 'exec'))
  File "/magma/orc8r/gateway/python/scripts/health_cli.py", line 19, in <module>
    from magma.common.health.docker_health_service import DockerHealthChecker
  File "/magma/orc8r/gateway/python/magma/common/health/docker_health_service.py", line 21, in <module>
    from magma.common.health.health_service import GenericHealthChecker
  File "/magma/orc8r/gateway/python/magma/common/health/health_service.py", line 21, in <module>
    import apt
ModuleNotFoundError: No module named 'apt'`

#### Expected behavior

The health status of the AGW should be reported

#### Additional context

Problem fixed when installing python3-apt in the container

**Comment by shahrahman-fb** [comment]
Closing this issue as part of a repository cleanup effort. This issue has had no activity for over 2 years.

If this issue is still relevant, please reopen it or file a new issue with updated information. We are actively maintaining the project again and want to focus on current, actionable issues.

See: #15833 (Phase 1 cleanup), #15828 (tracking issue)
