### ISSUE TITLE
MME crash

### ISSUE THREAD

**Issue by javieraubert** [magma/magma#15046]
Prior to submitting an issue, check to see if one has already been created. If there is currently an open issue, add a thumbs-up emoji to identify that it is also affecting you.

### Your Environment

- **Version: 1.8.0-1663094999-49ed2e69
- **Affected Component:AGW
- **Affected Subcomponent:MME
- **Deployment Environment:Bare-metal (AGW)

### Describe the Issue

After some time of normal operation the MME service crash and restarted itself.

#### To Reproduce

Not sure.

#### Additional context

The AGW had about 150 UE connected at the failure time.
Here are the logs at the crash moment.
Feb 22 21:13:23 gw2-4 sessiond[1768569]: I0222 21:13:23.763492 1768569 LocalEnforcer.cpp:433] Received stats for 151 active sessions and 0 stale sessions
Feb 22 21:13:25 gw2-4 sessiond[1768569]: I0222 21:13:25.780288 1768569 LocalEnforcer.cpp:433] Received stats for 151 active sessions and 0 stale sessions
Feb 22 21:13:27 gw2-4 mme[1768681]: LeakSanitizer:DEADLYSIGNAL
Feb 22 21:13:27 gw2-4 mme[1768681]: ==1768681==ERROR: LeakSanitizer: SEGV on unknown address 0x000000001068 (pc 0x5563e3a4eb57 bp 0x7fae524e2bc0 sp 0x7fae524e2b60 T15)
Feb 22 21:13:27 gw2-4 mme[1768681]: ==1768681==The signal is caused by a READ memory access.
Feb 22 21:13:27 gw2-4 mme[1768681]:     #0 0x5563e3a4eb57 in mme_app_handle_handover_required /home/vagrant/magma/lte/gateway/c/core/oai/tasks/mme_app/mme_app_bearer.c:3459
Feb 22 21:13:27 gw2-4 mme[1768681]:     #1 0x5563e3a48521 in handle_message /home/vagrant/magma/lte/gateway/c/core/oai/tasks/mme_app/mme_app_main.c:396
Feb 22 21:13:27 gw2-4 mme[1768681]:     #2 0x7fae5c34e5c6 in zloop_start (/lib/x86_64-linux-gnu/libczmq.so.4+0x295c6)
Feb 22 21:13:27 gw2-4 mme[1768681]:     #3 0x5563e3a487c5 in mme_app_thread /home/vagrant/magma/lte/gateway/c/core/oai/tasks/mme_app/mme_app_main.c:516
Feb 22 21:13:27 gw2-4 mme[1768681]:     #4 0x7fae5ce18608 in start_thread (/lib/x86_64-linux-gnu/libpthread.so.0+0x8608)
Feb 22 21:13:27 gw2-4 mme[1768681]:     #5 0x7fae5bd5d132 in __clone (/lib/x86_64-linux-gnu/libc.so.6+0x11f132)
Feb 22 21:13:27 gw2-4 mme[1768681]: LeakSanitizer can not provide additional info.
Feb 22 21:13:27 gw2-4 mme[1768681]: SUMMARY: LeakSanitizer: SEGV /home/vagrant/magma/lte/gateway/c/core/oai/tasks/mme_app/mme_app_bearer.c:3459 in mme_app_handle_handover_required
Feb 22 21:13:27 gw2-4 mme[1768681]: ==1768681==ABORTING
Feb 22 21:13:27 gw2-4 sctpd[1768551]: I0222 21:13:27.419365 1768731 sctpd_uplink_client.cpp:55] sctpul.sendul error
Feb 22 21:13:27 gw2-4 sctpd[1768551]: I0222 21:13:27.419395 1768731 sctpd_uplink_client.cpp:56] grpc error (14): OS Error
Feb 22 21:13:27 gw2-4 systemd[1]: magma@mme.service: Main process exited, code=exited, status=23/n/a
Feb 22 21:13:27 gw2-4 sctpd[1768551]: I0222 21:13:27.470436 1768731 sctpd_uplink_client.cpp:55] sctpul.sendul error
Feb 22 21:13:27 gw2-4 sctpd[1768551]: I0222 21:13:27.470467 1768731 sctpd_uplink_client.cpp:56] grpc error (14): Connect Failed
Feb 22 21:13:27 gw2-4 systemd[1]: magma@mme.service: Failed with result 'exit-code'.
Feb 22 21:13:28 gw2-4 sctpd[1768551]: I0222 21:13:28.470086 1768731 sctpd_uplink_client.cpp:55] sctpul.sendul error
Feb 22 21:13:28 gw2-4 sctpd[1768551]: I0222 21:13:28.470140 1768731 sctpd_uplink_client.cpp:56] grpc error (14): Connect Failed
Feb 22 21:13:28 gw2-4 smsd[246273]: INFO:root:mme non_eps_service_config is not SMS_ORC8R, sleeping.
Feb 22 21:13:28 gw2-4 magmad[246054]: WARNING:root:Collect mme Error! [StatusCode.UNAVAILABLE] failed to connect to all addresses
Feb 22 21:13:28 gw2-4 control_proxy[1577925]: 2023-02-22T21:13:28.641Z [127.0.0.1 -> metricsd-controller.yota.co.ni,8443] "POST /magma.orc8r.MetricsController/Collect HTTP/2" 200 5bytes 0.113s

**Comment by shahrahman-fb** [comment]
Closing this issue as part of a repository cleanup effort. This issue has had no activity for over 2 years.

If this issue is still relevant, please reopen it or file a new issue with updated information. We are actively maintaining the project again and want to focus on current, actionable issues.

See: #15833 (Phase 1 cleanup), #15828 (tracking issue)
