### ISSUE TITLE
Memory leak on services restart

### ISSUE THREAD

**Issue by javieraubert** [magma/magma#15160]
Prior to submitting an issue, check to see if one has already been created. If there is currently an open issue, add a thumbs-up emoji to identify that it is also affecting you.

### Your Environment

- **Version: 1.8.0-1663094999-49ed2e69
- **Affected Component: AGW
- **Affected Subcomponent: AGW
- **Deployment Environment: VM AGW

### Describe the Issue

When making a change on Orch8rs wich require a services restart of AGW, the syslogs shown a Memory Leak message. This happens also on our bare metal AGW.

#### To Reproduce

Make any change that needs a service restart.

#### Additional context

Syslogs are here:

Mar 25 15:15:11 DIG-OCN-AGW-01-TEST envoy_controller[20361]: I0325 15:15:11.728119   20361 control_plane.go:138] OnStreamClosed 1 closed
Mar 25 15:15:11 DIG-OCN-AGW-01-TEST envoy_controller[20361]: I0325 15:15:11.728168   20361 control_plane.go:138] OnStreamClosed 2 closed
Mar 25 15:15:11 DIG-OCN-AGW-01-TEST systemd[1]: Stopped Magma envoy service.
Mar 25 15:15:11 DIG-OCN-AGW-01-TEST mme[20464]: TASK_SERVICE303 terminated
Mar 25 15:15:11 DIG-OCN-AGW-01-TEST smsd[20318]: INFO:root:mme non_eps_service_config is not SMS_ORC8R, sleeping.
Mar 25 15:15:13 DIG-OCN-AGW-01-TEST mme[20464]: Cleaning up SPGW configs
Mar 25 15:15:13 DIG-OCN-AGW-01-TEST mme[20464]: =================================================================
Mar 25 15:15:13 DIG-OCN-AGW-01-TEST mme[20464]: ==20464==ERROR: LeakSanitizer: detected memory leaks
Mar 25 15:15:13 DIG-OCN-AGW-01-TEST mme[20464]: Direct leak of 48 byte(s) in 1 object(s) allocated from:
Mar 25 15:15:13 DIG-OCN-AGW-01-TEST mme[20464]:     #0 0x7f946236f712 in __interceptor_calloc ../../../../src/libsanitizer/lsan/lsan_interceptors.cpp:76
Mar 25 15:15:13 DIG-OCN-AGW-01-TEST mme[20464]:     #1 0x7f946166ac0f in zlist_new (/lib/x86_64-linux-gnu/libczmq.so.4+0x24c0f)
Mar 25 15:15:13 DIG-OCN-AGW-01-TEST mme[20464]: SUMMARY: LeakSanitizer: 48 byte(s) leaked in 1 allocation(s).
Mar 25 15:15:13 DIG-OCN-AGW-01-TEST systemd[1]: magma@mme.service: Main process exited, code=exited, status=23/n/a
Mar 25 15:15:13 DIG-OCN-AGW-01-TEST systemd[1]: magma@mme.service: Failed with result 'exit-code'.
Mar 25 15:15:13 DIG-OCN-AGW-01-TEST systemd[1]: Stopped Magma OAI MME service.
Mar 25 15:15:13 DIG-OCN-AGW-01-TEST systemd[1]: Stopping Magma pipelined service...
Mar 25 15:15:13 DIG-OCN-AGW-01-TEST systemd[1]: Stopping Magma session manager service...
Mar 25 15:15:13 DIG-OCN-AGW-01-TEST pipelined[20346]: INFO:root:Stopping pipelined with reason SIGTERM...
Mar 25 15:15:13 DIG-OCN-AGW-01-TEST systemd[1]: magma@sessiond.service: Succeeded.
Mar 25 15:15:13 DIG-OCN-AGW-01-TEST systemd[1]: Stopped Magma session manager service.
Mar 25 15:15:13 DIG-OCN-AGW-01-TEST systemd[1]: Started Magma session manager service.

**Comment by Sathyaj27** [comment]
[mme261023 (1).log](https://github.com/magma/magma/files/13185065/mme261023.1.log)
During service restart , No memory leak is observed. I have tried few times.  Attached logs.

**Comment by javieraubert** [comment]
Hello, this is mme.log right?, but all the memory leaks erros are on the syslog.

**Comment by Sathyaj27** [comment]
[sys.log](https://github.com/magma/magma/files/13213787/sys.log)
Added syslogs

**Comment by asantos-vk** [comment]
Hi! I am having the same leaks, but not when restarting the service. In fact it was during weeks of operation:
![image](https://github.com/magma/magma/assets/111907131/1eaf1044-6c67-4e79-a1b3-2b95918be962)

**Comment by javieraubert** [comment]
Hi, @asantos-vk  still having issues?
