### ISSUE TITLE
`snowflake` package name changed to `snowflake-uuid`

### ISSUE THREAD

**Issue by rogerpueyo** [magma/magma#15352]
### Environment

- **Version:** `v1.8`, `master`?
- **Affected Component:** Access Gateway, Federation Gateway?
- **Affected Subcomponent:** AGW MME, AGW Vagrant dev VM, FeG containers?
- **Deployment Environment:** Vagrant (AGW), Docker (FeG)?

### Describe the Issue

The [Python package used by Magma to generate an AGW's or a FeG's UUID](https://github.com/shaddi/snowflake) changed its name in PyPI from ~~[`snowflake`](https://pypi.org/project/snowflake/)~~ to [`snowflake-uuid`](https://pypi.org/project/snowflake-uuid/). The former ~~[`snowflake`](https://pypi.org/project/snowflake/)~~ now corresponds to another project with the same name with different functionalities. For more info, see:
- https://github.com/shaddi/snowflake/issues/4
- https://github.com/magma/magma/issues/6159

Launching a VM using Vagrant and building the `v1.8` AGW from source leads to downloading the wrong new ~~`snowflake`~~ package (which does not provide the required UUID capabilities), instead of the now-renamed-to `snowflake-uuid` package (which is the correct one).

#### To Reproduce

1. [Run AGW `v1.8` dev VM with Vagrant](https://magma.github.io/magma/docs/basics/quick_start_guide#terminal-tab-1-provision-the-agw-vm)
2. [Build the AGW from source](https://magma.github.io/magma/docs/basics/quick_start_guide#terminal-tab-1-build-agw-from-source) (`cd ~/magma/lte/gateway; make run` with Magma AGW `v1.8`) 
3. Show logs (`$ sudo journalctl -fu magma*`)
```
Dec 11 15:29:10 i2cat-gs75-magma-v1p8pp-agw systemd[1]: magma@magmad.service: Scheduled restart job, restart counter is at 5.
Dec 11 15:29:10 i2cat-gs75-magma-v1p8pp-agw systemd[1]: Stopped Magma magmad service.
Dec 11 15:29:10 i2cat-gs75-magma-v1p8pp-agw systemd[1]: Started Magma magmad service.
Dec 11 15:29:10 i2cat-gs75-magma-v1p8pp-agw magmad[32135]: INFO:root:Sentry disabled because of missing dsn_python. See documentation (Configure > AGW) on how to configure Sentry dsn.
Dec 11 15:29:10 i2cat-gs75-magma-v1p8pp-agw magmad[32135]: Traceback (most recent call last):
Dec 11 15:29:10 i2cat-gs75-magma-v1p8pp-agw magmad[32135]:   File "/usr/lib/python3.8/runpy.py", line 194, in _run_module_as_main
Dec 11 15:29:10 i2cat-gs75-magma-v1p8pp-agw magmad[32135]:     return _run_code(code, main_globals, None,
Dec 11 15:29:10 i2cat-gs75-magma-v1p8pp-agw magmad[32135]:   File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
Dec 11 15:29:10 i2cat-gs75-magma-v1p8pp-agw magmad[32135]:     exec(code, run_globals)
Dec 11 15:29:10 i2cat-gs75-magma-v1p8pp-agw magmad[32135]:   File "/home/vagrant/magma/orc8r/gateway/python/magma/magmad/main.py", line 316, in <module>
Dec 11 15:29:10 i2cat-gs75-magma-v1p8pp-agw magmad[32135]:     main()
Dec 11 15:29:10 i2cat-gs75-magma-v1p8pp-agw magmad[32135]:   File "/home/vagrant/magma/orc8r/gateway/python/magma/magmad/main.py", line 61, in main
Dec 11 15:29:10 i2cat-gs75-magma-v1p8pp-agw magmad[32135]:     logging.info('Starting magmad for UUID: %s', snowflake.make_snowflake())
Dec 11 15:29:10 i2cat-gs75-magma-v1p8pp-agw magmad[32135]:   File "/home/vagrant/build/python/lib/python3.8/site-packages/snowflake/_legacy/__init__.py", line 27, in make_snowflake
Dec 11 15:29:10 i2cat-gs75-magma-v1p8pp-agw magmad[32135]:     raise NotImplementedError('This function is only available in the snowflake-uuid package')
Dec 11 15:29:10 i2cat-gs75-magma-v1p8pp-agw magmad[32135]: NotImplementedError: This function is only available in the snowflake-uuid package
Dec 11 15:29:11 i2cat-gs75-magma-v1p8pp-agw systemd[1]: magma@magmad.service: Main process exited, code=exited, status=1/FAILURE
Dec 11 15:29:11 i2cat-gs75-magma-v1p8pp-agw magmad[32149]: ERROR:root:Failed to write to redis, status Error 111 connecting to 127.0.0.1:6380. Connection refused.
Dec 11 15:29:11 i2cat-gs75-magma-v1p8pp-agw magmad[32149]: ERROR:root:Logging exit info instead
Dec 11 15:29:11 i2cat-gs75-magma-v1p8pp-agw magmad[32149]: latest_service_result: EXIT_CODE
Dec 11 15:29:11 i2cat-gs75-magma-v1p8pp-agw magmad[32149]: latest_exit_code: EXITED
Dec 11 15:29:11 i2cat-gs75-magma-v1p8pp-agw magmad[32149]: latest_rc: 1
Dec 11 15:29:11 i2cat-gs75-magma-v1p8pp-agw systemd[1]: magma@magmad.service: Failed with result 'exit-code'.
```

**Comment by rogerpueyo** [comment]
This is printed during the `make run` process, showing we got the wrong `snowflake` package instead of the renamed `snowflake-uuid` one.
```
[...]
[56/94] Building CXX object CMakeFiles/SESSION_MANAGER.dir/orc8r/protos/digest.pb.cc.oERROR: pydantic 1.10.13 has requirement typing-extensions>=4.2.0, but you'll have typing-extensions 3.10.0.2 which is incompatible.
ERROR: snowflake-connector-python 3.6.0 has requirement cryptography<42.0.0,>=3.1.0, but you'll have cryptography 2.8 which is incompatible.
ERROR: snowflake-connector-python 3.6.0 has requirement typing-extensions<5,>=4.3, but you'll have typing-extensions 3.10.0.2 which is incompatible.
ERROR: snowflake-snowpark-python 1.11.1 has requirement typing-extensions<5.0.0,>=4.1.0, but you'll have typing-extensions 3.10.0.2 which is incompatible.
ERROR: snowflake-core 0.5.1 has requirement python-dateutil>=2.8.2, but you'll have python-dateutil 2.8.1 which is incompatible.
[57/94] Building CXX object CMakeFiles/SESSION_MANAGER.dir/orc8r/protos/directoryd.pb.cc.omake[2]: Leaving directory '/home/vagrant/magma/orc8r/gateway/python'
[...]
```

**Comment by shahrahman-fb** [comment]
Closing this issue as part of a repository cleanup effort. This issue has had no activity for over 2 years.

If this issue is still relevant, please reopen it or file a new issue with updated information. We are actively maintaining the project again and want to focus on current, actionable issues.

See: #15833 (Phase 1 cleanup), #15828 (tracking issue)
