### ISSUE TITLE
Error in s1aptests with regard to data transfer

### ISSUE THREAD

**Issue by rottenworld** [magma/magma#1846]
### Your Environment

- **Version:** 1.1.0
- **Affected Component:** Access Gateway
- **Affected Subcomponent:** s1aptests
- **Deployment Environment:** bare-metal, ubuntu 20.04, vagrant 2.2.6

### Describe the Issue

I followed the guide of [s1AP Integration tests](https://facebookincubator.github.io/magma/docs/lte/s1ap_tests#notes) and run some tests with regard to data transfer(i.e, `test_attach_ul_tcp_data.py`), and got error.
By the way, I can `run test_attach_detach.py` correctly. 

**To Reproduce**
1. Set up Test VM and ssh into it
2. cd `/home/vagrant/magma/lte/gateway/python/integ_tests/s1aptests`
3. run tests

```
make integ_test TESTS=./s1aptests/test_attach_ul_tcp_data.py
```

```
ERROR: Attach and send UL TCP data
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/vagrant/magma/lte/gateway/python/integ_tests/s1aptests/test_attach_ul_tcp_data.py", line 42, in test_attach_ul_tcp_data
    test.verify()
  File "/home/vagrant/magma/lte/gateway/python/integ_tests/s1aptests/util/traffic_util.py", line 488, in verify
    self.results),
RuntimeError: Cached results object is not a tuple : None
-------------------- >> begin captured logging << --------------------
root: ERROR: Could not load magmad yml config for mconfig modules
root: INFO: Adding subscriber : IMSI001010000000001
root: INFO: Ignoring FAILED_PRECONDITION exception
root: DEBUG: s1ap response expected, received: 12, 12
root: DEBUG: s1ap message expected, received: 68, 68
root: INFO: Deleting subscriber : IMSI001010000000001
--------------------- >> end captured logging << ---------------------

```

By the way, the above error occurs in udp and downlink as well.

**Comment by ulaskozat** [comment]
Failing at the stage of test.verify() is typically due to traffic server related issues. Restarting the VMs resolve the issue in most cases.

**Comment by rottenworld** [comment]
I am sorry the error message I provided is not complete and clear enough.

This is the complete error I got after rerun the VMs:

```
*************NbUiNbuHdlUeRadioCapMsg: Send UE cap msg SUCCESS*********                                                                  
PDN_TYPE: 1                                                                                                                             
PDN_ADDRESS: 192 168 128 206                                                                                                            
************************* Running UE uplink (TCP) for UE id  1                                                                          
Exception in thread Thread-1:                                                                                                           
Traceback (most recent call last):                                                                                                      
  File "/usr/lib/python3.5/threading.py", line 914, in _bootstrap_inner                                                                 
    self.run()                                                                                                                          
  File "/usr/lib/python3.5/threading.py", line 862, in run                                                                              
    self._target(*self._args, **self._kwargs)                                                                                           
  File "/home/vagrant/magma/lte/gateway/python/integ_tests/s1aptests/util/traffic_util.py", line 314, in _run                           
    sc = socket.create_connection(self._remote_server)                                                                                  
  File "/usr/lib/python3.5/socket.py", line 712, in create_connection                                                                   
    raise err                                                                                                                           
  File "/usr/lib/python3.5/socket.py", line 703, in create_connection                                                                   
    sock.connect(sa)                                                                                                                    
OSError: [Errno 113] No route to host

************************* send SCTP SHUTDOWN
Deleting Ue Context from Traffic Handler
E
======================================================================
ERROR: Attach and send UL TCP data 
----------------------------------------------------------------------
Traceback (most recent call last): 
  File "/home/vagrant/magma/lte/gateway/python/integ_tests/s1aptests/test_attach_ul_tcp_data.py", line 42, in test_attach_ul_tcp_data
    test.verify()
  File "/home/vagrant/magma/lte/gateway/python/integ_tests/s1aptests/util/traffic_util.py", line 489, in verify
    self.results),
RuntimeError: Cached results object is not a tuple : None
-------------------- >> begin captured logging << --------------------
root: ERROR: Could not load magmad yml config for mconfig modules
root: INFO: Adding subscriber : IMSI001010000000001
root: INFO: Ignoring FAILED_PRECONDITION exception
root: DEBUG: s1ap response expected, received: 12, 12
root: DEBUG: s1ap message expected, received: 68, 68
root: INFO: Deleting subscriber : IMSI001010000000001
--------------------- >> end captured logging << ---------------------

```

As the `create_connection` implies, it seems that something wrong happened in the process of connection establishment, before the data transfer started.

However, the attach procedure is correct and pdn type and pdn address are returned in response.

**Comment by ulaskozat** [comment]
Are you running the traffic server VM?

**Comment by rottenworld** [comment]
I redo the experiment on a bare metal server and it works. I think there's something wrong with my local environment. Thank you very much for you patience.
