### ISSUE TITLE
Bandwidth transform error while configuring eNodeB

### ISSUE THREAD

**Issue by bmurithi** [magma/magma#260]
eNodeB: BaiCells OUI: 48BF74, Software: BaiBS_RTS_3.1.4

```
May 08 17:18:11 debiansb enodebd[9648]: ERROR:spyne.application.server:Unknown bandwidth_rbs (10)
May 08 17:18:11 debiansb enodebd[9648]: Traceback (most recent call last):
May 08 17:18:11 debiansb enodebd[9648]:   File "/usr/local/lib/python3.5/dist-packages/spyne/application.py", line 151, in process_request
May 08 17:18:11 debiansb enodebd[9648]:     ctx.out_object = self.call_wrapper(ctx)
May 08 17:18:11 debiansb enodebd[9648]:   File "/usr/local/lib/python3.5/dist-packages/spyne/application.py", line 235, in call_wrapper
May 08 17:18:11 debiansb enodebd[9648]:     retval = ctx.descriptor.service_class.call_wrapper(ctx)
May 08 17:18:11 debiansb enodebd[9648]:   File "/usr/local/lib/python3.5/dist-packages/spyne/service.py", line 209, in call_wrapper
May 08 17:18:11 debiansb enodebd[9648]:     return ctx.function(ctx, *args)
May 08 17:18:11 debiansb enodebd[9648]:   File "/usr/local/lib/python3.5/dist-packages/magma/enodebd/tr069/rpc_methods.py", line 226, in set_parameter_values_response
May 08 17:18:11 debiansb enodebd[9648]:     return AutoConfigServer._handle_tr069_message(ctx, response)
May 08 17:18:11 debiansb enodebd[9648]:   File "/usr/local/lib/python3.5/dist-packages/magma/enodebd/tr069/rpc_methods.py", line 116, in _handle_tr069_message
May 08 17:18:11 debiansb enodebd[9648]:     req = cls.state_machine().handle_tr069_message(message)
May 08 17:18:11 debiansb enodebd[9648]:   File "/usr/local/lib/python3.5/dist-packages/magma/enodebd/state_machines/enb_acs_impl.py", line 86, in handle_tr069_message
May 08 17:18:11 debiansb enodebd[9648]:     self._read_tr069_msg(message)
May 08 17:18:11 debiansb enodebd[9648]:   File "/usr/local/lib/python3.5/dist-packages/magma/enodebd/state_machines/enb_acs_impl.py", line 141, in _read_tr069_msg
May 08 17:18:11 debiansb enodebd[9648]:     msg_handled, next_state = self.state.read_msg(message)
May 08 17:18:11 debiansb enodebd[9648]:   File "/usr/local/lib/python3.5/dist-packages/magma/enodebd/state_machines/enb_acs_states.py", line 835, in read_msg
May 08 17:18:11 debiansb enodebd[9648]:     self._mark_as_configured()
May 08 17:18:11 debiansb enodebd[9648]:   File "/usr/local/lib/python3.5/dist-packages/magma/enodebd/state_machines/enb_acs_states.py", line 862, in _mark_as_configured
May 08 17:18:11 debiansb enodebd[9648]:     magma_val = self.acs.data_model.transform_for_magma(name, val)
May 08 17:18:11 debiansb enodebd[9648]:   File "/usr/local/lib/python3.5/dist-packages/magma/enodebd/data_models/data_model.py", line 117, in transform_for_magma
May 08 17:18:11 debiansb enodebd[9648]:     return transform_function(enb_value)
May 08 17:18:11 debiansb enodebd[9648]:   File "/usr/local/lib/python3.5/dist-packages/magma/enodebd/data_models/transform_for_magma.py", line 69, in bandwidth
May 08 17:18:11 debiansb enodebd[9648]:     str(bandwidth_rbs))
May 08 17:18:11 debiansb enodebd[9648]: magma.enodebd.exceptions.ConfigurationError: Unknown bandwidth_rbs (10)
```

**Comment by andreilee** [comment]
resolved with https://github.com/facebookincubator/magma/pull/272
