### ISSUE TITLE
MME crashes on authentication of many UEs

### ISSUE THREAD

**Issue by uri200** [magma/magma#3499]
When running gxgx04 test on teravm we see that in some occasions MME crashes

This test authenticated 32 UEs and then runs some traffic. All happens in parallel

```
Oct 28 11:28:37 agw mme[24148]: [INFO] sent itti S6A-LOCATION-UPDATE_ANSWER for IMSI: 999991234567817
Oct 28 11:28:37 agw mme[24148]: Received SGW IP Address 0x629000405140
Oct 28 11:28:37 agw mme[24148]: [DEBUG] Sending S6A-UPDATE_LOCATION_REQUEST with IMSI: 999991234567828
Oct 28 11:28:37 agw mme[24148]: [INFO] Received S6A-AUTHENTICATION_INFORMATION_ANSWER for IMSI: 999991234567830; Status: ; StatusCode:0
Oct 28 11:28:37 agw mme[24148]: [INFO] Received S6A-AUTHENTICATION_INFORMATION_ANSWER for IMSI: 999991234567829; Status: ; StatusCode:0
Oct 28 11:28:37 agw mme[24148]: [INFO] Received S6A-LOCATION-UPDATE_ANSWER for IMSI: 999991234567818; Status: ; StatusCode: 0
Oct 28 11:28:37 agw mme[24148]: [INFO] sent itti S6A-LOCATION-UPDATE_ANSWER for IMSI: 999991234567818
Oct 28 11:28:37 agw mme[24148]: Received SGW IP Address 0x629000329140
Oct 28 11:28:37 agw mme[24148]: [DEBUG] Sending S6A-UPDATE_LOCATION_REQUEST with IMSI: 999991234567830
Oct 28 11:28:37 agw mme[24148]: [DEBUG] Sending S6A-UPDATE_LOCATION_REQUEST with IMSI: 999991234567829
Oct 28 11:28:37 agw mme[24148]: [INFO] Received S6A-AUTHENTICATION_INFORMATION_ANSWER for IMSI: 999991234567831; Status: ; StatusCode:0
Oct 28 11:28:37 agw mme[24148]: [INFO] Received S6A-AUTHENTICATION_INFORMATION_ANSWER for IMSI: 999991234567832; Status: ; StatusCode:0
Oct 28 11:28:37 agw mme[24148]: [DEBUG] Sending S6A-UPDATE_LOCATION_REQUEST with IMSI: 999991234567831
Oct 28 11:28:37 agw mme[24148]: [INFO] Received S6A-LOCATION-UPDATE_ANSWER for IMSI: 999991234567819; Status: ; StatusCode: 0
Oct 28 11:28:37 agw mme[24148]: [INFO] sent itti S6A-LOCATION-UPDATE_ANSWER for IMSI: 999991234567819
Oct 28 11:28:37 agw mme[24148]: [INFO] Received S6A-AUTHENTICATION_INFORMATION_ANSWER for IMSI: 999991234567833; Status: ; StatusCode:0
Oct 28 11:28:37 agw mme[24148]: Received SGW IP Address 0x6290002b1140
Oct 28 11:28:37 agw mme[24148]: [INFO] Received S6A-LOCATION-UPDATE_ANSWER for IMSI: 999991234567820; Status: ; StatusCode: 0
Oct 28 11:28:37 agw mme[24148]: [INFO] sent itti S6A-LOCATION-UPDATE_ANSWER for IMSI: 999991234567820
Oct 28 11:28:37 agw mme[24148]: [INFO] Received S6A-AUTHENTICATION_INFORMATION_ANSWER for IMSI: 999991234567834; Status: ; StatusCode:0
Oct 28 11:28:37 agw mme[24148]: Received SGW IP Address 0x62900049b140
Oct 28 11:28:37 agw mme[24148]: [DEBUG] Sending S6A-UPDATE_LOCATION_REQUEST with IMSI: 999991234567832
Oct 28 11:28:37 agw mme[24148]: [DEBUG] Sending S6A-UPDATE_LOCATION_REQUEST with IMSI: 999991234567833
Oct 28 11:28:37 agw mme[24148]: [INFO] Received S6A-LOCATION-UPDATE_ANSWER for IMSI: 999991234567821; Status: ; StatusCode: 0
Oct 28 11:28:37 agw mme[24148]: [INFO] sent itti S6A-LOCATION-UPDATE_ANSWER for IMSI: 999991234567821
Oct 28 11:28:37 agw mme[24148]: Received SGW IP Address 0x6290004b4140
Oct 28 11:28:37 agw mme[24148]: [DEBUG] Sending S6A-UPDATE_LOCATION_REQUEST with IMSI: 999991234567834
Oct 28 11:28:37 agw mme[24148]: [INFO] Received S6A-AUTHENTICATION_INFORMATION_ANSWER for IMSI: 999991234567835; Status: ; StatusCode:0
Oct 28 11:28:37 agw mme[24148]: [DEBUG] Sending S6A-UPDATE_LOCATION_REQUEST with IMSI: 999991234567835
Oct 28 11:28:38 agw mme[24148]:     #3 0x5570293b7259 in magma::lte::MobilityServiceClient::getInstance() /home/vagrant/magma/lte/gateway/c/oai/lib/mobility_client/MobilityServiceClient.cpp:185
Oct 28 11:28:38 agw mme[24148]:     #4 0x5570293b53c5 in get_assigned_ipv4_block /home/vagrant/magma/lte/gateway/c/oai/lib/mobility_client/MobilityClientAPI.cpp:52
Oct 28 11:28:38 agw mme[24148]:     #5 0x557029302358 in pgw_config_process /home/vagrant/magma/lte/gateway/c/oai/tasks/sgw/pgw_config.c:144
Oct 28 11:28:38 agw mme[24148]:     #6 0x5570293001c6 in spgw_config_process /home/vagrant/magma/lte/gateway/c/oai/tasks/sgw/spgw_config.c:74
Oct 28 11:28:38 agw mme[24148]:     #7 0x557029300d54 in spgw_config_parse_file /home/vagrant/magma/lte/gateway/c/oai/tasks/sgw/spgw_config.c:117
Oct 28 11:28:38 agw mme[24148]:     #8 0x557028ddc6dc in mme_config_embedded_spgw_parse_opt_line /home/vagrant/magma/lte/gateway/c/oai/tasks/mme_app/mme_app_embedded_spgw.c:132
Oct 28 11:28:38 agw mme[24148]:     #9 0x557028c96ba7 in main /home/vagrant/magma/lte/gateway/c/oai/oai_mme/oai_mme.c:98
Oct 28 11:28:38 agw mme[24148]:     #10 0x7f8b1973b2e0 in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x202e0)
Oct 28 11:28:38 agw mme[24148]: ==24148==ABORTING
Oct 28 11:28:39 agw systemd[1]: magma@mme.service: Main process exited, code=exited, status=1/FAILURE
Oct 28 11:28:39 agw systemd[1]: magma@mme.service: Unit entered failed state.
Oct 28 11:28:39 agw systemd[1]: magma@mme.service: Failed with result 'exit-code'.
Oct 28 11:28:44 agw systemd[1]: magma@mme.service: Service hold-off time over, scheduling restart.
Oct 28 11:28:44 agw systemd[1]: Stopped Magma OAI MME service.
Oct 28 11:28:45 agw systemd[1]: Starting Magma OAI MME service...
Oct 28 11:28:46 agw systemd[1]: Started Magma OAI MME service.
Oct 28 11:28:49 agw mme[8094]: terminate called after throwing an instance of 'std::runtime_error'
Oct 28 11:28:49 agw mme[8094]:   what():  Controller not connected to switch:
Oct 28 11:28:55 agw systemd[1]: magma@mme.service: Main process exited, code=killed, status=6/ABRT
Oct 28 11:28:55 agw systemd[1]: magma@mme.service: Unit entered failed state.
Oct 28 11:28:55 agw systemd[1]: magma@mme.service: Failed with result 'signal'.
Oct 28 11:29:00 agw systemd[1]: magma@mme.service: Service hold-off time over, scheduling restart.
Oct 28 11:29:00 agw systemd[1]: Stopped Magma OAI MME service.
Oct 28 11:29:01 agw systemd[1]: Starting Magma OAI MME service...
Oct 28 11:29:02 agw systemd[1]: Started Magma OAI MME service.
Oct 28 11:29:04 agw mme[9391]: [DEBUG] Success logging event: s1_setup_success
Oct 28 11:29:04 agw mme[9391]: [INFO] Sending S6A-AUTHENTICATION_INFORMATION_REQUEST with IMSI: 999991234567810
Oct 28 11:29:04 agw mme[9391]: [INFO] Sending S6A-AUTHENTICATION_INFORMATION_REQUEST with IMSI: 999991234567811
Oct 28 11:29:04 agw mme[9391]: [INFO] Sending S6A-AUTHENTICATION_INFORMATION_REQUEST with IMSI: 999991234567812

```

mme exec
dropbox.com/s/l9yx4443uzqxxrq/mme?dl=0

[core-1603909729-ITTI_bundle.zip](https://github.com/magma/magma/files/5454520/core-1603909729-ITTI_bundle.zip)
[syslog.txt.zip](https://github.com/magma/magma/files/5454526/syslog.txt.zip)

**Comment by ssanadhya** [comment]
@uri200 , is this issue still happening? If not, could you please close this issue?

**Comment by uri200** [comment]
Hey @ssanadhya  I haven't been able to test this lately due to our work on inbound roaming

But last time I tested we were having issues when we were using  4 ues per seconnd. 

Will update soon

**Comment by ulaskozat** [comment]
Closing this as looks unreported for a long time.
