### ISSUE TITLE
mme crashes during  S1 AP reset

### ISSUE THREAD

**Issue by wallyrb** [magma/magma#3865]
### Your Environment

- **Version:AGW Version:** 1.1.1-1603738830-8a6fe102
- **Affected Component:** Access Gateway
- **Affected Subcomponent:** mme
- **Deployment Environment:** bare-metal (AGW)

### Describe the Issue

mme service is crashing when handling the S1AP Reset 

**Expected behavior**
mme should handle the S1AP Reset without crashing

**Additional context**
Backtrace obtained from coredumps:

```
warning: .dynamic section for "/usr/lib/libfluid_msg.so.0" is not at the expected address (wrong library or version mismatch?)
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
Core was generated by `/usr/local/bin/mme -c /var/opt/magma/tmp/mme.conf -s /var/opt/magma/tmp/spgw.co'.
Program terminated with signal SIGSEGV, Segmentation fault.
#0  0x000055d5d209cd18 in s1ap_handle_enb_initiated_reset_ack (enb_reset_ack_p=0x7f8713616688, imsi64=0) at /home/vagrant/magma/lte/gateway/c/oai/tasks/s1ap/s1ap_mme_handlers.c:2602
2602                LOG_S1AP,
[Current thread is 1 (Thread 0x7f870a58e700 (LWP 14467))]
(gdb) bt
#0  0x000055d5d209cd18 in s1ap_handle_enb_initiated_reset_ack (enb_reset_ack_p=0x7f8713616688, imsi64=0) at /home/vagrant/magma/lte/gateway/c/oai/tasks/s1ap/s1ap_mme_handlers.c:2602
#1  0x000055d5d203e638 in s1ap_mme_thread (args=0x0) at /home/vagrant/magma/lte/gateway/c/oai/tasks/s1ap/s1ap_mme.c:247
```

In mme logs

```
041644 Mon Nov 30 18:34:08 2020 7F870A58E700 INFO  S1AP   tasks/s1ap/s1ap_mme_decoder.c   :0113
S1AP eNB RESET is received. Procedure code = 14
041645 Mon Nov 30 18:34:08 2020 7F870CE52700 WARNI MME-AP tasks/mme_app/mme_app_context.c :2341
Invalid mme_ue_s1ap_ue_id 0x00000000 received from S1AP. Using enb_s1ap_id_key 16777310 to get the context 
041646 Mon Nov 30 18:34:08 2020 7F870CE52700 INFO  MME-AP tasks/mme_app/mme_app_context.c :1803   [0]
Old UE ECM State (IDLE) is same as the new UE ECM state (IDLE)
041647 Mon Nov 30 18:34:08 2020 7F870CE52700 INFO  MME-AP tasks/mme_app/mme_app_itti_messa:0096   [0]
Sending UE Context Release Cmd to S1ap for (ue_id = 454)
UE Context Release Cause = (6)
041648 Mon Nov 30 18:34:08 2020 7F870CE52700 WARNI MME-AP tasks/mme_app/mme_app_context.c :2371   [0]
UE Conetext Release Reqeust:Cause SCTP RESET/SHUTDOWN. UE state: IDLE. mme_ue_s1ap_id = 454, enb_ue_s1ap_id = 94 Action -- Handle the message

 
041649 Mon Nov 30 18:34:08 2020 7F870CE52700 ERROR MME-AP tasks/mme_app/mme_app_context.c :2380   [0] 
ERROR: UE Context Release Request: UE state : IDLE. enb_ue_s1ap_ue_id 0x00005E mme_ue_s1ap_id 0x000001C6 Action--- Ignore the message
```

**Comment by pruthvihebbani** [comment]
@wallyrb Can you please add wireshark capture and complete mme log for this issue?
