### ISSUE TITLE
pipelied: UT: failure: test_restart_resilience.py

### ISSUE THREAD

**Issue by pshelar** [magma/magma#3990]
### Your Environment

- **Version:** master
- **Affected Component:** AGW
- **Affected Subcomponent:** pipelined
- **Deployment Environment:** CICD

### Describe the Issue
```
[magma@10.240.0.29] out: [vagrant@127.0.0.1:2222] out: --------------------- >> end captured logging << ---------------------
[magma@10.240.0.29] out: [vagrant@127.0.0.1:2222] out: 
[magma@10.240.0.29] out: [vagrant@127.0.0.1:2222] out: ======================================================================
[magma@10.240.0.29] out: [vagrant@127.0.0.1:2222] out: FAIL: Partial redirection test, checks if flows were added properly for url
[magma@10.240.0.29] out: [vagrant@127.0.0.1:2222] out: ----------------------------------------------------------------------
[magma@10.240.0.29] out: [vagrant@127.0.0.1:2222] out: Traceback (most recent call last):
[magma@10.240.0.29] out: [vagrant@127.0.0.1:2222] out:   File "/home/vagrant/magma/lte/gateway/python/magma/pipelined/tests/test_restart_resilience.py", line 545, in test_url_redirect
[magma@10.240.0.29] out: [vagrant@127.0.0.1:2222] out:     pkt_sender.send(packet)
[magma@10.240.0.29] out: [vagrant@127.0.0.1:2222] out:   File "/home/vagrant/magma/lte/gateway/python/magma/pipelined/tests/pipelined_test_util.py", line 589, in __exit__
[magma@10.240.0.29] out: [vagrant@127.0.0.1:2222] out:     self._snapshot_name, self._include_stats)
[magma@10.240.0.29] out: [vagrant@127.0.0.1:2222] out:   File "/home/vagrant/magma/lte/gateway/python/magma/pipelined/tests/pipelined_test_util.py", line 482, in assert_bridge_snapshot_match
[magma@10.240.0.29] out: [vagrant@127.0.0.1:2222] out:     current_snapshot)
[magma@10.240.0.29] out: [vagrant@127.0.0.1:2222] out:   File "/home/vagrant/magma/lte/gateway/python/magma/pipelined/tests/pipelined_test_util.py", line 422, in fail
[magma@10.240.0.29] out: [vagrant@127.0.0.1:2222] out:     return test_case.fail(msg)
[magma@10.240.0.29] out: [vagrant@127.0.0.1:2222] out: AssertionError: Snapshot mismatch with error:
[magma@10.240.0.29] out: [vagrant@127.0.0.1:2222] out: --- previous snapshot
[magma@10.240.0.29] out: [vagrant@127.0.0.1:2222] out: 
[magma@10.240.0.29] out: [vagrant@127.0.0.1:2222] out: +++ current snapshot
```

**Additional context**
https://circleci.com/api/v1.1/project/github/magma/magma/92241/output/110/0?file=true&allocation-id=5fd170aba209b93597127b1d-0-build%2F1CE7EB96

**Comment by koolzz** [comment]
@pshelar I think this failure is not indicative of whats happening, I think the root cause is 
```

[magma@10.240.0.29] out: [vagrant@127.0.0.1:2222] out: ryu.controller.controller: DEBUG: Datapath in process of terminating; send() to ('127.0.0.1', 56006) discarded.
[magma@10.240.0.29] out: [vagrant@127.0.0.1:2222] out: ryu.controller.controller: DEBUG: Datapath in process of terminating; send() to ('127.0.0.1', 56026) discarded.
[magma@10.240.0.29] out: [vagrant@127.0.0.1:2222] out: ryu.controller.controller: DEBUG: Datapath in process of terminating; send() to ('127.0.0.1', 55982) discarded.
[magma@10.240.0.29] out: [vagrant@127.0.0.1:2222] out: ryu.controller.controller: DEBUG: Datapath in process of terminating; send() to ('127.0.0.1', 55990) discarded.
[magma@10.240.0.29] out: [vagrant@127.0.0.1:2222] out: ryu.controller.controller: DEBUG: Datapath in process of terminating; send() to ('127.0.0.1', 55996) discarded.
[magma@10.240.0.29] out: [vagrant@127.0.0.1:2222] out: ryu.controller.controller: DEBUG: Datapath in process of terminating; send() to ('127.0.0.1', 56018) discarded.
[magma@10.240.0.29] out: [vagrant@127.0.0.1:2222] out: ryu.controller.controller: DEBUG: Datapath in process of terminating; send() to ('127.0.0.1', 56034) discarded.
```
 not sure why it happens though, any ideas on how we should get to the bottom of this?
