### ISSUE TITLE
Trying on Magma Test on Local machine

### ISSUE THREAD

**Issue by diorgesl** [magma/magma#4268]
Building 1.3.2 locally.
Everything went good until the command to connect the LTE with local Cloud:

fab -f dev_tools.py register_vm

This produces some errors:

>magma@magma:~/magma/lte/gateway$ fab -f dev_tools.py register_vm
Traceback (most recent call last):
  File "/home/magma/.local/lib/python3.6/site-packages/urllib3/connectionpool.py", line 706, in urlopen
    chunked=chunked,
  File "/home/magma/.local/lib/python3.6/site-packages/urllib3/connectionpool.py", line 382, in _make_request
    self._validate_conn(conn)
  File "/home/magma/.local/lib/python3.6/site-packages/urllib3/connectionpool.py", line 1010, in _validate_conn
    conn.connect()
  File "/home/magma/.local/lib/python3.6/site-packages/urllib3/connection.py", line 421, in connect
    tls_in_tls=tls_in_tls,
  File "/home/magma/.local/lib/python3.6/site-packages/urllib3/util/ssl_.py", line 392, in ssl_wrap_socket
    if keyfile and key_password is None and _is_key_file_encrypted(keyfile):
  File "/home/magma/.local/lib/python3.6/site-packages/urllib3/util/ssl_.py", line 451, in _is_key_file_encrypted
    with open(key_file, "r") as f:
PermissionError: [Errno 13] Permission denied: './../../.cache/test_certs/admin_operator.key.pem'

> During handling of the above exception, another exception occurred:

> Traceback (most recent call last):
  File "/home/magma/.local/lib/python3.6/site-packages/requests/adapters.py", line 449, in send
    timeout=timeout
  File "/home/magma/.local/lib/python3.6/site-packages/urllib3/connectionpool.py", line 756, in urlopen
    method, url, error=e, _pool=self, _stacktrace=sys.exc_info()[2]
  File "/home/magma/.local/lib/python3.6/site-packages/urllib3/util/retry.py", line 531, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "/home/magma/.local/lib/python3.6/site-packages/urllib3/packages/six.py", line 734, in reraise
    raise value.with_traceback(tb)
  File "/home/magma/.local/lib/python3.6/site-packages/urllib3/connectionpool.py", line 706, in urlopen
    chunked=chunked,
  File "/home/magma/.local/lib/python3.6/site-packages/urllib3/connectionpool.py", line 382, in _make_request
    self._validate_conn(conn)
  File "/home/magma/.local/lib/python3.6/site-packages/urllib3/connectionpool.py", line 1010, in _validate_conn
    conn.connect()
  File "/home/magma/.local/lib/python3.6/site-packages/urllib3/connection.py", line 421, in connect
    tls_in_tls=tls_in_tls,
  File "/home/magma/.local/lib/python3.6/site-packages/urllib3/util/ssl_.py", line 392, in ssl_wrap_socket
    if keyfile and key_password is None and _is_key_file_encrypted(keyfile):
  File "/home/magma/.local/lib/python3.6/site-packages/urllib3/util/ssl_.py", line 451, in _is_key_file_encrypted
    with open(key_file, "r") as f:
urllib3.exceptions.ProtocolError: ('Connection aborted.', PermissionError(13, 'Permission denied'))

> During handling of the above exception, another exception occurred:

> Traceback (most recent call last):
  File "/home/magma/.local/lib/python3.6/site-packages/fabric/main.py", line 763, in main
    *args, **kwargs
  File "/home/magma/.local/lib/python3.6/site-packages/fabric/tasks.py", line 427, in execute
    results['<local-only>'] = task.run(*args, **new_kwargs)
  File "/home/magma/.local/lib/python3.6/site-packages/fabric/tasks.py", line 174, in run
    return self.wrapped(*args, **kwargs)
  File "/home/magma/magma/lte/gateway/dev_tools.py", line 31, in register_vm
    if not dev_utils.does_network_exist('test'):
  File "../../orc8r/tools/fab/dev_utils.py", line 142, in does_network_exist
    networks = cloud_get('/networks', admin_cert)
  File "../../orc8r/tools/fab/dev_utils.py", line 258, in cloud_get
    resp = requests.get(PORTAL_URL + resource, verify=False, cert=admin_cert)
  File "/home/magma/.local/lib/python3.6/site-packages/requests/api.py", line 76, in get
    return request('get', url, params=params, **kwargs)
  File "/home/magma/.local/lib/python3.6/site-packages/requests/api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "/home/magma/.local/lib/python3.6/site-packages/requests/sessions.py", line 542, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/magma/.local/lib/python3.6/site-packages/requests/sessions.py", line 655, in send
    r = adapter.send(request, **kwargs)
  File "/home/magma/.local/lib/python3.6/site-packages/requests/adapters.py", line 498, in send
    raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', PermissionError(13, 'Permission denied'))

Can someone help me here?

Thank you!

**Comment by diorgesl** [comment]
nvm just changed the owner of certificates to magma user, thank you
