### ISSUE TITLE
[CI][LTE] LTE tests fail in s1aptests/test_attach_service_multi_ue.py

### ISSUE THREAD

**Issue by mattymo** [magma/magma#4666]
### Describe the Issue

This is happening to many CI magma_integration_tests jobs

s1aptests/test_attach_service_multi_ue.py  seems to break pipelined during unregister process. It's intermittent and doesn't always happen. Occasionally the next test s1aptests/test_attach_ipv4v6_pdn_type.py  will fail with a connection issue or will just hang for 2 hours until timeout.

```
Jan 30 01:37:25 magma-dev pipelined[22008]: Traceback (most recent call last):
Jan 30 01:37:25 magma-dev pipelined[22008]:   File "/usr/lib/python3.5/runpy.py", line 193, in _run_module_as_main
Jan 30 01:37:25 magma-dev pipelined[22008]:     "__main__", mod_spec)
Jan 30 01:37:25 magma-dev pipelined[22008]:   File "/usr/lib/python3.5/runpy.py", line 85, in _run_code
Jan 30 01:37:25 magma-dev pipelined[22008]:     exec(code, run_globals)
Jan 30 01:37:25 magma-dev pipelined[22008]:   File "/home/vagrant/magma/lte/gateway/python/magma/pipelined/main.py", line 186, in <module>
Jan 30 01:37:25 magma-dev pipelined[22008]:     main()
Jan 30 01:37:25 magma-dev pipelined[22008]:   File "/home/vagrant/magma/lte/gateway/python/magma/pipelined/main.py", line 170, in main
Jan 30 01:37:25 magma-dev pipelined[22008]:     service.run()
Jan 30 01:37:25 magma-dev pipelined[22008]:   File "/home/vagrant/magma/orc8r/gateway/python/magma/common/service.py", line 237, in run
Jan 30 01:37:25 magma-dev pipelined[22008]:     self._loop.run_forever()
Jan 30 01:37:25 magma-dev pipelined[22008]:   File "/usr/lib/python3/dist-packages/aioeventlet.py", line 253, in run_forever
Jan 30 01:37:25 magma-dev pipelined[22008]:     super(EventLoop, self).run_forever()
Jan 30 01:37:25 magma-dev pipelined[22008]:   File "/usr/lib/python3.5/asyncio/base_events.py", line 421, in run_forever
Jan 30 01:37:25 magma-dev pipelined[22008]:     self._run_once()
Jan 30 01:37:25 magma-dev pipelined[22008]:   File "/usr/lib/python3.5/asyncio/base_events.py", line 1388, in _run_once
Jan 30 01:37:25 magma-dev pipelined[22008]:     event_list = self._selector.select(timeout)
Jan 30 01:37:25 magma-dev pipelined[22008]:   File "/usr/lib/python3/dist-packages/aioeventlet.py", line 167, in select
Jan 30 01:37:25 magma-dev pipelined[22008]:     events = self._read_events()
Jan 30 01:37:25 magma-dev pipelined[22008]:   File "/usr/lib/python3/dist-packages/aioeventlet.py", line 162, in _read_events
Jan 30 01:37:25 magma-dev pipelined[22008]:     key = self.get_key(fd)
Jan 30 01:37:25 magma-dev pipelined[22008]:   File "/usr/lib/python3.5/selectors.py", line 191, in get_key
Jan 30 01:37:25 magma-dev pipelined[22008]:     raise KeyError("{!r} is not registered".format(fileobj)) from None
Jan 30 01:37:25 magma-dev pipelined[22008]: KeyError: '24 is not registered'
Jan 30 01:37:27 magma-dev systemd[1]: magma@pipelined.service: Main process exited, code=exited, status=1/FAILURE
Jan 30 01:37:28 magma-dev systemd[1]: Stopping User Manager for UID 1000...

```

**Expected behavior**
1 - no single integration test should take more than 15 minutes and should have a timeout wrapper
2 - unregistering a UE should never cause pipeline to crash so much that it can't restart

**Additional context**
There are logs in these jobs. Here are 2 examples:
Timed out running next test https://jenkins.magmacore.org/job/magma_integration_tests/2393/artifact/magma_logs.zip
Failed quickly running next test https://jenkins.magmacore.org/job/magma_integration_tests/2388/artifact/magma_logs.zip

**Comment by koolzz** [comment]
Will investigate

**Comment by mattymo** [comment]
@koolzz any updates?
