### ISSUE TITLE
Fix Redis initialization

### ISSUE THREAD

**Issue by pshelar** [magma/magma#4681]

**Comment by pshelar** [comment]
On `make start` syslog is logging error related to redis connectivity:
```
Feb  2 03:06:03 magma-dev-focal state[49616]: DEBUG:root:Check state
Feb  2 03:06:03 magma-dev-focal sessiond[49583]: I0202 03:06:03.715467 49583 sessiond_main.cpp:145] Attempting to connect to Redis
Feb  2 03:06:03 magma-dev-focal sessiond[49583]: [/home/vagrant/magma/orc8r/gateway/c/common/config/ServiceConfigLoader.cpp:34] Override file not found for service redis
Feb  2 03:06:03 magma-dev-focal sessiond[49583]: I0202 03:06:03.716267 49583 RedisStoreClient.cpp:42] Could not connect to redis: connect() failure
Feb  2 03:06:03 magma-dev-focal state[49616]: ERROR:root:Exception from _run: Error 111 connecting to 127.0.0.1:6380. Connection refused.
Feb  2 03:06:03 magma-dev-focal state[49616]: Traceback (most recent call last):
Feb  2 03:06:03 magma-dev-focal state[49616]:   File "/home/vagrant/build/python/lib/python3.8/site-packages/redis/connection.py", line 559, in connect
Feb  2 03:06:03 magma-dev-focal state[49616]:     sock = self._connect()
Feb  2 03:06:03 magma-dev-focal state[49616]:   File "/home/vagrant/build/python/lib/python3.8/site-packages/redis/connection.py", line 615, in _connect
Feb  2 03:06:03 magma-dev-focal state[49616]:     raise err
Feb  2 03:06:03 magma-dev-focal state[49616]:   File "/home/vagrant/build/python/lib/python3.8/site-packages/redis/connection.py", line 603, in _connect
Feb  2 03:06:03 magma-dev-focal state[49616]:     sock.connect(socket_address)
Feb  2 03:06:03 magma-dev-focal state[49616]: ConnectionRefusedError: [Errno 111] Connection refused
Feb  2 03:06:03 magma-dev-focal state[49616]: During handling of the above exception, another exception occurred:
Feb  2 03:06:03 magma-dev-focal state[49616]: Traceback (most recent call last):
Feb  2 03:06:03 magma-dev-focal state[49616]:   File "/home/vagrant/magma/orc8r/gateway/python/magma/common/job.py", line 121, in _periodic
Feb  2 03:06:03 magma-dev-focal state[49616]:     await self._run()
Feb  2 03:06:03 magma-dev-focal state[49616]:   File "/home/vagrant/magma/orc8r/gateway/python/magma/state/state_replicator.py", line 76, in _run
Feb  2 03:06:03 magma-dev-focal state[49616]:     await self._resync()
Feb  2 03:06:03 magma-dev-focal state[49616]:   File "/home/vagrant/magma/orc8r/gateway/python/magma/state/state_replicator.py", line 96, in _resync
Feb  2 03:06:03 magma-dev-focal state[49616]:     for key in redis_dict:
Feb  2 03:06:03 magma-dev-focal state[49616]:   File "/home/vagrant/magma/orc8r/gateway/python/magma/common/redis/containers.py", line 219, in __iter__
Feb  2 03:06:03 magma-dev-focal state[49616]:     for k in self.redis.keys(pattern=type_pattern):
Feb  2 03:06:03 magma-dev-focal state[49616]:   File "/home/vagrant/build/python/lib/python3.8/site-packages/redis/client.py", line 1661, in keys
Feb  2 03:06:03 magma-dev-focal state[49616]:     return self.execute_command('KEYS', pattern)
Feb  2 03:06:03 magma-dev-focal state[49616]:   File "/home/vagrant/build/python/lib/python3.8/site-packages/redis/client.py", line 898, in execute_command
Feb  2 03:06:03 magma-dev-focal state[49616]:     conn = self.connection or pool.get_connection(command_name, **options)
Feb  2 03:06:03 magma-dev-focal state[49616]:   File "/home/vagrant/build/python/lib/python3.8/site-packages/redis/connection.py", line 1192, in get_connection
Feb  2 03:06:03 magma-dev-focal state[49616]:     connection.connect()
Feb  2 03:06:03 magma-dev-focal state[49616]:   File "/home/vagrant/build/python/lib/python3.8/site-packages/redis/connection.py", line 563, in connect
Feb  2 03:06:03 magma-dev-focal state[49616]:     raise ConnectionError(self._error_message(e))
Feb  2 03:06:03 magma-dev-focal state[49616]: redis.exceptions.ConnectionError: Error 111 connecting to 127.0.0.1:6380. Connection refused.
```
