### ISSUE TITLE
Access Gateway health status crashes

### ISSUE THREAD

**Issue by electrocucaracha** [magma/magma#4692]
### Your Environment

- **Version:** `44b874b590d4270be1dc23139e4ddc58c1ae664f`
- **Affected Component:** Access Gateway
- **Affected Subcomponent:** Health Checker
- **Deployment Environment:** Vagrant

### Describe the Issue

**To Reproduce**
1. Follow the official steps described [here](https://docs.magmacore.org/docs/lte/s1ap_tests#gateway-vm-setup)
2. Enable the virtual environment with `magtivate`
3. Execute the `agw_health_cli.py status` command
4. See the following error
```
Access Gateway health summary

Using subscriberdb
#eNBs connected:    0    (run `enodebd_cli.py get_all_status` for more details)
#IPs allocated:     0    (run `mobility_cli.py list_allocated_ips` for more details)
#UEs connected:     0    (run `mobility_cli.py get_subscriber_table` for more details)
#Core dumps:        0    (run `ls /tmp/` to see core dumps)
Earliest core-dump: -, Latest core-dump: None
Registration success rate: No Attach requests (0 requests, 0 accepted)

Traceback (most recent call last):
  File "/home/vagrant/build/python/bin/health_cli.py", line 7, in <module>
    exec(compile(f.read(), __file__, 'exec'))
  File "/home/vagrant/magma/orc8r/gateway/python/scripts/health_cli.py", line 21, in <module>
    from magma.common.health.docker_health_service import DockerHealthChecker
  File "/home/vagrant/magma/orc8r/gateway/python/magma/common/health/docker_health_service.py", line 20, in <module>
    from magma.common.health.health_service import GenericHealthChecker
  File "/home/vagrant/magma/orc8r/gateway/python/magma/common/health/health_service.py", line 31, in <module>
    from pystemd.systemd1 import Unit
  File "/home/vagrant/build/python/lib/python3.5/site-packages/pystemd/__init__.py", line 103, in <module>
    from pystemd import DBus, __version__, machine1, systemd1
  File "/home/vagrant/build/python/lib/python3.5/site-packages/pystemd/DBus/__init__.py", line 10, in <module>
    from pystemd.base import SDObject
  File "/home/vagrant/build/python/lib/python3.5/site-packages/pystemd/base.py", line 14, in <module>
    from pystemd.dbuslib import DBus, apply_signature
ImportError: /home/vagrant/build/python/lib/python3.5/site-packages/pystemd/dbuslib.cpython-35m-x86_64-linux-gnu.so: undefined symbol: sd_bus_match_signal
```

**Expected behavior**
No errors

**Screenshots**
N/A

**Additional context**
N/A

**Comment by karthiksubraveti** [comment]
@ardzoht @themarwhal Is this a known issue?

**Comment by themarwhal** [comment]
@karthiksubraveti I am seeing this exact error on master actually. Will investigate. Maybe related: (https://github.com/facebookincubator/pystemd/issues/26)

Did this ever work? Looks like pystemd requires at least v237 when we have v232. (https://github.com/facebookincubator/pystemd)
```
(python) vagrant@magma-dev:~/magma/lte/gateway$ apt-cache policy systemd
systemd:
  Installed: 232-25+deb9u12
  Candidate: 232-25+deb9u12
```

**Comment by jordanvrtanoski** [comment]
I have applied following workaround:

1) Add the `stretch-backports` repository
```
~# echo 'deb http://deb.debian.org/debian stretch-backports main'  >> /etc/apt/sources.list
```
2) Rebuild the apt cache
```
~# apt update
~# apt-cache policy systemd
systemd:
  Installed: 241-5~bpo9+1
  Candidate: 241-5~bpo9+1
  Version table:
     241-5~bpo9+1 100
        100 http://deb.debian.org/debian stretch-backports/main amd64 Packages
        100 /var/lib/dpkg/status
 *** 232-25+deb9u12 500
        500 http://ftp.us.debian.org/debian stretch/main amd64 Packages
     232-25+deb9u11 500
        500 http://security.debian.org/debian-security stretch/updates/main amd64 Packages
```
3) Install the updated version
```
~#  apt -t stretch-backports install systemd
```
4) Check `agw_health_cli.py`
```
~# agw_health_cli.py
Access Gateway health summary

Using SubscriberDB
#eNBs connected:    0 	 (run `enodebd_cli.py get_all_status` for more details)
#IPs allocated:     0 	 (run `mobility_cli.py list_allocated_ips` for more details)
#UEs connected:     0 	 (run `mobility_cli.py get_subscriber_table` for more details)
#Core dumps:        2 	 (run `ls /var/core` to see core dumps)
Earliest core-dump: 2021-04-04 03:41:03, Latest core-dump: 2021-04-04 03:53:39
Registration success rate: No Attach requests (0 requests, 0 accepted)

/usr/local/lib/python3.5/dist-packages/magma/common/cert_utils.py:16: CryptographyDeprecationWarning: Python 3.5 support will be dropped in the next release of cryptography. Please upgrade your Python.
  from cryptography import x509
Health Summary

Gateway <-> Controller connectivity
1. -- Testing TCP connection to controller.magma.test:7443 --
2. -- Testing Certificate --
3. -- Testing SSL --
4. -- Creating direct cloud checkin --
5. -- Creating proxy cloud checkin --
Success!

Error: 'logLevel'
```
