### ISSUE TITLE
[MME][Stateless] MME crash during timer recovery

### ISSUE THREAD

**Issue by talkhasib** [magma/magma#4699]
```
#0  hashtable_ts_apply_callback_on_elements (hashtblP=0x60700000c860, funct_cb=funct_cb@entry=0x5607fca70bdb <mme_app_recover_timers_for_ue>, parameterP=parameterP@entry=0x0, resultP=resultP@entry=0x0)
    at /home/vagrant/magma/lte/gateway/c/oai/lib/hashtable/hashtable.c:572
#1  0x00005607fca75524 in mme_app_recover_timers_for_all_ues () at /home/vagrant/magma/lte/gateway/c/oai/tasks/mme_app/mme_app_context.c:2307
#2  0x00005607fca5642c in handle_message (loop=<optimized out>, reader=<optimized out>, arg=<optimized out>) at /home/vagrant/magma/lte/gateway/c/oai/tasks/mme_app/mme_app_main.c:438
#3  0x00007f3446a2e7be in zloop_start () from /usr/lib/x86_64-linux-gnu/libczmq.so.4
#4  0x00005607fca55d3a in mme_app_thread (args=<optimized out>) at /home/vagrant/magma/lte/gateway/c/oai/tasks/mme_app/mme_app_main.c:468
#5  0x00007f344920d4a4 in start_thread (arg=0x7f34368de700) at pthread_create.c:456
#6  0x00007f3445581d0f in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:97
```

[https://app.zenhub.com/files/170803235/407ce508-ce6f-4167-9183-5cb90d52b82b/download](https://app.zenhub.com/files/170803235/407ce508-ce6f-4167-9183-5cb90d52b82b/download)

**Comment by talkhasib** [comment]
[mme.zip](https://github.com/magma/magma/files/5915212/mme.zip)

**Comment by talkhasib** [comment]
on 1.4 commit e22e0fc709c455093aeb639f25651166f89c6c23
