### ISSUE TITLE
[MME][Stateless] Multiple cores generated from redis client

### ISSUE THREAD

**Issue by talkhasib** [magma/magma#4702]
```
#0  0x000056409192d0e6 in tacopie::io_service::set_wr_callback(tacopie::tcp_socket const&, std::function<void (int)> const&) ()
#1  0x4b80a8c09193098f in ?? ()
#2  0x000060200005c020 in ?? ()
#3  0x00007fcd593bd948 in ?? ()
#4  0x0000564091930c30 in ?? ()
#5  0x0000564091930cb0 in ?? ()
#6  0x00007fcd593bda50 in ?? ()
#7  0x00007fcd593bd9d0 in ?? ()
#8  0x000060100001bf40 in ?? ()
#9  0x00005640918db83d in std::_Function_base::_Base_manager<cpp_redis::client::exec_cmd(std::function<cpp_redis::client& (std::function<void (cpp_redis::reply&)> const&)> const&)::{lambda(cpp_redis::reply&)#1}>::_M_manager(std::_Any_data&, std::_Function_base::_Base_manager<cpp_redis::client::exec_cmd(std::function<cpp_redis::client& (std::function<void (cpp_redis::reply&)> const&)> const&)::{lambda(cpp_redis::reply&)#1}> const&, std::_Manager_operation) ()
#10 0x00005640918fa03c in cpp_redis::client::unprotected_send(std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > const&, std::function<void (cpp_redis::reply&)> const&) ()
#11 0x0000000000000000 in ?? ()
```

[core.2.zip](https://github.com/magma/magma/files/5915222/core.2.zip)
[core.5.zip](https://github.com/magma/magma/files/5915224/core.5.zip)
[core.7.zip](https://github.com/magma/magma/files/5915226/core.7.zip)
[core.10.zip](https://github.com/magma/magma/files/5915227/core.10.zip)
[core.11.zip](https://github.com/magma/magma/files/5915228/core.11.zip)
[mme.zip](https://github.com/magma/magma/files/5915229/mme.zip)

**Comment by talkhasib** [comment]
on 1.4 commit e22e0fc709c455093aeb639f25651166f89c6c23

**Comment by ardzoht** [comment]
Closed since this was fixed by https://github.com/magma/magma/pull/5416 changes
