### ISSUE TITLE
[MME][Stateless] MME crash during writing spgw state or spgw ue state

### ISSUE THREAD

**Issue by talkhasib** [magma/magma#4703]
```
#0  0x0000560788bb99ca in tacopie::tcp_client::async_write(tacopie::tcp_client::write_request const&) ()
#1  0x0000560788bb06d4 in cpp_redis::network::tcp_client::async_write(cpp_redis::network::tcp_client_iface::write_request&) ()
#2  0x0000560788baf146 in cpp_redis::network::redis_connection::commit() ()
#3  0x0000560788ba0b42 in cpp_redis::client::try_commit() ()
#4  0x0000560788ba0ca0 in cpp_redis::client::sync_commit() ()
#5  0x0000560788b53936 in magma::lte::RedisClient::write (this=0x60100000d430, key="IMSI001010000000088:SPGW",
    value="\n\360\002\n\355\002\n\325\002\n\017\060\060\061\060\061\060\060\060\060\060\060\060\060\070\070\020\001\"\016\n\f000000P܋\"`\177\060\330\350\303Ų\035P\311\004Z\004\300\250<\216x\311\004\202\001\004\000\000\000\000\242\001o\n\nmagma.ipv4\022\004\000\000\000\000\032\004\000\000\000\000P\005z?\b\005\022\004\000\000\000\000R\004\000\000\000\000b\004\000\000\000\000r\004\000\000\000\000x\311\004\202\001\004\000\000\000\000\242\001\n\b\001\020\017(\tR\000Z\000\252\001\004\n\000\022\000\322\001\004\000\000\000\000z\000z\000z\000z\000z\000z\000z\000z\000z\000z\000\252\001\242\001\032\017\060\060\061\060\061\060\060\060\060\060"...) at /home/vagrant/magma/lte/gateway/c/oai/common/redis_utils/redis_client.cpp:61
#6  0x0000560788b53cb8 in magma::lte::RedisClient::write_proto (this=0x60100000d430, key="IMSI001010000000088:SPGW", proto_msg=...)
    at /home/vagrant/magma/lte/gateway/c/oai/common/redis_utils/redis_client.cpp:112
#7  0x0000560788b33dda in magma::lte::StateManager<spgw_state_s, spgw_ue_context_s, magma::lte::oai::SpgwState, magma::lte::oai::SpgwUeContext, magma::lte::SpgwStateConverter>::write_ue_state_to_db (
    this=0x5607891e5e60 <magma::lte::SpgwStateManager::getInstance()::instance>, ue_context=0x60100001d0d0, imsi_str="001010000000088") at /home/vagrant/magma/lte/gateway/c/oai/include/state_manager.h:153
#8  0x0000560788b3238f in put_spgw_ue_state (spgw_state=0x60700000c630, imsi64=1010000000088) at /home/vagrant/magma/lte/gateway/c/oai/tasks/sgw/spgw_state.cpp:69
#9  0x0000560788b2a1e8 in handle_message (loop=<optimized out>, reader=<optimized out>, arg=<optimized out>) at /home/vagrant/magma/lte/gateway/c/oai/tasks/sgw/sgw_task.c:182
#10 0x00007f60352517be in zloop_start () from /usr/lib/x86_64-linux-gnu/libczmq.so.4
#11 0x0000560788b2a126 in spgw_app_thread (args=<optimized out>) at /home/vagrant/magma/lte/gateway/c/oai/tasks/sgw/sgw_task.c:196
#12 0x00007f6037a304a4 in start_thread (arg=0x7f60228d9700) at pthread_create.c:456
#13 0x00007f6033da4d0f in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:97
```

[core.4.zip](https://github.com/magma/magma/files/5915234/core.4.zip)
[core.6.zip](https://github.com/magma/magma/files/5915235/core.6.zip)
[mme.zip](https://github.com/magma/magma/files/5915236/mme.zip)

**Comment by talkhasib** [comment]
on 1.4 commit e22e0fc709c455093aeb639f25651166f89c6c23

**Comment by ekowtaylor** [comment]
related to https://github.com/magma/magma/issues/4492

**Comment by ardzoht** [comment]
Closing this issue since fixes https://github.com/magma/magma/pull/5416 and https://github.com/magma/magma/pull/5456 have merged to address issue with writing SPGW state on different thread
