### ISSUE TITLE
[MME] mme crash handling delete session request

### ISSUE THREAD

**Issue by talkhasib** [magma/magma#4704]
```
#0  0x00007f00ec0c6910 in gpr_ref () from /usr/local/lib/libgrpc.so.6
#1  0x00007f00ec0577d3 in grpc_call_create(grpc_call_create_args const*, grpc_call**) () from /usr/local/lib/libgrpc.so.6
#2  0x00007f00ec05824b in ?? () from /usr/local/lib/libgrpc.so.6
#3  0x00007f00ec0593fc in grpc_channel_create_registered_call () from /usr/local/lib/libgrpc.so.6
#4  0x00007f00ebda8d57 in grpc::Channel::CreateCall(grpc::internal::RpcMethod const&, grpc::ClientContext*, grpc::CompletionQueue*) () from /usr/local/lib/libgrpc++.so.1
#5  0x000055ef3c6efa0d in grpc::internal::ClientAsyncResponseReaderFactory<magma::lte::LocalEndSessionResponse>::Create<magma::lte::LocalEndSessionRequest> (channel=0x606000029dc0,
    cq=0x55ef3d0b8380 <magma::PCEFClient::get_instance()::client_instance>, method=..., context=0x61500016f5c0, request=..., start=true) at /usr/local/include/grpcpp/impl/codegen/async_unary_call.h:87
#6  0x000055ef3c6eb9c7 in magma::lte::LocalSessionManager::Stub::AsyncEndSessionRaw (this=0x60b000020df0, context=0x61500016f5c0, request=...,
    cq=0x55ef3d0b8380 <magma::PCEFClient::get_instance()::client_instance>) at /home/vagrant/build/c/oai/tasks/grpc_service/lte/protos/session_manager.grpc.pb.cc:72
#7  0x000055ef3cab8752 in magma::lte::LocalSessionManager::Stub::AsyncEndSession (this=0x60b000020df0, context=0x61500016f5c0, request=...,
    cq=0x55ef3d0b8380 <magma::PCEFClient::get_instance()::client_instance>) at lib/pcef/lte/protos/session_manager.grpc.pb.h:127
#8  0x000055ef3cab7f0e in magma::PCEFClient::end_session(magma::lte::LocalEndSessionRequest const&, std::function<void (grpc::Status, magma::lte::LocalEndSessionResponse)>) (request=..., callback=...)
    at /home/vagrant/magma/lte/gateway/c/oai/lib/pcef/PCEFClient.cpp:88
#9  0x000055ef3cab548b in pcef_end_session (imsi=0x62900015e000 "001010000000087", apn=0x601000009ef0 "magma.ipv4") at /home/vagrant/magma/lte/gateway/c/oai/lib/pcef/pcef_handlers.cpp:157
#10 0x000055ef3c9fe48c in sgw_handle_delete_session_request (spgw_state=spgw_state@entry=0x60700000c630, delete_session_req_pP=delete_session_req_pP@entry=0x62900044c026, imsi64=imsi64@entry=1010000000087)
    at /home/vagrant/magma/lte/gateway/c/oai/tasks/sgw/sgw_handlers.c:1103
#11 0x000055ef3c9fc229 in handle_message (loop=<optimized out>, reader=<optimized out>, arg=<optimized out>) at /home/vagrant/magma/lte/gateway/c/oai/tasks/sgw/sgw_task.c:83
#12 0x00007f00eafea7be in zloop_start () from /usr/lib/x86_64-linux-gnu/libczmq.so.4
#13 0x000055ef3c9fc126 in spgw_app_thread (args=<optimized out>) at /home/vagrant/magma/lte/gateway/c/oai/tasks/sgw/sgw_task.c:196
#14 0x00007f00ed7c94a4 in start_thread (arg=0x7f00d7ed8700) at pthread_create.c:456
#15 0x00007f00e9b3dd0f in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:97
```

[core.8.zip](https://github.com/magma/magma/files/5915243/core.8.zip)
[mme.zip](https://github.com/magma/magma/files/5915244/mme.zip)

**Comment by talkhasib** [comment]
on 1.4 commit e22e0fc709c455093aeb639f25651166f89c6c23

**Comment by ulaskozat** [comment]
@talkhasib was this reproduced using the random testing?

**Comment by ardzoht** [comment]
> @talkhasib was this reproduced using the random testing?

answering for Tariq here, correct, this issue was filed by using the continuous attach s1ap test

**Comment by talkhasib** [comment]
New core + logs
https://drive.google.com/file/d/1rrM4hQlsn8f26pngZvRPB1HFxnA6g12d/view?usp=sharing

Private drive. Can open it up if needed.

**Comment by ulaskozat** [comment]
@talkhasib is this the same issue?

```
#0  0x00007f9bbb35e910 in gpr_ref () from /usr/local/lib/libgrpc.so.6
[Current thread is 1 (Thread 0x7f9ba544b700 (LWP 11644))]
(gdb) bt
#0  0x00007f9bbb35e910 in gpr_ref () from /usr/local/lib/libgrpc.so.6
#1  0x00007f9bbb2ef65e in grpc_call_create(grpc_call_create_args const*, grpc_call**) ()
   from /usr/local/lib/libgrpc.so.6
#2  0x00007f9bbb2f024b in ?? () from /usr/local/lib/libgrpc.so.6
#3  0x00007f9bbb2f13fc in grpc_channel_create_registered_call () from /usr/local/lib/libgrpc.so.6
#4  0x00007f9bbb040d57 in grpc::Channel::CreateCall(grpc::internal::RpcMethod const&, grpc::ClientContext*, grpc::CompletionQueue*) () from /usr/local/lib/libgrpc++.so.1
#5  0x000055f5a8894c1f in grpc::internal::ClientAsyncResponseReaderFactory<magma::orc8r::Void>::Create<magma::lte::ReleaseIPRequest> (channel=0x608000049da0, 
    cq=0x55f5a9403908 <magma::lte::MobilityServiceClient::getInstance()::instance+8>, method=..., 
    context=0x616000529bc0, request=..., start=true)
    at /usr/local/include/grpcpp/impl/codegen/async_unary_call.h:87
#6  0x000055f5a88927cd in magma::lte::MobilityService::Stub::AsyncReleaseIPAddressRaw (
    this=0x612000007840, context=0x616000529bc0, request=..., 
    cq=0x55f5a9403908 <magma::lte::MobilityServiceClient::getInstance()::instance+8>)
    at /home/vagrant/build/c/oai/lib/mobility_client/lte/protos/mobilityd.grpc.pb.cc:106
#7  0x000055f5a8890b60 in magma::lte::MobilityService::Stub::AsyncReleaseIPAddress (
    this=0x612000007840, context=0x616000529bc0, request=..., 
    cq=0x55f5a9403908 <magma::lte::MobilityServiceClient::getInstance()::instance+8>)
    at lib/mobility_client/lte/protos/mobilityd.grpc.pb.h:212
#8  0x000055f5a888f3da in magma::lte::MobilityServiceClient::ReleaseIPAddressRPC(magma::lte::ReleaseIPRequest const&, std::function<void (grpc::Status, magma::orc8r::Void)> const&) (
    this=0x55f5a9403900 <magma::lte::MobilityServiceClient::getInstance()::instance>, request=..., 
    callback=...)
    at /home/vagrant/magma/lte/gateway/c/oai/lib/mobility_client/MobilityServiceClient.cpp:263
#9  0x000055f5a888e47f in magma::lte::MobilityServiceClient::ReleaseIPv4Address (
    this=0x55f5a9403900 <magma::lte::MobilityServiceClient::getInstance()::instance>, 
    imsi="001010000000097", apn="magma.ipv4", addr=...)
    at /home/vagrant/magma/lte/gateway/c/oai/lib/mobility_client/MobilityServiceClient.cpp:115
#10 0x000055f5a888be58 in release_ipv4_address (subscriber_id=0x629000622200 "001010000000097", 
---Type <return> to continue, or q <return> to quit---
    00045f970 "magma.ipv4", addr=0x7f9ba544a540)
    at /home/vagrant/magma/lte/gateway/c/oai/lib/mobility_client/MobilityClientAPI.cpp:162
#11 0x000055f5a87f9c18 in release_ue_ipv4_address (imsi=0x629000622200 "001010000000097", apn=0x60200045f970 "magma.ipv4", 
    addr=0x7f9ba544a540) at /home/vagrant/magma/lte/gateway/c/oai/tasks/sgw/mobilityd_ue_ip_address_alloc.c:32
#12 0x000055f5a87e4b5b in sgw_handle_sgi_endpoint_deleted (resp_pP=0x7f9ba544a740, imsi64=1010000000097)
    at /home/vagrant/magma/lte/gateway/c/oai/tasks/sgw/sgw_handlers.c:791
#13 0x000055f5a87e7f8d in sgw_handle_delete_session_request (spgw_state=0x60b000001220, delete_session_req_pP=0x6290009e7226, 
    imsi64=1010000000097) at /home/vagrant/magma/lte/gateway/c/oai/tasks/sgw/sgw_handlers.c:1158
#14 0x000055f5a87de55e in handle_message (loop=0x60b000031790, reader=0x60600012bf60, arg=0x0)
    at /home/vagrant/magma/lte/gateway/c/oai/tasks/sgw/sgw_task.c:83
#15 0x00007f9bba2827be in zloop_start () from /usr/lib/x86_64-linux-gnu/libczmq.so.4
#16 0x000055f5a87decc5 in spgw_app_thread (args=0x0) at /home/vagrant/magma/lte/gateway/c/oai/tasks/sgw/sgw_task.c:196
#17 0x00007f9bbca614a4 in start_thread (arg=0x7f9ba544b700) at pthread_create.c:456
#18 0x00007f9bb8dd5d0f in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:97
```

**Comment by ulaskozat** [comment]
@talkhasib @ardzoht indeed these two look related.

**Comment by ardzoht** [comment]
@ulaskozat Have we seen this crash again since the latest pipelined and mobilityd updates? Wondering if those were the result of the slow performance on the AGW

**Comment by ulaskozat** [comment]
@ardzoht all the crashes I see are now due to writing state to Redis. Have not seen this after the recent changes...

**Comment by ssanadhya** [comment]
Closing this issue as there have been several fixes to Mobilityd, MME and Pipelined around Redis state management.
There has also been a fix to handle duplicate attach requests and remove the race condition between processing new Attach request while detaching the old context.
