### ISSUE TITLE
[AGW][S1ap tests] Test fails to start due to OVS Rest API error

### ISSUE THREAD

**Issue by ssanadhya** [magma/magma#4814]
While running `test_continuous_random_attach.py` repeatedly, sometimes the test fails to start. Tcpdump shows that no SCTP packets are being sent/received at the gateway VM. On killing the test, it gives the following traceback.

```
vagrant@magma-test:~/magma/lte/gateway/python/integ_tests$ make integ_test TESTS=s1aptests/test_continuous_random_attach.py
. /home/vagrant/build/python/bin/activate
echo "Running test: s1aptests/test_continuous_random_attach.py"
Running test: s1aptests/test_continuous_random_attach.py
sudo -E PATH=/usr/lib/ccache:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/local/go/bin PYTHONPATH=:/home/vagrant/s1ap-tester/bin /home/vagrant/build/python/bin/nosetests -x -s s1aptests/test_continuous_random_attach.py || exit 1
^C
Traceback (most recent call last):
  File "/home/vagrant/build/python/bin/nosetests", line 8, in <module>
    sys.exit(run_exit())
  File "/home/vagrant/build/python/lib/python3.5/site-packages/nose/core.py", line 121, in __init__
    **extra_args)
  File "/usr/lib/python3.5/unittest/main.py", line 93, in __init__
    self.parseArgs(argv)
  File "/home/vagrant/build/python/lib/python3.5/site-packages/nose/core.py", line 179, in parseArgs
    self.createTests()
  File "/home/vagrant/build/python/lib/python3.5/site-packages/nose/core.py", line 193, in createTests
    self.test = self.testLoader.loadTestsFromNames(self.testNames)
  File "/home/vagrant/build/python/lib/python3.5/site-packages/nose/loader.py", line 481, in loadTestsFromNames
    return unittest.TestLoader.loadTestsFromNames(self, names, module)
  File "/usr/lib/python3.5/unittest/loader.py", line 219, in loadTestsFromNames
    suites = [self.loadTestsFromName(name, module) for name in names]
  File "/usr/lib/python3.5/unittest/loader.py", line 219, in <listcomp>
    suites = [self.loadTestsFromName(name, module) for name in names]
  File "/home/vagrant/build/python/lib/python3.5/site-packages/nose/loader.py", line 418, in loadTestsFromName
    addr.filename, addr.module)
  File "/home/vagrant/build/python/lib/python3.5/site-packages/nose/importer.py", line 47, in importFromPath
    return self.importFromDir(dir_path, fqname)
  File "/home/vagrant/build/python/lib/python3.5/site-packages/nose/importer.py", line 94, in importFromDir
    mod = load_module(part_fqname, fh, filename, desc)
  File "/home/vagrant/build/python/lib/python3.5/imp.py", line 234, in load_module
    return load_source(name, filename, file)
  File "/home/vagrant/build/python/lib/python3.5/imp.py", line 172, in load_source
    module = _load(spec)
  File "<frozen importlib._bootstrap>", line 693, in _load
  File "<frozen importlib._bootstrap>", line 673, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 673, in exec_module
  File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
  File "/home/vagrant/magma/lte/gateway/python/integ_tests/s1aptests/test_continuous_random_attach.py", line 20, in <module>
    import s1ap_wrapper
  File "/home/vagrant/magma/lte/gateway/python/integ_tests/s1aptests/s1ap_wrapper.py", line 28, in <module>
    from integ_tests.s1aptests.s1ap_utils import (
  File "/home/vagrant/magma/lte/gateway/python/integ_tests/s1aptests/s1ap_utils.py", line 68, in <module>
    class S1ApUtil(object):
  File "/home/vagrant/magma/lte/gateway/python/integ_tests/s1aptests/s1ap_utils.py", line 91, in S1ApUtil
    datapath = get_datapath()
  File "/home/vagrant/magma/lte/gateway/python/integ_tests/s1aptests/ovs/rest_api.py", line 60, in get_datapath
    return str(_ovs_api_request('GET', url)[0])
  File "/home/vagrant/magma/lte/gateway/python/integ_tests/s1aptests/ovs/rest_api.py", line 70, in _ovs_api_request
    response = requests.request(method, url, data=data)
  File "/home/vagrant/build/python/lib/python3.5/site-packages/requests/api.py", line 60, in request
    return session.request(method=method, url=url, **kwargs)
  File "/home/vagrant/build/python/lib/python3.5/site-packages/requests/sessions.py", line 533, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/vagrant/build/python/lib/python3.5/site-packages/requests/sessions.py", line 646, in send
    r = adapter.send(request, **kwargs)
  File "/home/vagrant/build/python/lib/python3.5/site-packages/requests/adapters.py", line 449, in send
    timeout=timeout
  File "/home/vagrant/build/python/lib/python3.5/site-packages/urllib3/connectionpool.py", line 677, in urlopen
    chunked=chunked,
  File "/home/vagrant/build/python/lib/python3.5/site-packages/urllib3/connectionpool.py", line 426, in _make_request
    six.raise_from(e, None)
  File "<string>", line 3, in raise_from
  File "/home/vagrant/build/python/lib/python3.5/site-packages/urllib3/connectionpool.py", line 421, in _make_request
    httplib_response = conn.getresponse()
  File "/usr/lib/python3.5/http/client.py", line 1252, in getresponse
    response.begin()
  File "/usr/lib/python3.5/http/client.py", line 311, in begin
    version, status, reason = self._read_status()
  File "/usr/lib/python3.5/http/client.py", line 272, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "/usr/lib/python3.5/socket.py", line 576, in readinto
    return self._sock.recv_into(b)
KeyboardInterrupt
Makefile:32: recipe for target 'integ_test' failed
make: *** [integ_test] Interrupt
```

Issue gets resolved by doing `sudo service sctpd restart`

**Comment by ssanadhya** [comment]
Pipelined logs show:

```
Feb 08 20:34:08 magma-dev pipelined[15699]: ERROR:pipelined.qos.qos_tc_impl:error deleting class 162, not releasing idx
Feb 08 20:34:08 magma-dev pipelined[15699]: RTNETLINK answers: Device or resource busy
Feb 08 20:34:08 magma-dev pipelined[15699]: Exception ignored when trying to write to the signal wakeup fd:
Feb 08 20:34:08 magma-dev pipelined[15699]: BlockingIOError: [Errno 11] Resource temporarily unavailable
``` 

Complete syslog attached in 
[s1aptest_fail_syslog_feb8.log.gz](https://github.com/magma/magma/files/5946770/s1aptest_fail_syslog_feb8.log.gz)

**Comment by pshelar** [comment]
@ssanadhya yes, this is known issue. I have seen it with and without QoS.

**Comment by ssanadhya** [comment]
> @ssanadhya yes, this is known issue. I have seen it with and without QoS.

@pshelar, if there is an existing issue tracking this, please feel free to link it to this one or close this as duplicate.

**Comment by ssanadhya** [comment]
Similar issue reported in https://github.com/magma/magma/issues/4475
