### ISSUE TITLE
[MME] stack-buffer-overflow discovery within decode_emm_cause() #fuzz

### ISSUE THREAD

**Issue by electronjoe** [magma/magma#4940]
Discovery thanks to Fuzzing driven by [American Fuzzy Lop](https://lcamtuf.coredump.cx/afl/).

Magma [Master df06398](https://github.com/magma/magma/commit/df0639879a5be15746c41507c5a40573a1675bfc).

Fuzzing [decode_attach_accept()](https://github.com/magma/magma/blob/4f87b3f/lte/gateway/c/oai/tasks/nas/emm/msg/AttachAccept.c#L26) with the top level main and input bytes of [Gist](https://gist.github.com/electronjoe/c24cae62cca935ba2d2a550e4423ebaf) result in the following ASAN failure / stack trace:

```
Starting program: /home/vagrant/build/c/oai/tasks/nas/attach_accept_fuzz sync_dir/fuzzer01/crashes/id:000029,sig:06,src:000167,op:havoc,rep:8
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
Initializing OAI Logging
Initializing OAI Logging to syslog
Could not create logging file: Permission denied
COULD NOT CREATE A LOGGINGFILE 20210212-183248.10494!Gathered 128 bytes from file with contents ''
=================================================================
==10494==ERROR: AddressSanitizer: stack-buffer-overflow on address 0x7fffffffdd40 at pc 0x5555555a131a bp 0x7fffffffd4b0 sp 0x7fffffffd4a8
READ of size 1 at 0x7fffffffdd40 thread T0
    #0 0x5555555a1319 in decode_emm_cause /home/vagrant/magma/lte/gateway/c/oai/tasks/nas/ies/EmmCause.c:34
    #1 0x55555559d9de in decode_attach_accept /home/vagrant/magma/lte/gateway/c/oai/tasks/nas/emm/msg/AttachAccept.c:119
    #2 0x55555558daa7 in LLVMFuzzerTestOneInput /home/vagrant/magma/lte/gateway/c/oai/tasks/nas/emm/msg/AttachAcceptFuzzer.cpp:24
    #3 0x555555589a93 in main /home/vagrant/magma/lte/gateway/c/oai/tasks/nas/emm/msg/AttachAcceptFuzzer.cpp:47
    #4 0x7ffff43e42e0 in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x202e0)
    #5 0x55555558d8b9 in _start (/home/vagrant/build/c/oai/tasks/nas/attach_accept_fuzz+0x398b9)

Address 0x7fffffffdd40 is located in stack of thread T0 at offset 160 in frame
    #0 0x55555558986f in main /home/vagrant/magma/lte/gateway/c/oai/tasks/nas/emm/msg/AttachAcceptFuzzer.cpp:28

  This frame has 1 object(s):
    [32, 160) 'input' <== Memory access at offset 160 overflows this variable
HINT: this may be a false positive if your program uses some custom stack unwind mechanism or swapcontext
      (longjmp and C++ exceptions *are* supported)
SUMMARY: AddressSanitizer: stack-buffer-overflow /home/vagrant/magma/lte/gateway/c/oai/tasks/nas/ies/EmmCause.c:34 in decode_emm_cause
Shadow bytes around the buggy address:
  0x10007fff7b50: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x10007fff7b60: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x10007fff7b70: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x10007fff7b80: 00 00 00 00 00 00 f4 f4 f3 f3 f3 f3 00 00 00 00
  0x10007fff7b90: 00 00 00 00 f1 f1 f1 f1 00 00 00 00 00 00 00 00
=>0x10007fff7ba0: 00 00 00 00 00 00 00 00[f3]f3 f3 f3 00 00 00 00
  0x10007fff7bb0: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x10007fff7bc0: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x10007fff7bd0: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x10007fff7be0: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x10007fff7bf0: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
Shadow byte legend (one shadow byte represents 8 application bytes):
  Addressable:           00
  Partially addressable: 01 02 03 04 05 06 07
  Heap left redzone:       fa
  Heap right redzone:      fb
  Freed heap region:       fd
  Stack left redzone:      f1
  Stack mid redzone:       f2
  Stack right redzone:     f3
  Stack partial redzone:   f4
  Stack after return:      f5
  Stack use after scope:   f8
  Global redzone:          f9
  Global init order:       f6
  Poisoned by user:        f7
  Container overflow:      fc
  Array cookie:            ac
  Intra object redzone:    bb
  ASan internal:           fe
  Left alloca redzone:     ca
  Right alloca redzone:    cb
==10494==ABORTING
[Inferior 1 (process 10494) exited with code 01]
```

**Comment by themarwhal** [comment]
@ardzoht should we add these in the BE Epic?

**Comment by electronjoe** [comment]
A note that some of these may be dupes - e.g. if packet parsing offset errors are occurring up the call stack.  What we might want to do is explore a couple of them - fix them - and then repeat the fuzzing infrastructure to see if we have eliminated the other reported GH Issues.
