### ISSUE TITLE
Failed to execute docker-compose

### ISSUE THREAD

**Issue by shoaibbutt50** [magma/magma#495]
~/magma/orc8r/cloud/docker$ sudo ./build.py
Orc8r_cache image does not exist. Building...
WARNING: The PWD variable is not set. Defaulting to a blank string.
Building cache
Traceback (most recent call last):
  File "bin/docker-compose", line 6, in <module>
  File "compose/cli/main.py", line 71, in main
  File "compose/cli/main.py", line 127, in perform_command
  File "compose/cli/main.py", line 287, in build
  File "compose/project.py", line 386, in build
  File "compose/project.py", line 368, in build_service
  File "compose/service.py", line 1084, in build
  File "site-packages/docker/api/build.py", line 157, in build
  File "site-packages/docker/api/build.py", line 345, in process_dockerfile
FileNotFoundError: [Errno 2] No such file or directory: '/controller/Dockerfile'
[21220] Failed to execute script docker-compose
Creating build context in '/tmp/magma_orc8r_build'...
Context created for modules: orc8r, lte, feg, cwf
Running 'docker-compose build --build-arg baseImage=orc8r_cache'...
WARNING: The PWD variable is not set. Defaulting to a blank string.
postgres uses an image, skipping
maria uses an image, skipping
Building proxy
Traceback (most recent call last):
  File "bin/docker-compose", line 6, in <module>
  File "compose/cli/main.py", line 71, in main
  File "compose/cli/main.py", line 127, in perform_command
  File "compose/cli/main.py", line 287, in build
  File "compose/project.py", line 386, in build
  File "compose/project.py", line 368, in build_service
  File "compose/service.py", line 1084, in build
  File "site-packages/docker/api/build.py", line 157, in build
  File "site-packages/docker/api/build.py", line 345, in process_dockerfile
FileNotFoundError: [Errno 2] No such file or directory: '/proxy/Dockerfile'
[21225] Failed to execute script docker-compose

**Comment by mpgermano** [comment]
This issue was resolved for the user (see https://github.com/facebookincubator/magma/issues/503). Closing.
