### ISSUE TITLE
AGW: stateless: scale-test: exception in state.

### ISSUE THREAD

**Issue by pshelar** [magma/magma#5088]
### Your Environment

- **Version:** 1.4
- **Affected Component:** Access Gateway
- **Affected Subcomponent:** state
- **Deployment Environment:** bare-metal (AGW)

### Describe the Issue
scale test issue:
```
Feb 22 08:03:12 agw1 state[6978]: ERROR:root:Exception from _run: 'IMSI001011234560108:MME'
Feb 22 08:03:12 agw1 state[6978]: Traceback (most recent call last):
Feb 22 08:03:12 agw1 state[6978]:   File "/usr/local/lib/python3.5/dist-packages/magma/common/job.py", line 121, in _periodic
Feb 22 08:03:12 agw1 state[6978]:     await self._run()
Feb 22 08:03:12 agw1 state[6978]:   File "/usr/local/lib/python3.5/dist-packages/magma/state/state_replicator.py", line 81, in _run
Feb 22 08:03:12 agw1 state[6978]:     request = await self._collect_states_to_replicate()
Feb 22 08:03:12 agw1 state[6978]:   File "/usr/local/lib/python3.5/dist-packages/magma/state/state_replicator.py", line 131, in _collect_states_to_replicate
Feb 22 08:03:12 agw1 state[6978]:     for key in redis_dict:
Feb 22 08:03:12 agw1 state[6978]:   File "/usr/local/lib/python3.5/dist-packages/magma/common/redis/containers.py", line 225, in __iter__
Feb 22 08:03:12 agw1 state[6978]:     if self.is_garbage(split_key[0]):
Feb 22 08:03:12 agw1 state[6978]:   File "/usr/local/lib/python3.5/dist-packages/magma/common/redis/containers.py", line 336, in is_garbage
Feb 22 08:03:12 agw1 state[6978]:     raise KeyError(composite_key)
Feb 22 08:03:12 agw1 state[6978]: KeyError: 'IMSI001011234560108:MME'
```

**Comment by themarwhal** [comment]
I think this is due to redis not being locked between reads for `keys <pattern>` and `get <key>`. We can ignore invalid keys and do __iter__ on a best effort approach.
