### ISSUE TITLE
[MME] SEGV in cpp_redis::network::redis_connection::send

### ISSUE THREAD

**Issue by themarwhal** [magma/magma#5155]
### Your Environment

- **Version:**1.4.0-1614171043-7cd5877d
- **Affected Component:** Orchestrator, Access Gateway, or NMS
- **Affected Subcomponent:** Orchestrator pod/service or AGW service
- **Deployment Environment:** e.g. AWS (orc8r), local docker-compose (orc8r), bare-metal (AGW), Vagrant (AGW)

### Describe the Issue
core with bt
```
b[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
t
Core was generated by `/usr/local/bin/mme -c /var/opt/magma/tmp/mme.conf -s /var/opt/magma/tmp/spgw.co'.
Program terminated with signal SIGSEGV, Segmentation fault.
#0  0x00007f358b36601d in std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::_M_append(char const*, unsigned long) () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
[Current thread is 1 (Thread 0x7f35795d9700 (LWP 17125))]
(gdb) bt
#0  0x00007f358b36601d in std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::_M_append(char const*, unsigned long) () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#1  0x0000563c38949577 in cpp_redis::network::redis_connection::send(std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > const&) ()
#2  0x0000563c3891d58c in cpp_redis::client::unprotected_send(std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > const&, std::function<void (cpp_redis::reply&)> const&) ()
#3  0x0000563c3891d794 in cpp_redis::client::send(std::vector<std::__cxx11::basic_string<char, 
```

[2021-Feb-23-07-27-22-core-1614094033-ITTI.zip](https://github.com/magma/magma/files/6045391/2021-Feb-23-07-27-22-core-1614094033-ITTI.zip)

**Comment by themarwhal** [comment]
[logs.zip](https://github.com/magma/magma/files/6045630/logs.zip)
[mme.zip](https://github.com/magma/magma/files/6045632/mme.zip)

**Comment by ekowtaylor** [comment]
@ardzoht I believe this is closed in the tracker, can it be closed here too?
