### ISSUE TITLE
[MME] SEGV get_mme_ue_ids_no_imsi

### ISSUE THREAD

**Issue by themarwhal** [magma/magma#5166]
### Your Environment

- **Version:** 1.4.0-1614171043-7cd5877d
- **Affected Component:** Orchestrator, Access Gateway, or NMS
- **Affected Subcomponent:** Orchestrator pod/service or AGW service
- **Deployment Environment:** e.g. AWS (orc8r), local docker-compose (orc8r), bare-metal (AGW), Vagrant (AGW)

### Describe the Issue
```
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
Core was generated by `/usr/local/bin/mme -c /var/opt/magma/tmp/mme.conf -s /var/opt/magma/tmp/spgw.co'.
Program terminated with signal SIGSEGV, Segmentation fault.
#0  0x0000564a3c348bb1 in get_mme_ue_ids_no_imsi (keyP=2945, dataP=1056561955408, argP=0x7ffdcb99a234, resultP=0x7ffdcb99a238) at /home/vagrant/magma/lte/gateway/c/oai/tasks/s1ap/s1ap_state.cpp:171
171	/home/vagrant/magma/lte/gateway/c/oai/tasks/s1ap/s1ap_state.cpp: No such file or directory.
[Current thread is 1 (Thread 0x7f63ffb4e7c0 (LWP 27888))]
(gdb) bt
#0  0x0000564a3c348bb1 in get_mme_ue_ids_no_imsi (keyP=2945, dataP=1056561955408, argP=0x7ffdcb99a234, resultP=0x7ffdcb99a238) at /home/vagrant/magma/lte/gateway/c/oai/tasks/s1ap/s1ap_state.cpp:171
#1  0x0000564a3c7c726b in hashtable_uint64_ts_apply_callback_on_elements (hashtblP=0x61600000e008, funct_cb=0x564a3c348b31 <get_mme_ue_ids_no_imsi(hash_key_t, uint64_t, void*, void**)>, parameterP=0x7ffdcb99a234, resultP=0x7ffdcb99a238)
    at /home/vagrant/magma/lte/gateway/c/oai/lib/hashtable/hashtable_uint64.c:509
#2  0x0000564a3c348cd8 in remove_ues_without_imsi_from_ue_id_coll () at /home/vagrant/magma/lte/gateway/c/oai/tasks/s1ap/s1ap_state.cpp:212
#3  0x0000564a3c348778 in s1ap_state_init (max_ues=16, max_enbs=8, use_stateless=true) at /home/vagrant/magma/lte/gateway/c/oai/tasks/s1ap/s1ap_state.cpp:40
#4  0x0000564a3c346ffb in s1ap_mme_init (mme_config_p=0x564a3ce84520 <mme_config>) at /home/vagrant/magma/lte/gateway/c/oai/tasks/s1ap/s1ap_mme.c:337
#5  0x0000564a3c333896 in main (argc=<optimized out>, argv=<optimized out>) at /home/vagrant/magma/lte/gateway/c/oai/oai_mme/oai_mme.c:133
(gdb)
```

**Comment by themarwhal** [comment]
[core-1614219837-mme-25123.zip](https://github.com/magma/magma/files/6045618/core-1614219837-mme-25123.zip)

**Comment by themarwhal** [comment]
[logs.zip](https://github.com/magma/magma/files/6045620/logs.zip)
[1.4.0-1614171043-7cd5877d-mme.zip](https://github.com/magma/magma/files/6045622/1.4.0-1614171043-7cd5877d-mme.zip)

**Comment by ulaskozat** [comment]
@themarwhal do you see this issue on the latest v1.4?

**Comment by ssanadhya** [comment]
This was fixed with https://github.com/magma/magma/pull/5122  and backported to v1.4 branch https://github.com/magma/magma/commit/d30112c0a721b281668507387694c794ddcced1d
