### ISSUE TITLE
[MME] Better handle sctp disconnect and not AssertFail

### ISSUE THREAD

**Issue by themarwhal** [magma/magma#5189]
### Your Environment

- **Version:** 1.4.0-1614258391-4690a84a

### Describe the Issue
When we get a sctp disconnect we currently assert fail, which is probably not the most graceful way.
```
Core was generated by `/usr/local/bin/mme -c /var/opt/magma/tmp/mme.conf -s /var/opt/magma/tmp/spgw.co'.
Program terminated with signal SIGSEGV, Segmentation fault.
#0  0x000055abc8a43469 in s1ap_handle_sctp_disconnection (state=state@entry=0x60f00000b4f0, assoc_id=661, reset=<optimized out>) at /home/vagrant/magma/lte/gateway/c/oai/tasks/s1ap/s1ap_mme_handlers.c:2287
[Current thread is 1 (Thread 0x7f16e0cd8700 (LWP 15439))]
#0  0x000055abc8a43469 in s1ap_handle_sctp_disconnection (state=state@entry=0x60f00000b4f0, assoc_id=661, reset=<optimized out>) at /home/vagrant/magma/lte/gateway/c/oai/tasks/s1ap/s1ap_mme_handlers.c:2287
#1  0x000055abc89f8517 in handle_message (loop=<optimized out>, reader=<optimized out>, arg=<optimized out>) at /home/vagrant/magma/lte/gateway/c/oai/tasks/s1ap/s1ap_mme.c:158
#2  0x00007f16f3e157be in zloop_start () from /usr/lib/x86_64-linux-gnu/libczmq.so.4
#3  0x000055abc89f8281 in s1ap_mme_thread (args=<optimized out>) at /home/vagrant/magma/lte/gateway/c/oai/tasks/s1ap/s1ap_mme.c:319
#4  0x00007f16f65f44a4 in start_thread (arg=0x7f16e0cd8700) at pthread_create.c:456
#5  0x00007f16f2968d0f in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:97
```

**Comment by themarwhal** [comment]
[mme.zip](https://github.com/magma/magma/files/6045725/mme.zip)
[logs.zip](https://github.com/magma/magma/files/6045727/logs.zip)
[core-1614266147-ITTI.zip](https://github.com/magma/magma/files/6045729/core-1614266147-ITTI.zip)
