### ISSUE TITLE
[MME][Core] sgw_s8_thread crash on exit

### ISSUE THREAD

**Issue by talkhasib** [magma/magma#5286]
Not critical. happens on exit. but might mask other issues
Multiple cores available.
sgw_s8_exit crash

====================core-1614758756-ITTI
Core was generated by `/usr/local/bin/mme -c /var/opt/magma/tmp/mme.conf -s /var/opt/magma/tmp/spgw.co'.
Program terminated with signal SIGABRT, Aborted.
#0  __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:51
[Current thread is 1 (Thread 0x7f4d0ee72700 (LWP 21242))]
#0  __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:51
#1  0x00007f4d2299642a in __GI_abort () at abort.c:89
#2  0x00007f4d278ea329 in ?? () from /usr/lib/x86_64-linux-gnu/libasan.so.3
#3  0x00007f4d278df9ab in ?? () from /usr/lib/x86_64-linux-gnu/libasan.so.3
#4  0x00007f4d278d9b57 in ?? () from /usr/lib/x86_64-linux-gnu/libasan.so.3
#5  0x00007f4d278da398 in __asan_report_load8 () from /usr/lib/x86_64-linux-gnu/libasan.so.3
#6  0x00007f4d23f8e1ea in as_socket_base_t (s_=0x61c00008f080) at src/zmq.cpp:245
#7  0x00007f4d23f8eb69 in zmq_close (s_=<optimized out>) at src/zmq.cpp:265
#8  0x00007f4d237700dc in zsys_close () from /home/vagrant/local/lib/libczmq.so.4
#9  0x00007f4d2375d1df in zsock_destroy_checked () from /home/vagrant/local/lib/libczmq.so.4
#10 0x000055f3fe99bfa4 in destroy_task_context (task_zmq_ctx_p=0x55f3ff47cbc0 <sgw_s8_task_zmq_ctx>) at /home/vagrant/magma/lte/gateway/c/oai/lib/itti/intertask_interface.c:205
#11 0x000055f3fe878a90 in sgw_s8_exit () at /home/vagrant/magma/lte/gateway/c/oai/tasks/sgw_s8/sgw_s8_task.c:86
#12 0x000055f3fe878555 in sgw_s8_thread (args=0x0) at /home/vagrant/magma/lte/gateway/c/oai/tasks/sgw_s8/sgw_s8_task.c:45
#13 0x00007f4d273ed4a4 in start_thread (arg=0x7f4d0ee72700) at pthread_create.c:456
#14 0x00007f4d22a4ad0f in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:97

**Comment by talkhasib** [comment]
Core are here
https://drive.google.com/drive/folders/1UJ3bNBw3AaHONDrSh601GVsffaIi5Bna?ths=true
