### ISSUE TITLE
[MME][Core] crash in zmq::v3_1_encoder_t

### ISSUE THREAD

**Issue by talkhasib** [magma/magma#5289]
Compiled ZMQ from source and enabled ASAN

====================core-1614754318-ZMQbg!IO!0-7930
Core was generated by `/usr/local/bin/mme -c /var/opt/magma/tmp/mme.conf -s /var/opt/magma/tmp/spgw.co'.
Program terminated with signal SIGABRT, Aborted.
#0  __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:51
[Current thread is 1 (Thread 0x7f7b47afd700 (LWP 7934))]
#0  __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:51
#1  0x00007f7b5242142a in __GI_abort () at abort.c:89
#2  0x00007f7b57375329 in ?? () from /usr/lib/x86_64-linux-gnu/libasan.so.3
#3  0x00007f7b5736a9ab in ?? () from /usr/lib/x86_64-linux-gnu/libasan.so.3
#4  0x00007f7b57364b57 in ?? () from /usr/lib/x86_64-linux-gnu/libasan.so.3
#5  0x00007f7b57365398 in __asan_report_load8 () from /usr/lib/x86_64-linux-gnu/libasan.so.3
#6  0x00007f7b5390f7dc in zmq::msg_t::size (this=0x61c000028e80) at src/msg.cpp:420
#7  0x00007f7b53a04236 in zmq::v3_1_encoder_t::message_ready (this=0x608000044020) at src/v3_1_encoder.cpp:53
#8  0x00007f7b539c13e4 in zmq::stream_engine_base_t::out_event (this=0x61c000028880) at src/stream_engine_base.cpp:355
#9  0x00007f7b53981e4a in zmq::session_base_t::read_activated (this=<optimized out>, pipe_=<optimized out>) at src/session_base.cpp:317
#10 0x00007f7b538ea6aa in zmq::io_thread_t::in_event (this=0x61100003bc80) at src/io_thread.cpp:91
#11 0x00007f7b538e1867 in zmq::epoll_t::loop (this=<optimized out>) at src/epoll.cpp:206
#12 0x00007f7b539e0002 in thread_routine (arg_=0x61100003bb98) at src/thread.cpp:256
#13 0x00007f7b56e784a4 in start_thread (arg=0x7f7b47afd700) at pthread_create.c:456
#14 0x00007f7b524d5d0f in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:97

**Comment by talkhasib** [comment]
cores are here
https://drive.google.com/drive/folders/1ehFBEzKdIZaMxfuJUlCmGFXaK1WixZ4w?ths=true
