### ISSUE TITLE
[MME][Core] crash in ZMQ zmq::pipe_t::read assert

### ISSUE THREAD

**Issue by talkhasib** [magma/magma#5292]
#0  __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:51
#1  0x00007fb70329142a in __GI_abort () at abort.c:89
#2  0x00007fb70546b29e in zmq::zmq_abort (errmsg_=errmsg_@entry=0x7fb705603780 "rc == 0") at src/err.cpp:88
#3  0x00007fb7054c2218 in zmq::pipe_t::read (this=this@entry=0x613000053cc0, msg_=msg_@entry=0x61c00002ce80) at src/pipe.cpp:213
#4  0x00007fb705501693 in zmq::session_base_t::pull_msg (this=0x61b00007d980, msg_=0x61c00002ce80) at src/session_base.cpp:173
#5  0x00007fb70554a4cd in zmq::stream_engine_base_t::pull_and_encode (this=0x61c00002c880, msg_=0x61c00002ce80) at src/stream_engine_base.cpp:626
#6  0x00007fb7055482ae in zmq::stream_engine_base_t::out_event (this=0x61c00002c880) at src/stream_engine_base.cpp:347
#7  0x00007fb70546874e in zmq::epoll_t::loop (this=<optimized out>) at src/epoll.cpp:202
#8  0x00007fb705567002 in thread_routine (arg_=0x611000021b58) at src/thread.cpp:256
#9  0x00007fb7089ff4a4 in start_thread (arg=0x7fb6f96e2700) at pthread_create.c:456
#10 0x00007fb703345d0f in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:97

**Comment by talkhasib** [comment]
core is here
https://drive.google.com/drive/folders/12MseLpQVHD7T62RQPnbiYdRKfYnKkyi8?ths=true
