### ISSUE TITLE
AGW: s1ap: precommit: failed: test_attach_service_with_multi_pdns_and_bearers_mt_data

### ISSUE THREAD

**Issue by pshelar** [magma/magma#5649]
### Your Environment

- **Version:** master
- **Affected Component:** Access Gateway
- **Affected Subcomponent:** AGW service
- **Deployment Environment:** Vagrant (AGW)

### Describe the Issue

one of precommit test failed on master branch:
```
Traceback (most recent call last):
  File "/home/vagrant/magma/lte/gateway/python/integ_tests/s1aptests/test_attach_service_with_multi_pdns_and_bearers_mt_data.py", line 314, in test_attach_service_with_multi_pdns_and_bearers_mt_data
    req, duration=1, is_udp=True
  File "/home/vagrant/magma/lte/gateway/python/integ_tests/s1aptests/s1ap_wrapper.py", line 356, in configDownlinkTest
    assert self._trf_util.update_dl_route(self.TEST_IP_BLOCK)
AssertionError:
-------------------- >> begin captured logging << --------------------
root: ERROR: Could not load magmad yml config for mconfig modules
urllib3.connectionpool: DEBUG: Starting new HTTP connection (1): 192.168.60.142:3333
urllib3.connectionpool: DEBUG: http://192.168.60.142:3333 "GET /stats/switches HTTP/1.1" 200 16
root: INFO: Adding subscriber : IMSI001010000000001
root: DEBUG: s1ap response expected, received: 12, 12
root: DEBUG: s1ap message expected, received: 68, 68
urllib3.connectionpool: DEBUG: Starting new HTTP connection (1): 192.168.60.142:3333
urllib3.connectionpool: DEBUG: http://192.168.60.142:3333 "POST /stats/flow/55415227300420 HTTP/1.1" 200 2673
urllib3.connectionpool: DEBUG: Starting new HTTP connection (1): 192.168.60.142:3333
urllib3.connectionpool: DEBUG: http://192.168.60.142:3333 "POST /stats/flow/55415227300420 HTTP/1.1" 200 1622
urllib3.connectionpool: DEBUG: Starting new HTTP connection (1): 192.168.60.142:3333
urllib3.connectionpool: DEBUG: http://192.168.60.142:3333 "POST /stats/flow/55415227300420 HTTP/1.1" 200 853
urllib3.connectionpool: DEBUG: Starting new HTTP connection (1): 192.168.60.142:3333
urllib3.connectionpool: DEBUG: http://192.168.60.142:3333 "POST /stats/flow/55415227300420 HTTP/1.1" 200 3293
urllib3.connectionpool: DEBUG: Starting new HTTP connection (1): 192.168.60.142:3333
urllib3.connectionpool: DEBUG: http://192.168.60.142:3333 "POST /stats/flow/55415227300420 HTTP/1.1" 200 856
urllib3.connectionpool: DEBUG: Starting new HTTP connection (1): 192.168.60.142:3333
urllib3.connectionpool: DEBUG: http://192.168.60.142:3333 "POST /stats/flow/55415227300420 HTTP/1.1" 200 854
urllib3.connectionpool: DEBUG: Starting new HTTP connection (1): 192.168.60.142:3333
urllib3.connectionpool: DEBUG: http://192.168.60.142:3333 "POST /stats/flow/55415227300420 HTTP/1.1" 200 854
urllib3.connectionpool: DEBUG: Starting new HTTP connection (1): 192.168.60.142:3333
urllib3.connectionpool: DEBUG: http://192.168.60.142:3333 "POST /stats/flow/55415227300420 HTTP/1.1" 200 424
urllib3.connectionpool: DEBUG: Starting new HTTP connection (1): 192.168.60.142:3333
urllib3.connectionpool: DEBUG: http://192.168.60.142:3333 "POST /stats/flow/55415227300420 HTTP/1.1" 200 425
root: INFO: Deleting subscriber : IMSI001010000000001
--------------------- >> end captured logging << ---------------------

----------------------------------------------------------------------
Ran 1 test in 23.733s

FAILED (failures=1)
Makefile:33: recipe for target 'precommit' failed
make: *** [precommit] Error 1
```

**Comment by ulaskozat** [comment]
@VinashakAnkitAman could you check out this issue?

**Comment by VinashakAnkitAman** [comment]
> @VinashakAnkitAman could you check out this issue?

I checked it today with latest master and I can see the test passing. Moreover, here the assertion seems to be failing in Shell commands on TRF Server VM which should be possible only if TRF Server VM is down. Otherwise basic shell commands have been used there like doing ssh and firing the following command:
"sudo ip route flush via 192.168.129.1 && sudo ip route add " + ue_ip_block + " via 192.168.129.1 dev eth2"


I have attached the terminal log where it is passing in a loop for 10 times:
[S1APTester_terminal_log_10_iterations.txt](https://github.com/magma/magma/files/6286029/S1APTester_terminal_log_10_iterations.txt)


I even tested it by running target "make precommit" and it passed without problem:
[S1APTester_terminal_log_precommit.txt](https://github.com/magma/magma/files/6286362/S1APTester_terminal_log_precommit.txt)


Following is the success log for individual run in my VM:
```
(python) vagrant@magma-test:~/magma/lte/gateway/python/integ_tests$ make integ_test TESTS=s1aptests/test_attach_service_with_multi_pdns_and_bearers_mt_data.py
. /home/vagrant/build/python/bin/activate
echo "Running test: s1aptests/test_attach_service_with_multi_pdns_and_bearers_mt_data.py"
Running test: s1aptests/test_attach_service_with_multi_pdns_and_bearers_mt_data.py
timeout --foreground -k 930s 900s sudo -E PATH=/home/vagrant/build/python/bin:/usr/lib/ccache:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/local/go/bin PYTHONPATH=:/home/vagrant/s1ap-tester/bin /home/vagrant/build/python/bin/nosetests --with-xunit --xunit-file=/var/tmp/test_results/test_attach_service_with_multi_pdns_and_bearers_mt_data.xml -x -s s1aptests/test_attach_service_with_multi_pdns_and_bearers_mt_data.py || exit 1
Start time 18:52:29
tag: AUTH_TYPE tagVal: MILENAGE
************************* Enb tester config

**********************TPT open server******** 0

 Server Socket FD =[13]
************* Testing *Time elapsed(in usec): for timer expiry               :516 usec
AGW is stateless
APN Correction configured
Health service is disabled
Using subscriber IMSI IMSI001010000000001
************************* UE device config for ue_id  1
************************* Configuring IP block
************************* Waiting for IP changes to propagate
************************* S1 setup
************************* UE App config
************************* Running End to End attach for UE id  1
ue id 1 found

*************NbUiNbuHdlUeRadioCapMsg: Send UE cap msg SUCCESS*********
PDN_TYPE: 1
IPv4 PDN_ADDRESS:192 168 128 12
Sleeping for 5 seconds
********************** Adding dedicated bearer to magma.ipv4 PDN
********************** Sending RAR for IMSI 001010000000001
Sending Policy RAR message to session manager
************** Sending activate dedicated EPS bearer context accept

Sleeping for 5 seconds
********* PDN type 1
************* Sending Standalone PDN Connectivity Request

Building PDN Connection Request
ue id 1 found
PDN_TYPE:1
IPv4 PDN_ADDRESS:192 168 128 13
********************** Sending Activate default EPS bearer context accept for UE id  1
Sleeping for 5 seconds
********************** Adding dedicated bearer to ims PDN
********************** Sending RAR for IMSI 001010000000001
Sending Policy RAR message to session manager
************** Sending activate dedicated EPS bearer context accept

************* Added dedicated bearer 8
Sleeping for 5 seconds
************ Verifying flow rules
Checking for uplink flow
Get uplink flows: attempt  0
Checking for downlink flow
Get downlink flows: attempt  0
Get downlink flows: attempt  0
Get downlink flows: attempt  0
Get downlink flows: attempt  0
*********** Moving UE to idle mode
************* Sending UE context release request  for UE id  1
Deleting Ue Context from Traffic Handler
************ Verifying paging flow rules
Verifying paging flow for ip 192.168.128.12
Get paging flows: attempt  0
Verifying paging flow for ip 192.168.128.13
Get paging flows: attempt  0
Get paging flows: attempt  1
************************* Running UE downlink (UDP) for UE id  1
-----------------------------------------------------------
Server listening on 7001
-----------------------------------------------------------
************************* Sending Service request for UE id  1
Received Paging Indication for ue-id 1
Accepted connection from 192.168.129.42, port 55553
[ 36] local 192.168.128.12 port 7001 connected to 192.168.129.42 port 45762
[ ID] Interval           Transfer     Bandwidth       Jitter    Lost/Total Datagrams
[ 36]   0.00-1.00   sec  0.00 Bytes  0.00 bits/sec  0.000 ms  0/0 (0%)
[ 36]   1.00-1.06   sec  0.00 Bytes  0.00 bits/sec  0.000 ms  0/0 (0%)
- - - - - - - - - - - - - - - - - - - - - - - - -
[ ID] Interval           Transfer     Bandwidth       Jitter    Lost/Total Datagrams
[ 36]   0.00-1.06   sec  0.00 Bytes  0.00 bits/sec  0.000 ms  0/0 (0%)
Sleeping for 5 seconds
************ Verifying flow rules
Checking for uplink flow
Get uplink flows: attempt  0
Checking for downlink flow
Get downlink flows: attempt  0
Get downlink flows: attempt  0
Get downlink flows: attempt  0
Get downlink flows: attempt  0
Building PDN Disconnect Request
ue id 1 found
******************* Received deactivate eps bearer context request
************* Sending deactivate EPS bearer context accept

Sleeping for 5 seconds
************************* Running UE detach for UE id  1
Deleting Ue Context from Traffic Handler
************************* send SCTP SHUTDOWN
Keys left in Redis (list should be empty)[

nb_enb_connected: 1
]
Entries left in hashtables (should be zero): 2
.
----------------------------------------------------------------------
Ran 1 test in 42.056s

OK
sleep 1
(python) vagrant@magma-test:~/magma/lte/gateway/python/integ_tests$
```

**Comment by ulaskozat** [comment]
@pshelar please close the issue if there is no further actions needed on this. otherwise advise or reassign to the devops team.
