### ISSUE TITLE
[AGW][S1ap tests] S1ap tests (integ_test) appear broken

### ISSUE THREAD

**Issue by electronjoe** [magma/magma#5806]
I have tested this twice against master at commit cd6221fb12a890efd621bc491535b17dea79f728 - from clean vagrant VMS `vagrant destroy magma && vagrant destroy magma_test`.

```
vagrant@magma-test:~/magma/lte/gateway/python/integ_tests$ make integ_test
. /home/vagrant/build/python/bin/activate
echo "Running test: s1aptests/test_modify_mme_config_for_sanity.py"
Running test: s1aptests/test_modify_mme_config_for_sanity.py
timeout --foreground -k 930s 900s sudo -E PATH=/usr/lib/ccache:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/local/go/bin PYTHONPATH=:/home/vagrant/s1ap-tester/bin /home/vagrant
/build/python/bin/nosetests --with-xunit --xunit-file=/var/tmp/test_results/test_modify_mme_config_for_sanity.xml -x -s s1aptests/test_modify_mme_config_for_sanity.py || exit 1
Modifying MME configuration for all sanity test cases to pass
MME configuration is updated successfully
Restarting services to apply configuration change
Waiting for all services to restart. Sleeping for 60 seconds..
*********** Slept for 5 seconds
*********** Slept for 10 seconds                                                                                                                                                                     *********** Slept for 15 seconds
*********** Slept for 20 seconds
*********** Slept for 25 seconds
*********** Slept for 30 seconds
*********** Slept for 35 seconds
*********** Slept for 40 seconds
*********** Slept for 45 seconds
*********** Slept for 50 seconds
*********** Slept for 55 seconds
*********** Slept for 60 seconds
.
----------------------------------------------------------------------
Ran 1 test in 64.973s

OK
sleep 1;        echo "Running test: s1aptests/test_attach_detach_dedicated_deactivation_timer_expiry.py"
Running test: s1aptests/test_attach_detach_dedicated_deactivation_timer_expiry.py
timeout --foreground -k 930s 900s sudo -E PATH=/usr/lib/ccache:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/local/go/bin PYTHONPATH=:/home/vagrant/s1ap-tester/bin /home/vagrant
/build/python/bin/nosetests --with-xunit --xunit-file=/var/tmp/test_results/test_attach_detach_dedicated_deactivation_timer_expiry.xml -x -s s1aptests/test_attach_detach_dedicated_deactivation_time
r_expiry.py || exit 1
E
======================================================================
ERROR: Failure: ConnectionError (HTTPConnectionPool(host='192.168.60.142', port=3333): Max retries exceeded with url: /stats/switches (Caused by NewConnectionError('<urllib3.connection.HTTPConnecti
on object at 0x7f561cf548d0>: Failed to establish a new connection: [Errno 111] Connection refused',)))
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/vagrant/build/python/lib/python3.5/site-packages/nose/failure.py", line 39, in runTest
    raise self.exc_val.with_traceback(self.tb)
  File "/home/vagrant/build/python/lib/python3.5/site-packages/nose/loader.py", line 418, in loadTestsFromName
    addr.filename, addr.module)
  File "/home/vagrant/build/python/lib/python3.5/site-packages/nose/importer.py", line 47, in importFromPath
    return self.importFromDir(dir_path, fqname)
  File "/home/vagrant/build/python/lib/python3.5/site-packages/nose/importer.py", line 94, in importFromDir
    mod = load_module(part_fqname, fh, filename, desc)
  File "/home/vagrant/build/python/lib/python3.5/imp.py", line 234, in load_module
   return load_source(name, filename, file)
  File "/home/vagrant/build/python/lib/python3.5/imp.py", line 172, in load_source
    module = _load(spec)
  File "<frozen importlib._bootstrap>", line 693, in _load
  File "<frozen importlib._bootstrap>", line 673, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 673, in exec_module
  File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
  File "/home/vagrant/magma/lte/gateway/python/integ_tests/s1aptests/test_attach_detach_dedicated_deactivation_timer_expiry.py", line 18, in <module>
    from integ_tests.s1aptests import s1ap_wrapper
  File "/home/vagrant/magma/lte/gateway/python/integ_tests/s1aptests/s1ap_wrapper.py", line 28, in <module>
    from integ_tests.s1aptests.s1ap_utils import (
  File "/home/vagrant/magma/lte/gateway/python/integ_tests/s1aptests/s1ap_utils.py", line 75, in <module>
    class S1ApUtil(object):
  File "/home/vagrant/magma/lte/gateway/python/integ_tests/s1aptests/s1ap_utils.py", line 98, in S1ApUtil
    datapath = get_datapath()
  File "/home/vagrant/magma/lte/gateway/python/integ_tests/s1aptests/ovs/rest_api.py", line 60, in get_datapath
    return str(_ovs_api_request('GET', url)[0])
  File "/home/vagrant/magma/lte/gateway/python/integ_tests/s1aptests/ovs/rest_api.py", line 70, in _ovs_api_request
    response = requests.request(method, url, data=data)
  File "/home/vagrant/build/python/lib/python3.5/site-packages/requests/api.py", line 60, in request
    return session.request(method=method, url=url, **kwargs)
  File "/home/vagrant/build/python/lib/python3.5/site-packages/requests/sessions.py", line 533, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/vagrant/build/python/lib/python3.5/site-packages/requests/sessions.py", line 646, in send
    r = adapter.send(request, **kwargs)
  File "/home/vagrant/build/python/lib/python3.5/site-packages/requests/adapters.py", line 516, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPConnectionPool(host='192.168.60.142', port=3333): Max retries exceeded with url: /stats/switches (Caused by NewConnectionError('<urllib3.connection.HTTPConn
ection object at 0x7f561cf548d0>: Failed to establish a new connection: [Errno 111] Connection refused',))
-------------------- >> begin captured logging << --------------------
root: ERROR: Could not load magmad yml config for mconfig modules
urllib3.connectionpool: DEBUG: Starting new HTTP connection (1): 192.168.60.142:3333
--------------------- >> end captured logging << ---------------------

----------------------------------------------------------------------
Ran 1 test in 0.003s

FAILED (errors=1)
Makefile:42: recipe for target 'integ_test' failed
make: *** [integ_test] Error 1
```

**Comment by electronjoe** [comment]
Is this truly root cause?

> root: ERROR: Could not load magmad yml config for mconfig modules

**Comment by electronjoe** [comment]
I saw this error on Jenkins integ_tests as well, but as of this morning it appears resolved.
