### ISSUE TITLE
[feg] magmad crashing on feg

### ISSUE THREAD

**Issue by uri200** [magma/magma#6282]
Magmad crashlooping in FEG

To reproduce this, 

```
cd ~/magma/feg/gateway/docker
docker-compose build 

# if you are in mac comment #LOG_DRIVER=journald in .env
vim .env 

docker-compose up -d
docker-compose logs -f magmad 
```

```
magmad           | Traceback (most recent call last):
magmad           |   File "/usr/lib/python3.8/runpy.py", line 194, in _run_module_as_main
magmad           |     return _run_code(code, main_globals, None,
magmad           |   File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
magmad           |     exec(code, run_globals)
magmad           |   File "/usr/local/lib/python3.8/dist-packages/magma/magmad/main.py", line 19, in <module>
magmad           |     from magma.common.sdwatchdog import SDWatchdog
magmad           |   File "/usr/local/lib/python3.8/dist-packages/magma/common/sdwatchdog.py", line 21, in <module>
magmad           |     import systemd.daemon
magmad           | ModuleNotFoundError: No module named 'systemd'

```

Note reverting this PR fixes the issue https://github.com/magma/magma/pull/6092

(revert PR is here https://github.com/magma/magma/pull/6092)

**Comment by themarwhal** [comment]
Probably same root cause: https://github.com/magma/magma/issues/6152
Or at least, it was cause by the same PR
