### ISSUE TITLE
[agw][pipelined] QoS Enforcement is not working with pyroute2 enabled

### ISSUE THREAD

**Issue by ulaskozat** [magma/magma#6289]
### Your Environment

- **Version:** master
- **Affected Component:** Access Gateway
- **Affected Subcomponent:** Pipelined
- **Deployment Environment:**  Vagrant (AGW)

### Describe the Issue

In the default setting of `enable_pyroute2: true` in pipelined.yml file, QoS enforcement is failing. When the setting is changed to `enable_pyroute2: false`, QoS enforcement is working as expected. 

**To Reproduce**
1. Bring up AGW test set up with magma, magma_test and magma_trfserver VMs. 
2. Disable tcp checksum on all three machines via running the command `disable-tcp-checksumming`.
3. Make sure that magma services are running on magma VM and traffic server is started on magma_trfserver VM.
4. Run the integration test with `make integ_test TESTS=s1aptests/test_attach_detach_setsessionrules_tcp_data.py` under directory `magma/lte/gateway/python/integ_tests` on magma_test VM.

Test fails on asserting the achieved rate (that it should be less than the MBR set in the test case). Also check the TC rules and packet marking rules using. Observe that TC rules are wrong.

```
echo 'DUMPING ETH1'
sudo tc -s -d class show dev eth1
sudo tc -s -d filter show dev eth1

echo 'DUMPING ETH2'
sudo tc -s -d class show dev eth2
sudo tc -s -d filter show dev eth2

echo 'Dumping flows'
sudo ~/build/python/bin/pipelined_cli.py debug display_flows | grep 'PKT_MARK'
```

Change the setting in pipelined.yml file and disable pyroute, restart magma services, rerun the test on step 4. Observe that the test passes this time.

**Expected behavior**
Test should pass whether or not the flag `enable_pyroute2` set as true or false.

**Comment by koolzz** [comment]
I see the pipelined unit tests are broken for qos... I didn't notice this until I updated to the ubuntu VM so I'm assuming thats the cause of issues

**Comment by koolzz** [comment]
```
======================================================================
FAIL: test_basic (test_qos_pyroute2.TcSetypTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/vagrant/magma/lte/gateway/python/magma/pipelined/tests/test_qos_pyroute2.py", line 63, in test_basic
    self.assertTrue(self.check_qid_in_tc(qid))
AssertionError: False is not true
-------------------- >> begin captured logging << --------------------
pipelined.qos.qos_tc_impl: ERROR: unable to read speed from /sys/class/net/dev_qos/speed defaulting to 1000
pipelined.qos.qos_tc_impl: INFO: Created root qdisc
pipelined.qos.tc_cmd: DEBUG: running tc qdisc add dev dev_qos root handle 1: htb
pipelined.qos.tc_cmd: DEBUG: running tc class replace dev dev_qos parent 1: classid 1:0xfffe htb rate 1000Mbit ceil 1000Mbit
pipelined.qos.tc_cmd: DEBUG: running tc class replace dev dev_qos parent 1:0xfffe classid 1:1 htb rate 12Kbit ceil 1000Mbit
pipelined.qos.tc_pyroute2: INFO: initialized
pipelined.qos.tc_pyroute2: DEBUG: Create HTB iface dev_qos qid 0xae
pipelined.qos.tc_pyroute2: DEBUG: Return: ({'header': {'length': 36, 'type': 2, 'flags': 256, 'sequence_number': 256, 'pid': 39503, 'error': None, 'target': 'localhost', 'stats': Stats(qsize=0, delta=0, delay=0)}, 'event': 'NLMSG_ERROR'},)
pipelined.qos.tc_pyroute2: DEBUG: Create Filter iface dev_qos qid 0xae
pipelined.qos.tc_pyroute2: DEBUG: Return: ({'header': {'length': 36, 'type': 2, 'flags': 256, 'sequence_number': 257, 'pid': 39503, 'error': None, 'target': 'localhost', 'stats': Stats(qsize=0, delta=0, delay=0)}, 'event': 'NLMSG_ERROR'},)
--------------------- >> end captured logging << ---------------------

======================================================================
FAIL: test_basic6 (test_qos_pyroute2.TcSetypTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/vagrant/magma/lte/gateway/python/magma/pipelined/tests/test_qos_pyroute2.py", line 79, in test_basic6
    self.assertTrue(self.check_qid_in_tc(qid))
AssertionError: False is not true
-------------------- >> begin captured logging << --------------------
pipelined.qos.tc_pyroute2: INFO: initialized
pipelined.qos.tc_pyroute2: DEBUG: Create HTB iface dev_qos qid 0xae
pipelined.qos.tc_pyroute2: ERROR: create-htb error : 17
pipelined.qos.tc_pyroute2: DEBUG: (17, 'File exists')
Traceback (most recent call last):
  File "/home/vagrant/magma/lte/gateway/python/magma/pipelined/qos/tc_ops_pyroute2.py", line 45, in create_htb
    ret = self._ipr.tc("add-class", "htb", if_index,
  File "/home/vagrant/build/python/lib/python3.8/site-packages/pyroute2/iproute/linux.py", line 1614, in tc
    return tuple(self.nlm_request(msg, msg_type=command, msg_flags=flags))
  File "/home/vagrant/build/python/lib/python3.8/site-packages/pyroute2/netlink/nlsocket.py", line 376, in nlm_request
    return tuple(self._genlm_request(*argv, **kwarg))
  File "/home/vagrant/build/python/lib/python3.8/site-packages/pyroute2/netlink/nlsocket.py", line 867, in nlm_request
    for msg in self.get(msg_seq=msg_seq,
  File "/home/vagrant/build/python/lib/python3.8/site-packages/pyroute2/netlink/nlsocket.py", line 379, in get
    return tuple(self._genlm_get(*argv, **kwarg))
  File "/home/vagrant/build/python/lib/python3.8/site-packages/pyroute2/netlink/nlsocket.py", line 704, in get
    raise msg['header']['error']
pyroute2.netlink.exceptions.NetlinkError: (17, 'File exists')
--------------------- >> end captured logging << ---------------------

======================================================================
FAIL: test_hierarchy (test_qos_pyroute2.TcSetypTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/vagrant/magma/lte/gateway/python/magma/pipelined/tests/test_qos_pyroute2.py", line 97, in test_hierarchy
    self.assertTrue(self.check_qid_in_tc(qid1))
AssertionError: False is not true
-------------------- >> begin captured logging << --------------------
pipelined.qos.tc_pyroute2: INFO: initialized
pipelined.qos.tc_pyroute2: DEBUG: Create HTB iface dev_qos qid 0xae
pipelined.qos.tc_pyroute2: ERROR: create-htb error : 17
pipelined.qos.tc_pyroute2: DEBUG: (17, 'File exists')
Traceback (most recent call last):
  File "/home/vagrant/magma/lte/gateway/python/magma/pipelined/qos/tc_ops_pyroute2.py", line 45, in create_htb
    ret = self._ipr.tc("add-class", "htb", if_index,
  File "/home/vagrant/build/python/lib/python3.8/site-packages/pyroute2/iproute/linux.py", line 1614, in tc
    return tuple(self.nlm_request(msg, msg_type=command, msg_flags=flags))
  File "/home/vagrant/build/python/lib/python3.8/site-packages/pyroute2/netlink/nlsocket.py", line 376, in nlm_request
    return tuple(self._genlm_request(*argv, **kwarg))
  File "/home/vagrant/build/python/lib/python3.8/site-packages/pyroute2/netlink/nlsocket.py", line 867, in nlm_request
    for msg in self.get(msg_seq=msg_seq,
  File "/home/vagrant/build/python/lib/python3.8/site-packages/pyroute2/netlink/nlsocket.py", line 379, in get
    return tuple(self._genlm_get(*argv, **kwarg))
  File "/home/vagrant/build/python/lib/python3.8/site-packages/pyroute2/netlink/nlsocket.py", line 704, in get
    raise msg['header']['error']
pyroute2.netlink.exceptions.NetlinkError: (17, 'File exists')
--------------------- >> end captured logging << ---------------------

======================================================================
FAIL: test_mix1 (test_qos_pyroute2.TcSetypTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/vagrant/magma/lte/gateway/python/magma/pipelined/tests/test_qos_pyroute2.py", line 132, in test_mix1
    self.assertTrue(self.check_qid_in_tc(qid))
AssertionError: False is not true
-------------------- >> begin captured logging << --------------------
pipelined.qos.tc_pyroute2: INFO: initialized
pipelined.qos.tc_cmd: INFO: initialized
pipelined.qos.tc_pyroute2: DEBUG: Create HTB iface dev_qos qid 0xae
pipelined.qos.tc_pyroute2: ERROR: create-htb error : 17
pipelined.qos.tc_pyroute2: DEBUG: (17, 'File exists')
Traceback (most recent call last):
  File "/home/vagrant/magma/lte/gateway/python/magma/pipelined/qos/tc_ops_pyroute2.py", line 45, in create_htb
    ret = self._ipr.tc("add-class", "htb", if_index,
  File "/home/vagrant/build/python/lib/python3.8/site-packages/pyroute2/iproute/linux.py", line 1614, in tc
    return tuple(self.nlm_request(msg, msg_type=command, msg_flags=flags))
  File "/home/vagrant/build/python/lib/python3.8/site-packages/pyroute2/netlink/nlsocket.py", line 376, in nlm_request
    return tuple(self._genlm_request(*argv, **kwarg))
  File "/home/vagrant/build/python/lib/python3.8/site-packages/pyroute2/netlink/nlsocket.py", line 867, in nlm_request
    for msg in self.get(msg_seq=msg_seq,
  File "/home/vagrant/build/python/lib/python3.8/site-packages/pyroute2/netlink/nlsocket.py", line 379, in get
    return tuple(self._genlm_get(*argv, **kwarg))
  File "/home/vagrant/build/python/lib/python3.8/site-packages/pyroute2/netlink/nlsocket.py", line 704, in get
    raise msg['header']['error']
pyroute2.netlink.exceptions.NetlinkError: (17, 'File exists')
--------------------- >> end captured logging << ---------------------

======================================================================
FAIL: test_mix2 (test_qos_pyroute2.TcSetypTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/vagrant/magma/lte/gateway/python/magma/pipelined/tests/test_qos_pyroute2.py", line 154, in test_mix2
    self.assertEqual(err1, 0)
AssertionError: -1 != 0
-------------------- >> begin captured logging << --------------------
pipelined.qos.tc_pyroute2: INFO: initialized
pipelined.qos.tc_cmd: INFO: initialized
pipelined.qos.tc_cmd: DEBUG: running tc class add dev dev_qos parent 1:fffe classid 1:0xae htb rate 1000 ceil 10000 prio 2
pipelined.qos.tc_cmd: ERROR: error: 2 running: tc class add dev dev_qos parent 1:fffe classid 1:0xae htb rate 1000 ceil 10000 prio 2
--------------------- >> end captured logging << ---------------------

----------------------------------------------------------------------
Ran 136 tests in 334.386s

```
cc @pshelar

**Comment by pshelar** [comment]
I see this failure on ubuntu. same test works on debian.

**Comment by ulaskozat** [comment]
Closing as PR #6335 fixed this issue.
