### ISSUE TITLE
Recurring mme directoryd UpdateLocation exception

### ISSUE THREAD

**Issue by bmurithi** [magma/magma#637]
> Magma Version: 0.3.78-1567853565-a69a32fa

```
Sep 18 11:20:19 lte-GW0 control_proxy[19810]: 2019-09-18T11:20:19.110+03:00 [127.0.0.1 -> directoryd-controller.magma.etagecom.io,8443] "POST /magma.orc8r.DirectoryService/DeleteLocation HTTP/2" 200 0bytes 0.222s
Sep 18 11:20:19 lte-GW0 control_proxy[19810]: 2019-09-18T11:20:19.110+03:00 [127.0.0.1 -> directoryd-controller.magma.etagecom.io,8443] "POST /magma.orc8r.DirectoryService/UpdateLocation HTTP/2" 200 5bytes 0.227s
Sep 18 11:20:19 lte-GW0 directoryd[562]: ERROR:grpc._server:Exception calling application: <_Rendezvous of RPC that terminated with:
Sep 18 11:20:19 lte-GW0 directoryd[562]:         status = StatusCode.UNKNOWN
Sep 18 11:20:19 lte-GW0 directoryd[562]:         details = "Error finding location record: No record for query"
Sep 18 11:20:19 lte-GW0 directoryd[562]:         debug_error_string = "{"created":"@1568794819.113702546","description":"Error received from peer","file":"src/core/lib/surface/call.cc","file_line":1017,"grpc_message":"Error finding location record: No record for query","grpc_status":2}"
Sep 18 11:20:19 lte-GW0 directoryd[562]: >
Sep 18 11:20:19 lte-GW0 directoryd[562]: Traceback (most recent call last):
Sep 18 11:20:19 lte-GW0 directoryd[562]:   File "/usr/local/lib/python3.5/dist-packages/grpc/_server.py", line 389, in _call_behavior
Sep 18 11:20:19 lte-GW0 directoryd[562]:     return behavior(argument, context), True
Sep 18 11:20:19 lte-GW0 directoryd[562]:   File "/usr/local/lib/python3.5/dist-packages/magma/common/rpc_utils.py", line 23, in wrapper
Sep 18 11:20:19 lte-GW0 directoryd[562]:     func(*args, **kwargs)
Sep 18 11:20:19 lte-GW0 directoryd[562]:   File "/usr/local/lib/python3.5/dist-packages/magma/directoryd/rpc_servicer.py", line 57, in DeleteLocation
Sep 18 11:20:19 lte-GW0 directoryd[562]:     self._get_grpc_client().DeleteLocation(request)
Sep 18 11:20:19 lte-GW0 directoryd[562]:   File "/usr/local/lib/python3.5/dist-packages/grpc/_channel.py", line 533, in __call__
Sep 18 11:20:19 lte-GW0 directoryd[562]:     return _end_unary_response_blocking(state, call, False, None)
Sep 18 11:20:19 lte-GW0 directoryd[562]:   File "/usr/local/lib/python3.5/dist-packages/grpc/_channel.py", line 467, in _end_unary_response_blocking
Sep 18 11:20:19 lte-GW0 directoryd[562]:     raise _Rendezvous(state, None, None, deadline)
Sep 18 11:20:19 lte-GW0 directoryd[562]: grpc._channel._Rendezvous: <_Rendezvous of RPC that terminated with:
Sep 18 11:20:19 lte-GW0 directoryd[562]:         status = StatusCode.UNKNOWN
Sep 18 11:20:19 lte-GW0 directoryd[562]:         details = "Error finding location record: No record for query"
Sep 18 11:20:19 lte-GW0 directoryd[562]:         debug_error_string = "{"created":"@1568794819.113702546","description":"Error received from peer","file":"src/core/lib/surface/call.cc","file_line":1017,"grpc_message":"Error finding location record: No record for query","grpc_status":2}"
Sep 18 11:20:19 lte-GW0 directoryd[562]: >
Sep 18 11:20:19 lte-GW0 mme[17589]: Directoryd RPC failed with code 2, msg: Exception calling application: <_Rendezvous of RPC that terminated with:
Sep 18 11:20:19 lte-GW0 mme[17589]:         status = StatusCode.UNKNOWN
Sep 18 11:20:19 lte-GW0 mme[17589]:         details = "Error finding location record: No record for query"
Sep 18 11:20:19 lte-GW0 mme[17589]:         debug_error_string = "{"created":"@1568794819.113702546","description":"Error received from peer","file":"src/core/lib/surface/call.cc","file_line":1017,"grpc_message":"Error finding location record: No record for query","grpc_status":2}"
Sep 18 11:20:19 lte-GW0 mme[17589]: >
Sep 18 11:20:20 lte-GW0 control_proxy[19810]: 2019-09-18T11:20:20.552+03:00 [127.0.0.1 -> meteringd_records-controller.magma.etagecom.io,8443] "POST /magma.lte.MeteringdRecordsController/UpdateFlows HTTP/2" 200 5bytes 0.224s
```

**Comment by xjtian** [comment]
As long as you're running a non-federated LTE network, this should be benign. directoryd issues are something of a KP on our end, we're investing into a significant refactor Q4.
