### ISSUE TITLE
[feg] Error while finding module specification for 'magma.magmad.main'.No module named 'magma'

### ISSUE THREAD

**Issue by robinge330** [magma/magma#6422]
### Your Environment

- **Version:** MAGMA_VERSION:-v1.5
- **Affected Component:** Orchestrator, Access Gateway, or NMS:  Access Gateway
- **Affected Subcomponent:** Orchestrator pod/service or AGW service: AGW service
- **Deployment Environment:** e.g. AWS (orc8r), local docker-compose (orc8r), bare-metal (AGW), Vagrant (AGW)
bare metal AGW
NAME="Ubuntu"
VERSION="18.04.5 LTS (Bionic Beaver)"
### Describe the Issue
After the deployment of agw_install.sh Magma services donot come up.

less /var/log/syslog
Apr 27 18:10:41 fbf-6agw systemd[1]: Started Magma magmad service.
Apr 27 18:10:41 fbf-6agw systemd[1]: Started Regular background program processing daemon.
Apr 27 18:10:41 fbf-6agw systemd[1]: Starting System Logging Service...
Apr 27 18:10:41 fbf-6agw systemd[1]: Started D-Bus System Message Bus.
Apr 27 18:10:41 fbf-6agw cron[850]: (CRON) INFO (pidfile fd = 3)
Apr 27 18:10:41 fbf-6agw magmad[843]: **/usr/bin/python3: Error while finding module specification for 'magma.magmad.main' (ModuleNotFoundError: No module named 'magma')**

Apr 27 18:10:43 fbf-6agw cloud-init[1250]:   File "/usr/bin/cloud-init", line 11, in <module>
Apr 27 18:10:43 fbf-6agw cloud-init[1250]:     load_entry_point('cloud-init==20.3', 'console_scripts', 'cloud-init')()
Apr 27 18:10:43 fbf-6agw cloud-init[1250]:   File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 480, in load_entry_point
Apr 27 18:10:43 fbf-6agw cloud-init[1250]:     return get_distribution(dist).load_entry_point(group, name)
Apr 27 18:10:43 fbf-6agw cloud-init[1250]:   File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2693, in load_entry_point
Apr 27 18:10:43 fbf-6agw cloud-init[1250]:     return ep.load()
Apr 27 18:10:43 fbf-6agw cloud-init[1250]:   File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2324, in load
Apr 27 18:10:43 fbf-6agw cloud-init[1250]:     return self.resolve()
Apr 27 18:10:43 fbf-6agw cloud-init[1250]:   File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2330, in resolve
Apr 27 18:10:43 fbf-6agw cloud-init[1250]:     module = __import__(self.module_name, fromlist=['__name__'], level=0)
Apr 27 18:10:43 fbf-6agw cloud-init[1250]:   File "/usr/lib/python3/dist-packages/cloudinit/cmd/main.py", line 26, in <module>
Apr 27 18:10:43 fbf-6agw cloud-init[1250]:     from cloudinit import netinfo
Apr 27 18:10:43 fbf-6agw cloud-init[1250]:   File "/usr/lib/python3/dist-packages/cloudinit/netinfo.py", line 15, in <module>
Apr 27 18:10:43 fbf-6agw cloud-init[1250]:     from cloudinit.net.network_state import net_prefix_to_ipv4_mask
Apr 27 18:10:43 fbf-6agw cloud-init[1250]:   File "/usr/lib/python3/dist-packages/cloudinit/net/__init__.py", line 15, in <module>
Apr 27 18:10:43 fbf-6agw cloud-init[1250]:     from cloudinit import util
Apr 27 18:10:43 fbf-6agw cloud-init[1250]:   File "/usr/lib/python3/dist-packages/cloudinit/util.py", line 42, in <module>
Apr 27 18:10:43 fbf-6agw cloud-init[1250]:     from cloudinit import (
Apr 27 18:10:43 fbf-6agw cloud-init[1250]:   File "/usr/lib/python3/dist-packages/cloudinit/url_helper.py", line 22, in <module>
Apr 27 18:10:43 fbf-6agw cloud-init[1250]:     import requests
Apr 27 18:10:43 fbf-6agw cloud-init[1250]: ModuleNotFoundError: No module named 'requests'
Apr 27 18:10:43 fbf-6agw systemd[1]: cloud-final.service: Main process exited, code=exited, status=1/FAILURE
Apr 27 18:10:43 fbf-6agw systemd[1]: cloud-final.service: Failed with result 'exit-code'.
Apr 27 18:10:43 fbf-6agw systemd[1]: Failed to start Execute cloud user/final scripts.

Apr 27 18:10:43 fbf-6agw systemd[1]: Startup finished in 4.137s (kernel) + 9.538s (userspace) = 13.676s.
Apr 27 18:10:47 fbf-6agw systemd[1]: magma@magmad.service: Service hold-off time over, scheduling restart.
Apr 27 18:10:47 fbf-6agw systemd[1]: magma@magmad.service: Scheduled restart job, restart counter is at 1.
Apr 27 18:10:47 fbf-6agw systemd[1]: Stopped Magma magmad service.
Apr 27 18:10:47 fbf-6agw systemd[1]: Started Magma magmad service.
Apr 27 18:10:47 fbf-6agw magmad[1287]: /usr/bin/python3: Error while finding module specification for 'magma.magmad.main' (ModuleNotFoundError: No module named 'magma')
Apr 27 18:10:47 fbf-6agw systemd[1]: magma@magmad.service: Main process exited, code=exited, status=1/FAILURE
Apr 27 18:10:47 fbf-6agw magmad[1296]: Traceback (most recent call last):
Apr 27 18:10:47 fbf-6agw magmad[1296]:   File "/usr/local/bin/service_util.py", line 20, in <module>
Apr 27 18:10:47 fbf-6agw magmad[1296]:     from magma.common.health.service_state_wrapper import ServiceStateWrapper
Apr 27 18:10:47 fbf-6agw magmad[1296]: ModuleNotFoundError: No module named 'magma'
Apr 27 18:10:47 fbf-6agw systemd[1]: magma@magmad.service: Control process exited, code=exited status=1
Apr 27 18:10:47 fbf-6agw systemd[1]: magma@magmad.service: Failed with result 'exit-code'.
Apr 27 18:10:48 fbf-6agw snapd[918]: daemon.go:589: gracefully waiting for running hooks
Apr 27 18:10:48 fbf-6agw snapd[918]: daemon.go:591: done waiting for running hooks
Apr 27 18:10:48 fbf-6agw snapd[918]: daemon stop requested to wait for socket activation
Apr 27 18:10:52 fbf-6agw systemd[1]: magma@magmad.service: Service hold-off time over, scheduling restart.
Apr 27 18:10:52 fbf-6agw systemd[1]: magma@magmad.service: Scheduled restart job, restart counter is at 2.
Apr 27 18:10:52 fbf-6agw systemd[1]: Stopped Magma magmad service.
Apr 27 18:10:52 fbf-6agw systemd[1]: Started Magma magmad service.
Apr 27 18:10:52 fbf-6agw magmad[1312]: /usr/bin/python3: Error while finding module specification for 'magma.magmad.main' (ModuleNotFoundError: No module named 'magma')
Apr 27 18:10:52 fbf-6agw systemd[1]: magma@magmad.service: Main process exited, code=exited, status=1/FAILURE
Apr 27 18:10:52 fbf-6agw magmad[1321]: Traceback (most recent call last):
Apr 27 18:10:52 fbf-6agw magmad[1321]:   File "/usr/local/bin/service_util.py", line 20, in <module>
Apr 27 18:10:52 fbf-6agw magmad[1321]:     from magma.common.health.service_state_wrapper import ServiceStateWrapper
Apr 27 18:10:52 fbf-6agw magmad[1321]: ModuleNotFoundError: No module named 'magma'
Apr 27 18:10:52 fbf-6agw systemd[1]: magma@magmad.service: Control process exited, code=exited status=1
Apr 27 18:10:52 fbf-6agw systemd[1]: magma@magmad.service: Failed with result 'exit-code'.
Apr 27 18:10:57 fbf-6agw systemd[1]: magma@magmad.service: Service hold-off time over, scheduling restart.
Apr 27 18:10:57 fbf-6agw systemd[1]: magma@magmad.service: Scheduled restart job, restart counter is at 3.
Apr 27 18:10:57 fbf-6agw systemd[1]: Stopped Magma magmad service.
Apr 27 18:10:57 fbf-6agw systemd[1]: Started Magma magmad service.
Apr 27 18:10:57 fbf-6agw magmad[1330]: /usr/bin/python3: Error while finding module specification for 'magma.magmad.main' (ModuleNotFoundError: No module named 'magma')
Apr 27 18:10:57 fbf-6agw systemd[1]: magma@magmad.service: Main process exited, code=exited, status=1/FAILURE

**To Reproduce**
1. Go to '...'    " Follow instruction as per https://docs.magmacore.org/docs/lte/setup_deb
2.2. Click on '....' as above and after agw_install.sh magma does not comeup

**Expected behavior**

Successful start of magma service

**Screenshots**

**Additional context**
Add any other context about the problem here (e.g. logs).

[AGW-27-April.Journalctl.log](https://github.com/magma/magma/files/6387984/AGW-27-April.Journalctl.log)

**Comment by robinge330** [comment]
Please could i get an assistance

**Comment by robinge330** [comment]
Resolved by following https://docs.magmacore.org/docs/lte/deploy_install_ubun
