### ISSUE TITLE
[Magma] [Bug] AGW 1.3 keeps crashing after checkin with Orc8r 1.4

### ISSUE THREAD

**Issue by wallyrb** [magma/magma#6838]
### Your Environment

- **Version:AGW 1.3 and Orc8r 1.4**
- **Affected Component:** Orchestrator, Access Gateway
- **Affected Subcomponent:** AGW Services
- **Deployment Environment:** AWS (orc8r)bare-metal (AGW)

### Describe the Issue

```
May  5 11:17:17 magma mme[11368]: ERROR:root:Error retrieving config for mme, key not found: enable_nat
May  5 11:17:17 magma mme[11368]: ERROR:root:Error retrieving config for spgw, key not found: ovs_internal_sampling_fwd_tbl
May  5 11:17:17 magma mme[11368]: WARNING:root:Service (spgw) missing in mconfig

```

```
May  4 09:00:44 magma enodebd[501]: ERROR:grpc._server:Exception calling application: 'NoneType' object has no attribute 'is_enodeb_configured'
May  4 09:00:44 magma enodebd[501]: Traceback (most recent call last):
May  4 09:00:44 magma enodebd[501]:   File "/usr/local/lib/python3.5/dist-packages/grpc/_server.py", line 389, in _call_behavior
May  4 09:00:44 magma enodebd[501]:     return behavior(argument, context), True
May  4 09:00:44 magma enodebd[501]:   File "/usr/local/lib/python3.5/dist-packages/magma/common/service.py", line 350, in GetServiceInfo
May  4 09:00:44 magma enodebd[501]:     status = self._get_status_callback()
May  4 09:00:44 magma enodebd[501]:   File "/usr/local/lib/python3.5/dist-packages/magma/enodebd/main.py", line 63, in get_enodebd_status
May  4 09:00:44 magma enodebd[501]:     return get_service_status_old(state_machine_manager)
May  4 09:00:44 magma enodebd[501]:   File "/usr/local/lib/python3.5/dist-packages/magma/enodebd/enodeb_status.py", line 128, in get_service_status_old
May  4 09:00:44 magma enodebd[501]:     enb_status_by_serial = get_all_enb_status(enb_acs_manager)
May  4 09:00:44 magma enodebd[501]:   File "/usr/local/lib/python3.5/dist-packages/magma/enodebd/enodeb_status.py", line 225, in get_all_enb_status
May  4 09:00:44 magma enodebd[501]:     status = get_enb_status(handler)
May  4 09:00:44 magma enodebd[501]:   File "/usr/local/lib/python3.5/dist-packages/magma/enodebd/enodeb_status.py", line 253, in get_enb_status
May  4 09:00:44 magma enodebd[501]:     enodeb_configured = enodeb.is_enodeb_configured()
May  4 09:00:44 magma enodebd[501]: AttributeError: 'NoneType' object has no attribute 'is_enodeb_configured'
May  4 09:00:44 magma magmad[410]: ERROR:root:GetServiceInfo Error for enodebd! [StatusCode.UNKNOWN] Exception calling application: 'NoneType' object has no attribute 'is_enodeb_configured'

```

**Expected behavior**
After AGW checking with Orcr8r, mme and other services shouldn't crash

**Comment by ekowtaylor** [comment]
@karthiksubraveti we didn't test this specifically but is this behavior expected?

**Comment by ekowtaylor** [comment]
Newer release available https://github.com/magma/magma/releases/tag/v1.5.3
