### ISSUE TITLE
eNodeB get status exception

### ISSUE THREAD

**Issue by bmurithi** [magma/magma#685]
```
magma version: 1.0.0-1568436857-c4da5d25

Cell configured and transmitting.
```

```
Oct 03 17:59:31 lte enodebd[28184]: ERROR:grpc._server:Exception calling application: True has type <class 'bool'>, but expected one of: (<class 'bytes'>, <class 'str'>)
Oct 03 17:59:31 lte enodebd[28184]: Traceback (most recent call last):
Oct 03 17:59:31 lte enodebd[28184]:   File "/usr/local/lib/python3.5/dist-packages/grpc/_server.py", line 389, in _call_behavior
Oct 03 17:59:31 lte enodebd[28184]:     return behavior(argument, context), True
Oct 03 17:59:31 lte enodebd[28184]:   File "/usr/local/lib/python3.5/dist-packages/magma/enodebd/rpc_servicer.py", line 127, in GetAllEnodebStatus
Oct 03 17:59:31 lte enodebd[28184]:     self.state_machine_manager)
Oct 03 17:59:31 lte enodebd[28184]:   File "/usr/local/lib/python3.5/dist-packages/magma/enodebd/enodeb_status.py", line 287, in get_single_enb_status
Oct 03 17:59:31 lte enodebd[28184]:     enb_status.connected = status.enodeb_connected
Oct 03 17:59:31 lte enodebd[28184]:   File "/usr/local/lib/python3.5/dist-packages/google/protobuf/internal/python_message.py", line 662, in field_setter
Oct 03 17:59:31 lte enodebd[28184]:     new_value = type_checker.CheckValue(new_value)
Oct 03 17:59:31 lte enodebd[28184]:   File "/usr/local/lib/python3.5/dist-packages/google/protobuf/internal/type_checkers.py", line 177, in CheckValue
Oct 03 17:59:31 lte enodebd[28184]:     raise TypeError(message)
Oct 03 17:59:31 lte enodebd[28184]: TypeError: True has type <class 'bool'>, but expected one of: (<class 'bytes'>, <class 'str'>)
Oct 03 17:59:39 lte enodebd[28184]: ERROR:grpc._server:Exception calling application: True has type <class 'bool'>, but expected one of: (<class 'bytes'>, <class 'str'>)
Oct 03 17:59:39 lte enodebd[28184]: Traceback (most recent call last):
Oct 03 17:59:39 lte enodebd[28184]:   File "/usr/local/lib/python3.5/dist-packages/grpc/_server.py", line 389, in _call_behavior
Oct 03 17:59:39 lte enodebd[28184]:     return behavior(argument, context), True
Oct 03 17:59:39 lte enodebd[28184]:   File "/usr/local/lib/python3.5/dist-packages/magma/enodebd/rpc_servicer.py", line 127, in GetAllEnodebStatus
Oct 03 17:59:39 lte enodebd[28184]:     self.state_machine_manager)
Oct 03 17:59:39 lte enodebd[28184]:   File "/usr/local/lib/python3.5/dist-packages/magma/enodebd/enodeb_status.py", line 287, in get_single_enb_status
Oct 03 17:59:39 lte enodebd[28184]:     enb_status.connected = status.enodeb_connected
Oct 03 17:59:39 lte enodebd[28184]:   File "/usr/local/lib/python3.5/dist-packages/google/protobuf/internal/python_message.py", line 662, in field_setter
Oct 03 17:59:39 lte enodebd[28184]:     new_value = type_checker.CheckValue(new_value)
Oct 03 17:59:39 lte enodebd[28184]:   File "/usr/local/lib/python3.5/dist-packages/google/protobuf/internal/type_checkers.py", line 177, in CheckValue
Oct 03 17:59:39 lte enodebd[28184]:     raise TypeError(message)
Oct 03 17:59:39 lte enodebd[28184]: TypeError: True has type <class 'bool'>, but expected one of: (<class 'bytes'>, <class 'str'>)
```

**Comment by andreilee** [comment]
https://github.com/facebookincubator/magma/pull/692 also fixes this issue.

**Comment by bmurithi** [comment]
Is this fix missing in the latest `stretch-stable`?

```
1.0.0-1569942546-301a6ae9
```
