### ISSUE TITLE
[1.5][nms][upgrade] Unable to add new users after upgrade from 1.4 to 1.5

### ISSUE THREAD

**Issue by mattymo** [magma/magma#6851]
### Your Environment

- **Version:** 1.5.0
- **Affected Component:** NMS
- **Affected Subcomponent:** NMS
- **Deployment Environment:** AWS orc8r

### Describe the Issue

Cannot add new users. The UI shows the error: SequelizeUniqueConstraintError: Validation error

Logs show the following error:
```
{"message":"162.250.209.110 - - [10/May/2021:18:18:56 +0000] \"POST /user/async/ HTTP/1.1\" 400 60 \"https://master.nms.newton.mycompany.mydomain/master/users\" \"Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) 
AppleWebKit/605.1.15 (KHTML, like Gecko) Version/14.1 Safari/605.1.15\"\n","level":"info","label":"express-middleware/appMiddleware.js","timestamp":"2021-05-10T18:18:56.912Z"}
{"message":"Executing (default): INSERT INTO \"AuditLogEntries\" (\"id\",\"actingUserId\",\"organization\",\"mutationType\",\"objectId\",\"objectDisplayName\",\"objectType\",\"mutationData\",\"url\",\"ipAdd
ress\",\"status\",\"statusCode\",\"createdAt\",\"updatedAt\") VALUES (DEFAULT,$1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13) RETURNING *;","level":"debug","label":"sequelize-models/sequelizeConfig.js","timesta
mp":"2021-05-10T18:18:56.916Z"}
(node:27) UnhandledPromiseRejectionWarning: SequelizeUniqueConstraintError: Validation error
    at Query.formatError (/usr/src/node_modules/sequelize/lib/dialects/postgres/query.js:324:18)
    at query.catch.err (/usr/src/node_modules/sequelize/lib/dialects/postgres/query.js:72:18)
    at tryCatcher (/usr/src/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/usr/src/node_modules/bluebird/js/release/promise.js:547:31)
    at Promise._settlePromise (/usr/src/node_modules/bluebird/js/release/promise.js:604:18)
    at Promise._settlePromise0 (/usr/src/node_modules/bluebird/js/release/promise.js:649:10)
    at Promise._settlePromises (/usr/src/node_modules/bluebird/js/release/promise.js:725:18)
    at _drainQueueStep (/usr/src/node_modules/bluebird/js/release/async.js:93:12)
    at _drainQueue (/usr/src/node_modules/bluebird/js/release/async.js:86:9)
    at Async._drainQueues (/usr/src/node_modules/bluebird/js/release/async.js:102:5)
    at Immediate.Async.drainQueues [as _onImmediate] (/usr/src/node_modules/bluebird/js/release/async.js:15:14)
    at runCallback (timers.js:705:18)
    at tryOnImmediate (timers.js:676:5)
    at processImmediate (timers.js:658:5)
(node:27) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not h
andled with .catch(). (rejection id: 9)
```

**To Reproduce**
1. Deploy orc8r 1.4 and upgrade to 1.5
2. Go to Organizations
3. Add user to master org

**Additional context**
NMS db was migrated from mariadb to postgres using the migration script.

**Comment by mattymo** [comment]
This was fixed in some followup patch present in v1.5 stable branch. I'm closing this issue because I can't reproduce it any more

**Comment by jpad-freedomfi** [comment]
we are seeing this issue in production environment after updating to 1.5.1. it appears to effect user creation and organization creation. 

@119Vik @mattymo @sudhikan

**Comment by andreilee** [comment]
It looks like updating the 'id sequence' for tables in Postgres
- `Users`
- `Sessions`
- `Organizations`
- `AuditLogEntries`
should fix this issue.

Two ways to fix this, one manual, and also a PR, but first:

StackOverflow link for doing this manually: [link](https://stackoverflow.com/questions/244243/how-to-reset-postgres-primary-key-sequence-when-it-falls-out-of-sync)

DB data migration from MariaDB to Postgres when updating from 1.4.x to 1.5.x did not account for Postgres not automatically updating the 'id sequence', and this causes new row inserts to re-use unique number IDs.

Manual comparison for 'id sequence' in Postgres:
```
nms=# select id from "Organizations";
 id
----
  1
  2
  3
  4
  5
  8
  9
 10
 11
 12
(10 rows)

nms=# select * from "Organizations_id_seq";
    sequence_name     | last_value | start_value | increment_by |      max_value      | min_value | cache_value | log_cnt | is_cycled | is_called
----------------------+------------+-------------+--------------+---------------------+-----------+-------------+---------+-----------+-----------
 Organizations_id_seq |          4 |           1 |            1 | 9223372036854775807 |         1 |           1 |       0 | f         | f
(1 row)

nms=# \d "Organizations";
                                                  Table "public.Organizations"
         Column          |                 Type                 |                           Modifiers
-------------------------+--------------------------------------+---------------------------------------------------------------
 id                      | integer                              | not null default nextval('"Organizations_id_seq"'::regclass)
 name                    | character varying(255)               |
 tabs                    | json                                 | not null default '[]'::json
 csvCharset              | character varying(255)               |
 customDomains           | json                                 | not null default '[]'::json
 networkIDs              | json                                 | not null default '[]'::json
 ssoSelectedType         | "enum_Organizations_ssoSelectedType" | not null default 'none'::"enum_Organizations_ssoSelectedType"
 ssoCert                 | text                                 | not null default ''::text
 ssoEntrypoint           | character varying(255)               | not null default ''::character varying
 ssoIssuer               | character varying(255)               | not null default ''::character varying
 ssoOidcClientID         | character varying(255)               | not null default ''::character varying
 ssoOidcClientSecret     | character varying(255)               | not null default ''::character varying
 ssoOidcConfigurationURL | character varying(255)               | not null default ''::character varying
 createdAt               | timestamp with time zone             | not null
 updatedAt               | timestamp with time zone             | not null
Indexes:
    "Organizations_pkey" PRIMARY KEY, btree (id)

nms=#
```

**Comment by andreilee** [comment]
Fix will be in package `@fbcnms/sequelize-models`: [(gh pull request)](https://github.com/facebookincubator/fbc-js-core/pull/106) `0.1.9`

**Comment by andreilee** [comment]
See this [gist](https://gist.github.com/andreilee/1809a510ba2021a72713e7999686b2e0) for script to hotfix on v1.5.0 and v1.5.1.

Or just run this in a shell prompt where you have access to your kubernetes cluster:
`wget https://gist.githubusercontent.com/andreilee/1809a510ba2021a72713e7999686b2e0/raw/b24b984adf673199b0c9428601524ad3e2beffd5/post-upgrade-fix.sh && chmod +x post-upgrade-fix.sh && ./post-upgrade-fix.sh`
