### ISSUE TITLE
ERROR:grpc._server:Exception calling application: database table is locked: subscriberdb

### ISSUE THREAD

**Issue by pshelar** [magma/magma#6937]
### Your Environment

- **Version:** 1.5.0-1620963309-d2135127
- **Affected Component:** Access Gateway
- **Affected Subcomponent:** MME, subscriberDB
- **Deployment Environment:** bare-metal (AGW)

### Describe the Issue

on scale test:
```
May 14 11:04:17 phy-u3 subscriberdb[1608292]: ERROR:grpc._server:Exception calling application: database table is locked: subscriberdb
May 14 11:04:17 phy-u3 subscriberdb[1608292]: Traceback (most recent call last):
May 14 11:04:17 phy-u3 subscriberdb[1608292]:   File "/usr/local/lib/python3.8/dist-packages/grpc/_server.py", line 435, in _call_behavior
May 14 11:04:17 phy-u3 subscriberdb[1608292]:     response_or_iterator = behavior(argument, context)
May 14 11:04:17 phy-u3 subscriberdb[1608292]:   File "/usr/local/lib/python3.8/dist-packages/magma/subscriberdb/protocols/s6a_proxy_servicer.py", line 100, in UpdateLocation
May 14 11:04:17 phy-u3 subscriberdb[1608292]:     sub_data = self.lte_processor.get_sub_data(imsi)
May 14 11:04:17 phy-u3 subscriberdb[1608292]:   File "/usr/local/lib/python3.8/dist-packages/magma/subscriberdb/processor.py", line 282, in get_sub_data
May 14 11:04:17 phy-u3 subscriberdb[1608292]:     sub_data = self._store.get_subscriber_data(sid)
May 14 11:04:17 phy-u3 subscriberdb[1608292]:   File "/usr/local/lib/python3.8/dist-packages/magma/subscriberdb/store/sqlite.py", line 152, in get_subscriber_data
May 14 11:04:17 phy-u3 subscriberdb[1608292]:     res = conn.execute("SELECT data FROM subscriberdb WHERE "
May 14 11:04:17 phy-u3 subscriberdb[1608292]: sqlite3.OperationalError: database table is locked: subscriberdb
May 14 11:04:17 phy-u3 sctpd[1724711]: I0514 11:04:17.986675 1724716 sctpd_downlink_impl.cpp:76] SctpdDownlinkImpl::SendDl starting
May 14 11:04:17 phy-u3 mme[1724838]: [ERROR] 2: Exception calling application: database table is locked: subscriberdb
May 14 11:04:17 phy-u3 mme[1724838]: [ERROR]  Received S6A-LOCATION-UPDATE_ANSWER for IMSI: 001011234560379; Status: Exception calling application: database table is locked: subscriberdb; ErrorCode: 0
```
attached logs from mme and subscriberDB.

[logs.tjz.txt](https://github.com/magma/magma/files/6480725/logs.tjz.txt)

**Comment by ulaskozat** [comment]
Hey @pshelar db lock cannot be avoided as we have multiple writers/readers to subscriber tables. I thought you were going to post the query about `Failed to process primitive ESM_EPS_BEARER_CONTEXT_DEACTIVATE_REQ`. Is the log file for the same test?

**Comment by pshelar** [comment]
@ulaskozat after this error I do not see attach succeeding

**Comment by pshelar** [comment]
I will create separate issue for deactivate issue.

**Comment by pshelar** [comment]
I am also worried about following ERR msg from MME. if it not issue, it shld not logged at ERROR level.
```
May 14 11:04:17 phy-u3 mme[1724838]: [ERROR] 2: Exception calling application: database table is locked: subscriberdb

```

**Comment by ulaskozat** [comment]
I am closing this issue. We may switch the log level to Warning. But since this is GRPC error, better to keep track of them at this level.
