### ISSUE TITLE
[agw] mme service keep crashing after change in configuration

### ISSUE THREAD

**Issue by wallyrb** [magma/magma#6985]
### Your Environment

AGW Version: 1.3.3-1617310617-87e22392
- **Affected Component:** AGW
- **Affected Subcomponent:** AGW mme service
- **Deployment Environment:**  bare-metal (AGW)

### Describe the Issue

MME crashed after remove eNB from AGW in NMS

```
May 17 15:55:28 magmaAGW-0001 systemd[1]: Stopping Magma OAI MME service...
May 17 15:55:28 magmaAGW-0001 mme[2968]: Received SIGINT or SIGTERM
May 17 15:55:28 magmaAGW-0001 mme[2968]: [TRACE] Entering shared_log_exit
May 17 15:55:28 magmaAGW-0001 mme[2968]: TASK_SERVICE303 terminated
May 17 15:55:28 magmaAGW-0001 mme[2968]: [TRACE] Leaving shared_log_exit
May 17 15:55:28 magmaAGW-0001 mme[2968]: TASK_SHARED_TS_LOG terminated
May 17 15:55:28 magmaAGW-0001 mme[2968]: TASK_SERVICE303_SERVER terminated
May 17 15:55:28 magmaAGW-0001 mme[2968]: TASK_S6A terminated
May 17 15:55:28 magmaAGW-0001 td-agent-bit[7640]: [2021/05/17 15:55:28] [ warn] [engine] Task cannot be retried: task_id=3 thread_id=2 output=forward.0
May 17 15:55:28 magmaAGW-0001 mme[2968]: TASK_SPGW_APP terminated
May 17 15:55:28 magmaAGW-0001 mme[2968]: TASK_GRPC_SERVICE terminated
May 17 15:55:28 magmaAGW-0001 mme[2968]: TASK_MME_APP terminated
May 17 15:55:28 magmaAGW-0001 mme[2968]: TASK_S1AP terminated
May 17 15:55:28 magmaAGW-0001 mme[2968]: TASK_SCTP terminated
```

After that, there is several mme keeps crashing with LeakSanitizer errors

```
May 17 15:55:29 magmaAGW-0001 systemd[1]: Stopped Magma sctpd service.
May 17 15:55:29 magmaAGW-0001 systemd[1]: Stopped Magma enodebd service.
May 17 15:55:29 magmaAGW-0001 systemd[1]: Started Magma enodebd service.
May 17 15:55:29 magmaAGW-0001 pipelined[2819]: ERROR:EnforcementStatsController:127063227 bytes total not reported.
May 17 15:55:29 magmaAGW-0001 mme[2968]: Cleaning up SPGW configs
May 17 15:55:29 magmaAGW-0001 mme[2968]: =================================================================
May 17 15:55:29 magmaAGW-0001 mme[2968]: ==2968==ERROR: LeakSanitizer: detected memory leaks
May 17 15:55:29 magmaAGW-0001 mme[2968]: Direct leak of 4856112 byte(s) in 303507 object(s) allocated from:
May 17 15:55:29 magmaAGW-0001 mme[2968]:     #0 0x7f9256a05c6f in __interceptor_malloc (/usr/lib/x86_64-linux-gnu/liblsan.so.0+0xcc6f)
May 17 15:55:29 magmaAGW-0001 mme[2968]:     #1 0x564d84375465 in blk2bstr /home/vagrant/magma/lte/gateway/c/oai/lib/bstr/bstrlib.c:314
May 17 15:55:29 magmaAGW-0001 mme[2968]:     #2 0x564d843c7ef8 in s1ap_handle_paging_request /home/vagrant/magma/lte/gateway/c/oai/tasks/s1ap/s1ap_mme_handlers.c:2539
May 17 15:55:29 magmaAGW-0001 mme[2968]:     #3 0x564d8437f2d0 in handle_message /home/vagrant/magma/lte/gateway/c/oai/tasks/s1ap/s1ap_mme.c:215
```
..

**Additional context**
Mitigation done running:
mv /etc/openvswitch/conf.db /root/ 
sudo reboot

**Comment by ekowtaylor** [comment]
@ulaskozat , @ardzoht could some of the recent changes have addressed these issues?

**Comment by ulaskozat** [comment]
@ekowtaylor I don't think we have. @wallyrb is this reproducible by the partner? This is for unmanaged eNB right?

**Comment by ulaskozat** [comment]
The MME as far as I see is not crashing but getting restarted by systemd on the top view (potentially due to a config change in TAI list). When the service is stopped, the memory leaks would be reported. What is causing the restarts is not clear to me here. Can we have the full syslog rather than a fragment.

**Comment by wallyrb** [comment]
thanks for checking @ulaskozat , yes for unamanaged eNB. I sent you the logs

**Comment by ekowtaylor** [comment]
Newer release available https://github.com/magma/magma/releases/tag/v1.5.3
