### ISSUE TITLE
`get_test_summaries` is  broken even locally

### ISSUE THREAD

**Issue by themarwhal** [magma/magma#7688]
Prior to submitting an issue, check to see if one has already been created. If there is currently an open issue, add a thumbs-up emoji to identify that it is also affecting you.

### Your Environment

- **Version:** master
Broken on CI: https://app.circleci.com/pipelines/github/magma/magma/26763/workflows/7ebcb510-208b-4881-82e5-8a025f5daa8d/jobs/286731
```
## run `fab integ_test` to trigger some tests first
➜  gateway git:(disable-test-summary-temporarily) ✗ fab get_test_summaries:dst_path="./"
[localhost] local: mkdir -p ./
[localhost] local: pwd
[localhost] local: vagrant status magma
[localhost] local: vagrant ssh-config magma
Traceback (most recent call last):
  File "/Users/marwhal/.pyenv/versions/3.7.3/lib/python3.7/site-packages/fabric/main.py", line 763, in main
    *args, **kwargs
  File "/Users/marwhal/.pyenv/versions/3.7.3/lib/python3.7/site-packages/fabric/tasks.py", line 427, in execute
    results['<local-only>'] = task.run(*args, **new_kwargs)
  File "/Users/marwhal/.pyenv/versions/3.7.3/lib/python3.7/site-packages/fabric/tasks.py", line 174, in run
    return self.wrapped(*args, **kwargs)
  File "/Users/marwhal/Desktop/magma/lte/gateway/fabfile.py", line 304, in get_test_summaries
    get(remote_path=TEST_SUMMARY_GLOB, local_path=dst_path)
  File "/Users/marwhal/.pyenv/versions/3.7.3/lib/python3.7/site-packages/fabric/network.py", line 692, in host_prompting_wrapper
    return func(*args, **kwargs)
  File "/Users/marwhal/.pyenv/versions/3.7.3/lib/python3.7/site-packages/fabric/operations.py", line 540, in get
    ftp = SFTP(env.host_string)
  File "/Users/marwhal/.pyenv/versions/3.7.3/lib/python3.7/site-packages/fabric/sftp.py", line 34, in __init__
    self.ftp = connections[host_string].open_sftp()
  File "/Users/marwhal/.pyenv/versions/3.7.3/lib/python3.7/site-packages/paramiko/client.py", line 479, in open_sftp
    return self._transport.open_sftp_client()
  File "/Users/marwhal/.pyenv/versions/3.7.3/lib/python3.7/site-packages/paramiko/transport.py", line 909, in open_sftp_client
    return SFTPClient.from_transport(self)
  File "/Users/marwhal/.pyenv/versions/3.7.3/lib/python3.7/site-packages/paramiko/sftp_client.py", line 131, in from_transport
    chan.invoke_subsystem('sftp')
  File "/Users/marwhal/.pyenv/versions/3.7.3/lib/python3.7/site-packages/paramiko/channel.py", line 60, in _check
    return func(self, *args, **kwds)
  File "/Users/marwhal/.pyenv/versions/3.7.3/lib/python3.7/site-packages/paramiko/channel.py", line 259, in invoke_subsystem
    self._wait_for_event()
  File "/Users/marwhal/.pyenv/versions/3.7.3/lib/python3.7/site-packages/paramiko/channel.py", line 1162, in _wait_for_event
    raise e
paramiko.ssh_exception.SSHException: Channel closed.
Disconnecting from vagrant@127.0.0.1:2222... done.
```

**Comment by themarwhal** [comment]
pretty sure it's related to the recent ubuntu vm switch because getting artifacts works for the magma_test VM but not magma

**Comment by themarwhal** [comment]
The same issue is also breaking lte-agw-deploy job
https://app.circleci.com/pipelines/github/magma/magma/26816/workflows/895d684d-5cef-42f2-9a99-250e9fb3d6d8/jobs/288110

**Comment by themarwhal** [comment]
fixed on master
