### ISSUE TITLE
1.5 branch Monitord not working

### ISSUE THREAD

**Issue by jpad-freedomfi** [magma/magma#7701]
Prior to submitting an issue, check to see if one has already been created. If there is currently an open issue, add a thumbs-up emoji to identify that it is also affecting you.

### Your Environment

- **Version:** 6/20 1.5 Branch Head build
- **Affected Component:** Access Gateway
- **Affected Subcomponent:** monitord
- **Deployment Environment:** bare-metal (AGW)

### Describe the Issue

Monitord is crashing.

@ardzoht 

**To Reproduce**
1. Build and run 1.5 branch (6/20 or later) using NAT at network and NAT at Gateway
2. Enable CPE monitoring in NMS on Gateway Config
3. view logs via "sudo journalctl -fu magma@monitord"

**Expected behavior**
Monitord should work, ping UE, and track "last seen time/date"

Logs are small so I'll post here:

```
magma@minipc:~$ sudo journalctl -fu magma@monitord
-- Logs begin at Mon 2021-06-21 07:23:14 UTC. --
Jun 22 14:28:55 minipc monitord[1411]:     states = self._get_operational_states_cb()
Jun 22 14:28:55 minipc monitord[1411]: TypeError: 'list' object is not callable
Jun 22 14:29:19 minipc monitord[1411]: WARNING:root:No subscribers/ping targets found
Jun 22 14:29:56 minipc monitord[1411]: ERROR:grpc._server:Exception calling application: 'list' object is not callable
Jun 22 14:29:56 minipc monitord[1411]: Traceback (most recent call last):
Jun 22 14:29:56 minipc monitord[1411]:   File "/usr/local/lib/python3.5/dist-packages/grpc/_server.py", line 444, in _call_behavior
Jun 22 14:29:56 minipc monitord[1411]:     response_or_iterator = behavior(argument, context)
Jun 22 14:29:56 minipc monitord[1411]:   File "/usr/local/lib/python3.5/dist-packages/magma/common/service.py", line 402, in GetOperationalStates
Jun 22 14:29:56 minipc monitord[1411]:     states = self._get_operational_states_cb()
Jun 22 14:29:56 minipc monitord[1411]: TypeError: 'list' object is not callable
Jun 22 14:30:29 minipc monitord[1411]: WARNING:root:No subscribers/ping targets found
Jun 22 14:30:57 minipc monitord[1411]: ERROR:grpc._server:Exception calling application: 'list' object is not callable
Jun 22 14:30:57 minipc monitord[1411]: Traceback (most recent call last):
Jun 22 14:30:57 minipc monitord[1411]:   File "/usr/local/lib/python3.5/dist-packages/grpc/_server.py", line 444, in _call_behavior
Jun 22 14:30:57 minipc monitord[1411]:     response_or_iterator = behavior(argument, context)
Jun 22 14:30:57 minipc monitord[1411]:   File "/usr/local/lib/python3.5/dist-packages/magma/common/service.py", line 402, in GetOperationalStates
Jun 22 14:30:57 minipc monitord[1411]:     states = self._get_operational_states_cb()
Jun 22 14:30:57 minipc monitord[1411]: TypeError: 'list' object is not callable
Jun 22 14:31:39 minipc monitord[1411]: WARNING:root:No subscribers/ping targets found
Jun 22 14:31:58 minipc monitord[1411]: ERROR:grpc._server:Exception calling application: 'list' object is not callable
Jun 22 14:31:58 minipc monitord[1411]: Traceback (most recent call last):
Jun 22 14:31:58 minipc monitord[1411]:   File "/usr/local/lib/python3.5/dist-packages/grpc/_server.py", line 444, in _call_behavior
Jun 22 14:31:58 minipc monitord[1411]:     response_or_iterator = behavior(argument, context)
Jun 22 14:31:58 minipc monitord[1411]:   File "/usr/local/lib/python3.5/dist-packages/magma/common/service.py", line 402, in GetOperationalStates
Jun 22 14:31:58 minipc monitord[1411]:     states = self._get_operational_states_cb()
Jun 22 14:31:58 minipc monitord[1411]: TypeError: 'list' object is not callable
Jun 22 14:32:49 minipc monitord[1411]: WARNING:root:No subscribers/ping targets found
Jun 22 14:32:59 minipc monitord[1411]: ERROR:grpc._server:Exception calling application: 'list' object is not callable
Jun 22 14:32:59 minipc monitord[1411]: Traceback (most recent call last):
Jun 22 14:32:59 minipc monitord[1411]:   File "/usr/local/lib/python3.5/dist-packages/grpc/_server.py", line 444, in _call_behavior
Jun 22 14:32:59 minipc monitord[1411]:     response_or_iterator = behavior(argument, context)
Jun 22 14:32:59 minipc monitord[1411]:   File "/usr/local/lib/python3.5/dist-packages/magma/common/service.py", line 402, in GetOperationalStates
Jun 22 14:32:59 minipc monitord[1411]:     states = self._get_operational_states_cb()
Jun 22 14:32:59 minipc monitord[1411]: TypeError: 'list' object is not callable
Jun 22 14:33:59 minipc monitord[1411]: WARNING:root:No subscribers/ping targets found
Jun 22 14:34:01 minipc monitord[1411]: ERROR:grpc._server:Exception calling application: 'list' object is not callable
Jun 22 14:34:01 minipc monitord[1411]: Traceback (most recent call last):
Jun 22 14:34:01 minipc monitord[1411]:   File "/usr/local/lib/python3.5/dist-packages/grpc/_server.py", line 444, in _call_behavior
Jun 22 14:34:01 minipc monitord[1411]:     response_or_iterator = behavior(argument, context)
Jun 22 14:34:01 minipc monitord[1411]:   File "/usr/local/lib/python3.5/dist-packages/magma/common/service.py", line 402, in GetOperationalStates
Jun 22 14:34:01 minipc monitord[1411]: 
```

**Comment by karthiksubraveti** [comment]
@sourabh-nanoti  @ardzoht Can you take a look at this issue. Thanks
