### ISSUE TITLE
[pipelined] override config doesnt work with some parameters

### ISSUE THREAD

**Issue by uri200** [magma/magma#7750]
When using any yml file, like sessiond.yml on `/var/opt/magma/configs`  we can overwrite specific parameters that differ from the default configuration. That allows the user to specify their own configuraton. Also on update that file doesnt get overwrtien. 

When we do the same on pipelined, that doesnt work on nested keys. For example, if we just want to override the key poll_interval from enforcement, we need to include default_drop_flow_name even that we dont want to override. otherwise pipelined crashes.

```
magma@ubuntuAGW:~$ cat /var/opt/magma/configs/pipelined.yml
enforcement:
  poll_interval: 2
  default_drop_flow_name: 'internal_default_drop_flow_rule' <---- Fails if this is not included in the override file
```

```
n 24 12:21:25 ubuntuAGW pipelined[1307047]: INFO:ryu.base.app_manager:instantiating app magma.pipelined.app.dpi of DPIController
Jun 24 12:21:25 ubuntuAGW pipelined[1307047]: INFO:ryu.base.app_manager:instantiating app magma.pipelined.app.he of HeaderEnrichmentController
Jun 24 12:21:25 ubuntuAGW pipelined[1307047]: INFO:HeaderEnrichmentController:Header Enrichment app config: heConfig(he_proxy_port=1, he_enabled=False, encryption_enabled=False, encryption_algorithm=None, encryption_key=None, hash_function=None, encoding_type=None, uplink_port=4294967294, gtp_port=32768)
Jun 24 12:21:25 ubuntuAGW pipelined[1307047]: INFO:ryu.base.app_manager:instantiating app magma.pipelined.app.gy of GYController
Jun 24 12:21:25 ubuntuAGW pipelined[1307047]: INFO:ryu.base.app_manager:instantiating app magma.pipelined.app.enforcement of EnforcementController
Jun 24 12:21:25 ubuntuAGW pipelined[1307047]: INFO:ryu.base.app_manager:instantiating app magma.pipelined.app.enforcement_stats of EnforcementStatsController
Jun 24 12:21:25 ubuntuAGW pipelined[1307047]: Traceback (most recent call last):
Jun 24 12:21:25 ubuntuAGW pipelined[1307047]:   File "/usr/lib/python3.8/runpy.py", line 194, in _run_module_as_main
Jun 24 12:21:25 ubuntuAGW pipelined[1307047]:     return _run_code(code, main_globals, None,
Jun 24 12:21:25 ubuntuAGW pipelined[1307047]:   File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
Jun 24 12:21:25 ubuntuAGW pipelined[1307047]:     exec(code, run_globals)
Jun 24 12:21:25 ubuntuAGW pipelined[1307047]:   File "/usr/local/lib/python3.8/dist-packages/magma/pipelined/main.py", line 229, in <module>
Jun 24 12:21:25 ubuntuAGW pipelined[1307047]:     main()
Jun 24 12:21:25 ubuntuAGW pipelined[1307047]:   File "/usr/local/lib/python3.8/dist-packages/magma/pipelined/main.py", line 136, in main
Jun 24 12:21:25 ubuntuAGW pipelined[1307047]:     service_manager.load()
Jun 24 12:21:25 ubuntuAGW pipelined[1307047]:   File "/usr/local/lib/python3.8/dist-packages/magma/pipelined/service_manager.py", line 573, in load
Jun 24 12:21:25 ubuntuAGW pipelined[1307047]:     for app in manager.instantiate_apps(**contexts):
Jun 24 12:21:25 ubuntuAGW pipelined[1307047]:   File "/usr/lib/python3/dist-packages/ryu/base/app_manager.py", line 509, in instantiate_apps
Jun 24 12:21:25 ubuntuAGW pipelined[1307047]:     self._instantiate(app_name, cls, *args, **kwargs)
Jun 24 12:21:25 ubuntuAGW pipelined[1307047]:   File "/usr/lib/python3/dist-packages/ryu/base/app_manager.py", line 495, in _instantiate
Jun 24 12:21:25 ubuntuAGW pipelined[1307047]:     app = cls(*args, **kwargs)
Jun 24 12:21:25 ubuntuAGW pipelined[1307047]:   File "/usr/local/lib/python3.8/dist-packages/magma/pipelined/app/enforcement_stats.py", line 88, in __init__
Jun 24 12:21:25 ubuntuAGW pipelined[1307047]:     kwargs['config']['enforcement']['default_drop_flow_name']
Jun 24 12:21:25 ubuntuAGW pipelined[1307047]: KeyError: 'default_drop_flow_name'
Jun 24 12:21:26 ubuntuAGW systemd[1]: magma@pipelined.service: Main process exited, code=exited, status=1/FAILURE
Jun 24 12:21:26 ubuntuAGW systemd[1]: magma@pipelined.service: Failed with result 'exit-code'.
Jun 24 12:21:31 ubuntuAGW systemd[1]: magma@pipelined.service: Scheduled restart job, restart counter is at 7.
Jun 24 12:21:32 ubuntuAGW systemd[1]: Stopped Magma pipelined service.

```

**Comment by koolzz** [comment]
This feels like a general issue with how we ingest configs? If overriding all fields must be overriden?
I can add defaults to the code thoguh

**Comment by uri200** [comment]
Yes that can be a python config general issue. But i think the problem is pipelined is the only one using nested fields.

```
enforcement:
  poll_interval: 2
```

The other services use a flat config file so probably that is why we don't see it.
