### ISSUE TITLE
AGW error bringing up Baicells 227 enodeb

### ISSUE THREAD

**Issue by jdesai61ilu** [magma/magma#7963]
### Your Environment

- **Version: 1.6.0 - fresh install
- **Affected Component: AGW
- **Affected Subcomponent:** eNodeB service
- **Deployment Environment:** e.g. bare-metal (AGW),  (Aorc8r(AWS)

### Describe the Issue
When I add a Baicells 227 in the NMS and connect the gateway, I am getting following in the AGW log. Note, Since there is no option to choose Baicells 227 in the NMS UI, I have added it as a Baicells 233.

Here is the log
```
magma@magmaagw:~/downloads$ enodebd_cli.py get_all_status
--- eNodeB Serial: xxxx ---
IP Address..................10.0.2.241
eNodeB Connected via TR-069............ON
eNodeB Configured...................ON
Opstate Enabled....................OFF
RF TX on...........................OFF
RF TX desired.......................ON
GPS Connected.......................ON
PTP Connected......................OFF
MME Connected......................OFF
GPS Longitude...............-xx.xx
GPS Latitude.................yy.yy
FSM State...............Error state - awaiting manual restart of enodebd service or an Inform to be received from the eNB


Jul  9 03:14:34 magmaagw enodebd[107401]: ERROR:root:Failed to handle tr069 message
Jul  9 03:14:34 magmaagw enodebd[107401]: ERROR:root:Traceback (most recent call last):
Jul  9 03:14:34 magmaagw enodebd[107401]:   File "/usr/local/lib/python3.8/dist-packages/magma/enodebd/state_machines/enb_acs_impl.py", line 90, in handle_tr069_message
Jul  9 03:14:34 magmaagw enodebd[107401]:     self._read_tr069_msg(message)
Jul  9 03:14:34 magmaagw enodebd[107401]:   File "/usr/local/lib/python3.8/dist-packages/magma/enodebd/state_machines/enb_acs_impl.py", line 148, in _read_tr069_msg
Jul  9 03:14:34 magmaagw enodebd[107401]:     msg_handled, next_state = self.state.read_msg(message)
Jul  9 03:14:34 magmaagw enodebd[107401]:   File "/usr/local/lib/python3.8/dist-packages/magma/enodebd/state_machines/enb_acs_states.py", line 1170, in read_msg
Jul  9 03:14:34 magmaagw enodebd[107401]:     raise Tr069Error(
Jul  9 03:14:34 magmaagw enodebd[107401]: magma.enodebd.exceptions.Tr069Error: Did not receive M Reboot event code in Inform
Jul  9 03:14:34 magmaagw enodebd[107401]: ERROR:root:Device configuration: Param values: {
Jul  9 03:14:34 magmaagw enodebd[107401]:   "MME status": "0",
Jul  9 03:14:34 magmaagw enodebd[107401]:   "REM status": "1",
Jul  9 03:14:34 magmaagw enodebd[107401]:   "SW version": "BaiBS_RTS_3.6.6",
Jul  9 03:14:34 magmaagw enodebd[107401]:   "Serial number": "xxxxxxxxxxxx",
Jul  9 03:14:34 magmaagw enodebd[107401]:   "Admin state": "true",
Jul  9 03:14:34 magmaagw enodebd[107401]:   "Opstate": "false",
Jul  9 03:14:34 magmaagw enodebd[107401]:   "RF TX status": "false",
Jul  9 03:14:34 magmaagw enodebd[107401]:   "GPS lat": "xx.xx",
Jul  9 03:14:34 magmaagw enodebd[107401]:   "GPS long": "-y.yy",
Jul  9 03:14:34 magmaagw enodebd[107401]:   "GPS status": "1",
Jul  9 03:14:34 magmaagw enodebd[107401]:   "PTP status": "0",
Jul  9 03:14:34 magmaagw enodebd[107401]:   "Local gateway enable": "0",
Jul  9 03:14:34 magmaagw enodebd[107401]:   "Duplex mode capability": "TDDMode",
Jul  9 03:14:34 magmaagw enodebd[107401]:   "Band capability": "43",
Jul  9 03:14:34 magmaagw enodebd[107401]:   "EARFCNDL": 44190,
Jul  9 03:14:34 magmaagw enodebd[107401]:   "EARFCNUL": "44490",
Jul  9 03:14:34 magmaagw enodebd[107401]:   "Band": "43",
Jul  9 03:14:34 magmaagw enodebd[107401]:   "PCI": "260",
Jul  9 03:14:34 magmaagw enodebd[107401]:   "DL bandwidth": 20,
Jul  9 03:14:34 magmaagw enodebd[107401]:   "UL bandwidth": 20,
Jul  9 03:14:34 magmaagw enodebd[107401]:   "Subframe assignment": "2",
Jul  9 03:14:34 magmaagw enodebd[107401]:   "Special subframe pattern": "7",
Jul  9 03:14:34 magmaagw enodebd[107401]:   "Cell ID": 1,
Jul  9 03:14:34 magmaagw enodebd[107401]:   "Cell reserved": "false",
Jul  9 03:14:34 magmaagw enodebd[107401]:   "Cell barred": "false",
Jul  9 03:14:34 magmaagw enodebd[107401]:   "MME IP": "\"10.0.2.1\"",
Jul  9 03:14:34 magmaagw enodebd[107401]:   "MME port": "36412",
Jul  9 03:14:34 magmaagw enodebd[107401]:   "Num PLMNs": "1",
Jul  9 03:14:34 magmaagw enodebd[107401]:   "TAC": "1",
Jul  9 03:14:34 magmaagw enodebd[107401]:   "IPSec enable": "false",
Jul  9 03:14:34 magmaagw enodebd[107401]:   "MME pool enable": false,
Jul  9 03:14:34 magmaagw enodebd[107401]:   "Periodic inform enable": "true",
Jul  9 03:14:34 magmaagw enodebd[107401]:   "Periodic inform interval": "5",
Jul  9 03:14:34 magmaagw enodebd[107401]:   "Perf mgmt enable": "true",
Jul  9 03:14:34 magmaagw enodebd[107401]:   "Perf mgmt upload interval": "300",
Jul  9 03:14:34 magmaagw enodebd[107401]:   "Perf mgmt upload URL": "http://10.0.2.1:8081/"
Jul  9 03:14:34 magmaagw enodebd[107401]: },
Jul  9 03:14:34 magmaagw enodebd[107401]:  Object values: {
Jul  9 03:14:34 magmaagw enodebd[107401]:   "PLMN 1": {
Jul  9 03:14:34 magmaagw enodebd[107401]:     "PLMN 1 cell reserved": "false",
Jul  9 03:14:34 magmaagw enodebd[107401]:     "PLMN 1 enable": "true",
Jul  9 03:14:34 magmaagw enodebd[107401]:     "PLMN 1 primary": "true",
Jul  9 03:14:34 magmaagw enodebd[107401]:     "PLMN 1 PLMNID": "00101"
Jul  9 03:14:34 magmaagw enodebd[107401]:   }
Jul  9 03:14:34 magmaagw enodebd[107401]: }
Jul  9 03:14:34 magmaagw enodebd[107401]: ERROR:root:Desired configuration: Param values: {
Jul  9 03:14:34 magmaagw enodebd[107401]:   "Periodic inform enable": true,
Jul  9 03:14:34 magmaagw enodebd[107401]:   "Periodic inform interval": 5,
Jul  9 03:14:34 magmaagw enodebd[107401]:   "EARFCNDL": 44190,
Jul  9 03:14:34 magmaagw enodebd[107401]:   "Band": 43,
Jul  9 03:14:34 magmaagw enodebd[107401]:   "Subframe assignment": 2,
Jul  9 03:14:34 magmaagw enodebd[107401]:   "Special subframe pattern": 7,
Jul  9 03:14:34 magmaagw enodebd[107401]:   "PCI": 260,
Jul  9 03:14:34 magmaagw enodebd[107401]:   "TAC": 1,
Jul  9 03:14:34 magmaagw enodebd[107401]:   "DL bandwidth": 20,
Jul  9 03:14:34 magmaagw enodebd[107401]:   "UL bandwidth": 20,
Jul  9 03:14:34 magmaagw enodebd[107401]:   "Cell ID": 1,
Jul  9 03:14:34 magmaagw enodebd[107401]:   "Perf mgmt enable": true,
Jul  9 03:14:34 magmaagw enodebd[107401]:   "Perf mgmt upload interval": 300,
Jul  9 03:14:34 magmaagw enodebd[107401]:   "Perf mgmt upload URL": "http://10.0.2.1:8081/",
Jul  9 03:14:34 magmaagw enodebd[107401]:   "Local gateway enable": 0,
Jul  9 03:14:34 magmaagw enodebd[107401]:   "IPSec enable": false,
Jul  9 03:14:34 magmaagw enodebd[107401]:   "Cell reserved": false,
Jul  9 03:14:34 magmaagw enodebd[107401]:   "MME pool enable": false,
Jul  9 03:14:34 magmaagw enodebd[107401]:   "MME IP": "10.0.2.1",
Jul  9 03:14:34 magmaagw enodebd[107401]:   "MME port": 36412,
Jul  9 03:14:34 magmaagw enodebd[107401]:   "Admin state": true,
Jul  9 03:14:34 magmaagw enodebd[107401]:   "Cell barred": false
Jul  9 03:14:34 magmaagw enodebd[107401]: },
Jul  9 03:14:34 magmaagw enodebd[107401]:  Object values: {
Jul  9 03:14:34 magmaagw enodebd[107401]:   "PLMN 1": {
Jul  9 03:14:34 magmaagw enodebd[107401]:     "PLMN 1 enable": true,
Jul  9 03:14:34 magmaagw enodebd[107401]:     "PLMN 1 cell reserved": false,
Jul  9 03:14:34 magmaagw enodebd[107401]:     "PLMN 1 primary": true,
Jul  9 03:14:34 magmaagw enodebd[107401]:     "PLMN 1 PLMNID": "00101"
Jul  9 03:14:34 magmaagw enodebd[107401]:   }
Jul  9 03:14:34 magmaagw enodebd[107401]: }

```

**Comment by ekowtaylor** [comment]
@ardzoht , @talkhasib to review

**Comment by talkhasib** [comment]
Would you please share a pcap of the s1 interface during the bring up of this eNB and the enodebd log file under /var/log/enodebd.log

**Comment by jdesai61ilu** [comment]
Please see attached pcap and logs. I have progressed from above error (which was due to incorrect value for EARFCNDL. After correcting that, I am getting another error.

`
2021-07-09 14:32:12,238 DEBUG Sending TR069 message: {'ParameterList': ParameterValueList(ParameterValueStruct=[ParameterValueStruct(Name='Device.Services.FAPService.1.FAPControl.LTE.AdminState', Value=1), ParameterValueStruct(Name='Device.Services.FAPService.1.FAPControl.LTE.Gateway.X_BAICELLS_COM_MmePool.Enable', Value=0)], arrayType='cwmp:ParameterValueStruct[2]')}
2021-07-09 14:32:12,242 DEBUG 10.0.2.241 - "POST /smallcell/AcsService HTTP/1.1" 200 922
2021-07-09 14:32:12,298 DEBUG Handling TR069 message: <class 'magma.enodebd.tr069.models.Fault'>
2021-07-09 14:32:12,298 ERROR Received Fault in response to SetParameterValues, Code (9003), Message (Invalid arguments)
2021-07-09 14:32:12,299 ERROR SetParameterValuesFault Param: Device.Services.FAPService.1.FAPControl.LTE.AdminState, Code: 9007, String: LTE_FAP_ADMIN_STATE:Other: Rem is not ready, now cannot active cell
2021-07-09 14:32:12,299 DEBUG ACS in (Setting parameter values) state. Received a Fault <Invalid arguments>
2021-07-09 14:32:12,299 DEBUG State transition to <unexpected_fault>
2021-07-09 14:32:12,299 DEBUG Sending TR069 message: {}
[baicells227.zip](https://github.com/magma/magma/files/6792395/baicells227.zip)

`

**Comment by jdesai61ilu** [comment]
Sometimes I am also getting the error message listed in my first post above - 
**magma.enodebd.exceptions.Tr069Error: Did not receive M Reboot event code in Inform**
However, I was not capturing packets when this happened. I will try to re-capture and post it.

**Comment by jdesai61ilu** [comment]
Attached is the dump and log file (look at the last reboot) with the error I reported . 

magma.enodebd.exceptions.Tr069Error: Did not receive M Reboot event code in Inform

This happens when I change some settings in NMS (e.g. Cell ID) and then AGW/enodebd/ACS asks the Baicells unit to reboot. Any help or hints n how to properly setup the RF network using 227 unit will be greatly appreciated. Thanks

[baicells227-2.zip](https://github.com/magma/magma/files/6793413/baicells227-2.zip)

**Comment by jdesai61ilu** [comment]
Just checking to see if attached logs were sufficient to diagnose the problem. The enodeb does show up in NMS as 
Health: 'Good' and MME Connected: 'Connected'. However, the **enodebd_cli.py get_all_status** returns following and restarting enodeb or rebooting gateway doesn't help.
```

magma@magmaagw:~$ enodebd_cli.py get_all_status

--- eNodeB Serial: 1202000107204NT0288 ---
IP Address..................10.0.2.241
eNodeB Connected via TR-069............ON
eNodeB Configured..................OFF
Opstate Enabled.....................ON
RF TX on............................ON
RF TX desired.......................ON
GPS Connected......................OFF
PTP Connected......................OFF
MME Connected.......................ON
GPS Longitude...............-84.179383
GPS Latitude.................33.999697
FSM State...............Error state - awaiting manual restart of enodebd service or an Inform to be received from the eNB

```

**Comment by talkhasib** [comment]
@jdesai61ilu thanks for providing the logs. Its going to take some time before I look into this.
In the meantime, you can use the eNB in "Unmanaged" mode with manual configuration of the unit.

**Comment by jdesai61ilu** [comment]
Just checking to see if there are any plans to support this.  Also, any hints/links on how to setup proper MME and other key configuration values manually? Thanks
