### ISSUE TITLE
Default LTE gateway EPC configuration values are invalid

### ISSUE THREAD

**Issue by xjtian** [magma/magma#800]
The default EPC configuration is NAT disabled and 192.168.0.1/24 as the IP block, but the IP block causes pipelined to crash on the gateway with

```
Oct 30 17:06:49 magma pipelined[2137]: Traceback (most recent call last):
Oct 30 17:06:49 magma pipelined[2137]:   File "/usr/lib/python3.5/runpy.py", line 193, in _run_module_as_main
Oct 30 17:06:49 magma pipelined[2137]:     "__main__", mod_spec)
Oct 30 17:06:49 magma pipelined[2137]:   File "/usr/lib/python3.5/runpy.py", line 85, in _run_code
Oct 30 17:06:49 magma pipelined[2137]:     exec(code, run_globals)
Oct 30 17:06:49 magma pipelined[2137]:   File "/usr/local/lib/python3.5/dist-packages/magma/pipelined/main.py", line 92, in <module>
Oct 30 17:06:49 magma pipelined[2137]:     main()
Oct 30 17:06:49 magma pipelined[2137]:   File "/usr/local/lib/python3.5/dist-packages/magma/pipelined/main.py", line 52, in main
Oct 30 17:06:49 magma pipelined[2137]:     service_manager.load()
Oct 30 17:06:49 magma pipelined[2137]:   File "/usr/local/lib/python3.5/dist-packages/magma/pipelined/service_manager.py", line 330, in load
Oct 30 17:06:49 magma pipelined[2137]:     for app in manager.instantiate_apps(**contexts):
Oct 30 17:06:49 magma pipelined[2137]:   File "/usr/local/lib/python3.5/dist-packages/ryu/base/app_manager.py", line 509, in instantiate_apps
Oct 30 17:06:49 magma pipelined[2137]:     self._instantiate(app_name, cls, *args, **kwargs)
Oct 30 17:06:49 magma pipelined[2137]:   File "/usr/local/lib/python3.5/dist-packages/ryu/base/app_manager.py", line 495, in _instantiate
Oct 30 17:06:49 magma pipelined[2137]:     app = cls(*args, **kwargs)
Oct 30 17:06:49 magma pipelined[2137]:   File "/usr/local/lib/python3.5/dist-packages/magma/pipelined/app/arp.py", line 56, in __init__
Oct 30 17:06:49 magma pipelined[2137]:     self.config = self._get_config(kwargs['config'], kwargs['mconfig'])
Oct 30 17:06:49 magma pipelined[2137]:   File "/usr/local/lib/python3.5/dist-packages/magma/pipelined/app/arp.py", line 67, in _get_config
Oct 30 17:06:49 magma pipelined[2137]:     ue_ip_blocks=[cidr_to_ip_netmask_tuple(mconfig.ue_ip_block)],
Oct 30 17:06:49 magma pipelined[2137]:   File "/usr/local/lib/python3.5/dist-packages/magma/common/misc_utils.py", line 195, in cidr_to_ip_netmask_tuple
Oct 30 17:06:49 magma pipelined[2137]:     network = ipaddress.ip_network(cidr_network)
Oct 30 17:06:49 magma pipelined[2137]:   File "/usr/lib/python3.5/ipaddress.py", line 74, in ip_network
Oct 30 17:06:49 magma pipelined[2137]:     return IPv4Network(address, strict)
Oct 30 17:06:49 magma pipelined[2137]:   File "/usr/lib/python3.5/ipaddress.py", line 1536, in __init__
Oct 30 17:06:49 magma pipelined[2137]:     raise ValueError('%s has host bits set' % self)
Oct 30 17:06:49 magma pipelined[2137]: ValueError: 192.168.0.1/24 has host bits set
```

Changing the configuration to 192.168.0.0/24 resolves the issue.

**Comment by xjtian** [comment]
Verified fixed on release branch
