### ISSUE TITLE
[AGW] Error in state_cli.py parse KEY in Ubuntu AGW

### ISSUE THREAD

**Issue by emersonacuna** [magma/magma#8301]
### Your Environment

- **Version:** 1.6 
- **Affected Component:** Access Gateway Ubuntu
- **Affected Subcomponent:** AGW service
- **Deployment Environment:** local docker-compose (orc8r), AGW Ubuntu in OpenStack, Federated LTE Network, FeGW and Federation Network

### Describe the Issue
When I try to parse the KEY `IMSI716770120033398:MME` with `state_cli.py`, it shows an error : `Error: 'utf-8' codec can't decode byte 0xf5 in position 5: 'utf-8' codec can't decode byte 0xf5 in position 5: invalid start byte in field: magma.lmsisdn`. 

It looks like it trying to decode the MSISDN and not the IMSI. 

````
magma@agw-magma-backup:~$ redis-cli -p 6380
127.0.0.1:6380> KEYS *
 1) "sctpd:systemd_status"
 2) "NO_VLAN:mobilityd_gw_info"
 3) "IMSI716770120033398.bafi.amt.pe,ipv4:mobilityd_ipdesc_record"
 4) "directoryd:systemd_status"
 5) "R_BAFI_FREE:pipelined:rule_ids"
 6) "mme:systemd_status"
 7) "pipelined:rule_names"
 8) "spgw_state"
 9) "mobilityd:assigned_ip_blocks"
10) "mme_nas_state"
11) "sessiond:systemd_status"
12) "IMSI716770120033398:directory_record"
13) "IMSI716770120033398:MME"
14) "pipelined:tunnel_map"
15) "internal_default_drop_flow_rule:pipelined:rule_ids"
16) "ctraced:systemd_status"
17) "state:systemd_status"
18) "sessiond:sessions"
19) "policydb:rules"
20) "mobilityd:ip_states:IPState.FREE"
21) "eventd:systemd_status"
22) "envoy_controller:systemd_status"
23) "block_private_entel_ips:pipelined:rule_ids"
24) "subscriberdb:systemd_status"
25) "policydb:systemd_status"
26) "IMSI716770120033398:SPGW"
27) "s1ap_state"
28) "magmad:systemd_status"
29) "pipelined:systemd_status"
30) "mobilityd:ip_states:IPState.RESERVED"
31) "QosManager"
32) "mobilityd:systemd_status"
33) "s1ap_imsi_map"
34) "mobilityd:ip_states:IPState.ALLOCATED"
35) "enodebd:systemd_status"
127.0.0.1:6380> exit
magma@agw-magma-backup:~$ state_cli.py parse IMSI716770120033398:MME
Error: 'utf-8' codec can't decode byte 0xf5 in position 5: 'utf-8' codec can't decode byte 0xf5 in position 5: invalid start byte in field: magma.lte.oai.UeContext.msisdn

````

**Expected behavior**
Get the output of the given KEY

**Comment by ardzoht** [comment]
@emersonacuna @joary was this resolved on the updated magma package?

**Comment by emersonacuna** [comment]
No update yet. Please @joary can you give us more details about the update? Thanks.

**Comment by joary** [comment]
@emersonacuna, the proposed procedure is to update both magma and magma-sctpd packages, from your package versions it is possible to see it is upgradable to a version that already includes this fix:

```
magma-sctpd/now 1.7.0-1625779552-d6169104 amd64 [installed,upgradable to: 1.7.0-1627422458-d1cde5a0]
magma/now 1.7.0-1625779552-d6169104 amd64 [installed,upgradable to: 1.7.0-1627422458-d1cde5a0]
```

You can them upgrade using

```
apt upgrade magma magma-sctpd
```

**Comment by emersonacuna** [comment]
hi @joary this is our upgradable version that we have. Can you confirm if still we should do the upgrade of the packages?
```
magma-sctpd/now 1.7.0-1625779552-d6169104 amd64 [installed,upgradable to: 1.7.0-1628560576-0f98f5fe]
magma/now 1.7.0-1625779552-d6169104 amd64 [installed,upgradable to: 1.7.0-1628560576-0f98f5fe]
```

**Comment by joary** [comment]
Yes @emersonacuna , I believe any later release would include the fix we're aiming for. @ardzoht can correct me if I'm wrong.

**Comment by emersonacuna** [comment]
hi @joary . I just did the upgrade using this: `apt upgrade magma magma-sctpd`. These are the current version of packages:

```
magma-cpp-redis/now 4.3.1.1-2 amd64 [installed,local]
magma-libfluid/now 0.1.0.6-1 amd64 [installed,local]
magma-libtacopie/now 3.2.0.1-1 amd64 [installed,local]
magma-sctpd/focal-ci,now 1.7.0-1629188480-d0b4cdcc amd64 [installed]
magma/focal-ci,now 1.7.0-1629188480-d0b4cdcc amd64 [installed]
```

But now the `pipelined `and `mme` services are failing. These are the logs for the **pipelined**, looks like it is a OVS issue. Can you help me to check, please?
```
magma@agw-magma-backup:~$ sudo journalctl -fu magma@pipelined
-- Logs begin at Tue 2021-08-17 15:18:46 -05. --
Aug 17 17:16:31 agw-magma-backup pipelined[3502769]: INFO:InOutController:Received Setup request with epoch - 1629238590, current epoch  is - 1629238590
Aug 17 17:16:31 agw-magma-backup pipelined[3502769]: WARNING:GYController:Datapath not initilized, setup failed
Aug 17 17:16:31 agw-magma-backup pipelined[3502769]: WARNING:InOutController:Datapath not initilized, setup failed
Aug 17 17:16:34 agw-magma-backup pipelined[3502769]: INFO:EnforcementStatsController:Sending RPC payload: RuleRecordTable{
Aug 17 17:16:34 agw-magma-backup pipelined[3502769]: epoch: 1629238590
Aug 17 17:16:34 agw-magma-backup pipelined[3502769]: }
Aug 17 17:16:35 agw-magma-backup systemd[1]: Stopping Magma pipelined service...
Aug 17 17:16:35 agw-magma-backup pipelined[3502769]: INFO:root:Stopping pipelined with reason SIGTERM...
Aug 17 17:16:36 agw-magma-backup systemd[1]: magma@pipelined.service: Succeeded.
Aug 17 17:16:36 agw-magma-backup systemd[1]: Stopped Magma pipelined service.
Aug 17 17:16:38 agw-magma-backup systemd[1]: Starting Magma pipelined service...
Aug 17 17:16:38 agw-magma-backup ovs-vsctl[3504091]: ovs|00001|vsctl|INFO|Called as /usr/bin/ovs-vsctl --all destroy Flow_Sample_Collector_Set
Aug 17 17:16:38 agw-magma-backup ovs-vsctl[3504097]: ovs|00001|vsctl|INFO|Called as /usr/bin/ovs-vsctl set bridge gtp_br0 protocols=OpenFlow10,OpenFlow13,OpenFlow14 other-config:disable-in-band=true
Aug 17 17:16:38 agw-magma-backup ovs-vsctl[3504098]: ovs|00001|vsctl|INFO|Called as /usr/bin/ovs-vsctl set-controller gtp_br0 tcp:127.0.0.1:6633 tcp:127.0.0.1:6654
Aug 17 17:16:38 agw-magma-backup ovs-vsctl[3504107]: ovs|00001|vsctl|INFO|Called as /usr/bin/ovs-vsctl set-fail-mode gtp_br0 secure
Aug 17 17:16:38 agw-magma-backup sudo[3504110]:     root : TTY=unknown ; PWD=/ ; USER=root ; COMMAND=/usr/bin/ovsdb-client dump Controller _uuid
Aug 17 17:16:38 agw-magma-backup sudo[3504110]: pam_unix(sudo:session): session opened for user root by (uid=0)
Aug 17 17:16:38 agw-magma-backup sudo[3504110]: pam_unix(sudo:session): session closed for user root
Aug 17 17:16:38 agw-magma-backup sudo[3504116]:     root : TTY=unknown ; PWD=/ ; USER=root ; COMMAND=/usr/bin/ovs-vsctl set Controller 252dff90-2745-4531-890a-62efa7f9ce45 inactivity_probe=300
Aug 17 17:16:38 agw-magma-backup sudo[3504116]: pam_unix(sudo:session): session opened for user root by (uid=0)
Aug 17 17:16:38 agw-magma-backup ovs-vsctl[3504117]: ovs|00001|vsctl|INFO|Called as /usr/bin/ovs-vsctl set Controller 252dff90-2745-4531-890a-62efa7f9ce45 inactivity_probe=300
Aug 17 17:16:38 agw-magma-backup sudo[3504116]: pam_unix(sudo:session): session closed for user root
Aug 17 17:16:38 agw-magma-backup sudo[3504118]:     root : TTY=unknown ; PWD=/ ; USER=root ; COMMAND=/usr/bin/ovs-vsctl set Controller 4578d866-7055-4039-85aa-71b02eb8d837 inactivity_probe=300
Aug 17 17:16:38 agw-magma-backup sudo[3504118]: pam_unix(sudo:session): session opened for user root by (uid=0)
Aug 17 17:16:38 agw-magma-backup ovs-vsctl[3504121]: ovs|00001|vsctl|INFO|Called as /usr/bin/ovs-vsctl set Controller 4578d866-7055-4039-85aa-71b02eb8d837 inactivity_probe=300
Aug 17 17:16:38 agw-magma-backup sudo[3504118]: pam_unix(sudo:session): session closed for user root
Aug 17 17:16:38 agw-magma-backup ovs-vsctl[3504123]: ovs|00001|vsctl|INFO|Called as /usr/bin/ovs-vsctl set-manager ptcp:6640
Aug 17 17:16:38 agw-magma-backup systemd[1]: Started Magma pipelined service.
Aug 17 17:16:40 agw-magma-backup pipelined[3504125]: INFO:root:Nat: False
Aug 17 17:16:40 agw-magma-backup pipelined[3504125]: INFO:root:DP Tuning not enabled.
Aug 17 17:16:40 agw-magma-backup pipelined[3504125]: INFO:root:added uplink bridge controller
Aug 17 17:16:40 agw-magma-backup pipelined[3504125]: INFO:ryu.base.app_manager:loading app magma.pipelined.app.inout
Aug 17 17:16:40 agw-magma-backup pipelined[3504125]: INFO:ryu.base.app_manager:loading app magma.pipelined.app.startup_flows
Aug 17 17:16:40 agw-magma-backup pipelined[3504125]: INFO:ryu.base.app_manager:loading app magma.pipelined.app.uplink_bridge
Aug 17 17:16:40 agw-magma-backup pipelined[3504125]: INFO:ryu.base.app_manager:loading app magma.pipelined.app.arp
Aug 17 17:16:40 agw-magma-backup pipelined[3504125]: INFO:ryu.base.app_manager:loading app magma.pipelined.app.access_control
Aug 17 17:16:40 agw-magma-backup pipelined[3504125]: INFO:ryu.base.app_manager:loading app magma.pipelined.app.he
Aug 17 17:16:40 agw-magma-backup pipelined[3504125]: INFO:ryu.base.app_manager:loading app magma.pipelined.app.gy
Aug 17 17:16:40 agw-magma-backup pipelined[3504125]: INFO:ryu.base.app_manager:loading app magma.pipelined.app.enforcement
Aug 17 17:16:40 agw-magma-backup pipelined[3504125]: INFO:ryu.base.app_manager:loading app magma.pipelined.app.enforcement_stats
Aug 17 17:16:40 agw-magma-backup pipelined[3504125]: INFO:ryu.base.app_manager:loading app ryu.controller.ofp_handler
Aug 17 17:16:40 agw-magma-backup pipelined[3504125]: INFO:ryu.base.app_manager:loading app ryu.app.ofctl.service
Aug 17 17:16:40 agw-magma-backup pipelined[3504125]: INFO:ryu.base.app_manager:loading app ryu.controller.ofp_handler
Aug 17 17:16:40 agw-magma-backup pipelined[3504125]: INFO:ryu.base.app_manager:instantiating app None of DPSet
Aug 17 17:16:40 agw-magma-backup pipelined[3504125]: INFO:ryu.base.app_manager:creating context dpset
Aug 17 17:16:40 agw-magma-backup pipelined[3504125]: INFO:ryu.base.app_manager:instantiating app magma.pipelined.app.inout of InOutController
Aug 17 17:16:40 agw-magma-backup pipelined[3504125]: INFO:ryu.base.app_manager:instantiating app magma.pipelined.app.startup_flows of StartupFlows
Aug 17 17:16:40 agw-magma-backup pipelined[3504125]: INFO:ryu.base.app_manager:instantiating app magma.pipelined.app.uplink_bridge of UplinkBridgeController
Aug 17 17:16:40 agw-magma-backup pipelined[3504125]: INFO:UplinkBridgeController:uplink bridge app config: UplinkBridgeConfig(uplink_bridge='uplink_br0', uplink_eth_port_name='eth1.1506', uplink_patch='patch-agw', enable_nat=False, virtual_mac='3c:78:43:c5:1f:80', dhcp_port='dhcp0', sgi_management_iface_vlan='', sgi_management_iface_ip_addr='10.68.140.135/27', dev_vlan_in='vlan_pop_in', dev_vlan_out='vlan_pop_out', ovs_vlan_workaround=True, sgi_management_iface_gw='10.68.140.129')
Aug 17 17:16:40 agw-magma-backup pipelined[3504125]: INFO:ryu.base.app_manager:instantiating app magma.pipelined.app.arp of ArpController
Aug 17 17:16:40 agw-magma-backup pipelined[3504125]: INFO:ryu.base.app_manager:instantiating app magma.pipelined.app.access_control of AccessControlController
Aug 17 17:16:40 agw-magma-backup pipelined[3504125]: INFO:ryu.base.app_manager:instantiating app magma.pipelined.app.he of HeaderEnrichmentController
Aug 17 17:16:40 agw-magma-backup pipelined[3504125]: INFO:HeaderEnrichmentController:Header Enrichment app config: heConfig(he_proxy_port=1, he_enabled=False, encryption_enabled=False, encryption_algorithm=None, encryption_key=None, hash_function=None, encoding_type=None, uplink_port=2, gtp_port=32768)
Aug 17 17:16:40 agw-magma-backup pipelined[3504125]: INFO:ryu.base.app_manager:instantiating app magma.pipelined.app.gy of GYController
Aug 17 17:16:40 agw-magma-backup pipelined[3504125]: INFO:ryu.base.app_manager:instantiating app magma.pipelined.app.enforcement of EnforcementController
Aug 17 17:16:40 agw-magma-backup pipelined[3504125]: INFO:ryu.base.app_manager:instantiating app magma.pipelined.app.enforcement_stats of EnforcementStatsController
Aug 17 17:16:40 agw-magma-backup pipelined[3504125]: INFO:EnforcementStatsController:Stored ovs_pid 5196, new ovs pid 5196
Aug 17 17:16:40 agw-magma-backup pipelined[3504125]: INFO:ryu.base.app_manager:instantiating app ryu.controller.ofp_handler of OFPHandler
Aug 17 17:16:40 agw-magma-backup pipelined[3504125]: INFO:ryu.base.app_manager:instantiating app ryu.app.ofctl.service of OfctlService
Aug 17 17:16:40 agw-magma-backup pipelined[3504125]: INFO:root:Running GTP stats collector...
Aug 17 17:16:40 agw-magma-backup pipelined[3504125]: INFO:root:Starting pipelined...
Aug 17 17:16:40 agw-magma-backup pipelined[3504125]: INFO:root:Listening on address 127.0.0.1:50063
Aug 17 17:16:40 agw-magma-backup pipelined[3504125]: INFO:EnforcementStatsController:Sending RPC payload: RuleRecordTable{
Aug 17 17:16:40 agw-magma-backup pipelined[3504125]: epoch: 1629238599
Aug 17 17:16:40 agw-magma-backup pipelined[3504125]: }
Aug 17 17:16:40 agw-magma-backup pipelined[3504125]: INFO:root:Got RPC payload:
Aug 17 17:16:40 agw-magma-backup pipelined[3504125]:   SetupPolicyRequest {
Aug 17 17:16:40 agw-magma-backup pipelined[3504125]:     epoch: 1629238599
Aug 17 17:16:40 agw-magma-backup pipelined[3504125]:   }
Aug 17 17:16:40 agw-magma-backup pipelined[3504125]: INFO:root:Got RPC payload:
Aug 17 17:16:40 agw-magma-backup pipelined[3504125]:   SetupDefaultRequest {
Aug 17 17:16:40 agw-magma-backup pipelined[3504125]:     epoch: 1629238599
Aug 17 17:16:40 agw-magma-backup pipelined[3504125]:   }
Aug 17 17:16:40 agw-magma-backup pipelined[3504125]: INFO:GYController:Received Setup request with epoch - 1629238599, current epoch  is - 1629238599
Aug 17 17:16:40 agw-magma-backup pipelined[3504125]: INFO:InOutController:Received Setup request with epoch - 1629238599, current epoch  is - 1629238599
Aug 17 17:16:40 agw-magma-backup pipelined[3504125]: WARNING:GYController:Datapath not initilized, setup failed
Aug 17 17:16:40 agw-magma-backup pipelined[3504125]: WARNING:InOutController:Datapath not initilized, setup failed
Aug 17 17:16:43 agw-magma-backup pipelined[3504125]: INFO:EnforcementStatsController:Sending RPC payload: RuleRecordTable{
Aug 17 17:16:43 agw-magma-backup pipelined[3504125]: epoch: 1629238599
Aug 17 17:16:43 agw-magma-backup pipelined[3504125]: }
Aug 17 17:16:44 agw-magma-backup systemd[1]: Stopping Magma pipelined service...
Aug 17 17:16:44 agw-magma-backup pipelined[3504125]: INFO:root:Stopping pipelined with reason SIGTERM...
Aug 17 17:16:45 agw-magma-backup systemd[1]: magma@pipelined.service: Succeeded.
Aug 17 17:16:45 agw-magma-backup systemd[1]: Stopped Magma pipelined service.
Aug 17 17:16:47 agw-magma-backup systemd[1]: Starting Magma pipelined service...
```

And this is the current version of OVS:
```
magma@agw-magma-backup:~$ apt policy openvswitch-switch
openvswitch-switch:
  Installed: 2.14.3-13
  Candidate: 2.14.3-13
  Version table:
 *** 2.14.3-13 500
        500 https://artifactory.magmacore.org/artifactory/debian-test focal-ci/main amd64 Packages
        100 /var/lib/dpkg/status
     2.14.3-12 500
        500 https://artifactory.magmacore.org/artifactory/debian-test focal-ci/main amd64 Packages
     2.14.3-8 500
        500 https://artifactory.magmacore.org/artifactory/debian-test focal-ci/main amd64 Packages
     2.14.3-7 500
        500 https://artifactory.magmacore.org/artifactory/debian-test focal-ci/main amd64 Packages
     2.13.3-0ubuntu0.20.04.1 500
        500 http://archive.ubuntu.com/ubuntu focal-updates/main amd64 Packages
     2.13.1-0ubuntu0.20.04.4 500
        500 http://security.ubuntu.com/ubuntu focal-security/main amd64 Packages
     2.13.0-0ubuntu1 500
        500 http://archive.ubuntu.com/ubuntu focal/main amd64 Packages
```

**Comment by joary** [comment]
More triaging on the issue seen after the upgrade:

Looking at syslogs we can see mme restarting because:

```
Aug 18 08:58:29 localhost systemd[1]: Started Magma pipelined service.
Aug 18 08:58:29 localhost systemd[1]: Starting Magma OAI MME service...
Aug 18 08:58:30 localhost mme[3914490]: Traceback (most recent call last):
Aug 18 08:58:30 localhost mme[3914490]:   File "/usr/local/bin/generate_oai_config.py", line 348, in <module>
Aug 18 08:58:30 localhost mme[3914490]:     main()
Aug 18 08:58:30 localhost mme[3914490]:   File "/usr/local/bin/generate_oai_config.py", line 333, in main
Aug 18 08:58:30 localhost mme[3914490]:     context = _get_context()
Aug 18 08:58:30 localhost mme[3914490]:   File "/usr/local/bin/generate_oai_config.py", line 289, in _get_context
Aug 18 08:58:30 localhost mme[3914490]:     "service_area_map": _get_service_area_maps(mme_service_config),
Aug 18 08:58:30 localhost mme[3914490]:   File "/usr/local/bin/generate_oai_config.py", line 209, in _get_service_area_maps
Aug 18 08:58:30 localhost mme[3914490]:     service_area_map.append({'sac': sac, 'tac': sam.tac.copy()})
Aug 18 08:58:30 localhost mme[3914490]: AttributeError: 'RepeatedScalarFieldContainer' object has no attribute 'copy'
Aug 18 08:58:30 localhost systemd[1]: magma@mme.service: Control process exited, code=exited, status=1/FAILURE
Aug 18 08:58:30 localhost mme[3914497]: ERROR:root:Error parsing service exit status: None
```

Looking at gateway.mconfig, it is possible to see the serviceAreaMaps configured as expected:

```
"serviceAreaMaps":{"257":{"tac":[4015,3523]}},"federatedModeMap":{}},
```

I believe we can solve it by converting [sam.tac](https://github.com/magma/magma/blob/375a1a1987bb7e85cc262d0a9620b9a98ae5b04a/lte/gateway/python/scripts/generate_oai_config.py#L209) to list before copying it, wdyt @ardzoht

**Comment by joary** [comment]
@ardzoht we validated the issue in partner AGW, and to unblocked them I applied a hotfix directly to generate_oai_config.py
, also created a PR (https://github.com/magma/magma/pull/8672) with the hotfix.

**Comment by ardzoht** [comment]
@joary the `AttributeError` that is causing MME to restart is different from the `state_cli` parsing issue right? Should we open a different issue to track this?

**Comment by joary** [comment]
> the AttributeError that is causing MME to restart is different from the state_cli parsing issue right? 

Yes, they're different.

> Should we open a different issue to track this?

Sure let me do that

**Comment by emersonacuna** [comment]
Now we can parse correctly the key MME:

```
magma@agw-magma-backup:~$ state_cli.py parse IMSI716770120257790:MME
msisdn: "\025)\0038i\366"
rel_cause: 3
mm_state: 1
ecm_state: 1
emm_context {
  imsi64: 716770120257790
  imsi {
    value: "qgp\022\002Wy\017"
    num_digits: 15
  }
  imei {
    value: "\000\000\000\000\000\000\000\000"
  }
  imeisv {
    value: "\206\220\220\003\004G\022\000\000"
  }
  emm_cause: 255
  emm_fsm_state: 2
  esm_ctx {
    n_active_ebrs: 1
    esm_proc_data {
      pti: 1
      request_type: 1
      apn: "bafi.amt.pe"
      pdn_type: 1
      bearer_qos {
        pci: 1
        pl: 1
        pvi: 1
        qci: 9
        gbr {
        }
        mbr {
        }
      }
      pco {
        num_protocol_or_container_id: 3
        proto_or_container_id {
          id: 32801
          length: 16
          contents: "\001\001\000\020\201\006\000\000\000\000\203\006\000\000\000\000"
        }
        proto_or_container_id {
          id: 10
        }
        proto_or_container_id {
          id: 13
        }
      }
    }
  }
  member_present_mask: 67116533
  member_valid_mask: 67116405
  vector {
    kasme: "\342\204\315\340\006m~]Rd\0015\254\033\037g\337\036>\264\353\021\210\224\366\226E\357\177(gz"
    rand: "\311\366\207\361\264\235\027\rCnZ0Uj\234\207"
    autn: "\366w\271\004:U\362LX\255\252Y\016\021?\370"
    xres: "\266(\340\361\313\264\276\021"
  }
  security {
    sc_type: 2
    knas_enc: "#\321oa\370\031\316\215\237\242\030#\212\262]S"
    knas_int: "\001K\204B\207\206\264e\007\335\310\346x\312\250\305"
    dl_count {
      seq_num: 4
    }
    ul_count {
      overflow: 3
      seq_num: 166
    }
    kenb_ul_count {
      overflow: 3
      seq_num: 166
    }
    selected_algos {
      integrity: 2
    }
    direction_encode: 1
    next_hop: "\255\027[s\246\206\242p\2045LzSj\223)\333*\212\207Bn\027\205\272\275\233F\342\252;\227"
    next_hop_chaining_count: 1
  }
  _non_current_security {
    eksi: 7
    knas_enc: "\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000"
    knas_int: "\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000"
    dl_count {
    }
    ul_count {
    }
    kenb_ul_count {
    }
    selected_algos {
    }
    next_hop: "\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000"
  }
  is_dynamic: true
  is_attached: true
  is_guti_based_attach: true
  num_attach_request: 1
  guti {
    plmn: "71677?"
    mme_gid: 32777
    mme_code: 120
    m_tmsi: 287197170
  }
  old_guti {
    plmn: "000000"
    m_tmsi: 4294967295
  }
  tai_list {
    numberoflists: 1
    partial_tai_lists {
      number_of_elements: 1
      plmn: "71677?"
      tac: 3523
      tac: 4015
      tac: 0
      tac: 0
      tac: 0
      tac: 0
      tac: 0
      tac: 0
      tac: 0
      tac: 0
      tac: 0
      tac: 0
      tac: 0
      tac: 0
      tac: 0
      tac: 0
    }
  }
  lvr_tai {
    mcc_mnc: "71677?"
    tac: 4015
  }
  originating_tai {
    mcc_mnc: "71677?"
    tac: 4015
  }
  ue_network_capability {
    eea: 240
    eia: 240
    uea: 192
    ucs2: 1
    uia: 64
    umts_present: true
    length: 5
  }
  ue_additional_security_capability {
  }
}
sctp_assoc_id_key: 5
enb_ue_s1ap_id: 1474029
enb_s1ap_id_key: 1065539239405
mme_ue_s1ap_id: 11
e_utran_cgi {
  plmn: "71617?"
  enb_id: 63511
  cell_id: 1
}
lai: "\000\000\000\000\000"
apn_config {
  context_identifier: 15
  all_apn_conf_ind: 1
  apn_configs {
    context_identifier: 15
    service_selection: "bafi.amt.pe"
    subscribed_qos {
      qci: 9
      priority_level: 1
      pre_emption_vulnerability: 1
      pre_emption_capability: 1
    }
    ambr {
      br_ul: 10000000
      br_dl: 10000000
    }
  }
}
access_restriction_data: 32
mme_teid_s11: 11
subscribed_ue_ambr {
  br_ul: 200000000
  br_dl: 200000000
}
used_ue_ambr {
}
used_ambr {
}
nb_active_pdn_contexts: 1
pdn_contexts {
  context_identifier: 15
  apn_subscribed: "bafi.amt.pe"
  paa: "\n\370\021\020"
  p_gw_address_s5_s8_cp: "\000\000\000\000"
  default_bearer_qos_profile {
    qci: 9
    priority_level: 1
    pre_emption_vulnerability: 1
    pre_emption_capability: 1
  }
  subscribed_apn_ambr {
    br_ul: 10000000
    br_dl: 10000000
  }
  p_gw_apn_ambr {
  }
  default_ebi: 5
  bearer_contexts: 0
  bearer_contexts: 4294967295
  bearer_contexts: 4294967295
  bearer_contexts: 4294967295
  bearer_contexts: 4294967295
  bearer_contexts: 4294967295
  bearer_contexts: 4294967295
  bearer_contexts: 4294967295
  bearer_contexts: 4294967295
  bearer_contexts: 4294967295
  bearer_contexts: 4294967295
  s_gw_address_s11_s4: "\000\000\000\000"
  s_gw_teid_s11_s4: 1178257964
  esm_data {
    pti: 1
    n_bearers: 1
  }
  is_active: true
  pco {
    num_protocol_or_container_id: 3
    proto_or_container_id {
      id: 32801
      length: 16
      contents: "\001\001\000\020\201\006\000\000\000\000\203\006\000\000\000\000"
    }
    proto_or_container_id {
      id: 10
    }
    proto_or_container_id {
      id: 13
    }
  }
}
bearer_contexts {
  ebi: 5
  transaction_identifier: 1
  s_gw_fteid_s1u {
    ipv4_address: 3347596298
    interface_type: 1
    teid: 9
  }
  p_gw_fteid_s5_s8_up {
  }
  qci: 9
  esm_ebr_context {
    status: 1
  }
  enb_fteid_s1u {
  }
  priority_level: 1
  preemption_vulnerability: 1
  preemption_capability: 1
  validity: VALID
}
bearer_contexts {
}
bearer_contexts {
}
bearer_contexts {
}
bearer_contexts {
}
bearer_contexts {
}
bearer_contexts {
}
bearer_contexts {
}
bearer_contexts {
}
bearer_contexts {
}
bearer_contexts {
}
ue_radio_capability: "\001\302\001\003\\\333\340\020\000\300\000\277\006\354A\000\024\001\205\310\000\000\000\002\254\004\001d\004\000\334@\000a\200\002\010\000\025\003\000\000\017\"\201\200\000\001\037\374\000\000\000\031\212\000\301\200"
send_ue_purge_request: true
ppf: true
subscription_known: true
sgs_context {
}
mobile_reachability_timer {
  id: 18446744073709551615
  sec: 3480
}
implicit_detach_timer {
  id: 18446744073709551615
  sec: 3480
}
initial_context_setup_rsp_timer {
  id: 18446744073709551615
  sec: 4
}
ue_context_modification_timer {
  id: 18446744073709551615
  sec: 2
}
paging_response_timer {
  id: 18446744073709551615
  sec: 4
}
rau_tau_timer: 10
ulr_response_timer {
  id: 18446744073709551615
  sec: 3
}
time_mobile_reachability_timer_started {
  seconds: 1629380659
}
time_implicit_detach_timer_started {
}
time_paging_response_timer_started {
}
time_ics_rsp_timer_started {
}

==================
State version: 2888
```
