### ISSUE TITLE
[agw] monitord service causes high memory usage

### ISSUE THREAD

**Issue by ardzoht** [magma/magma#8309]
### Your Environment

- **Version:** 1.5, 1.6
- **Affected Component:** Access Gateway
- **Affected Subcomponent:** monitord 
- **Deployment Environment:** e.g.  bare-metal (AGW)

### Describe the Issue

- monitord service ends up reaching memory limits of service (300MB) 
- `Too many open files` OSError is thrown on service logs

```
Jul 23 05:26:05 agwbrisa30 monitord[118102]:   File "/usr/lib/python3.8/asyncio/base_subprocess.py", line 36, in __init__
Jul 23 05:26:05 agwbrisa30 monitord[118102]:     self._start(args=args, shell=shell, stdin=stdin, stdout=stdout,
Jul 23 05:26:05 agwbrisa30 monitord[118102]:   File "/usr/lib/python3.8/asyncio/unix_events.py", line 789, in _start
Jul 23 05:26:05 agwbrisa30 monitord[118102]:     self._proc = subprocess.Popen(
Jul 23 05:26:05 agwbrisa30 monitord[118102]:   File "/usr/lib/python3.8/subprocess.py", line 858, in __init__
Jul 23 05:26:05 agwbrisa30 monitord[118102]:     self._execute_child(args, executable, preexec_fn, close_fds,
Jul 23 05:26:05 agwbrisa30 monitord[118102]:   File "/usr/lib/python3.8/subprocess.py", line 1605, in _execute_child
Jul 23 05:26:05 agwbrisa30 monitord[118102]:     errpipe_read, errpipe_write = os.pipe()
Jul 23 05:26:05 agwbrisa30 monitord[118102]: OSError: [Errno 24] Too many open files
Jul 23 05:26:56 agwbrisa30 magmad[117928]: ERROR:root:GetServiceInfo Error for monitord! [StatusCode.DEADLINE_EXCEEDED] Deadline Exceeded
Jul 23 05:27:00 agwbrisa30 monitord[118102]: ERROR:grpc._server:Exception calling application: 'list' object is not callable
Jul 23 05:27:00 agwbrisa30 monitord[118102]: Traceback (most recent call last):
Jul 23 05:27:00 agwbrisa30 monitord[118102]:   File "/usr/local/lib/python3.8/dist-packages/grpc/_server.py", line 435, in _call_behavior
Jul 23 05:27:00 agwbrisa30 monitord[118102]:     response_or_iterator = behavior(argument, context)
Jul 23 05:27:00 agwbrisa30 monitord[118102]:   File "/usr/local/lib/python3.8/dist-packages/magma/common/service.py", line 402, in GetOperationalStates
Jul 23 05:27:00 agwbrisa30 monitord[118102]:     states = self._get_operational_states_cb()
Jul 23 05:27:00 agwbrisa30 monitord[118102]: TypeError: 'list' object is not callable
```

**To Reproduce**
- activated monitord service
- attach multiple UEs to be monitored

**Expected behavior**
- service should not throw this error and should not reach memory limits

**Comment by ardzoht** [comment]
This issue has been reported on https://github.com/magma/magma/issues/7290, closing this one as it's duplicate to follow up the status.
