### ISSUE TITLE
1.4 branch Monitord not working

### ISSUE THREAD

**Issue by blueandhack** [magma/magma#8337]
Prior to submitting an issue, check to see if one has already been created. If there is currently an open issue, add a thumbs-up emoji to identify that it is also affecting you.

### Your Environment

- **Version:** 1.4
- **Affected Component:** Access Gateway
- **Affected Subcomponent:** monitord
- **Deployment Environment:** bare-metal (AGW)

### Describe the Issue

**To Reproduce**
1. Build and run 1.4 branch using NAT at network and NAT at Gateway
2. Enable CPE monitoring in NMS on Gateway Config
3. view logs via "sudo journalctl -fu magma@monitord"

**Expected behavior**
Monitord should work, ping UE, and track "last seen time/date"

**Additional context**

```
Jul 29 11:32:44 magma monitord[8838]:     states = self._get_operational_states_cb()
Jul 29 11:32:44 magma monitord[8838]: TypeError: 'list' object is not callable
Jul 29 11:33:45 magma monitord[8838]: ERROR:grpc._server:Exception calling application: 'list' object is not callable
Jul 29 11:33:45 magma monitord[8838]: Traceback (most recent call last):
Jul 29 11:33:45 magma monitord[8838]:   File "/usr/local/lib/python3.5/dist-packages/grpc/_server.py", line 435, in _call_behavior
Jul 29 11:33:45 magma monitord[8838]:     response_or_iterator = behavior(argument, context)
Jul 29 11:33:45 magma monitord[8838]:   File "/usr/local/lib/python3.5/dist-packages/magma/common/service.py", line 400, in GetOperationalStates
Jul 29 11:33:45 magma monitord[8838]:     states = self._get_operational_states_cb()
Jul 29 11:33:45 magma monitord[8838]: TypeError: 'list' object is not callable
Jul 29 11:33:52 magma monitord[8838]: WARNING:root:No subscribers/ping targets found
Jul 29 11:34:46 magma monitord[8838]: ERROR:grpc._server:Exception calling application: 'list' object is not callable
Jul 29 11:34:46 magma monitord[8838]: Traceback (most recent call last):
Jul 29 11:34:46 magma monitord[8838]:   File "/usr/local/lib/python3.5/dist-packages/grpc/_server.py", line 435, in _call_behavior
Jul 29 11:34:46 magma monitord[8838]:     response_or_iterator = behavior(argument, context)
Jul 29 11:34:46 magma monitord[8838]:   File "/usr/local/lib/python3.5/dist-packages/magma/common/service.py", line 400, in GetOperationalStates
Jul 29 11:34:46 magma monitord[8838]:     states = self._get_operational_states_cb()
Jul 29 11:34:46 magma monitord[8838]: TypeError: 'list' object is not callable
Jul 29 11:35:02 magma monitord[8838]: WARNING:root:No subscribers/ping targets found
Jul 29 11:35:48 magma monitord[8838]: ERROR:grpc._server:Exception calling application: 'list' object is not callable
Jul 29 11:35:48 magma monitord[8838]: Traceback (most recent call last):
Jul 29 11:35:48 magma monitord[8838]:   File "/usr/local/lib/python3.5/dist-packages/grpc/_server.py", line 435, in _call_behavior
Jul 29 11:35:48 magma monitord[8838]:     response_or_iterator = behavior(argument, context)
Jul 29 11:35:48 magma monitord[8838]:   File "/usr/local/lib/python3.5/dist-packages/magma/common/service.py", line 400, in GetOperationalStates
Jul 29 11:35:48 magma monitord[8838]:     states = self._get_operational_states_cb()
Jul 29 11:35:48 magma monitord[8838]: TypeError: 'list' object is not callable
```

**Comment by ekowtaylor** [comment]
Newer release available https://github.com/magma/magma/releases/
