### ISSUE TITLE
Fail to execute  "fab -f dev_tools.py register_vm"

### ISSUE THREAD

**Issue by rbk1001** [magma/magma#837]
Hi

when trying to run this command, it got failed. any idea?

[root@localhost gateway]# fab -f dev_tools.py register_vm
Traceback (most recent call last):
  File "/usr/bin/fab", line 8, in <module>
    sys.exit(program.run())
  File "/usr/lib/python2.7/site-packages/invoke/program.py", line 373, in run
    self.parse_collection()
  File "/usr/lib/python2.7/site-packages/invoke/program.py", line 465, in parse_collection
    self.load_collection()
  File "/usr/lib/python2.7/site-packages/fabric/main.py", line 87, in load_collection
    super(Fab, self).load_collection()
  File "/usr/lib/python2.7/site-packages/invoke/program.py", line 696, in load_collection
    module, parent = loader.load(coll_name)
  File "/usr/lib/python2.7/site-packages/invoke/loader.py", line 76, in load
    module = imp.load_module(name, fd, path, desc)
  File "/data1/magma/lte/gateway/fabfile.py", line 13, in <module>
    from fabric.api import cd, env, execute, local, run, settings
ImportError: No module named api

**Comment by xjtian** [comment]
Please use the issue template when reporting bugs in the future.

The script should be run using python3/fabric3. It looks like we made a bit of a typo in the docs, but I would follow the shell commands in the code snippet at https://facebookincubator.github.io/magma/docs/basics/prerequisites#build-deploy-tooling and the one above it. I'll update the docs.

**Comment by xjtian** [comment]
Docs fixed by #856
