### ISSUE TITLE
[agw] Memory leak: EMMCommonProcedureInitiated

### ISSUE THREAD

**Issue by ardzoht** [magma/magma#8568]
Running the spirent test to switch between Active and Idle modes on UEs, on the magma version `1.5.2` produces following memory leak:

```
Aug  3 14:20:12 phy-u13 mme[21761]: Direct leak of 560 byte(s) in 1 object(s) allocated from:
Aug  3 14:20:12 phy-u13 mme[21761]:     #0 0x7f67db805712 in __interceptor_calloc ../../../../src/libsanitizer/lsan/lsan_interceptors.cpp:76
Aug  3 14:20:12 phy-u13 mme[21761]:     #1 0x561e954e863b in esm_recv_pdn_connectivity_request /home/vagrant/magma/lte/gateway/c/oai/tasks/nas/esm/sap/esm_recv.c:192
Aug  3 14:20:12 phy-u13 mme[21761]:     #2 0x561e954dd8f6 in esm_sap_recv /home/vagrant/magma/lte/gateway/c/oai/tasks/nas/esm/sap/esm_sap.c:629
Aug  3 14:20:12 phy-u13 mme[21761]:     #3 0x561e954ddf1d in esm_sap_send /home/vagrant/magma/lte/gateway/c/oai/tasks/nas/esm/sap/esm_sap.c:283
Aug  3 14:20:12 phy-u13 mme[21761]:     #4 0x561e954c13e5 in emm_attach /home/vagrant/magma/lte/gateway/c/oai/tasks/nas/emm/Attach.c:1544
Aug  3 14:20:12 phy-u13 mme[21761]:     #5 0x561e954c160e in emm_attach_success_security_cb /home/vagrant/magma/lte/gateway/c/oai/tasks/nas/emm/Attach.c:1335
Aug  3 14:20:12 phy-u13 mme[21761]:     #6 0x561e954e6852 in EmmCommonProcedureInitiated /home/vagrant/magma/lte/gateway/c/oai/tasks/nas/emm/sap/EmmCommonProcedureInitiated.c:113
Aug  3 14:20:12 phy-u13 mme[21761]:     #7 0x561e954d2fce in emm_fsm_process /home/vagrant/magma/lte/gateway/c/oai/tasks/nas/emm/sap/emm_fsm.c:246
Aug  3 14:20:12 phy-u13 mme[21761]:     #8 0x561e954e7a1f in emm_reg_send /home/vagrant/magma/lte/gateway/c/oai/tasks/nas/emm/sap/emm_reg.c:87
Aug  3 14:20:12 phy-u13 mme[21761]:     #9 0x561e954d56fb in emm_sap_send /home/vagrant/magma/lte/gateway/c/oai/tasks/nas/emm/sap/emm_sap.c:89
Aug  3 14:20:12 phy-u13 mme[21761]:     #10 0x561e954cd8f3 in emm_proc_security_mode_complete /home/vagrant/magma/lte/gateway/c/oai/tasks/nas/emm/SecurityModeControl.c:550
Aug  3 14:20:12 phy-u13 mme[21761]:     #11 0x561e954d4f70 in emm_recv_security_mode_complete /home/vagrant/magma/lte/gateway/c/oai/tasks/nas/emm/sap/emm_recv.c:1101
Aug  3 14:20:12 phy-u13 mme[21761]:     #12 0x561e954e4f5d in emm_as_recv /home/vagrant/magma/lte/gateway/c/oai/tasks/nas/emm/sap/emm_as.c:428
Aug  3 14:20:12 phy-u13 mme[21761]:     #13 0x561e954e6318 in emm_as_data_ind /home/vagrant/magma/lte/gateway/c/oai/tasks/nas/emm/sap/emm_as.c:678
Aug  3 14:20:12 phy-u13 mme[21761]:     #14 0x561e954e6318 in emm_as_send /home/vagrant/magma/lte/gateway/c/oai/tasks/nas/emm/sap/emm_as.c:180
Aug  3 14:20:12 phy-u13 mme[21761]:     #15 0x561e954d5717 in emm_sap_send /home/vagrant/magma/lte/gateway/c/oai/tasks/nas/emm/sap/emm_sap.c:105
Aug  3 14:20:12 phy-u13 mme[21761]:     #16 0x561e954b3df8 in nas_proc_ul_transfer_ind /home/vagrant/magma/lte/gateway/c/oai/tasks/nas/nas_proc.c:326
Aug  3 14:20:12 phy-u13 mme[21761]:     #17 0x561e951cb2e9 in handle_message /home/vagrant/magma/lte/gateway/c/oai/tasks/mme_app/mme_app_main.c:98
Aug  3 14:20:12 phy-u13 mme[21761]:     #18 0x7f67daa785c6 in zloop_start (/lib/x86_64-linux-gnu/libczmq.so.4+0x295c6)
```

**Comment by ardzoht** [comment]
Closing this as well since it is not reproducible on latest v1.5 or master
