### ISSUE TITLE
Pipelined does not to apply subsequent rules after failing to parse redirect address

### ISSUE THREAD

**Issue by joary** [magma/magma#8569]
### Your Environment

- **Version:** master
- **Affected Component:** AGW
- **Affected Subcomponent:** pipelined
- **Deployment Environment:** bare-metal (AGW)
- **Type of Deployment:** Federated to OCS, PCRF and HSS

### Describe the Issue

Network was configured with multiple static rules with different priorities, including a redirection rule. The redirection rule used a serverAdress as an url instead of IP.

The redirection rule causes a pipelined failure (seen below), pipelined is not able to parse the subsequent rules after failure.

```
Aug  6 05:36:43 localhost pipelined[980583]: ERROR:OfctlService:unknown barrier xid 744261324
Aug  6 05:36:43 localhost pipelined[980583]: INFO:EnforcementController:Saved redirect rule for 10.248.17.13 in Redis
Aug  6 05:36:43 localhost pipelined[980583]: ERROR:asyncio:Exception in callback PipelinedRpcServicer._activate_flows(sid {
Aug  6 05:36:43 localhost pipelined[980583]:   id: "... version: 1
Aug  6 05:36:43 localhost pipelined[980583]: }
Aug  6 05:36:43 localhost pipelined[980583]: , <Future at 0x...state=pending>)
Aug  6 05:36:43 localhost pipelined[980583]: handle: <Handle PipelinedRpcServicer._activate_flows(sid {
Aug  6 05:36:43 localhost pipelined[980583]:   id: "... version: 1
Aug  6 05:36:43 localhost pipelined[980583]: }
Aug  6 05:36:43 localhost pipelined[980583]: , <Future at 0x...state=pending>)>
Aug  6 05:36:43 localhost pipelined[980583]: Traceback (most recent call last):
Aug  6 05:36:43 localhost pipelined[980583]:   File "/usr/lib/python3/dist-packages/netaddr/strategy/ipv4.py", line 127, in str_to_int
Aug  6 05:36:43 localhost pipelined[980583]:     return _struct.unpack('>I', _inet_aton(addr))[0]
Aug  6 05:36:43 localhost pipelined[980583]: OSError: illegal IP address string passed to inet_aton
Aug  6 05:36:43 localhost pipelined[980583]: During handling of the above exception, another exception occurred:
Aug  6 05:36:43 localhost pipelined[980583]: Traceback (most recent call last):
Aug  6 05:36:43 localhost pipelined[980583]:   File "/usr/lib/python3/dist-packages/netaddr/ip/__init__.py", line 311, in __init__
Aug  6 05:36:43 localhost pipelined[980583]:     self._value = self._module.str_to_int(addr, flags)
Aug  6 05:36:43 localhost pipelined[980583]:   File "/usr/lib/python3/dist-packages/netaddr/strategy/ipv4.py", line 129, in str_to_int
Aug  6 05:36:43 localhost pipelined[980583]:     raise AddrFormatError('%r is not a valid IPv4 address string!' % addr)
Aug  6 05:36:43 localhost pipelined[980583]: netaddr.core.AddrFormatError: 'alertasbafi.entel.pe' is not a valid IPv4 address string!
Aug  6 05:36:43 localhost pipelined[980583]: During handling of the above exception, another exception occurred:
Aug  6 05:36:43 localhost pipelined[980583]: Traceback (most recent call last):
Aug  6 05:36:43 localhost pipelined[980583]:   File "/usr/lib/python3/dist-packages/ryu/lib/addrconv.py", line 29, in text_to_bin
Aug  6 05:36:43 localhost pipelined[980583]:     return self._addr(text, **self._addr_kwargs).packed
Aug  6 05:36:43 localhost pipelined[980583]:   File "/usr/lib/python3/dist-packages/netaddr/ip/__init__.py", line 313, in __init__
Aug  6 05:36:43 localhost pipelined[980583]:     raise AddrFormatError('base address %r is not IPv%d'
Aug  6 05:36:43 localhost pipelined[980583]: netaddr.core.AddrFormatError: base address 'alertasbafi.entel.pe' is not IPv4
Aug  6 05:36:43 localhost pipelined[980583]: During handling of the above exception, another exception occurred:
Aug  6 05:36:43 localhost pipelined[980583]: Traceback (most recent call last):
Aug  6 05:36:43 localhost pipelined[980583]:   File "/usr/lib/python3/dist-packages/netaddr/strategy/ipv4.py", line 125, in str_to_int
Aug  6 05:36:43 localhost pipelined[980583]:     return _struct.unpack('>I', _inet_pton(AF_INET, addr))[0]
Aug  6 05:36:43 localhost pipelined[980583]: OSError: illegal IP address string passed to inet_pton
Aug  6 05:36:43 localhost pipelined[980583]: During handling of the above exception, another exception occurred:
Aug  6 05:36:43 localhost pipelined[980583]: Traceback (most recent call last):
Aug  6 05:36:43 localhost pipelined[980583]:   File "/usr/lib/python3/dist-packages/netaddr/ip/__init__.py", line 311, in __init__
Aug  6 05:36:43 localhost pipelined[980583]:     self._value = self._module.str_to_int(addr, flags)
Aug  6 05:36:43 localhost pipelined[980583]:   File "/usr/lib/python3/dist-packages/netaddr/strategy/ipv4.py", line 129, in str_to_int
Aug  6 05:36:43 localhost pipelined[980583]:     raise AddrFormatError('%r is not a valid IPv4 address string!' % addr)
Aug  6 05:36:43 localhost pipelined[980583]: netaddr.core.AddrFormatError: 'alertasbafi.entel.pe' is not a valid IPv4 address string!
Aug  6 05:36:43 localhost pipelined[980583]: During handling of the above exception, another exception occurred:
Aug  6 05:36:43 localhost pipelined[980583]: Traceback (most recent call last):
Aug  6 05:36:43 localhost pipelined[980583]:   File "/usr/lib/python3/dist-packages/netaddr/ip/__init__.py", line 791, in parse_ip_network
Aug  6 05:36:43 localhost pipelined[980583]:     ip = IPAddress(val1, module.version, flags=INET_PTON)
Aug  6 05:36:43 localhost pipelined[980583]:   File "/usr/lib/python3/dist-packages/netaddr/ip/__init__.py", line 313, in __init__
Aug  6 05:36:43 localhost pipelined[980583]:     raise AddrFormatError('base address %r is not IPv%d'
Aug  6 05:36:43 localhost pipelined[980583]: netaddr.core.AddrFormatError: base address 'alertasbafi.entel.pe' is not IPv4
Aug  6 05:36:43 localhost pipelined[980583]: During handling of the above exception, another exception occurred:
Aug  6 05:36:43 localhost pipelined[980583]: Traceback (most recent call last):
Aug  6 05:36:43 localhost pipelined[980583]:   File "/usr/lib/python3/dist-packages/netaddr/strategy/ipv4.py", line 263, in expand_partial_address
Aug  6 05:36:43 localhost pipelined[980583]:     tokens = ['%d' % int(o) for o in addr.split('.')]
Aug  6 05:36:43 localhost pipelined[980583]:   File "/usr/lib/python3/dist-packages/netaddr/strategy/ipv4.py", line 263, in <listcomp>
Aug  6 05:36:43 localhost pipelined[980583]:     tokens = ['%d' % int(o) for o in addr.split('.')]
Aug  6 05:36:43 localhost pipelined[980583]: ValueError: invalid literal for int() with base 10: 'alertasbafi'
Aug  6 05:36:43 localhost pipelined[980583]: During handling of the above exception, another exception occurred:
Aug  6 05:36:43 localhost pipelined[980583]: Traceback (most recent call last):
Aug  6 05:36:43 localhost pipelined[980583]:   File "/usr/lib/python3.8/asyncio/events.py", line 81, in _run
Aug  6 05:36:43 localhost pipelined[980583]:     self._context.run(self._callback, *self._args)
Aug  6 05:36:43 localhost pipelined[980583]:   File "/usr/local/lib/python3.8/dist-packages/magma/pipelined/rpc_servicer.py", line 286, in _activate_flows
Aug  6 05:36:43 localhost pipelined[980583]:     ret_ipv4 = self._install_flows_gx(request, ipv4)
Aug  6 05:36:43 localhost pipelined[980583]:   File "/usr/local/lib/python3.8/dist-packages/magma/pipelined/rpc_servicer.py", line 331, in _install_flows_gx
Aug  6 05:36:43 localhost pipelined[980583]:     enforcement_res = self._activate_rules_in_enforcement(
Aug  6 05:36:43 localhost pipelined[980583]:   File "/usr/local/lib/python3.8/dist-packages/magma/pipelined/rpc_servicer.py", line 405, in _activate_rules_in_enforcement
Aug  6 05:36:43 localhost pipelined[980583]:     enforcement_res = self._enforcer_app.activate_rules(
Aug  6 05:36:43 localhost pipelined[980583]:   File "/usr/local/lib/python3.8/dist-packages/magma/pipelined/app/policy_mixin.py", line 92, in activate_rules
Aug  6 05:36:43 localhost pipelined[980583]:     res = self._install_flow_for_rule(imsi, msisdn, uplink_tunnel, ip_addr, apn_ambr, policy.rule, policy.version)
Aug  6 05:36:43 localhost pipelined[980583]:   File "/usr/local/lib/python3.8/dist-packages/magma/pipelined/app/enforcement.py", line 198, in _install_flow_for_rule
Aug  6 05:36:43 localhost pipelined[980583]:     return self._install_redirect_flow(imsi, ip_addr, rule, version)
Aug  6 05:36:43 localhost pipelined[980583]:   File "/usr/local/lib/python3.8/dist-packages/magma/pipelined/app/enforcement.py", line 230, in _install_redirect_flow
Aug  6 05:36:43 localhost pipelined[980583]:     self._redirect_manager.setup_lte_redirect(
Aug  6 05:36:43 localhost pipelined[980583]:   File "/usr/local/lib/python3.8/dist-packages/magma/pipelined/redirect.py", line 121, in setup_lte_redirect
Aug  6 05:36:43 localhost pipelined[980583]:     self._install_redirect_flows(datapath, loop, imsi, ip_addr, rule,
Aug  6 05:36:43 localhost pipelined[980583]:   File "/usr/local/lib/python3.8/dist-packages/magma/pipelined/redirect.py", line 145, in _install_redirect_flows
Aug  6 05:36:43 localhost pipelined[980583]:     self._install_ipv4_bypass_flows(datapath, imsi, rule,
Aug  6 05:36:43 localhost pipelined[980583]:   File "/usr/local/lib/python3.8/dist-packages/magma/pipelined/redirect.py", line 579, in _install_ipv4_bypass_flows
Aug  6 05:36:43 localhost pipelined[980583]:     flows.add_resubmit_next_service_flow(
Aug  6 05:36:43 localhost pipelined[980583]:   File "/usr/local/lib/python3.8/dist-packages/magma/pipelined/openflow/flows.py", line 200, in add_resubmit_next_service_flow
Aug  6 05:36:43 localhost pipelined[980583]:     mod = get_add_resubmit_next_service_flow_msg(
Aug  6 05:36:43 localhost pipelined[980583]:   File "/usr/local/lib/python3.8/dist-packages/magma/pipelined/openflow/flows.py", line 415, in get_add_resubmit_next_service_flow_msg
Aug  6 05:36:43 localhost pipelined[980583]:     ryu_match = parser.OFPMatch(**match.ryu_match)
Aug  6 05:36:43 localhost pipelined[980583]:   File "/usr/lib/python3/dist-packages/ryu/ofproto/ofproto_v1_4_parser.py", line 760, in __init__
Aug  6 05:36:43 localhost pipelined[980583]:     fields = [ofproto.oxm_from_user(k, v) for (k, v)
Aug  6 05:36:43 localhost pipelined[980583]:   File "/usr/lib/python3/dist-packages/ryu/ofproto/ofproto_v1_4_parser.py", line 760, in <listcomp>
Aug  6 05:36:43 localhost pipelined[980583]:     fields = [ofproto.oxm_from_user(k, v) for (k, v)
Aug  6 05:36:43 localhost pipelined[980583]:   File "/usr/lib/python3/dist-packages/ryu/ofproto/oxx_fields.py", line 72, in _from_user
Aug  6 05:36:43 localhost pipelined[980583]:     value = t.from_user(value)
Aug  6 05:36:43 localhost pipelined[980583]:   File "/usr/lib/python3/dist-packages/ryu/lib/addrconv.py", line 36, in text_to_bin
Aug  6 05:36:43 localhost pipelined[980583]:     ip = self._fallback(text, **self._addr_kwargs)
Aug  6 05:36:43 localhost pipelined[980583]:   File "/usr/lib/python3/dist-packages/netaddr/ip/__init__.py", line 915, in __init__
Aug  6 05:36:43 localhost pipelined[980583]:     value, prefixlen = parse_ip_network(_ipv4, addr,
Aug  6 05:36:43 localhost pipelined[980583]:   File "/usr/lib/python3/dist-packages/netaddr/ip/__init__.py", line 795, in parse_ip_network
Aug  6 05:36:43 localhost pipelined[980583]:     expanded_addr = _ipv4.expand_partial_address(val1)
Aug  6 05:36:43 localhost pipelined[980583]:   File "/usr/lib/python3/dist-packages/netaddr/strategy/ipv4.py", line 267, in expand_partial_address
Aug  6 05:36:43 localhost pipelined[980583]:     raise error
Aug  6 05:36:43 localhost pipelined[980583]: netaddr.core.AddrFormatError: invalid partial IPv4 address: 'alertasbafi.entel.pe'!
```

**Expected behavior**
Pipelined should not stop parsing rules after not being able to parse a rule.

**Comment by koolzz** [comment]
@joary are these rules configured via nms? I wonder if we should do the check there, otherwise if I just log an error it might be ignored and lead to unexpected behavior

**Comment by joary** [comment]
@koolzz , Yes rules were created in NMS. @emersonacuna can give more details if necessary.

I believe having a failure in one rule should not impact the ability of the subsequent ones to be installed.

Thinking for example in the scenario of dynamic rules (from Federated PCRF), a parsing error of in a new rule can cause the connectivity loss for a given user (or user-base).

From my point of view magma should parse error separately for each rule. But I'm open to ideas.
