### ISSUE TITLE
[agw] Memory leak: nas_new_attach_procedure

### ISSUE THREAD

**Issue by ardzoht** [magma/magma#8570]
Running the spirent test to switch between Active and Idle modes on UEs, on the magma version `1.5.2` produces following memory leaks:

```
Aug  3 14:20:12 phy-u13 mme[21761]: Direct leak of 160 byte(s) in 1 object(s) allocated from:
Aug  3 14:20:12 phy-u13 mme[21761]:     #0 0x7f67db805712 in __interceptor_calloc ../../../../src/libsanitizer/lsan/lsan_interceptors.cpp:76
Aug  3 14:20:12 phy-u13 mme[21761]:     #1 0x561e954b5105 in nas_new_emm_procedures /home/vagrant/magma/lte/gateway/c/oai/tasks/nas/nas_procedures.c:577
Aug  3 14:20:12 phy-u13 mme[21761]:     #2 0x561e954b5aae in nas_new_attach_procedure /home/vagrant/magma/lte/gateway/c/oai/tasks/nas/nas_procedures.c:586
Aug  3 14:20:12 phy-u13 mme[21761]:     #3 0x561e954bfdf6 in emm_proc_create_procedure_attach_request /home/vagrant/magma/lte/gateway/c/oai/tasks/nas/emm/Attach.c:895
Aug  3 14:20:12 phy-u13 mme[21761]:     #4 0x561e954c2f4a in emm_proc_attach_request /home/vagrant/magma/lte/gateway/c/oai/tasks/nas/emm/Attach.c:616
Aug  3 14:20:12 phy-u13 mme[21761]:     #5 0x561e954d349a in emm_recv_attach_request /home/vagrant/magma/lte/gateway/c/oai/tasks/nas/emm/sap/emm_recv.c:422
Aug  3 14:20:12 phy-u13 mme[21761]:     #6 0x561e954e5af0 in emm_as_establish_req /home/vagrant/magma/lte/gateway/c/oai/tasks/nas/emm/sap/emm_as.c:802
Aug  3 14:20:12 phy-u13 mme[21761]:     #7 0x561e954e6373 in emm_as_send /home/vagrant/magma/lte/gateway/c/oai/tasks/nas/emm/sap/emm_as.c:185
Aug  3 14:20:12 phy-u13 mme[21761]:     #8 0x561e954d5717 in emm_sap_send /home/vagrant/magma/lte/gateway/c/oai/tasks/nas/emm/sap/emm_sap.c:105
Aug  3 14:20:12 phy-u13 mme[21761]:     #9 0x561e954b3c0d in nas_proc_establish_ind /home/vagrant/magma/lte/gateway/c/oai/tasks/nas/nas_proc.c:185
Aug  3 14:20:12 phy-u13 mme[21761]:     #10 0x561e951ccbbb in mme_app_handle_initial_ue_message /home/vagrant/magma/lte/gateway/c/oai/tasks/mme_app/mme_app_bearer.c:728
Aug  3 14:20:12 phy-u13 mme[21761]:     #11 0x561e951cb4ed in handle_message /home/vagrant/magma/lte/gateway/c/oai/tasks/mme_app/mme_app_main.c:205
Aug  3 14:20:12 phy-u13 mme[21761]:     #12 0x7f67daa785c6 in zloop_start (/lib/x86_64-linux-gnu/libczmq.so.4+0x295c6)
Aug  3 14:20:12 phy-u13 mme[21761]: Direct leak of 48 byte(s) in 1 object(s) allocated from:
Aug  3 14:20:12 phy-u13 mme[21761]:     #0 0x7f67db805712 in __interceptor_calloc ../../../../src/libsanitizer/lsan/lsan_interceptors.cpp:76
Aug  3 14:20:12 phy-u13 mme[21761]:     #1 0x7f67daa73c0f in zlist_new (/lib/x86_64-linux-gnu/libczmq.so.4+0x24c0f)
Aug  3 14:20:12 phy-u13 mme[21761]: Indirect leak of 200 byte(s) in 1 object(s) allocated from:
Aug  3 14:20:12 phy-u13 mme[21761]:     #0 0x7f67db805712 in __interceptor_calloc ../../../../src/libsanitizer/lsan/lsan_interceptors.cpp:76
Aug  3 14:20:12 phy-u13 mme[21761]:     #1 0x561e954b5a30 in nas_new_attach_procedure /home/vagrant/magma/lte/gateway/c/oai/tasks/nas/nas_procedures.c:597
Aug  3 14:20:12 phy-u13 mme[21761]:     #2 0x561e954bfdf6 in emm_proc_create_procedure_attach_request /home/vagrant/magma/lte/gateway/c/oai/tasks/nas/emm/Attach.c:895
Aug  3 14:20:12 phy-u13 mme[21761]:     #3 0x561e954c2f4a in emm_proc_attach_request /home/vagrant/magma/lte/gateway/c/oai/tasks/nas/emm/Attach.c:616
Aug  3 14:20:12 phy-u13 mme[21761]:     #4 0x561e954d349a in emm_recv_attach_request /home/vagrant/magma/lte/gateway/c/oai/tasks/nas/emm/sap/emm_recv.c:422
Aug  3 14:20:12 phy-u13 mme[21761]:     #5 0x561e954e5af0 in emm_as_establish_req /home/vagrant/magma/lte/gateway/c/oai/tasks/nas/emm/sap/emm_as.c:802
Aug  3 14:20:12 phy-u13 mme[21761]:     #6 0x561e954e6373 in emm_as_send /home/vagrant/magma/lte/gateway/c/oai/tasks/nas/emm/sap/emm_as.c:185
Aug  3 14:20:12 phy-u13 mme[21761]:     #7 0x561e954d5717 in emm_sap_send /home/vagrant/magma/lte/gateway/c/oai/tasks/nas/emm/sap/emm_sap.c:105
Aug  3 14:20:12 phy-u13 mme[21761]:     #8 0x561e954b3c0d in nas_proc_establish_ind /home/vagrant/magma/lte/gateway/c/oai/tasks/nas/nas_proc.c:185
Aug  3 14:20:12 phy-u13 mme[21761]:     #9 0x561e951ccbbb in mme_app_handle_initial_ue_message /home/vagrant/magma/lte/gateway/c/oai/tasks/mme_app/mme_app_bearer.c:728
Aug  3 14:20:12 phy-u13 mme[21761]:     #10 0x561e951cb4ed in handle_message /home/vagrant/magma/lte/gateway/c/oai/tasks/mme_app/mme_app_main.c:205
Aug  3 14:20:12 phy-u13 mme[21761]:     #11 0x7f67daa785c6 in zloop_start (/lib/x86_64-linux-gnu/libczmq.so.4+0x295c6)
```

**Comment by ardzoht** [comment]
Closing this since it's verified this is not reproducible on latest v1.5 branch.
