### ISSUE TITLE
[agw] Memory leak: emm_cn_send

### ISSUE THREAD

**Issue by ardzoht** [magma/magma#8571]
Running the spirent test to switch between Active and Idle modes on UEs, on the magma version `1.5.2` produces following memory leak:

```
Aug  3 14:20:12 phy-u13 mme[21761]: Indirect leak of 32 byte(s) in 1 object(s) allocated from:
Aug  3 14:20:12 phy-u13 mme[21761]:     #0 0x7f67db8059c1 in __interceptor_malloc ../../../../src/libsanitizer/lsan/lsan_interceptors.cpp:54
Aug  3 14:20:12 phy-u13 mme[21761]:     #1 0x561e95110120 in blk2bstr /home/vagrant/magma/lte/gateway/c/oai/lib/bstr/bstrlib.c:323
Aug  3 14:20:12 phy-u13 mme[21761]:     #2 0x561e954d1878 in emm_cn_cs_response_success /home/vagrant/magma/lte/gateway/c/oai/tasks/nas/emm/sap/emm_cn.c:597
Aug  3 14:20:12 phy-u13 mme[21761]:     #3 0x561e954d26fd in emm_cn_send /home/vagrant/magma/lte/gateway/c/oai/tasks/nas/emm/sap/emm_cn.c:1163
Aug  3 14:20:12 phy-u13 mme[21761]:     #4 0x561e954d56ed in emm_sap_send /home/vagrant/magma/lte/gateway/c/oai/tasks/nas/emm/sap/emm_sap.c:113
Aug  3 14:20:12 phy-u13 mme[21761]:     #5 0x561e954b45dc in nas_proc_cs_respose_success /home/vagrant/magma/lte/gateway/c/oai/tasks/nas/nas_proc.c:485
Aug  3 14:20:12 phy-u13 mme[21761]:     #6 0x561e951cdcf3 in mme_app_handle_create_sess_resp /home/vagrant/magma/lte/gateway/c/oai/tasks/mme_app/mme_app_bearer.c:1260
Aug  3 14:20:12 phy-u13 mme[21761]:     #7 0x561e951cb316 in handle_message /home/vagrant/magma/lte/gateway/c/oai/tasks/mme_app/mme_app_main.c:116
Aug  3 14:20:12 phy-u13 mme[21761]:     #8 0x7f67daa785c6 in zloop_start (/lib/x86_64-linux-gnu/libczmq.so.4+0x295c6)
Aug  3 14:20:12 phy-u13 mme[21761]: Indirect leak of 16 byte(s) in 1 object(s) allocated from:
Aug  3 14:20:12 phy-u13 mme[21761]:     #0 0x7f67db8059c1 in __interceptor_malloc ../../../../src/libsanitizer/lsan/lsan_interceptors.cpp:54
Aug  3 14:20:12 phy-u13 mme[21761]:     #1 0x561e9510fee7 in bfromcstr /home/vagrant/magma/lte/gateway/c/oai/lib/bstr/bstrlib.c:216
Aug  3 14:20:12 phy-u13 mme[21761]:     #2 0x561e954d2648 in emm_cn_ula_success /home/vagrant/magma/lte/gateway/c/oai/tasks/nas/emm/sap/emm_cn.c:330
Aug  3 14:20:12 phy-u13 mme[21761]:     #3 0x561e954d2648 in emm_cn_send /home/vagrant/magma/lte/gateway/c/oai/tasks/nas/emm/sap/emm_cn.c:1159
Aug  3 14:20:12 phy-u13 mme[21761]:     #4 0x561e954d56ed in emm_sap_send /home/vagrant/magma/lte/gateway/c/oai/tasks/nas/emm/sap/emm_sap.c:113
Aug  3 14:20:12 phy-u13 mme[21761]:     #5 0x561e954b4545 in nas_proc_ula_success /home/vagrant/magma/lte/gateway/c/oai/tasks/nas/nas_proc.c:467
Aug  3 14:20:12 phy-u13 mme[21761]:     #6 0x561e951d6c79 in mme_app_handle_s6a_update_location_ans /home/vagrant/magma/lte/gateway/c/oai/tasks/mme_app/mme_app_location.c:346
Aug  3 14:20:12 phy-u13 mme[21761]:     #7 0x561e951cb52f in handle_message /home/vagrant/magma/lte/gateway/c/oai/tasks/mme_app/mme_app_main.c:215
Aug  3 14:20:12 phy-u13 mme[21761]:     #8 0x7f67daa785c6 in zloop_start (/lib/x86_64-linux-gnu/libczmq.so.4+0x295c6)
Aug  3 14:20:12 phy-u13 mme[21761]: Indirect leak of 16 byte(s) in 1 object(s) allocated from:
Aug  3 14:20:12 phy-u13 mme[21761]:     #0 0x7f67db8059c1 in __interceptor_malloc ../../../../src/libsanitizer/lsan/lsan_interceptors.cpp:54
Aug  3 14:20:12 phy-u13 mme[21761]:     #1 0x561e951100fd in blk2bstr /home/vagrant/magma/lte/gateway/c/oai/lib/bstr/bstrlib.c:314
Aug  3 14:20:12 phy-u13 mme[21761]:     #2 0x561e954d1878 in emm_cn_cs_response_success /home/vagrant/magma/lte/gateway/c/oai/tasks/nas/emm/sap/emm_cn.c:597
Aug  3 14:20:12 phy-u13 mme[21761]:     #3 0x561e954d26fd in emm_cn_send /home/vagrant/magma/lte/gateway/c/oai/tasks/nas/emm/sap/emm_cn.c:1163
Aug  3 14:20:12 phy-u13 mme[21761]:     #4 0x561e954d56ed in emm_sap_send /home/vagrant/magma/lte/gateway/c/oai/tasks/nas/emm/sap/emm_sap.c:113
Aug  3 14:20:12 phy-u13 mme[21761]:     #5 0x561e954b45dc in nas_proc_cs_respose_success /home/vagrant/magma/lte/gateway/c/oai/tasks/nas/nas_proc.c:485
Aug  3 14:20:12 phy-u13 mme[21761]:     #6 0x561e951cdcf3 in mme_app_handle_create_sess_resp /home/vagrant/magma/lte/gateway/c/oai/tasks/mme_app/mme_app_bearer.c:1260
Aug  3 14:20:12 phy-u13 mme[21761]:     #7 0x561e951cb316 in handle_message /home/vagrant/magma/lte/gateway/c/oai/tasks/mme_app/mme_app_main.c:116
Aug  3 14:20:12 phy-u13 mme[21761]:     #8 0x7f67daa785c6 in zloop_start (/lib/x86_64-linux-gnu/libczmq.so.4+0x295c6)
```

Culprit of leak seems to be originating from `emm_cn_send` function

**Comment by ardzoht** [comment]
Closing since it is not reproducible on latest v1.5 or master branches
