### ISSUE TITLE
[AGW][1.7]Subscriberdb erroring out with "Exception deserializing response!" 

### ISSUE THREAD

**Issue by sudhikan** [magma/magma#8628]
### Your Environment

- **Version: 1.7.0-1628772113-a86e8ba8
- **Affected Component:** AGW
- **Affected Subcomponent:** subscriberdb
- **Deployment Environment:**  AWS (orc8r), bare-metal (AGW)

### Describe the Issue

Upon upgrading AGW to 1.7.0-1628772113-a86e8ba8, `subscriberdb` kept erroring out. 

```
Aug 12 15:37:06 phy-u7 subscriberdb[6833]: ERROR:grpc._common:Exception deserializing message!
Aug 12 15:37:06 phy-u7 subscriberdb[6833]: Traceback (most recent call last):
Aug 12 15:37:06 phy-u7 subscriberdb[6833]:   File "/usr/local/lib/python3.8/dist-packages/grpc/_common.py", line 86, in _transform
Aug 12 15:37:06 phy-u7 subscriberdb[6833]:     return transformer(message)
Aug 12 15:37:06 phy-u7 subscriberdb[6833]:   File "/usr/local/lib/python3.8/dist-packages/google/protobuf/internal/python_message.py", line 812, in FromString
Aug 12 15:37:06 phy-u7 subscriberdb[6833]:     message.MergeFromString(s)
Aug 12 15:37:06 phy-u7 subscriberdb[6833]:   File "/usr/local/lib/python3.8/dist-packages/google/protobuf/internal/python_message.py", line 1145, in MergeFromString
Aug 12 15:37:06 phy-u7 subscriberdb[6833]:     if self._InternalParse(serialized, 0, length) != length:
Aug 12 15:37:06 phy-u7 subscriberdb[6833]:   File "/usr/local/lib/python3.8/dist-packages/google/protobuf/internal/python_message.py", line 1212, in InternalParse
Aug 12 15:37:06 phy-u7 subscriberdb[6833]:     pos = field_decoder(buffer, new_pos, end, self, field_dict)
Aug 12 15:37:06 phy-u7 subscriberdb[6833]:   File "/usr/local/lib/python3.8/dist-packages/google/protobuf/internal/decoder.py", line 754, in DecodeField
Aug 12 15:37:06 phy-u7 subscriberdb[6833]:     if value._InternalParse(buffer, pos, new_pos) != new_pos:
Aug 12 15:37:06 phy-u7 subscriberdb[6833]:   File "/usr/local/lib/python3.8/dist-packages/google/protobuf/internal/python_message.py", line 1212, in InternalParse
Aug 12 15:37:06 phy-u7 subscriberdb[6833]:     pos = field_decoder(buffer, new_pos, end, self, field_dict)
Aug 12 15:37:06 phy-u7 subscriberdb[6833]:   File "/usr/local/lib/python3.8/dist-packages/google/protobuf/internal/decoder.py", line 754, in DecodeField
Aug 12 15:37:06 phy-u7 subscriberdb[6833]:     if value._InternalParse(buffer, pos, new_pos) != new_pos:
Aug 12 15:37:06 phy-u7 subscriberdb[6833]:   File "/usr/local/lib/python3.8/dist-packages/google/protobuf/internal/python_message.py", line 1205, in InternalParse
Aug 12 15:37:06 phy-u7 subscriberdb[6833]:     new_pos = local_SkipField(buffer, old_pos, end, tag_bytes)
Aug 12 15:37:06 phy-u7 subscriberdb[6833]:   File "/usr/local/lib/python3.8/dist-packages/google/protobuf/internal/decoder.py", line 1053, in SkipField
Aug 12 15:37:06 phy-u7 subscriberdb[6833]:     return WIRETYPE_TO_SKIPPER[wire_type](buffer, pos, end)
Aug 12 15:37:06 phy-u7 subscriberdb[6833]:   File "/usr/local/lib/python3.8/dist-packages/google/protobuf/internal/decoder.py", line 943, in _SkipLengthDelimited
Aug 12 15:37:06 phy-u7 subscriberdb[6833]:     raise _DecodeError('Truncated message.')
Aug 12 15:37:06 phy-u7 subscriberdb[6833]: google.protobuf.message.DecodeError: Truncated message.
Aug 12 15:37:06 phy-u7 subscriberdb[6833]: ERROR:root:Fetch subscribers error! [StatusCode.INTERNAL] Exception deserializing response!
Aug 12 15:37:06 phy-u7 subscriberdb[6833]: INFO:root:get digest stored in gateway:
Aug 12 15:37:06 phy-u7 subscriberdb[6833]: ERROR:root:Check subscribers in sync request error! [StatusCode.UNIMPLEMENTED] unknown method CheckInSync for service magma.lte.SubscriberDBCloud
```

Had to revert AGW back to `1.7.0-1628722629-0f98f5fe` to recover from this. 

**To Reproduce**
1. Upgrade gateway to latest 1.7
2. Observer syslogs. 
3. Impacting attach procedure to UEs.

**Comment by sudhikan** [comment]
duplicate of #8629; closing this one.
