### ISSUE TITLE
MME loop restart due to failure to parse service-area-map configuration.

### ISSUE THREAD

**Issue by joary** [magma/magma#8677]
### Your Environment

- **Version:** master
- **Affected Component:** AGW
- **Affected Subcomponent:** MME config
- **Deployment Environment:** all

### Describe the Issue

AGW is unable to parse the "Service Area Map" configuration due to a failure in the generate_oai_config.py

**To Reproduce**

Configure service area in NMS in order to have a valid serviceAreaMaps in AGW gateway.mconfig

```
"serviceAreaMaps":{"257":{"tac":[4015,3523]}},"federatedModeMap":{}},
```

Check syslogs mme is loop crashing with:
```
Aug 18 08:58:29 localhost systemd[1]: Started Magma pipelined service.
Aug 18 08:58:29 localhost systemd[1]: Starting Magma OAI MME service...
Aug 18 08:58:30 localhost mme[3914490]: Traceback (most recent call last):
Aug 18 08:58:30 localhost mme[3914490]:   File "/usr/local/bin/generate_oai_config.py", line 348, in <module>
Aug 18 08:58:30 localhost mme[3914490]:     main()
Aug 18 08:58:30 localhost mme[3914490]:   File "/usr/local/bin/generate_oai_config.py", line 333, in main
Aug 18 08:58:30 localhost mme[3914490]:     context = _get_context()
Aug 18 08:58:30 localhost mme[3914490]:   File "/usr/local/bin/generate_oai_config.py", line 289, in _get_context
Aug 18 08:58:30 localhost mme[3914490]:     "service_area_map": _get_service_area_maps(mme_service_config),
Aug 18 08:58:30 localhost mme[3914490]:   File "/usr/local/bin/generate_oai_config.py", line 209, in _get_service_area_maps
Aug 18 08:58:30 localhost mme[3914490]:     service_area_map.append({'sac': sac, 'tac': sam.tac.copy()})
Aug 18 08:58:30 localhost mme[3914490]: AttributeError: 'RepeatedScalarFieldContainer' object has no attribute 'copy'
Aug 18 08:58:30 localhost systemd[1]: magma@mme.service: Control process exited, code=exited, status=1/FAILURE
Aug 18 08:58:30 localhost mme[3914497]: ERROR:root:Error parsing service exit status: None
```

**Comment by joary** [comment]
The PR https://github.com/magma/magma/pull/8672 solves this issue.
