### ISSUE TITLE
[agw]ERROR: LeakSanitizer: detected memory leaks

### ISSUE THREAD

**Issue by shanku9** [magma/magma#9199]
### Your Environment

- **Version:** 1.7.0-1629904616-2e3c1183
- **Affected Component:** Access Gateway
- **Affected Subcomponent:** AGW service
- **Deployment Environment:** e.g. AWS (orc8r), bare-metal (mpk-dogfooding)

### Describe the Issue
Subscriber fails to authenticate after LeakSanitizer error. Attached logs 
```
Sep 02 16:58:20 mpk-dogfooding systemd[1]: Stopping Magma OAI MME service...
Sep 02 16:58:20 mpk-dogfooding mme[434735]: Received SIGINT or SIGTERM
Sep 02 16:58:20 mpk-dogfooding mme[434735]: [TRACE] Entering shared_log_exit
Sep 02 16:58:20 mpk-dogfooding mme[434735]: TASK_S6A terminated
Sep 02 16:58:20 mpk-dogfooding mme[434735]: TASK_S1AP terminated
Sep 02 16:58:20 mpk-dogfooding mme[434735]: TASK_SCTP terminated
Sep 02 16:58:20 mpk-dogfooding mme[434735]: TASK_SERVICE303 terminated
Sep 02 16:58:20 mpk-dogfooding mme[434735]: TASK_SERVICE303_SERVER terminated
Sep 02 16:58:20 mpk-dogfooding mme[434735]: TASK_GRPC_SERVICE terminated
Sep 02 16:58:20 mpk-dogfooding mme[434735]: TASK_MME_APP terminated
Sep 02 16:58:20 mpk-dogfooding mme[434735]: TASK_SGW_S8 terminated
Sep 02 16:58:20 mpk-dogfooding mme[434735]: [TRACE] Leaving shared_log_exit
Sep 02 16:58:20 mpk-dogfooding mme[434735]: TASK_SHARED_TS_LOG terminated
Sep 02 16:58:20 mpk-dogfooding mme[434735]: TASK_SPGW_APP terminated
Sep 02 16:58:23 mpk-dogfooding mme[434735]: Cleaning up SPGW configs
Sep 02 16:58:23 mpk-dogfooding mme[434735]: =================================================================
Sep 02 16:58:23 mpk-dogfooding mme[434735]: ==434735==ERROR: LeakSanitizer: detected memory leaks
Sep 02 16:58:23 mpk-dogfooding mme[434735]: Direct leak of 48 byte(s) in 1 object(s) allocated from:
Sep 02 16:58:23 mpk-dogfooding mme[434735]:     #0 0x7f822e9d2712 in __interceptor_calloc ../../../../src/libsanitizer/lsan/lsan_interceptors.cpp:76
Sep 02 16:58:23 mpk-dogfooding mme[434735]:     #1 0x7f822dc01c0f in zlist_new (/lib/x86_64-linux-gnu/libczmq.so.4+0x24c0f)
Sep 02 16:58:23 mpk-dogfooding mme[434735]: Direct leak of 16 byte(s) in 1 object(s) allocated from:
Sep 02 16:58:23 mpk-dogfooding mme[434735]:     #0 0x7f822e9d29c1 in __interceptor_malloc ../../../../src/libsanitizer/lsan/lsan_interceptors.cpp:54
Sep 02 16:58:23 mpk-dogfooding mme[434735]:     #1 0x562549f0c038 in bfromcstr_with_str_len /home/vagrant/magma/lte/gateway/c/core/oai/lib/bstr/bstrlib.c:243
Sep 02 16:58:23 mpk-dogfooding mme[434735]:     #2 0x56254a32edc9 in magma::lte::NasStateConverter::proto_to_pco_protocol_or_container_id(magma::lte::oai::Protocol>
Sep 02 16:58:23 mpk-dogfooding mme[434735]:     #3 0x56254a32ef68 in magma::lte::NasStateConverter::proto_to_protocol_configuration_options(magma::lte::oai::Protoc>
Sep 02 16:58:23 mpk-dogfooding mme[434735]:     #4 0x56254a32f656 in magma::lte::NasStateConverter::proto_to_esm_proc_data(magma::lte::oai::EsmProcData const&, esm>
Sep 02 16:58:23 mpk-dogfooding mme[434735]:     #5 0x56254a32f7db in magma::lte::NasStateConverter::proto_to_esm_context(magma::lte::oai::EsmContext const&, esm_co>
Sep 02 16:58:23 mpk-dogfooding mme[434735]:     #6 0x56254a333f6c in magma::lte::NasStateConverter::proto_to_emm_context(magma::lte::oai::EmmContext const&, emm_co>
Sep 02 16:58:23 mpk-dogfooding mme[434735]:     #7 0x56254a0e27d0 in magma::lte::MmeNasStateConverter::proto_to_ue_mm_context(magma::lte::oai::UeContext const&, ue>
Sep 02 16:58:23 mpk-dogfooding mme[434735]:     #8 0x56254a0e31fc in magma::lte::MmeNasStateConverter::proto_to_ue(magma::lte::oai::UeContext const&, ue_mm_context>
Sep 02 16:58:23 mpk-dogfooding mme[434735]:     #9 0x56254a00373e in magma::lte::MmeNasStateManager::read_ue_state_from_db() /home/vagrant/magma/lte/gateway/c/core>
Sep 02 16:58:23 mpk-dogfooding mme[434735]:     #10 0x56254a002c35 in magma::lte::MmeNasStateManager::initialize_state(mme_config_s const*) /home/vagrant/magma/lte>
Sep 02 16:58:23 mpk-dogfooding mme[434735]:     #11 0x562549ff49b0 in mme_nas_state_init /home/vagrant/magma/lte/gateway/c/core/oai/tasks/mme_app/mme_app_state.cpp>
Sep 02 16:58:23 mpk-dogfooding mme[434735]:     #12 0x562549fd74db in mme_app_init /home/vagrant/magma/lte/gateway/c/core/oai/tasks/mme_app/mme_app_main.c:545
Sep 02 16:58:23 mpk-dogfooding mme[434735]:     #13 0x562549f01892 in main /home/vagrant/magma/lte/gateway/c/core/oai/oai_mme/oai_mme.c:140
Sep 02 16:58:23 mpk-dogfooding mme[434735]:     #14 0x7f822d4800b2 in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x270b2)
Sep 02 16:58:23 mpk-dogfooding mme[434735]: Direct leak of 16 byte(s) in 1 object(s) allocated from:
Sep 02 16:58:23 mpk-dogfooding mme[434735]:     #0 0x7f822e9d29c1 in __interceptor_malloc ../../../../src/libsanitizer/lsan/lsan_interceptors.cpp:54
Sep 02 16:58:23 mpk-dogfooding mme[434735]:     #1 0x562549f0c038 in bfromcstr_with_str_len /home/vagrant/magma/lte/gateway/c/core/oai/lib/bstr/bstrlib.c:243
Sep 02 16:58:23 mpk-dogfooding mme[434735]:     #2 0x56254a32edc9 in magma::lte::NasStateConverter::proto_to_pco_protocol_or_container_id(magma::lte::oai::Protocol>
Sep 02 16:58:23 mpk-dogfooding mme[434735]:     #3 0x56254a32ef68 in magma::lte::NasStateConverter::proto_to_protocol_configuration_options(magma::lte::oai::Protoc>
Sep 02 16:58:23 mpk-dogfooding mme[434735]:     #4 0x56254a0e1b1c in magma::lte::MmeNasStateConverter::proto_to_pdn_context(magma::lte::oai::PdnContext const&, pdn>
Sep 02 16:58:23 mpk-dogfooding mme[434735]:     #5 0x56254a0e1c95 in magma::lte::MmeNasStateConverter::proto_to_pdn_context_list(magma::lte::oai::UeContext const&,>
Sep 02 16:58:23 mpk-dogfooding mme[434735]:     #6 0x56254a0e2a0b in magma::lte::MmeNasStateConverter::proto_to_ue_mm_context(magma::lte::oai::UeContext const&, ue>
Sep 02 16:58:23 mpk-dogfooding mme[434735]:     #7 0x56254a0e31fc in magma::lte::MmeNasStateConverter::proto_to_ue(magma::lte::oai::UeContext const&, ue_mm_context>
Sep 02 16:58:23 mpk-dogfooding mme[434735]:     #8 0x56254a00373e in magma::lte::MmeNasStateManager::read_ue_state_from_db() /home/vagrant/magma/lte/gateway/c/core>
Sep 02 16:58:23 mpk-dogfooding mme[434735]:     #9 0x56254a002c35 in magma::lte::MmeNasStateManager::initialize_state(mme_config_s const*) /home/vagrant/magma/lte/>
Sep 02 16:58:23 mpk-dogfooding mme[434735]:     #10 0x562549ff49b0 in mme_nas_state_init /home/vagrant/magma/lte/gateway/c/core/oai/tasks/mme_app/mme_app_state.cpp>
Sep 02 16:58:23 mpk-dogfooding mme[434735]:     #11 0x562549fd74db in mme_app_init /home/vagrant/magma/lte/gateway/c/core/oai/tasks/mme_app/mme_app_main.c:545
Sep 02 16:58:23 mpk-dogfooding mme[434735]:     #12 0x562549f01892 in main /home/vagrant/magma/lte/gateway/c/core/oai/oai_mme/oai_mme.c:140
Sep 02 16:58:23 mpk-dogfooding mme[434735]:     #13 0x7f822d4800b2 in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x270b2)
Sep 02 16:58:23 mpk-dogfooding mme[434735]: Indirect leak of 32 byte(s) in 1 object(s) allocated from:
Sep 02 16:58:23 mpk-dogfooding mme[434735]:     #0 0x7f822e9d29c1 in __interceptor_malloc ../../../../src/libsanitizer/lsan/lsan_interceptors.cpp:54
Sep 02 16:58:23 mpk-dogfooding mme[434735]:     #1 0x562549f0c04e in bfromcstr_with_str_len /home/vagrant/magma/lte/gateway/c/core/oai/lib/bstr/bstrlib.c:246
Sep 02 16:58:23 mpk-dogfooding mme[434735]:     #2 0x56254a32edc9 in magma::lte::NasStateConverter::proto_to_pco_protocol_or_container_id(magma::lte::oai::Protocol>
Sep 02 16:58:23 mpk-dogfooding mme[434735]:     #3 0x56254a32ef68 in magma::lte::NasStateConverter::proto_to_protocol_configuration_options(magma::lte::oai::Protoc>
Sep 02 16:58:23 mpk-dogfooding mme[434735]:     #4 0x56254a0e1b1c in magma::lte::MmeNasStateConverter::proto_to_pdn_context(magma::lte::oai::PdnContext const&, pdn>
Sep 02 16:58:23 mpk-dogfooding mme[434735]:     #5 0x56254a0e1c95 in magma::lte::MmeNasStateConverter::proto_to_pdn_context_list(magma::lte::oai::UeContext const&,>
Sep 02 16:58:23 mpk-dogfooding mme[434735]:     #6 0x56254a0e2a0b in magma::lte::MmeNasStateConverter::proto_to_ue_mm_context(magma::lte::oai::UeContext const&, ue>
Sep 02 16:58:23 mpk-dogfooding mme[434735]:     #7 0x56254a0e31fc in magma::lte::MmeNasStateConverter::proto_to_ue(magma::lte::oai::UeContext const&, ue_mm_context>
Sep 02 16:58:23 mpk-dogfooding mme[434735]:     #8 0x56254a00373e in magma::lte::MmeNasStateManager::read_ue_state_from_db() /home/vagrant/magma/lte/gateway/c/core>
Sep 02 16:58:23 mpk-dogfooding mme[434735]:     #9 0x56254a002c35 in magma::lte::MmeNasStateManager::initialize_state(mme_config_s const*) /home/vagrant/magma/lte/>
Sep 02 16:58:23 mpk-dogfooding mme[434735]:     #10 0x562549ff49b0 in mme_nas_state_init /home/vagrant/magma/lte/gateway/c/core/oai/tasks/mme_app/mme_app_state.cpp>
Sep 02 16:58:23 mpk-dogfooding mme[434735]:     #11 0x562549fd74db in mme_app_init /home/vagrant/magma/lte/gateway/c/core/oai/tasks/mme_app/mme_app_main.c:545
Sep 02 16:58:23 mpk-dogfooding mme[434735]:     #12 0x562549f01892 in main /home/vagrant/magma/lte/gateway/c/core/oai/oai_mme/oai_mme.c:140
Sep 02 16:58:23 mpk-dogfooding mme[434735]:     #13 0x7f822d4800b2 in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x270b2)
Sep 02 16:58:23 mpk-dogfooding mme[434735]: Indirect leak of 32 byte(s) in 1 object(s) allocated from:
Sep 02 16:58:23 mpk-dogfooding mme[434735]:     #0 0x7f822e9d29c1 in __interceptor_malloc ../../../../src/libsanitizer/lsan/lsan_interceptors.cpp:54
Sep 02 16:58:23 mpk-dogfooding mme[434735]:     #1 0x562549f0c04e in bfromcstr_with_str_len /home/vagrant/magma/lte/gateway/c/core/oai/lib/bstr/bstrlib.c:246
Sep 02 16:58:23 mpk-dogfooding mme[434735]:     #2 0x56254a32edc9 in magma::lte::NasStateConverter::proto_to_pco_protocol_or_container_id(magma::lte::oai::Protocol>
Sep 02 16:58:23 mpk-dogfooding mme[434735]:     #3 0x56254a32ef68 in magma::lte::NasStateConverter::proto_to_protocol_configuration_options(magma::lte::oai::Protoc>
Sep 02 16:58:23 mpk-dogfooding mme[434735]:     #4 0x56254a32f656 in magma::lte::NasStateConverter::proto_to_esm_proc_data(magma::lte::oai::EsmProcData const&, esm>
Sep 02 16:58:23 mpk-dogfooding mme[434735]:     #5 0x56254a32f7db in magma::lte::NasStateConverter::proto_to_esm_context(magma::lte::oai::EsmContext const&, esm_co>
Sep 02 16:58:23 mpk-dogfooding mme[434735]:     #6 0x56254a333f6c in magma::lte::NasStateConverter::proto_to_emm_context(magma::lte::oai::EmmContext const&, emm_co>
Sep 02 16:58:23 mpk-dogfooding mme[434735]:     #7 0x56254a0e27d0 in magma::lte::MmeNasStateConverter::proto_to_ue_mm_context(magma::lte::oai::UeContext const&, ue>
Sep 02 16:58:23 mpk-dogfooding mme[434735]:     #8 0x56254a0e31fc in magma::lte::MmeNasStateConverter::proto_to_ue(magma::lte::oai::UeContext const&, ue_mm_context>
Sep 02 16:58:23 mpk-dogfooding mme[434735]:     #9 0x56254a00373e in magma::lte::MmeNasStateManager::read_ue_state_from_db() /home/vagrant/magma/lte/gateway/c/core>
Sep 02 16:58:23 mpk-dogfooding mme[434735]:     #10 0x56254a002c35 in magma::lte::MmeNasStateManager::initialize_state(mme_config_s const*) /home/vagrant/magma/lte>
Sep 02 16:58:23 mpk-dogfooding mme[434735]:     #11 0x562549ff49b0 in mme_nas_state_init /home/vagrant/magma/lte/gateway/c/core/oai/tasks/mme_app/mme_app_state.cpp>
Sep 02 16:58:23 mpk-dogfooding mme[434735]:     #12 0x562549fd74db in mme_app_init /home/vagrant/magma/lte/gateway/c/core/oai/tasks/mme_app/mme_app_main.c:545
Sep 02 16:58:23 mpk-dogfooding mme[434735]:     #13 0x562549f01892 in main /home/vagrant/magma/lte/gateway/c/core/oai/oai_mme/oai_mme.c:140
Sep 02 16:58:23 mpk-dogfooding mme[434735]:     #14 0x7f822d4800b2 in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x270b2)
Sep 02 16:58:23 mpk-dogfooding mme[434735]: SUMMARY: LeakSanitizer: 144 byte(s) leaked in 5 allocation(s).
Sep 02 16:58:23 mpk-dogfooding systemd[1]: magma@mme.service: Main process exited, code=exited, status=23/n/a
Sep 02 16:58:25 mpk-dogfooding systemd[1]: magma@mme.service: Failed with result 'exit-code'.
Sep 02 16:58:25 mpk-dogfooding systemd[1]: Stopped Magma OAI MME service.
Sep 02 16:58:31 mpk-dogfooding systemd[1]: Starting Magma OAI MME service...
Sep 02 16:58:32 mpk-dogfooding mme[1564311]: ERROR:root:Error retrieving config for mme, key not found: enable_nat
Sep 02 16:58:32 mpk-dogfooding mme[1564311]: ERROR:root:Error retrieving config for mme, key not found: congestion_control_enabled
Sep 02 16:58:32 mpk-dogfooding mme[1564311]: ERROR:root:Error retrieving config for mme, key not found: enable_converged_core
Sep 02 16:58:32 mpk-dogfooding mme[1564311]: ERROR:root:Error retrieving config for spgw, key not found: ovs_internal_sampling_fwd_tbl
Sep 02 16:58:32 mpk-dogfooding mme[1564311]: WARNING:root:Service (spgw) missing in mconfig
Sep 02 16:58:33 mpk-dogfooding mme[1564339]: STATELESS        mme -> use_stateless
Sep 02 16:58:33 mpk-dogfooding mme[1564339]: STATELESS        mobilityd -> persist_to_redis
Sep 02 16:58:33 mpk-dogfooding mme[1564339]: STATELESS        pipelined -> clean_restart
Sep 02 16:58:33 mpk-dogfooding mme[1564339]: STATELESS        pipelined -> redis_enabled
Sep 02 16:58:33 mpk-dogfooding mme[1564339]: STATELESS        sessiond -> support_stateless
Sep 02 16:58:33 mpk-dogfooding mme[1564339]: Check returning return_codes.STATELESS
Sep 02 16:58:33 mpk-dogfooding mme[1564339]: AGW is stateless, no need to restart Sctpd
Sep 02 16:58:33 mpk-dogfooding systemd[1]: Started Magma OAI MME service.
Sep 02 16:58:33 mpk-dogfooding mme[1564341]: Initializing OAI Logging
Sep 02 16:58:33 mpk-dogfooding mme[1564341]: Initializing OAI Logging to syslog
Sep 02 16:58:33 mpk-dogfooding mme[1564341]: Initializing shared logging
Sep 02 16:58:33 mpk-dogfooding mme[1564341]: Initializing shared logging Done
Sep 02 16:58:33 mpk-dogfooding mme[1564341]: [/home/vagrant/magma/orc8r/gateway/c/common/config/ServiceConfigLoader.cpp:35] Override file not found for service ser>
Sep 02 16:58:33 mpk-dogfooding mme[1564341]: Initializing TIMER module
Sep 02 16:58:33 mpk-dogfooding mme[1564341]: Initializing TIMER module: DONE
Sep 02 16:58:33 mpk-dogfooding mme[1564341]: filename /var/run/mme.pid failed to be written
Sep 02 16:58:33 mpk-dogfooding mme[1564341]: [/home/vagrant/magma/orc8r/gateway/c/common/config/ServiceConfigLoader.cpp:35] Override file not found for service red>
Sep 02 16:58:33 mpk-dogfooding mme[1564341]: [/home/vagrant/magma/orc8r/gateway/c/common/config/ServiceConfigLoader.cpp:35] Override file not found for service red>
Sep 02 16:58:33 mpk-dogfooding sudo[1564363]:     root : TTY=unknown ; PWD=/ ; USER=root ; COMMAND=/usr/bin/ovs-vsctl list Open_vSwitch
Sep 02 16:58:33 mpk-dogfooding sudo[1564363]: pam_unix(sudo:session): session opened for user root by (uid=0)
Sep 02 16:58:33 mpk-dogfooding sudo[1564363]: pam_unix(sudo:session): session closed for user root
Sep 02 16:58:33 mpk-dogfooding mme[1564364]: iface_types         : [erspan, geneve, gre, gtpu, internal, ip6erspan, ip6gre, lisp, patch, stt, system, tap, vxlan]
Sep 02 16:58:33 mpk-dogfooding mme[1564341]: Server running (127.0.0.1:6654)
Sep 02 16:58:36 mpk-dogfooding mme[1564341]: [/home/vagrant/magma/orc8r/gateway/c/common/config/ServiceConfigLoader.cpp:35] Override file not found for service red>
Sep 08 22:33:17 mpk-dogfooding mme[1564341]: PCEF Client thread id 140457276212992[DEBUG] Success logging event: detach_success
Sep 08 22:33:17 mpk-dogfooding mme[1564341]: [INFO] Sending S6A-AUTHENTICATION_INFORMATION_REQUEST with IMSI: 001010000000099
Sep 08 22:33:18 mpk-dogfooding mme[1564341]: [ERROR] 5: could not load federated network configs for access network mpk_dogfooding: Not found
Sep 08 22:33:18 mpk-dogfooding mme[1564341]: [ERROR] Received S6A-AUTHENTICATION_INFORMATION_ANSWER for IMSI: 001010000000099; Status: could not load federated net>
Sep 08 22:33:18 mpk-dogfooding mme[1564341]: Directoryd RPC failed with code 5, msg: Record for ID IMSI001010000000099 was not found.
Sep 08 22:33:28 mpk-dogfooding mme[1564341]: [INFO] Sending S6A-AUTHENTICATION_INFORMATION_REQUEST with IMSI: 001010000000099
Sep 08 22:33:28 mpk-dogfooding mme[1564341]: [ERROR] 5: could not load federated network configs for access network mpk_dogfooding: Not found
Sep 08 22:33:28 mpk-dogfooding mme[1564341]: [ERROR] Received S6A-AUTHENTICATION_INFORMATION_ANSWER for IMSI: 001010000000099; Status: could not load federated net>
Sep 08 22:33:28 mpk-dogfooding mme[1564341]: Directoryd RPC failed with code 5, msg: Record for ID IMSI001010000000099 was not found.
Sep 08 22:33:38 mpk-dogfooding mme[1564341]: [INFO] Sending S6A-AUTHENTICATION_INFORMATION_REQUEST with IMSI: 001010000000099
Sep 08 22:33:39 mpk-dogfooding mme[1564341]: [ERROR] 5: could not load federated network configs for access network mpk_dogfooding: Not found
```

**To Reproduce**
1. Go to `mpk-dogfooding agw`
2. Check mme logs 

**Expected behavior**
- No memory leak and service crash
- Subs should be able to authenticate

**Comment by ulaskozat** [comment]
Looks like dogfooding is crash looping due to a missing module.

**Comment by ulaskozat** [comment]
I had to install manually the following packages after upgrading to 1.7.0-1632271226-da9f305e (cc @pshelar @tmdzk): 
```
sudo pip install oslo.config --upgrade
sudo pip install routes --upgrade
sudo pip install tinyrpc --upgrade
sudo pip install webob --upgrade
```
