### ISSUE TITLE
heap_buffer_overflow

### ISSUE THREAD

**Issue by ulaskozat** [magma/magma#9478]

**Comment by ulaskozat** [comment]
Observed the following after running test_attach_detach_with_mme_restart.py.

```
Oct  6 00:19:59 magma-dev-focal mme[264279]: ==264279==ERROR: AddressSanitizer: heap-buffer-overflow on address 0x602000019b3b at pc 0x55d758ac31b9 bp 0x7f41838f1110 sp 0x7f41838f1100
Oct  6 00:19:59 magma-dev-focal mme[264279]: READ of size 1 at 0x602000019b3b thread T14
Oct  6 00:19:59 magma-dev-focal mme[264279]:     #0 0x55d758ac31b8 in def_hashfunc /home/vagrant/magma/lte/gateway/c/core/oai/lib/hashtable/obj_hashtable_uint64.c:80
Oct  6 00:19:59 magma-dev-focal mme[264279]:     #1 0x55d758acf59b in obj_hashtable_uint64_ts_get /home/vagrant/magma/lte/gateway/c/core/oai/lib/hashtable/obj_hashtable_uint64.c:935
Oct  6 00:19:59 magma-dev-focal mme[264279]:     #2 0x55d757d4fe17 in magma::lte::MmeNasStateConverter::guti_table_to_proto(obj_hash_table_uint64_s const*, google::protobuf::Map<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, unsigned long>*) /home/vagrant/magma/lte/gateway/c/core/oai/tasks/mme_app/mme_app_state_converter.cpp:133
Oct  6 00:19:59 magma-dev-focal mme[264279]:     #3 0x55d757d56085 in magma::lte::MmeNasStateConverter::state_to_proto(mme_app_desc_s const*, magma::lte::oai::MmeNasState*) /home/vagrant/magma/lte/gateway/c/core/oai/tasks/mme_app/mme_app_state_converter.cpp:789
Oct  6 00:19:59 magma-dev-focal mme[264279]:     #4 0x55d757b8db09 in magma::lte::StateManager<mme_app_desc_s, ue_mm_context_s, magma::lte::oai::MmeNasState, magma::lte::oai::UeContext, magma::lte::MmeNasStateConverter>::write_state_to_db() /home/vagrant/magma/lte/gateway/c/core/oai/include/state_manager.h:143
Oct  6 00:19:59 magma-dev-focal mme[264279]:     #5 0x55d757b4ce62 in put_mme_nas_state /home/vagrant/magma/lte/gateway/c/core/oai/tasks/mme_app/mme_app_state.cpp:48
Oct  6 00:19:59 magma-dev-focal mme[264279]:     #6 0x55d757a5b016 in handle_message /home/vagrant/magma/lte/gateway/c/core/oai/tasks/mme_app/mme_app_main.c:482
Oct  6 00:19:59 magma-dev-focal mme[264279]:     #7 0x7f41923b95c6 in zloop_start (/lib/x86_64-linux-gnu/libczmq.so.4+0x295c6)
Oct  6 00:19:59 magma-dev-focal mme[264279]:     #8 0x55d757a5b491 in mme_app_thread /home/vagrant/magma/lte/gateway/c/core/oai/tasks/mme_app/mme_app_main.c:503
Oct  6 00:19:59 magma-dev-focal mme[264279]:     #9 0x7f4192f50608 in start_thread /build/glibc-eX1tMB/glibc-2.31/nptl/pthread_create.c:477
Oct  6 00:19:59 magma-dev-focal mme[264279]:     #10 0x7f419127d292 in __clone (/lib/x86_64-linux-gnu/libc.so.6+0x122292)
Oct  6 00:19:59 magma-dev-focal mme[264279]: 0x602000019b3b is located 3 bytes to the right of 8-byte region [0x602000019b30,0x602000019b38)
Oct  6 00:19:59 magma-dev-focal mme[264279]: allocated by thread T0 here:
Oct  6 00:19:59 magma-dev-focal mme[264279]:     #0 0x7f4193283dc6 in calloc (/lib/x86_64-linux-gnu/libasan.so.5+0x10ddc6)
Oct  6 00:19:59 magma-dev-focal mme[264279]:     #1 0x55d758ac9e0c in obj_hashtable_uint64_ts_insert /home/vagrant/magma/lte/gateway/c/core/oai/lib/hashtable/obj_hashtable_uint64.c:636
Oct  6 00:19:59 magma-dev-focal mme[264279]:     #2 0x55d757d50ee0 in magma::lte::MmeNasStateConverter::proto_to_guti_table(google::protobuf::Map<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, unsigned long> const&, obj_hash_table_uint64_s*) /home/vagrant/magma/lte/gateway/c/core/oai/tasks/mme_app/mme_app_state_converter.cpp:186
Oct  6 00:19:59 magma-dev-focal mme[264279]:     #3 0x55d757d565da in magma::lte::MmeNasStateConverter::proto_to_state(magma::lte::oai::MmeNasState const&, mme_app_desc_s*) /home/vagrant/magma/lte/gateway/c/core/oai/tasks/mme_app/mme_app_state_converter.cpp:830
Oct  6 00:19:59 magma-dev-focal mme[264279]:     #4 0x55d757b8b62c in magma::lte::StateManager<mme_app_desc_s, ue_mm_context_s, magma::lte::oai::MmeNasState, magma::lte::oai::UeContext, magma::lte::MmeNasStateConverter>::read_state_from_db() /home/vagrant/magma/lte/gateway/c/core/oai/include/state_manager.h:98
Oct  6 00:19:59 magma-dev-focal mme[264279]:     #5 0x55d757b88c1a in magma::lte::MmeNasStateManager::initialize_state(mme_config_s const*) /home/vagrant/magma/lte/gateway/c/core/oai/tasks/mme_app/mme_app_state_manager.cpp:78
Oct  6 00:19:59 magma-dev-focal mme[264279]:     #6 0x55d757b4cdad in mme_nas_state_init /home/vagrant/magma/lte/gateway/c/core/oai/tasks/mme_app/mme_app_state.cpp:30
Oct  6 00:19:59 magma-dev-focal mme[264279]:     #7 0x55d757a5babe in mme_app_init /home/vagrant/magma/lte/gateway/c/core/oai/tasks/mme_app/mme_app_main.c:523
Oct  6 00:19:59 magma-dev-focal mme[264279]:     #8 0x55d7577934e7 in main /home/vagrant/magma/lte/gateway/c/core/oai/oai_mme/oai_mme.c:138
Oct  6 00:19:59 magma-dev-focal mme[264279]:     #9 0x7f41911820b2 in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x270b2)
Oct  6 00:19:59 magma-dev-focal mme[264279]: Thread T14 created by T0 here:
Oct  6 00:19:59 magma-dev-focal mme[264279]:     #0 0x7f41931b0805 in pthread_create (/lib/x86_64-linux-gnu/libasan.so.5+0x3a805)
Oct  6 00:19:59 magma-dev-focal mme[264279]:     #1 0x55d758ea3b06 in itti_create_task /home/vagrant/magma/lte/gateway/c/core/oai/lib/itti/intertask_interface.c:347
Oct  6 00:19:59 magma-dev-focal mme[264279]:     #2 0x55d757a5bd51 in mme_app_init /home/vagrant/magma/lte/gateway/c/core/oai/tasks/mme_app/mme_app_main.c:543
Oct  6 00:19:59 magma-dev-focal mme[264279]:     #3 0x55d7577934e7 in main /home/vagrant/magma/lte/gateway/c/core/oai/oai_mme/oai_mme.c:138
Oct  6 00:19:59 magma-dev-focal mme[264279]:     #4 0x7f41911820b2 in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x270b2)
Oct  6 00:19:59 magma-dev-focal mme[264279]: SUMMARY: AddressSanitizer: heap-buffer-overflow /home/vagrant/magma/lte/gateway/c/core/oai/lib/hashtable/obj_hashtable_uint64.c:80 in def_hashfunc
Oct  6 00:19:59 magma-dev-focal mme[264279]: Shadow bytes around the buggy address:
Oct  6 00:19:59 magma-dev-focal mme[264279]:   0x0c047fffb310: fa fa fd fd fa fa fd fd fa fa fd fd fa fa fd fd
Oct  6 00:19:59 magma-dev-focal mme[264279]:   0x0c047fffb320: fa fa fd fd fa fa fd fd fa fa fd fd fa fa fd fd
Oct  6 00:19:59 magma-dev-focal mme[264279]:   0x0c047fffb330: fa fa fd fd fa fa fd fd fa fa fd fd fa fa fd fd
Oct  6 00:19:59 magma-dev-focal mme[264279]:   0x0c047fffb340: fa fa fd fd fa fa fd fd fa fa fd fd fa fa fd fd
Oct  6 00:19:59 magma-dev-focal mme[264279]:   0x0c047fffb350: fa fa fd fd fa fa fd fd fa fa fd fd fa fa fd fd
Oct  6 00:19:59 magma-dev-focal mme[264279]: =>0x0c047fffb360: fa fa fd fd fa fa 00[fa]fa fa fd fd fa fa fd fd
Oct  6 00:19:59 magma-dev-focal mme[264279]:   0x0c047fffb370: fa fa fd fd fa fa fd fd fa fa fd fd fa fa fd fd
Oct  6 00:19:59 magma-dev-focal mme[264279]:   0x0c047fffb380: fa fa fd fd fa fa fd fd fa fa fd fd fa fa fd fd
Oct  6 00:19:59 magma-dev-focal mme[264279]:   0x0c047fffb390: fa fa fd fd fa fa fd fd fa fa fd fd fa fa fd fd
Oct  6 00:19:59 magma-dev-focal mme[264279]:   0x0c047fffb3a0: fa fa 00 00 fa fa 00 fa fa fa 00 00 fa fa 00 fa
Oct  6 00:19:59 magma-dev-focal mme[264279]:   0x0c047fffb3b0: fa fa 00 00 fa fa 00 fa fa fa 00 00 fa fa 00 00
Oct  6 00:19:59 magma-dev-focal mme[264279]: Shadow byte legend (one shadow byte represents 8 application bytes):
```
