### ISSUE TITLE
sctpd uplink server and downlink client memory leaks

### ISSUE THREAD

**Issue by ulaskozat** [magma/magma#9479]

**Comment by ulaskozat** [comment]
Observed the following after dedicated bearer test runs and service restart:

```
Oct  6 00:42:48 magma-dev-focal mme[298752]: =================================================================
Oct  6 00:42:48 magma-dev-focal mme[298752]: ==298752==ERROR: LeakSanitizer: detected memory leaks
Oct  6 00:42:48 magma-dev-focal mme[298752]: Direct leak of 80 byte(s) in 1 object(s) allocated from:
Oct  6 00:42:48 magma-dev-focal mme[298752]:     #0 0x7f19f3a51b47 in operator new[](unsigned long) (/lib/x86_64-linux-gnu/libasan.so.5+0x10fb47)
Oct  6 00:42:48 magma-dev-focal mme[298752]:     #1 0x7f19f2ce1b73 in fluid_base::BaseOFConnection::OFReadBuffer::read_notify(unsigned short) fluid/base/BaseOFConnection.cc:84
Oct  6 00:42:48 magma-dev-focal mme[298752]:     #2 0x7f19f2ce1b73 in fluid_base::BaseOFConnection::OFReadBuffer::read_notify(unsigned short) fluid/base/BaseOFConnection.cc:77
Oct  6 00:42:48 magma-dev-focal mme[298752]:     #3 0x7f19f2ce1b73 in fluid_base::BaseOFConnection::LibEventBaseOFConnection::read_cb(bufferevent*, void*) fluid/base/BaseOFConnection.cc:353
Oct  6 00:42:48 magma-dev-focal mme[298752]: Direct leak of 34 byte(s) in 1 object(s) allocated from:
Oct  6 00:42:48 magma-dev-focal mme[298752]:     #0 0x7f19f3a4fbc8 in malloc (/lib/x86_64-linux-gnu/libasan.so.5+0x10dbc8)
Oct  6 00:42:48 magma-dev-focal mme[298752]:     #1 0x5635380d9f3d in bstr2cstr /home/vagrant/magma/lte/gateway/c/core/oai/lib/bstr/bstrlib.c:348
Oct  6 00:42:48 magma-dev-focal mme[298752]:     #2 0x563538307ba5 in init_sctpd_downlink_client /home/vagrant/magma/lte/gateway/c/core/oai/tasks/sctp/sctpd_downlink_client.cpp:113
Oct  6 00:42:48 magma-dev-focal mme[298752]:     #3 0x563538306e2a in sctp_init /home/vagrant/magma/lte/gateway/c/core/oai/tasks/sctp/sctp_primitives_server.c:148
Oct  6 00:42:48 magma-dev-focal mme[298752]:     #4 0x56353809b8dc in main /home/vagrant/magma/lte/gateway/c/core/oai/oai_mme/oai_mme.c:142
Oct  6 00:42:48 magma-dev-focal mme[298752]:     #5 0x7f19f194e0b2 in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x270b2)
Oct  6 00:42:48 magma-dev-focal mme[298752]: Direct leak of 32 byte(s) in 1 object(s) allocated from:
Oct  6 00:42:48 magma-dev-focal mme[298752]:     #0 0x7f19f3a4fbc8 in malloc (/lib/x86_64-linux-gnu/libasan.so.5+0x10dbc8)
Oct  6 00:42:48 magma-dev-focal mme[298752]:     #1 0x5635380d9f3d in bstr2cstr /home/vagrant/magma/lte/gateway/c/core/oai/lib/bstr/bstrlib.c:348
Oct  6 00:42:48 magma-dev-focal mme[298752]:     #2 0x56353830c0c7 in start_sctpd_uplink_server /home/vagrant/magma/lte/gateway/c/core/oai/tasks/sctp/sctpd_uplink_server.cpp:144
Oct  6 00:42:48 magma-dev-focal mme[298752]:     #3 0x563538305833 in handle_message /home/vagrant/magma/lte/gateway/c/core/oai/tasks/sctp/sctp_primitives_server.c:65
Oct  6 00:42:48 magma-dev-focal mme[298752]:     #4 0x7f19f2b855c6 in zloop_start (/lib/x86_64-linux-gnu/libczmq.so.4+0x295c6)
Oct  6 00:42:48 magma-dev-focal mme[298752]: Direct leak of 16 byte(s) in 1 object(s) allocated from:
Oct  6 00:42:48 magma-dev-focal mme[298752]:     #0 0x7f19f3a4fbc8 in malloc (/lib/x86_64-linux-gnu/libasan.so.5+0x10dbc8)
Oct  6 00:42:48 magma-dev-focal mme[298752]:     #1 0x5635380d86ca in bfromcstr /home/vagrant/magma/lte/gateway/c/core/oai/lib/bstr/bstrlib.c:216
Oct  6 00:42:48 magma-dev-focal mme[298752]:     #2 0x5635380fd440 in bread /home/vagrant/magma/lte/gateway/c/core/oai/lib/bstr/bstrlib.c:1979
Oct  6 00:42:48 magma-dev-focal mme[298752]:     #3 0x5635383fafb9 in mme_config_parse_file /home/vagrant/magma/lte/gateway/c/core/oai/tasks/mme_app/mme_config.c:1814
Oct  6 00:42:48 magma-dev-focal mme[298752]:     #4 0x563538467097 in mme_config_embedded_spgw_parse_opt_line /home/vagrant/magma/lte/gateway/c/core/oai/tasks/mme_app/mme_app_embedded_spgw.c:133
Oct  6 00:42:48 magma-dev-focal mme[298752]:     #5 0x56353809ad59 in main /home/vagrant/magma/lte/gateway/c/core/oai/oai_mme/oai_mme.c:106
Oct  6 00:42:48 magma-dev-focal mme[298752]:     #6 0x7f19f194e0b2 in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x270b2)
Oct  6 00:42:48 magma-dev-focal mme[298752]: Indirect leak of 16384 byte(s) in 1 object(s) allocated from:
Oct  6 00:42:48 magma-dev-focal mme[298752]:     #0 0x7f19f3a4fbc8 in malloc (/lib/x86_64-linux-gnu/libasan.so.5+0x10dbc8)
Oct  6 00:42:48 magma-dev-focal mme[298752]:     #1 0x5635380d7699 in balloc /home/vagrant/magma/lte/gateway/c/core/oai/lib/bstr/bstrlib.c:148
Oct  6 00:42:48 magma-dev-focal mme[298752]:     #2 0x5635380fd001 in breada /home/vagrant/magma/lte/gateway/c/core/oai/lib/bstr/bstrlib.c:1959
Oct  6 00:42:48 magma-dev-focal mme[298752]:     #3 0x5635380fd46d in bread /home/vagrant/magma/lte/gateway/c/core/oai/lib/bstr/bstrlib.c:1979
Oct  6 00:42:48 magma-dev-focal mme[298752]:     #4 0x5635383fafb9 in mme_config_parse_file /home/vagrant/magma/lte/gateway/c/core/oai/tasks/mme_app/mme_config.c:1814
Oct  6 00:42:48 magma-dev-focal mme[298752]:     #5 0x563538467097 in mme_config_embedded_spgw_parse_opt_line /home/vagrant/magma/lte/gateway/c/core/oai/tasks/mme_app/mme_app_embedded_spgw.c:133
Oct  6 00:42:48 magma-dev-focal mme[298752]:     #6 0x56353809ad59 in main /home/vagrant/magma/lte/gateway/c/core/oai/oai_mme/oai_mme.c:106
Oct  6 00:42:48 magma-dev-focal mme[298752]:     #7 0x7f19f194e0b2 in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x270b2)
Oct  6 00:42:48 magma-dev-focal mme[298752]: SUMMARY: AddressSanitizer: 16546 byte(s) leaked in 5 allocation(s).
```
