### ISSUE TITLE
mme config memory leak

### ISSUE THREAD

**Issue by ulaskozat** [magma/magma#9486]

**Comment by ulaskozat** [comment]
```
Oct  6 05:55:15 magma-dev-focal mme[734767]: ==734767==ERROR: LeakSanitizer: detected memory leaks
Oct  6 05:55:15 magma-dev-focal mme[734767]: Direct leak of 48 byte(s) in 1 object(s) allocated from:
Oct  6 05:55:15 magma-dev-focal mme[734767]:     #0 0x7ff943053dc6 in calloc (/lib/x86_64-linux-gnu/libasan.so.5+0x10ddc6)
Oct  6 05:55:15 magma-dev-focal mme[734767]:     #1 0x7ff942184c0f in zlist_new (/lib/x86_64-linux-gnu/libczmq.so.4+0x24c0f)
Oct  6 05:55:15 magma-dev-focal mme[734767]: Direct leak of 16 byte(s) in 1 object(s) allocated from:
Oct  6 05:55:15 magma-dev-focal mme[734767]:     #0 0x7ff943053bc8 in malloc (/lib/x86_64-linux-gnu/libasan.so.5+0x10dbc8)
Oct  6 05:55:15 magma-dev-focal mme[734767]:     #1 0x56247a1b86ca in bfromcstr /home/vagrant/magma/lte/gateway/c/core/oai/lib/bstr/bstrlib.c:216
Oct  6 05:55:15 magma-dev-focal mme[734767]:     #2 0x56247a1dd440 in bread /home/vagrant/magma/lte/gateway/c/core/oai/lib/bstr/bstrlib.c:1979
Oct  6 05:55:15 magma-dev-focal mme[734767]:     #3 0x56247a4dafcb in mme_config_parse_file /home/vagrant/magma/lte/gateway/c/core/oai/tasks/mme_app/mme_config.c:1814
Oct  6 05:55:15 magma-dev-focal mme[734767]:     #4 0x56247a5470a9 in mme_config_embedded_spgw_parse_opt_line /home/vagrant/magma/lte/gateway/c/core/oai/tasks/mme_app/mme_app_embedded_spgw.c:133
Oct  6 05:55:15 magma-dev-focal mme[734767]:     #5 0x56247a17ad59 in main /home/vagrant/magma/lte/gateway/c/core/oai/oai_mme/oai_mme.c:106
Oct  6 05:55:15 magma-dev-focal mme[734767]:     #6 0x7ff940f520b2 in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x270b2)
Oct  6 05:55:15 magma-dev-focal mme[734767]: Indirect leak of 32768 byte(s) in 1 object(s) allocated from:
Oct  6 05:55:15 magma-dev-focal mme[734767]:     #0 0x7ff943053ffe in __interceptor_realloc (/lib/x86_64-linux-gnu/libasan.so.5+0x10dffe)
Oct  6 05:55:15 magma-dev-focal mme[734767]:     #1 0x56247a1b7592 in balloc /home/vagrant/magma/lte/gateway/c/core/oai/lib/bstr/bstrlib.c:132
Oct  6 05:55:15 magma-dev-focal mme[734767]:     #2 0x56247a1dd001 in breada /home/vagrant/magma/lte/gateway/c/core/oai/lib/bstr/bstrlib.c:1959
Oct  6 05:55:15 magma-dev-focal mme[734767]:     #3 0x56247a1dd46d in bread /home/vagrant/magma/lte/gateway/c/core/oai/lib/bstr/bstrlib.c:1979
Oct  6 05:55:15 magma-dev-focal mme[734767]:     #4 0x56247a4dafcb in mme_config_parse_file /home/vagrant/magma/lte/gateway/c/core/oai/tasks/mme_app/mme_config.c:1814
Oct  6 05:55:15 magma-dev-focal mme[734767]:     #5 0x56247a5470a9 in mme_config_embedded_spgw_parse_opt_line /home/vagrant/magma/lte/gateway/c/core/oai/tasks/mme_app/mme_app_embedded_spgw.c:133
```
